### ISSUE TITLE
Adding support for volume module for NetApp Volumes with existing GCP provider.

### ISSUE THREAD

**Issue by G-NamanGupta** [hashicorp/terraform-provider-google#16590] opened 2023-11-22 17:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This issue is for adding new support to Google Cloud NetApp NetApp Volumes capabilities to google terraform provider for creating volumes.
Volume provides a filesystem that you can mount.

### New or Affected Resource(s)

google_netapp_volume

### Potential Terraform Configuration

```tf
resource "google_netapp_volume" "test_volume" {
  location = "us-central1"
  volume_id = "testvolume1"
  capacity_gib = "200"
  share_name = "testshare"
  storage_pool = "testpool"
  protocols = ["NFSV3"]
  smb_settings = []
  labels = {}
  description = ""
  snap_reserve = 0
  snapshot_directory = false
  kerberos_enabled = false
  security_style   = "UNIX"
  unix_permissions = "0770"
}
```

### References

* #0000

b/319619589

**Comment by shuyama1** [comment] 2024-01-11 21:52
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/16019

**Closed by shuyama1** 2024-01-11 21:52 UTC
Labels: enhancement, new-resource, size/m, forward/linked, service/netapp
