### ISSUE TITLE
google_tags_location_tag_binding does not behave appropriately when a binding is removed outside of tf

### ISSUE THREAD

**Issue by alexjmoore** [hashicorp/terraform-provider-google#15928] opened 2023-09-21 15:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.83.0
+ provider registry.terraform.io/hashicorp/google-beta v4.83.0
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```
### Affected Resource(s)

* google_tags_location_tag_binding

### Terraform Configuration Files

```tf
resource "google_tags_location_tag_binding" "binding" {
  count     = var.vm_count
  parent    = "//compute.googleapis.com/projects/${google_project.this-project.number}/zones/${google_compute_instance.vm[count.index].zone}/instances/${google_compute_instance.vm[count.index].instance_id}"
  tag_value = google_tags_tag_value.iap_value.id
  location  = var.zone
}
```

### Expected Behavior

If a tag binding is removed outside of terraform (for example by deletion of a VM), terraform should treat it as missing just like any other missing resource, both by highlighting its absence in a plan and then by re-creating it in an apply.

### Actual Behavior

It seems it fails with a 403, example:

```
Error: Error when reading or editing TagsLocationTagBinding "europe-west2-a/tagBindings/%2F%2Fcompute.googleapis.com%2Fprojects%2FREDACTED%2Fzones%2Feurope-west2-a%2Finstances%2FREDACTED/tagValues/REDACTED": googleapi: Error 403: The caller does not have permission
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ResourceInfo",
│     "description": "permission [compute.instances.listTagBindings] required (or the resource may not exist in this location)",
│     "resourceName": "//compute.googleapis.com/projects/REDACTED/zones/europe-west2-a/instances/REDACTED"
│   }
│ ]
│ 
│   with google_tags_location_tag_binding.binding[1],
│   on main.tf line 191, in resource "google_tags_location_tag_binding" "binding":
│  191: resource "google_tags_location_tag_binding" "binding" {
```

Now it's true that the resource does not exist - because in this case the VM has been deleted and so too has the binding.  However it shouldn't hard fail in this manner.  The only resolution is to manually remove the binding resource entry from the state with a `terraform state rm` , at which point everything behaves as expected, but this doesn't seem like typical terraform behaviour, it should be able to recover from such a scenario without intervention like that.

### Steps to Reproduce

1. Use Terraform to create a VM with a tag binding
2. Manually delete the VM outside of Terraform
3. Attempt to plan or apply again, will result in a hard failure

### Important Factoids

N/A

### References

N/A

* #0000

b/331856795

**Comment by alexjmoore** [comment] 2023-09-21 16:44
I will try and create an example, but essentially if the binding is removed manually either the binding itself or as I discovered by the VM being deleted (which therefore removes the binding), then it will hard fail with this error. The error itself is correct, the binding isn't there any more so it won't be able to read it. But typically terraform would simply treat that as config drift and try and prompt a recreate rather than a hard fail.

**Comment by edwardmedia** [comment] 2023-09-21 17:14
@alexjmoore can you also share the debug logs for your original apply and re-apply?

**Comment by alexjmoore** [comment] 2023-09-22 17:13
I have put together an example terraform here: https://gist.github.com/alexjmoore/0bfb62718f872e6fb72e73dedda2ca3e

Simply replace the project ID with your own at the top.  This will deploy a single vpc and subnet with a VM inside and a tag bound to it.  Then to re-create the issue simply delete the vm - e.g. `gcloud compute instances delete my-vm` and on plan/apply you will see a 403 error stated above.

Curiously testing this, I saw that if I manually delete the binding itself but leave the VM intact (e.g. with `gcloud resource-manager tags bindings delete`) terraform doesn't even pick up that the binding has gone on a plan/apply, it reports "No changes. Your infrastructure matches the configuration." - despite the tag binding no longer being present.  So I think that is another possible issue there with this resource.

**Comment by edwardmedia** [comment] 2023-09-25 18:52
@hao-nan-li in the provider, [parent](https://github.com/hashicorp/terraform-provider-google/blob/e07be002edb0418df6b0d94c7b644c674bcd0124/google/services/tags/resource_tags_location_tag_bindings.go#L165) is part of the url. Once the vm instance is removed, the url becomes invalid. How do you want to resolve this case?

**Comment by hao-nan-li** [comment] 2023-09-25 20:23
What is the reason for the manual deletion? You may want to take a look at **resource drift** and see if there's any possible solution to your issue.

**Comment by alexjmoore** [comment] 2023-09-28 21:45
Not sure if this is a question to me.  Yes removing the resource manually from the state allows things to resume, but this seems an unusual pattern.  Typical response from Terraform to a resource that no longer exists is simply to prompt for its recreation, not fail hard in this way. 

Additionally as per my other point, this error occurs if the VM with the binding is removed (in the example), but actually if the binding alone is removed (the VM remains), terraform doesn't even pick up that the binding is missing.

So there are actually two unusual behaviours here imho.

**Comment by rileykarson** [comment] 2024-03-28 22:47
This is a case of 403s getting returned on 404 it seems, we should drop the resource on 403s as if it was a 404.

**Comment by tfalkenberg1** [comment] 2024-06-24 19:26
We are hitting this issue also frequently because we are using this strategy to provide public cloud run service with DRS activated: https://cloud.google.com/blog/topics/developers-practitioners/how-create-public-cloud-run-services-when-domain-restricted-sharing-enforced (which is what enterprises are recommended to do in Google Cloud).
Note this piece in the post:
> The platform team is responsible for managing organization-wide DRS policies and their exceptions, therefore only they should be able to manage and attach this tag value to any resources. The Google Cloud Console can be used to [manage the access to tags](https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#managing_access) and their values, so that project team members aren’t able to apply the tag themselves, they rather need to request the tag from the platform team.

That means one team (say the service developers) create the resource (cloud run in this case) while the platform team creates the binding. So these resources reside in different repos, different tf states. The case that one of these resources is deleted (or rather re-created) is not rare. Resolving from this situation requires state manipulation which adds risk and friction to the overall experience for both teams. 

I hope this example helps to raise the priority on this issue.

**Comment by evan-koanix** [comment] 2024-06-25 14:59
We are also hitting this issue. Also because of DRS and cloud run

**Comment by kamalmarhubi** [comment] 2024-07-22 18:23
@rileykarson 
> This is a case of 403s getting returned on 404 it seems, we should drop the resource on 403s as if it was a 404.

would a PR against magic-modules to do this be accepted? since introducing Cloud NGFW which targets firewall rules based on resource manager tags, we've had a lot of confusion caused by this error!

(I haven't looked closely enough, but I think it might require switching to fully custom resource code since as far as I can see there's no template hook to handle non-2xx API responses specially.)

**Comment by rileykarson** [comment] 2024-07-24 16:14
Yeah, we'd accept a change!

> (I haven't looked closely enough, but I think it might require switching to fully custom resource code since as far as I can see there's no template hook to handle non-2xx API responses specially.)

It's not a common case- [`read_error_transform`](https://github.com/GoogleCloudPlatform/magic-modules/blob/2b6e2fac92b47dca3c9f5b6e86cfac64923d9a36/mmv1/api/resource.rb#L241-L244) does it, I think, and https://github.com/hashicorp/terraform-provider-google-beta/blob/09358e6b0e5f0a9874893e1de78ca9c6f14d585a/google-beta/services/cloudidentity/cloud_identity_group_membership_utils.go#L13-L29 is likely a nearly identical function to what we'd want here.

**Comment by kamalmarhubi** [comment] 2024-07-24 16:16
Ah nice, I missed that! Much easier than a full migration to custom resource code. I'll try to take a look in the next week or so.

**Closed** 2024-09-30 20:15 UTC
Labels: bug, forward/linked, service/cloudresourcemanager-tags
