### ISSUE TITLE
Failing test(s): TestAccContainerAzureNodePool_BasicHandWritten

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16980] opened 2024-01-12 10:46 UTC
### Failure rates

- 100% since 2023-12-15

### Impacted tests

- TestAccContainerAzureNodePool_BasicHandWritten

### Affected Resource(s)

* google_container_azure_node_pool

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/995775231611490523?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
Error:
    Error creating NodePool:
        googleapi: Error 400: node auto repair feature is not available at this cluster version, field: azure_node_pool.management.auto_repair
```

b/319825301

**Comment by SarahFrench** [comment] 2024-01-12 10:50
The affected test is [here in the generated provider](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/containerazure/resource_container_azure_node_pool_generated_test.go), and the file header says the test is defined using the DCL/`tpgtools` in the magic-modules repo.

**Comment by SnowmanCharles** [comment] 2024-01-24 18:23
@NickElliot The root cause of this issue could be a regression in the Anthos Multi-Cloud service. We merged a fix. Could you verify that the test is now passing? If so, we can close this.

**Closed** 2024-01-24 22:45 UTC
Labels: size/s, test-failure, forward/linked, test-failure-100, service/gkemulticloud
