### ISSUE TITLE
Support user-managed service account for App Engine deployment

### ISSUE THREAD

**Issue by edwardsPaul421** [hashicorp/terraform-provider-google#11596] opened 2022-04-27 15:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
By default, when creating app engine, a default service account with `roles/editor` permission. 
Google's best practice is to create a custom service account with minimal permissions, and deploy the app using this service account instead of the default service account.

If there's any workaround doing this right now I would like to know.
   

### New or Affected Resource(s)

* google_app_engine_flexible_app_version
* google_app_engine_standard_app_version

### Potential Terraform Configuration

```tf
resource "google_app_engine_flexible_app_version" "app_engine" {
   service_account = "<CUSTOM_SERVICE_ACCOUNT_EMAIL>"
}
```

### References

* [User Managed Service Account on App Engine](https://cloud.google.com/appengine/docs/flexible/python/user-managed-service-accounts#app.yaml)

**Comment by roaks3** [comment] 2022-09-20 18:47
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11813

Note that the implementation specific to standard_app_version is captured by https://github.com/hashicorp/terraform-provider-google/issues/12607

**Closed by roaks3** 2022-09-20 18:47 UTC
Labels: enhancement, size/s
