### ISSUE TITLE
Compute Firewall API Response Mismatch

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-google#12257] opened 2022-08-04 15:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.2.1

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
resource "google_compute_firewall" "resource_name" {

  name    = "resource-name"
  network = var.subnetwork.network # network attribute on a google_compute_subnetwork resource
  project = var.project_id

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
  # Allow access to the instances via iap ranges
  source_ranges = [
    "35.235.240.0/20",
  ]
  target_tags = ["ssh-iap"]

  log_config {
    metadata = "INCLUDE_ALL_METADATA"
  }
}
```

### Debug Output

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.sandbox["redacted"].module.bastion.google_compute_firewall.resource_name
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google" produced an invalid new value for
│ .network: was cty.StringVal("redacted"), but now
│ cty.StringVal("https://www.googleapis.com/compute/v1/projects/fake-project-1234/global/networks/redacted").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Expected Behavior

Applies without error

### Actual Behavior

Applies with the stored value not consistent with what the API returns.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by megan07** [comment] 2022-08-04 21:01
Hi @tgoodsell-tempus, sorry that you're running into this issue. Unfortunately, I was unable to reproduce it. Could you please provide me the version of the provider that you're using? And also any logs you have generated with `TF_LOG=DEBUG`? Thanks!

**Comment by edwardmedia** [comment] 2023-09-18 13:38
@tgoodsell-tempus closing assuming it is no longer an issue

**Closed by edwardmedia** 2023-09-18 13:38 UTC
Labels: bug, waiting-response
