### ISSUE TITLE
Terraform apply for cloudfunctions returns 400 if function is modified in gcp console whilst managed by terraform state

### ISSUE THREAD

**Issue by nyc3-mikekot** [hashicorp/terraform-provider-google#9268] opened 2021-06-01 14:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

-----

Running Terraform Version:  `0.12.18`
Running Terraform Google Provider: `3.47.0`

I believe the breaking change was introduced in this commit: https://github.com/hashicorp/terraform-provider-google/pull/7723

Pre 3.47.0 (our old version was 3.42.0, I believe), whenever someone modified a cloud function that was managed by terraform state, re-running an apply would detect the drift and replace whatever was in the console with whatever Terraform had been configured to.

Now, we receive this error:

```
 Error: Error while updating cloudfunction configuration: googleapi: Error 400: Invalid value at 'function' (oneof), oneof field 'source_code' is already set. Cannot set 'sourceUploadUrl', invalid
```

To try to reproduce, set the `source_archive_bucket` and `source_archive_object` arguments, for example (so that the source code is stored from a bucket object), then modify the code in the resulting cloud function with the inline code editor, and then try re-running an apply to revert the code. (This should work in versions prior to 3.47.0)

**Comment by megan07** [comment] 2021-06-07 19:18
Hi @nyc3-mikekot! I'm sorry you're running into this issue. Unfortunately, I'm unable to reproduce the error that you're seeing. Would you please provide me with some debug logs and I can take a look at what might be going on?

Thanks!

**Comment by nyc3-mikekot** [comment] 2021-06-08 17:48
Hi @megan07! I have an update regarding on how to more accurately reproduce the bug.

1) Make sure to be on google provider version 3.47.0
2) Provision your cloud function via `terraform apply`, and make sure that the function is sourced from blob storage using `source_archive_bucket` and `source_archive_object` (a simple hello world function works - additionally, in my case, I use the python runtime)
3) Edit the function's source inside of the console after it is fully created in the inline code editor.
4) Now edit the code that's going to be used to provision the source code inside of your terraform configs (not in console), and re-run a `terraform apply`  (this is expected to fail)
5) Downgrade provider to old version (3.42.0), and re-run `terraform apply`, which will work (as opposed to failing in 3.47.0).

Here is a partial gist of the apply failure with TF_LOG set to DEBUG: https://gist.githubusercontent.com/nyc3-mikekot/8f0062419851156e3d673badc96ddd10/raw/a06b3f47f6c2c626ddbcc7390f0012acec25c804/gistfile1.txt

--

As I mentioned previously, I believe #7723 could be the cause of this error - as there is a conflict happening on the API when the patching occurs.

There is a limitation in cloud functions such that there can only be "one source set", and the patching endpoint is seeing that the function's source was set through the inline code editor, so a conflict arises when it tries to patch it with multiple "source locations" (both blob as well as inline code, I guess), since #7723 "reads the function" before "patching it". 

I am assuming it was possible to get away with editing the function in console whilst managed by terraform state without this happening in older versions since the terraform configuration was just being blindly trusted.

**Comment by nyc3-mikekot** [comment] 2021-06-08 18:02
When looking at the PATCH request on 3.42.0, for my specific case, it only updates the properties that have "actually changed", e.g in my case it simply looks like

```
{
  "name": name
  "sourceArchiveUrl': url
}
```

Whereas the 3.47.0 version sets multiple conflicting variables like `sourceUploadUrl` and `sourceArchiveUrl` together after reading in the function from the console changes, whilst also trying to set the request args of what's actually being changed.

**Comment by megan07** [comment] 2021-06-09 17:26
Hi @nyc3-mikekot ! I'm still unable to reproduce it unfortunately, however, I found this old issue that looks to have had the same error returned from google in `3.49.0` and it looks to be closed https://github.com/hashicorp/terraform-provider-google/issues/7921
Could you try upgrading your provider to `3.52.0` or later and see if this is resolved? I'll keep looking into it and seeing if I can repro until I hear back from you.
Thanks!

**Comment by nyc3-mikekot** [comment] 2021-06-10 14:59
Hi @megan07 - it appears version 3.52.0 does not have this problem (as opposed to 3.47.0), at least from what I'm seeing so far. Thank you!

**Comment by megan07** [comment] 2021-06-10 16:00
Great! Thanks! I will close this issue then, and if you encounter it again, feel free to open a new issue. Thanks!

**Closed by megan07** 2021-06-10 16:00 UTC
Labels: bug, waiting-response
