### ISSUE TITLE
Error: Collection of global_address confuses networking_connection

### ISSUE THREAD

**Issue by sirius-ed-hammond** [hashicorp/terraform-provider-google#12589] opened 2022-09-19 16:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_service_networking_connection

### Terraform Configuration Files

```tf
resource "google_compute_global_address" "psc_ip_range" {
  depends_on = [google_compute_router.routers]
  for_each = {
    for k, v in local.priv_svc_conn_listmap : k => v if try(contains(var.networks, v.network), false)
  }
  project       = var.project_id
  network       = each.value.network
  name          = "${each.value.network}-psc-${each.value.psc_name}"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  address       = each.value.psc_range
  prefix_length = 16
}
resource "google_service_networking_connection" "private_service_connection" {
  for_each = {
    for k, v in google_compute_global_address.psc_ip_range : k => v
  }
  network                 = each.value.network
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [each.value.name]
}
```
gets interpreted to be this when expanded:
```tf
  # module.network.google_service_networking_connection.private_service_connection["0"] will be created
  + resource "google_service_networking_connection" "private_service_connection" {
      + id                      = (known after apply)
      + network                 = "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/net1"
      + peering                 = (known after apply)
      + reserved_peering_ranges = [
          + "net1-psc-range1",
        ]
      + service                 = "servicenetworking.googleapis.com"
    }
```

Errors on first execution.  When run a second time, it creates the service connection without error.

### Expected Behavior

Resources should get created without internal symbolic name confusion.

### Actual Behavior
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.network.google_service_networking_connection.private_service_connection["0"] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google" produced an invalid new value for .network: was cty.StringVal("net1"), but now
│ cty.StringVal("https://www.googleapis.com/compute/v1/projects/my-project/global/networks/net1").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* none

**Comment by edwardmedia** [comment] 2022-09-19 17:00
@sirius-ed-hammond can you provide the config without the dynamic code which can be used to repro the issue?

**Comment by sirius-ed-hammond** [comment] 2022-09-19 17:26
My use case is:
1) Create a GCP project
2) Create a variable number of VPC networks in the project  (a list of networks names that map the IP ranges, etc.)
3) Configure a Private Service Connection in each VPC  (using the map value from the list of network names)

The issue is that the "simple name" of 'net1' is then getting fully qualified and it is confusing Terraform.

here is more of the code
```tf
variable "networks" {
  description = "List of network names to create"
  type        = list(string)
  default     = ["net1"]
}
variable "private_service_connection_sets" {
  type = map(map(string))
  default = {
    net1 = { range1 = "10.4.0.0" }
    net2 = { range1 = "10.5.0.0" }
    net3 = { range1 = "10.6.0.0" }
    net4 = { range1 = "10.7.0.0" }
  }
}
locals {
  priv_svc_conn_listmap = flatten([
    for net_key, net_value in var.private_service_connection_sets : [
      for psc_key, psc_value in net_value : {
        "network"     = net_key
        "psc_name"    = psc_key
        "psc_range"   = psc_value
     }
    ]
  ])
}
resource "google_compute_network" "network" {
  count                           = length(var.networks)
  project                         = var.project_id
  name                            = var.networks[count.index]
  auto_create_subnetworks         = false
  mtu                             = 1500
  routing_mode                    = "GLOBAL"
}
resource "google_compute_global_address" "psc_ip_range" {
  depends_on = [google_compute_router.routers]
  for_each = {
    for k, v in local.priv_svc_conn_listmap : k => v if try(contains(var.networks, v.network), false)
  }
  project       = var.project_id
  network       = each.value.network
  name          = "${each.value.network}-psc-${each.value.psc_name}"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  address       = each.value.psc_range
  prefix_length = 16
}
resource "google_service_networking_connection" "private_service_connection" {
  for_each = {
    for k, v in google_compute_global_address.psc_ip_range : k => v
  }
  network                 = each.value.network
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [each.value.name]
}
```

**Comment by edwardmedia** [comment] 2022-09-19 22:05
@sirius-ed-hammond it appears to me that is a question more about how to use the dynamic code. By removing the `for_each`, are you able to repro the issue? Please share the config if you can.

**Comment by sirius-ed-hammond** [comment] 2022-09-20 11:25
If I remove the for_each, then the functional requirement would not be met.  We need to have a dynamic list of networks, within each we allocate an internal global IP address range, and with that, we create the private network connection.  

Without the for_each, we would need to have a static configuration of "allocate address and create connection with that address" pairs in the terraform code.  That is not extensible nor the desired deliverable.

I provided the code snippet in previous comment.

The error is thrown on first apply and the connection is not made.
When we apply a second time it works without error and the connection is made.
Destroy has no error.

I have not tried to hard-code the indeterminate number of couplets to "allocate address then create connection" as I assumed that would be part of a regression test you might already have.

**Comment by edwardmedia** [comment] 2022-09-20 21:25
@sirius-ed-hammond not sure how I can help. Please keep in mind that here is the site we focus on individual resources. In term how to put various resources together, terraform core/sdk plays bigger role. By saying that, it is still possible there are issues in the provider. Maybe you can hard-code the resources to see where the problem is?

**Comment by sirius-ed-hammond** [comment] 2022-09-21 12:41
Seem we have differing perspectives.  Terraform exists to create collections of resources within a plan file, not a single resource in a plan file.  Iteration and symbolic substitution of values is vital to the effective use of the real world terraform plans.  

In this case, the provider is not adapting to the value change that gets resolved to being more specific.  
As the error message says:
`"registry.terraform.io/hashicorp/google" produced an invalid new value for .network: was cty.StringVal("net1"), but now cty.StringVal("https://www.googleapis.com/compute/v1/projects/my-project/global/networks/net1").`
the value went from the simple name to the fully qualified name due to the further resolution driven by the creation of previous resources.  **The provider needs to accommodate the change in value and operate with the new value when it is in execution.**  When the second apply occurs, there is no change in value because the precursor resource already exists and there is no change in value, thus all works as it should.

One might say "working as designed" but I would say "insufficient for the real world".  This type of iteration and value change is common among many other resources being created.  They handle the value change without error and the terraform apply succeeds without failure.  What I am asking for is the same tolerance to be manifest in the google_service_networking_connection resource.

**Comment by edwardmedia** [comment] 2022-09-24 23:18
@sirius-ed-hammond do you see below plan in the initial plan? After the first apply and the networks are created, the value for network in the plan has changed. That is what the Terraform complains about and the execution is blocked by Terraform. It is beyond what the provider can do.

```tf
 + resource "google_service_networking_connection" "private_service_connection" {
      + id                      = (known after apply)
      + network                 = "net1"
      + peering                 = (known after apply)
      + reserved_peering_ranges = [
          + "net1-psc-range1",
        ]
      + service                 = "servicenetworking.googleapis.com"
    }
```

```tf
  + resource "google_service_networking_connection" "private_service_connection" {
      + id                      = (known after apply)
      + network                 = "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/net1"
      + peering                 = (known after apply)
      + reserved_peering_ranges = [
          + "net1-psc-range1",
        ]
      + service                 = "servicenetworking.googleapis.com"
    }
```

I was also thinking you may use its data source. But unfortunately the data source does not export the network at all. You may file an enhancement to ask for it.

To make it work, you may think of a way to keep the network value static. Below code might still work for you.
```tf
resource "google_service_networking_connection" "private_service_connection" {
  for_each = {
    for k, v in local.priv_svc_conn_listmap : k => v if try(contains(var.networks, v.network), false)
  }
  network                 = each.value.network
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${each.value.network}-psc-${each.value.psc_name}"]
}
```

Does this make sense?

**Comment by edwardmedia** [comment] 2022-10-31 17:23
@sirius-ed-hammond is this still an issue?

**Comment by edwardmedia** [comment] 2022-11-03 17:07
@sirius-ed-hammond closing this now assuming it is no longer an issue. Feel free to reopen if you want to continue the discussion

**Closed by edwardmedia** 2022-11-03 17:07 UTC
Labels: bug, waiting-response
