### ISSUE TITLE
Adding cpu_cfs_quota breaks node pool

### ISSUE THREAD

**Issue by hprotzek** [hashicorp/terraform-provider-google#9104] opened 2021-05-07 09:30 UTC
Terraform v0.15.2
on darwin_amd64

Google 1.20.5-gke.2000

google-beta 3.66.1

Since we upgraded GKE to 1.20.5-gke.2000

our terraform plan failed for various node pools with the error:

```
ERR │ Error: googleapi: Error 400: At least one of ['node_version', 'image_type', 'updated_node_pool', 'locations', 'workload_metadata_config', 'upgrade_settings', 'kubelet_config', 'linux_node_config', 'tags', 'taints', 'labels', 'node_network_config', 'gcfs_config'] must be specified., badRequest
  ERR │ 
  ERR │   on ../../../modules/10_k8s/k8s-nodepool-actions.tf line 9, in resource "google_container_node_pool" "actions":
  ERR │    9: resource "google_container_node_pool" "actions" {
```

After adding kubelet_config (was't set beore) with the default values

```
kubelet_config {
      cpu_manager_policy   = "static"
      cpu_cfs_quota        = true
      cpu_cfs_quota_period = "100us"
    }
```

the node pools get completely broken and had to be deleted, as no pods couldn't run on it anymore:

```
Error: failed to create containerd task: OCI runtim
 e create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: se
 tting cgroup config for procHooks process caused: failed to write "100" to "/sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod8230a76c-fc9e-4ad0-
 be3d-c828025fdb5b/download-dashboards/cpu.cfs_period_us": write /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod8230a76c-fc9e-4ad0-be3d-c828025
 fdb5b/download-dashboards/cpu.cfs_period_us: invalid argument: unknown
``` 

Re-creating the node pools fixed the problem, but running our terraform plan again, reveals again the first problem and also with complete random nodepools on dev and prod. 

This is the nodepool config:

```
resource "google_container_node_pool" "iris" {
  for_each           = var.node_pool_config_iris
  project            = var.project_k8s
  provider           = google-beta
  name               = each.value.name
  location           = var.region
  cluster            = google_container_cluster.ee_k8s.name
  initial_node_count = 1
  version            = var.k8s_version

  node_config {
    image_type   = "COS_CONTAINERD"
    disk_size_gb = "50"
    machine_type = each.value.machine_type
    preemptible  = each.value.preemptible

    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }

  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  autoscaling {
    min_node_count = 0
    max_node_count = 40
  }

  timeouts {
    create = "90m"
    delete = "90m"
    update = "90m"
  }

  upgrade_settings {
    max_surge       = 10
    max_unavailable = 1
  }
}

```

**Comment by hprotzek** [comment] 2021-05-25 07:56
@ScottSuarez here is the debug output: https://gist.github.com/hprotzek/30e23e0348e8ee070b114df2206968b4

Also the latest updated from gke and terraform google provider didn't change anything.

**Comment by ScottSuarez** [comment] 2021-05-25 20:02
To confirm this is happening at *plan* and not at *apply*. Do you have a minimum config/change that can get me to a reproduction. Trying to find the source of this, looks like we are sending some improper `PUT` request somewhere. Just trying to track it down.

**Comment by hprotzek** [comment] 2021-05-28 12:29
The error happens at _apply_. I am struggling to reproduce it in a test case, as it happened to random nodepools in our dev and prod clusters.

**Comment by hprotzek** [comment] 2021-06-01 08:12
I deleted the affected node pools and let Terraform re-create them with the config from above. When I re-run terraform I get this:

```
~ node_config {
            tags              = [
                "internal",
            ]
            # (12 unchanged attributes hidden)

          - kubelet_config {
              - cpu_cfs_quota = false -> null
            }
```

When I look into the node pool with gcloud:
```
config:
  diskSizeGb: 50
  diskType: pd-standard
  imageType: COS_CONTAINERD
  kubeletConfig: {}
```

So it seems the terraform provider thinks the default of `cpu_cfs_quota` is false, which is wrong according to https://cloud.google.com/sdk/gcloud/reference/beta/container/node-pools/create#--system-config-from-file

**Comment by ScottSuarez** [comment] 2021-06-02 21:16
hmm curious, let me look a little more into this. In the meantime if you like you can always try debugging the raw provider. It's not overly complex that you wouldn't be able to understand it. Although getting it to run locally can be a little annoying. 

Also, before the apply breaks your node pools, I assume there is already something pre-existing? Could you give me the plan before the apply so I can see what terraform attempts to change that breaks it.

**Comment by grugnog** [comment] 2021-06-03 03:04
This has been driving me a bit nuts for the last week also. I handful of things I have confirmed:

- Based on my testing it appears to be a change in the GCP API sometime since May 21.
- I have a log of an working apply to create a completely new environment (projects, VPC and GKE) with Git tagged config and pinned versions of everything (Docker image containing OS/libraries, gcloud, TF, providers etc) from May 21, 2021 11:53am PDT.
- A week later I retried to create an environment by rerunning the same CI job (which reuses the original Docker image and configuration) and it failed with this issue.
- The delta appears when running plan and the fail occurs when running apply whenever the cluster is already provisioned.
- This delta shows up after successful creation of a completely fresh environment with no configuration changes - i.e. the initial apply creates the environment without issue, but a subsequent one (with no changes) shows the cpu_cfs_quota delta on plan and fails with the "Error 400: At least one of..." error on apply, preventing any subsequent changes to the infrastructure.
- I appear to be having the issue with zonal clusters, but not with regional clusters. I have 2 with basically identical configuration and only the zonal one is failing (the zonal one is also on a shared VPC subnet, which could be a factor I guess?).

**Comment by grugnog** [comment] 2021-06-03 03:08
Here is a snippet showing the delta for a plan on a freshly provisioned infrastructure with no configuration change, and no configuration referencing kubelet_config or cpu_cfs_quota:

```
Terraform will perform the following actions:

  # module.cicd-gke.google_container_node_pool.pools["general-node-pool-a"] will be updated in-place
  ~ resource "google_container_node_pool" "pools" {
...
        location            = "us-central1-c"
...
        version             = "1.20.6-gke.1000"
...
      ~ node_config {
...
          - kubelet_config {
              - cpu_cfs_quota = false -> null
            }
...
```

**Comment by grugnog** [comment] 2021-06-03 19:56
I have put together a minimal reproduction:

main.tf:
```
resource "google_container_cluster" "gke" {
  provider = google-beta
  name                     = "gke"
  initial_node_count       = 1
  remove_default_node_pool = true
  release_channel {
    channel = "RAPID"
  }
  min_master_version = "1.20.6"
}

resource "google_container_node_pool" "gke" {
  provider = google-beta
  name       = "gke"
  cluster    = google_container_cluster.gke.name
  node_count = 1
  version    = "1.20.6-gke.1000"

  node_config {
    preemptible  = true
    machine_type = "e2-standard-2"
  }
}
```

You will also need to create a project (which I just did manually) and create a providers.tf along the lines of:
```
provider "google-beta" {
  project = "project-id-here"
  region  = "us-central1"
  zone    = "us-central1-c"
}
```

Here is a log of output from an initial and subsequent apply: https://gist.github.com/grugnog/089049e17c7cc9b15454f4f7096cac4e

**Comment by grugnog** [comment] 2021-06-03 22:15
This appears to be the code that sets the value here https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/utils/node_config.go.erb#L542 - the ForceSendFields was added in Dec via this PR https://github.com/GoogleCloudPlatform/magic-modules/pull/4331 which could be related.

**Comment by ScottSuarez** [comment] 2021-06-08 22:42
This looks like an upstream issue since the api is returning an empty `"kubeletConfig": {}` in the rest response. The underlying sdk supporting resource [deserializes the rest api into the native object.](https://github.com/googleapis/google-api-go-client/blame/master/container/v1beta1/container-gen.go#L10105-L10115) Because the empty kubeletConfig is present `NodeKubeletConfig` is populated on the `NodePool.NodeConfig`. Since this field is populated the default values are specified on the field including the `cpu_cfs_quota` which golang defaults to false. This is inherently incorrect since if `cpu_cfs_quota` [is defined it should be enabled by default](https://cloud.google.com/sdk/gcloud/reference/beta/container/node-pools/create#--system-config-from-file). 

This is causing issues for terraform as we try to determine the state of the resource from the `NodePool` object but the state is corrupted due to this behavior.

I can probably patch a workaround for this but maintaining numerous workaround can be a bit of maintenance burden. Two questions : how impactful is this for you? Could you wait for this be fixed upstream or is it pressing to be resolved now. 

I'm not sure why you can't speicify the default values for the config. The original response you got from the api when you tried to do so seems to infer that there was something wrong with the formatting of `quota_period`. `failed to write "100"`

**Comment by hprotzek** [comment] 2021-06-09 06:39
Thanks @ScottSuarez for looking into it. Our current workaround:

```
lifecycle {
    ignore_changes = [
      node_config
    ]
  }
```

So as long as don't need to change something in the node config we are fine :-) I guess we are fine waiting for the upstream fix.

**Comment by jarrod-manwaring** [comment] 2021-06-16 16:01
@ScottSuarez I'm also bumping into this same issue, and I'm hesitant to move forward with the workarounds proposed above. Is there a possible timeline on when this will be resolved upstream?

**Comment by josandstrom** [comment] 2021-06-16 16:19
Unfortunately, we are running into the same issue. We are currently doing the same as @hpidcock did but it is kinda bad as we might need to do some changes to node config soon.

**Comment by ScottSuarez** [comment] 2021-06-16 17:32
@jarrod-manwaring @josandstrom , The api team is communicating that they have a fix in motion on the bug. I'll ask for a timeline once the fix it checked in. I am thinking < 2 weeks max

**Comment by hprotzek** [comment] 2021-06-28 08:32
@ScottSuarez Morning, any progress with the fix from the api team?

**Comment by renaudguerin** [comment] 2021-06-29 17:01
I'm also running into this problem and I don't think I can easily apply the `lifecycle` workaround @hprotzek offered, because I'm using the [GKE Google module](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest) (I initially opened [an issue](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/941) against it)

Before I saw this thread, I tried to manually reset the node pool's `kubelet_config` using `gcloud beta container node-pools update pool-xxxx --system-config-from-file=config.txt` with the default empty config [described here](https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#update-node-pool) in the hope that would help the provider go back to a known good state.

I've also tried the  `cpu_cfs_quota = false  cpu_manager_policy = ""` workaround @ScottSuarez offered, but the GKE TF module only supports `cpu_manager_policy` for some reason (I've opened [a PR to add the other attributes](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/942)) so that's unlikely to work either, unless I start using my patched version (which would cause us other problems)

Finally, since I did the manual system config reset, I seem to have a similar issue with `linux_node_config` : 
```          - kubelet_config {
              - cpu_cfs_quota = false -> null
            }
          - linux_node_config {
              - sysctls = {} -> null
            }
```

Looking forward to the upstream fix, because I can't see a good workaround in my case at the moment !

**Comment by ScottSuarez** [comment] 2021-06-29 18:05
The fix should have been promoted to prod recently. Hopefully a full role-out by the end of the week. I'll check in next week to ensure that it's fixed

**Comment by hprotzek** [comment] 2021-07-06 09:17
@ScottSuarez Do I have to update to a specific gke version to get the fix? It's still failing when I try to run it.

**Comment by ScottSuarez** [comment] 2021-07-08 17:15
i'll put it on my agenda to look at it today or tmrw.

**Comment by ScottSuarez** [comment] 2021-07-08 23:26
ya just tried, still failing out. I reached out to the api team to see whats up. I'm guessing slow rollout

**Comment by ScottSuarez** [comment] 2021-07-09 17:24
ETA from api team - full rollout by end of next week

**Comment by ScottSuarez** [comment] 2021-07-17 00:15
Just deployed locally, seemed to be resolved...

Thanks folks for your patience here :)

**Closed by ScottSuarez** 2021-07-17 00:15 UTC
Labels: bug, upstream
