### ISSUE TITLE
google_cloudfunctions2_function - .service_config[0].environment_variables: was null, but now...

### ISSUE THREAD

**Issue by NimJay** [hashicorp/terraform-provider-google#18747] opened 2024-07-16 18:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v5.38.0
+ provider registry.terraform.io/hashicorp/google-beta v5.38.0

### Affected Resource(s)

google_cloudfunctions2_function

### Terraform Configuration

```tf
resource "google_cloudfunctions2_function" "webhook" {
  project  = module.project_services.project_id
  name     = local.webhook_name
  location = var.region
  labels   = var.labels

  build_config {
    runtime           = "python312"
    entry_point       = "on_cloud_event"
    docker_repository = google_artifact_registry_repository.webhook_images.id
    source {
      storage_source {
        bucket = google_storage_bucket.main.name
        object = google_storage_bucket_object.webhook_staging.name
      }
    }
  }

  service_config {
    available_memory      = "1G"
    service_account_email = google_service_account.webhook.email
    environment_variables = {
      OUTPUT_BUCKET   = google_storage_bucket.main.name
      DOCAI_PROCESSOR = google_document_ai_processor.ocr.id
      DOCAI_LOCATION  = google_document_ai_processor.ocr.location
      BQ_DATASET      = google_bigquery_dataset.main.dataset_id
      BQ_TABLE        = google_bigquery_table.main.table_id
    }
  }
}
```

### Expected Behavior

Terraform should successfully create the Cloud Function.

### Actual Behavior

I get the following error during `terraform apply` when Terraform tries to create the Cloud Function:
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.simple.google_cloudfunctions2_function.webhook to include new values
learned so far during apply, provider
"registry.terraform.io/hashicorp/google" produced an invalid new value for
.service_config[0].environment_variables: was null, but now
cty.MapVal(map[string]cty.Value{"DATABASE":cty.StringVal("knowledge-base-database"),
"DOCAI_LOCATION":cty.StringVal("us"),
"DOCAI_PROCESSOR":cty.StringVal("projects/my-project-id/locations/us/processors/d7d722cbf9123456"),
"INDEX_ID":cty.StringVal("projects/my-project-id/locations/us-central1/indexes/1124505726098123456"),
"OUTPUT_BUCKET":cty.StringVal("knowledge-base-bucket-my-project-id"),
"PROJECT_ID":cty.StringVal("my-project-id"),
"VERTEXAI_LOCATION":cty.StringVal("us-central1")}).
```

### Steps to reproduce

1. `git clone git@github.com:GoogleCloudPlatform/terraform-genai-knowledge-base.git`
2. `terraform apply -var project_id=your-project-id`

### References

* Could it be related to https://github.com/hashicorp/terraform-provider-google/pull/18651/files? Which was released in [v5.38.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.38.0).

b/354262525

**Comment by ggtisc** [comment] 2024-07-19 21:26
Confirmed issue!

After a `terraform apply` If the variables have a value equal to the resources that are being created, it generates the following error:

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.simple.google_cloudfunctions2_function.webhook to include new values
learned so far during apply, provider
"registry.terraform.io/hashicorp/google" produced an invalid new value for
.service_config[0].environment_variables: was null, but now
cty.MapVal(map[string]cty.Value{"DATABASE":cty.StringVal("knowledge-base-database"),
"DOCAI_LOCATION":cty.StringVal("us"),
"DOCAI_PROCESSOR":cty.StringVal("projects/my-project-id/locations/us/processors/d7d722cbf9123456"),
"INDEX_ID":cty.StringVal("projects/my-project-id/locations/us-central1/indexes/1124505726098123456"),
"OUTPUT_BUCKET":cty.StringVal("knowledge-base-bucket-my-project-id"),
"PROJECT_ID":cty.StringVal("my-project-id"),
"VERTEXAI_LOCATION":cty.StringVal("us-central1")}).
```

**Comment by daniel-cit** [comment] 2024-08-01 02:26
The error ocorres when at least one of the values in the `service_config[0].environment_variables` depends on resources that will be created during the apply. 

If they are all fixed values at the plan time there is no error, that is the reason the test at [testAccCloudfunctions2function_cloudfunctions2FullExample](https://github.com/hashicorp/terraform-provider-google/blob/b8837957bb25e73de449be61a348430c4ed4ca24/google/services/cloudfunctions2/resource_cloudfunctions2_function_generated_test.go#L187C5-L189C6) was not able to detect the issue.

before the fix in #[18651](https://github.com/hashicorp/terraform-provider-google/pull/18651/files) when running `terraform plan` the resulting plan had `(known after apply)` as the value for `environment_variables `

```
...
      + service_config {
          + all_traffic_on_latest_revision   = true
          + available_cpu                    = "1"
          + available_memory                 = "256M"
          + environment_variables            = (known after apply)   <===============
          + gcf_uri                          = (known after apply)
...
```

after the change the field `environment_variables` is missing

```
...
      + service_config {
          + all_traffic_on_latest_revision   = true
          + available_cpu                    = "1"
          + available_memory                 = "256M"
          + gcf_uri                          = (known after apply)
...
```

But if we replace the values for fixed values it works

```
... 
      + service_config {
          + all_traffic_on_latest_revision   = true
          + available_cpu                    = "1"
          + available_memory                 = "256M"
          + environment_variables            = {
              + "SERVICE_CONFIG_TEST" = "build_test"    <===========
            }
          + gcf_uri                          = (known after apply)
... 
```

**Comment by daniel-cit** [comment] 2024-08-01 03:27
the issue is on [this line](https://github.com/hashicorp/terraform-provider-google/blob/b8837957bb25e73de449be61a348430c4ed4ca24/google/services/cloudfunctions2/resource_cloudfunctions2_function.go#L43) in the `environmentVariablesDiffSuppress` function
```
if strings.HasPrefix(k, "service_config.0.environment_variables.%") {
```

this line is telling Terraform to ignore changes in the size of the map and compere only the keys, so that the key `LOG_EXECUTION_ID` can be ignored. This does not works in the initial plan if at least one of the values is not available during the plan phase.

if the map has only fixed values like ` "SERVICE_CONFIG_TEST" = "build_test"` there are two calls of the diff function

```
2024-08-01T00:06:53.752-0300 [DEBUG] provider.terraform-provider-google: 2024/08/01 00:06:53 [DEBUG] DiffSuppress  k:"service_config.0.environment_variables.%" old:"0" new:"1"
2024-08-01T00:06:53.753-0300 [DEBUG] provider.terraform-provider-google: 2024/08/01 00:06:53 [DEBUG] DiffSuppress  k:"service_config.0.environment_variables.SERVICE_CONFIG_TEST" old:"" new:"build_test"
...
      + service_config {
          + all_traffic_on_latest_revision   = true
          + available_cpu                    = "1"
          + available_memory                 = "256M"
          + environment_variables            = {
              + "SERVICE_CONFIG_TEST" = "build_test"    <===========
            }
          + gcf_uri                          = (known after apply)
```

but if at least one value is `known after apply` we have only

```
2024-08-01T00:09:54.231-0300 [DEBUG] provider.terraform-provider-google: 2024/08/01 00:09:54 [DEBUG] DiffSuppress  k:"service_config.0.environment_variables.%" old:"" new:""
...
      + service_config {
          + all_traffic_on_latest_revision   = true
          + available_cpu                    = "1"
          + available_memory                 = "256M"
          + gcf_uri                          = (known after apply)
```
It should be enough to fix the problem to check the value of `new` for the empty string`""`  and in this case not to suppress the diff. 

using 
```
if strings.HasPrefix(k, "service_config.0.environment_variables.%")  && new != "" {
```

in a local built version of the provider fixes the issue.


```` 
....
2024-08-01T00:17:38.672-0300 [DEBUG] provider.terraform-provider-google: 2024/08/01 00:17:38 [DEBUG] DiffSuppress  k:"service_config.0.environment_variables.%" old:"" new:""
...
      + service_config {
          + all_traffic_on_latest_revision   = true
          + available_cpu                    = "1"
          + available_memory                 = "256M"
          + environment_variables            = (known after apply)    <===========
          + gcf_uri                          = (known after apply)
...

**Comment by rileykarson** [comment] 2024-08-08 18:47
@SarahFrench was this resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/11333?

**Comment by SarahFrench** [comment] 2024-08-08 18:53
Yes it was - [@/trodge reproduced the issue via a change to an acceptance test](https://github.com/GoogleCloudPlatform/magic-modules/pull/11333#issuecomment-2273547877), and that PR made the same acceptance test update and made those tests pass

I'll close this issue

**Closed by SarahFrench** 2024-08-08 18:53 UTC
Labels: bug, forward/linked, service/cloudfunctions
