### ISSUE TITLE
Support SSH authentication configuration in `google_dataform_repository` resource 

### ISSUE THREAD

**Issue by jochenstark** [hashicorp/terraform-provider-google#16025] opened 2023-09-28 13:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Feature Request:
Please support the SSH authentication configuration (SshAuthenticationConfig) in the terraform provider “terraform-provider-google”. 

Dataform API Reference for SshAuthenticationConfig:
https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#SshAuthenticationConfig

Use Case:
Supporting “SshAuthenticationConfig” will make it possible to create over Dataform REST API a repository object (https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#resource:-repository), where you can configure in GitRemote Settings (https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#GitRemoteSettings) a SSH configuration (https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#SshAuthenticationConfig).
This makes it possible to automate the setup of Dataform with a git repository over SSH Authentication.

### New or Affected Resource(s)
N/A

### Potential Terraform Configuration
N/A

### References
N/A

**Comment by SarahFrench** [comment] 2023-10-02 17:18
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/15975

**Closed by SarahFrench** 2023-10-02 17:18 UTC
Labels: enhancement, size/s
