### ISSUE TITLE
Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

### ISSUE THREAD

**Issue by jayenzo** [hashicorp/terraform-provider-google#7747] opened 2020-11-09 16:35 UTC
it seems I'm getting the following error when applying this terraform config

when I remove network and subnetwork inside the resource block it works 

```
module.gke_cluster.google_container_cluster.primary: Creating...

Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

  on ../../modules/gke/main.tf line 26, in resource "google_container_cluster" "primary":
  26: resource "google_container_cluster" "primary" {

```

**Comment by edwardmedia** [comment] 2020-11-09 17:25
@jayenzo  can you post your config and the steps how to reach the error?

**Comment by jayenzo** [comment] 2020-11-09 17:49
```
resource "google_container_cluster" "primary" {
  name    = var.name
  project = var.project
  location = var.location
  # network = var.network
  # subnetwork = var.subnetwork
  

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1
  

  # network     = google_compute_network.container_network.name
  # subnetwork  = google_compute_subnetwork.container_subnetwork.name

  logging_service    = var.logging_service
  monitoring_service = var.monitoring_service
  min_master_version = var.kubernetes_version

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  addons_config {
    horizontal_pod_autoscaling {
      disabled = false
    }
    network_policy_config {
      disabled = ! var.enable_network_policy
     }
  }

  ip_allocation_policy {
    cluster_ipv4_cidr_block  = "10.0.0.0/16"
    services_ipv4_cidr_block = "10.1.0.0/16"
  }

  vertical_pod_autoscaling {
    enabled = true
  } 

}
```

**Comment by jayenzo** [comment] 2020-11-09 17:50
If I uncomment the network and subnetwork portion it throws the errorn related to 
module.gke_cluster.google_container_cluster.primary: Creating...

```
Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

  on ../../modules/gke/main.tf line 26, in resource "google_container_cluster" "primary":
  26: resource "google_container_cluster" "primary" {
```

**Comment by edwardmedia** [comment] 2020-11-09 20:15
@jayenzo  did you run the above config directly (removing module code)? With `subnetwork` uncommented, what do you see? If it still fail, can you post your debug log?

**Comment by jayenzo** [comment] 2020-11-09 20:59
not I didn't run the resource directly I ran this module infront 

```
module "gke_cluster" { 
    source = "../../modules/gke"
    name = "swiq-development"
    project = var.project
    location = var.location
    network = var.network
    subnetwork = var.subnetwork
    kubernetes_version = "1.16.13-gke.401"
    cluster_secondary_range_name = "podcidr"
}
```

**Comment by jayenzo** [comment] 2020-11-09 21:55
Hey I've attached the debug output 
[terraform.txt](https://github.com/hashicorp/terraform-provider-google/files/5513491/terraform.txt)

**Comment by edwardmedia** [comment] 2020-11-10 00:15
@jayenzo we need to isolate if this is the provider issue or the module issue. I encourage you to run your above code directly to create the resource. I can't repro your issue. Let me know if the issue remains.

**Comment by edwardmedia** [comment] 2020-11-15 23:13
@jayenzo  is this still an issue?

**Comment by edwardmedia** [comment] 2020-11-17 18:31
@jayenzo I am closing this issue now. Feel free to reopen it once you can help isolate where the issue issue.

**Closed by edwardmedia** 2020-11-17 18:31 UTC
Labels: bug, waiting-response
