### ISSUE TITLE
Can not use `monitoring_config` alongside `monitoring_service`/`logging_service`

### ISSUE THREAD

**Issue by miko083** [hashicorp/terraform-provider-google#13861] opened 2023-02-28 15:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.55.0
+ provider registry.terraform.io/hashicorp/google-beta v4.55.0
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "gke-cluster" {
  name     = "my-test-cluster"
  location = "europe-west3-a"
  monitoring_service          = "monitoring.googleapis.com/kubernetes"
  logging_service             = "logging.googleapis.com/kubernetes"

  remove_default_node_pool = true
  initial_node_count       = 1
  
  monitoring_config {
    enable_components = [ "SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER" ]
    managed_prometheus {
      enabled = true
    }
  }
}

resource "google_container_node_pool" "cluster_node_pool" {
  name       = "my-test-node-pool"
  location   = "europe-west3-a"
  cluster    = google_container_cluster.gke-cluster.name
  node_count = 1

  node_config {
    preemptible  = true
    machine_type = "e2-medium"
    oauth_scopes = [
       "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}
```

### Debug Output

```
google_container_cluster.gke-cluster: Creating...
╷
│ Error: googleapi: Error 400: Cannot specify logging_config or monitoring_config together with logging_service or monitoring_service., badRequest
│ 
│   with google_container_cluster.gke-cluster,
│   on quick_cluster_to_reproduce.tf line 1, in resource "google_container_cluster" "gke-cluster":
│    1: resource "google_container_cluster" "gke-cluster" {
│ 
```

### Expected Behavior

GKE cluster created successfully from Terraform configuration file with `monitoring_service`, `logging_service` and `monitoring_config` parts defined.

### Actual Behavior

GKE cluster is not created (error above).

To create a GKE cluster one of these conditions must be met:
- comment `monitoring_service` and `logging_service` lines and leave  `monitoring_config` 
- comment `monitoring_config` part and leave `monitoring_service` and `logging_service` lines

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by edwardmedia** [comment] 2023-02-28 16:13
@miko083 the error is from api which sets the rule.  Where do you see below `Expected Behavior`?

```
GKE cluster created successfully from Terraform configuration file with monitoring_service, logging_service and monitoring_config parts defined.
```

**Comment by s-shin** [comment] 2023-03-03 12:40
Related: https://github.com/hashicorp/terraform-provider-google/issues/10820

In my understanding, as we can see [this documentation](https://cloud.google.com/stackdriver/docs/solutions/gke/installing?hl=en#deprecated_configuration_parameters), Google Cloud is trying to replace `--monitoring-service` and `--logging-service` (correspond to `monitoring_service` and `logging_service` in terraform) with `--monitoring` and `--logging` (correspond to `monitoring_config` and `logging_config` in terraform).

> Cannot specify logging_config or monitoring_config together with logging_service or monitoring_service., badRequest

This error seems to occur because the new and old parameters are mixed.

The problematic configuration could be fixed like this:

```terraform
resource "google_container_cluster" "gke-cluster" {
  name     = "my-test-cluster"
  location = "europe-west3-a"
  // Remove old parameters
  // monitoring_service          = "monitoring.googleapis.com/kubernetes"
  // logging_service             = "logging.googleapis.com/kubernetes"

  remove_default_node_pool = true
  initial_node_count       = 1
  
  monitoring_config {
    // `logging_service = "logging.googleapis.com/kubernetes"` corresponds to "SYSTEM_COMPONENTS".
    enable_components = [ "SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER" ]
    managed_prometheus {
      enabled = true
    }
  }

  logging_config {
    // `logging_service = "logging.googleapis.com/kubernetes"` corresponds to these.
    enable_components = [ "SYSTEM_COMPONENTS", "WORKLOADS"]
  }
}
```

**Comment by miko083** [comment] 2023-03-03 16:32
True, the error is from the Google Cloud REST API.

Even the official Google documentation is incorrect - [here (REST Resource: projects.locations.clusters)](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#resource:-cluster ) `loggingService`, `monitoringService` and `monitoringConfig` are all defined.

What's interesting, after successfully creating a cluster (only with `monitoringConfig`), you can [get the details](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/get) of newly created cluster and see that all three parameters (`loggingService`, `monitoringService` and `monitoringConfig`) are here:
```json
{
	"loggingService": "logging.googleapis.com/kubernetes",
	"monitoringService": "monitoring.googleapis.com/kubernetes",
	"monitoringConfig": {
		"componentConfig": {
			"enableComponents": [
				"SYSTEM_COMPONENTS",
				"APISERVER",
				"CONTROLLER_MANAGER",
				"SCHEDULER"
			]
},
```

**Comment by edwardmedia** [comment] 2023-03-07 23:24
@miko083 besides the config [here](https://github.com/hashicorp/terraform-provider-google/issues/13861#issuecomment-1453475842), below one is also working. I think the error message is clear, based on the two working configs. Does this make sense? 

```tf
resource "google_container_cluster" "gke-cluster" {
  name     = "issue13861-2"
  location = "europe-west3-a"
  monitoring_service          = "monitoring.googleapis.com/kubernetes"
  logging_service             = "logging.googleapis.com/kubernetes"

  remove_default_node_pool = true
  initial_node_count       = 1
  
}
```

**Comment by miko083** [comment] 2023-03-13 17:21
@edwardmedia that's true.

Creating cluster using configuration only with `monitoring_service` and `logging_service` or only with `monitoring_config` works fine, but as I presented in my previous post, if you [get the details](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/get) of newly created cluster all three parameters are here, so it's kind of misleading.

It's a little mess, looks like Google Cloud team needs to clean it out :) 

Thanks for your support.

**Comment by edwardmedia** [comment] 2023-03-17 13:46
@miko083 here is the [source](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters) the resource is built on. You may see both pairs co-exist, but apparently they are different.  Below rule is set by the API, I don't think there is little the provider can do. 

```
Error: googleapi: Error 400: Cannot specify logging_config or monitoring_config together with logging_service or monitoring_service., badRequest
```

@s-shin to your [comment](https://github.com/hashicorp/terraform-provider-google/issues/13861#issuecomment-1453475842), I do see the deprecation on these fields. But they are for gcloud. I do not see the changes in the api spec. 

I think the provider behaves by design. Closing the issue accordingly. Feel free to reopen if you see it differently.

**Closed by edwardmedia** 2023-03-17 13:46 UTC
Labels: bug
