### ISSUE TITLE
Error creating GlobalAddress

### ISSUE THREAD

**Issue by Vendin** [hashicorp/terraform-provider-google#5527] opened 2020-01-29 03:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.19
+ provider.google v3.4.0
+ provider.google-beta v3.5.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

```
### Affected Resource(s)

* google_compute_global_address

### Terraform Configuration Files

```tf

module "gcp-network" {
  source       = "terraform-google-modules/network/google"
  version      = "2.0.2"
  project_id   = var.project_id
  network_name = var.network

  subnets = [
    {
      subnet_name   = var.subnetwork
      subnet_ip     = "10.0.0.0/17"
      subnet_region = var.region
    },
  ]

  secondary_ranges = {
    "${var.subnetwork}" = [
      {
        range_name    = var.ip_range_pods_name
        ip_cidr_range = "10.52.0.0/14"
      },
      {
        range_name    = var.ip_range_services_name
        ip_cidr_range = "10.56.0.0/20"
      },
    ]
  }
}

```

```tf
resource "google_compute_subnetwork" "mysql" {
  project                  = var.project_id
  name                     = "${var.environment_name}-mysql"
  ip_cidr_range            = "10.127.0.0/20"
  network                  = module.gcp-network.network_self_link
  region                   = var.region
  private_ip_google_access = true
}

module "private-service-access" {
  source      = "GoogleCloudPlatform/sql-db/google//modules/private_service_access"
  version     = "2.0.0"
  project_id  = var.project_id
  vpc_network = module.gcp-network.network_name
}

```
### Debug Output

https://gist.github.com/Vendin/52ce0c36094ca487c3e9b75f84d5b367#file-terraform-trace

### Panic Output

```

Error: Error creating GlobalAddress: googleapi: Error 403: Required 'compute.globalAddresses.createInternal' permission for 'projects/tubebiz/global/addresses/google-managed-services-production-viewsta-vpc', forbidden

  on .terraform/modules/private-service-access/modules/private_service_access/main.tf line 27, in resource "google_compute_global_address" "google-managed-services-range":
  27: resource "google_compute_global_address" "google-managed-services-range" {

```
### Expected Behavior

Success create.

### Actual Behavior

Incomprehensible error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Authenticating with service account key, service account he have roles.

![image](https://user-images.githubusercontent.com/9011975/73326976-3239cb80-4265-11ea-8228-a316352f1e0c.png)

but I am confused by the lack of numbers in the likeness

![image](https://user-images.githubusercontent.com/9011975/73327034-7200b300-4265-11ea-888c-443817df2f32.png)

And remote backend

```
terraform {
  required_version = "0.12.19"

  backend "remote" {
    organization = "c"

    workspaces {
      name = "production-infrastructure"
    }
  }
}
```

### References

Interesting
https://github.com/googleapis/google-api-nodejs-client/issues/1382#issuecomment-466306678

**Comment by edwardmedia** [comment] 2020-01-29 20:40
@Vendin can you check if the terraform account has below permissions.
```
In addition to any permissions specified on the fields above, authorization requires one or more of the following Google IAM permissions:

compute.globalAddresses.create
compute.globalAddresses.createInternal
Examples
```
Check out  https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses/insert
Let me know if this helps address your issue

**Comment by Vendin** [comment] 2020-01-31 06:49
My service account has roles.
![image](https://user-images.githubusercontent.com/9011975/73517867-d2caef80-440d-11ea-959f-92d46e15fe9f.png)

Compute Network Admin role has compute.globalAddresses.createInternal  compute.globalAddresses.create permissions. My service account has this role. You can see it in the picture.

**Comment by edwardmedia** [comment] 2020-01-31 20:16
@Vendin To me, your issue is more credential related. How do you use your credential? Can you follow below instruction to create new and then try? 
https://www.terraform.io/docs/providers/google/guides/getting_started.html

**Comment by xEcEz** [comment] 2020-03-07 17:44
I am actually getting similar errors while trying to create a private ip address:

```
Error: Error creating GlobalAddress: googleapi: Error 403: Required 'compute.globalAddresses.createInternal' permission for 'projects/fluid-firefly-202213/global/addresses/private-ip-address'
More details:
Reason: forbidden, Message: Required 'compute.globalAddresses.createInternal' permission for 'projects/fluid-firefly-202213/global/addresses/private-ip-address'
Reason: forbidden, Message: Required 'compute.networks.use' permission for 'projects/fluid-firefly-202213/global/networks/zar-network-2'
```

Could it be that terraform looks for wrong permission? To me, it seems that it looks for `compute.globalAddresses.createInternal` which is not listed in the [roles/permissions list](https://cloud.google.com/iam/docs/understanding-roles). Checking the [globalAdresses](https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses) page, the only methods listed there are: delete, get, insert & list.

**Comment by edwardmedia** [comment] 2020-03-09 20:26
@xEcEz how do you verify if the account you use is the right one? can you try to create a brand new account to test the results?

**Comment by xEcEz** [comment] 2020-03-10 08:40
@edwardmedia The error was on my side and due to a configuration mistake in the `google-beta` provider block that was referring to an outdated credentials file. Sorry about this.

**Comment by edwardmedia** [comment] 2020-03-11 17:24
@Vendin Have you resolved the issue? How do you use your credential? Can you follow below instruction to create new and then try?
https://www.terraform.io/docs/providers/google/guides/getting_started.html

**Comment by Vendin** [comment] 2020-03-13 16:58
@edwardmedia  my issue is not resolved. A new account has not yet been possible to create.

**Comment by edwardmedia** [comment] 2020-03-13 21:32
@Vendin your error message clearly indicates the account your terraform uses does not the specified permission. I have verified that if the account has the role of `Compute Network Admin`, it is enough for the account that can successfully run the scripts. Your error message is from API. It has nothing to do with terraform itself. I would suggest you go back to verify if you use the account you think of. If you can't create a new account, how about disabling this account, and then see what happens? Let me know if I can provide any further assistance. Thanks

**Comment by Vendin** [comment] 2020-04-04 17:59
@edwardmedia screenshot also shows that the service account has the role of Compute Network Admin. 

Could there be a problem with the time applying the permissions to service account in Google Cloud Platform ?

I found the like.
googleapis / google-api-nodejs-client # 1382 (comment)

I will return to this question again, check and write to you, thank you.

**Comment by edwardmedia** [comment] 2020-04-06 20:53
@Vendin `google-api-nodejs-client` is a client tool. There is nothing to do with `terraform-provider-google`.
Anything possible. If you can provide a little bit details and then we can take a look. 
Have you tried to verify the account for terraofrm is the one you think of? Can you specify how you did?

**Comment by edwardmedia** [comment] 2020-05-12 16:42
@Vendin likely this is related to the account you used for running terraform. At this moment, I am going to close the issue. Please feel free to reopen it if you need further assistance for your issue. Thanks

**Comment by slevenick** [comment] 2022-10-11 23:36
Reopened for workaround documentation

**Comment by betsy-lichtenberg** [comment] 2022-10-12 18:17
The Data Guy has posted an article with a workaround. I personally tried it, and confirmed that it worked in my project. Here is the article: https://thedataguy.in/cloudsql-shared-vpc-private-ip-and-servicenetworking.serviceagent-role/

TL;DR: here is the workaround:

```
gcloud projects add-iam-policy-binding YOUR_HOST_PROJECT_NAME \
  --member=[serviceAccount:service-HOST_PROJECT_ACCOUNT_NUMBER@service-networking.iam.gserviceaccount.com](mailto:serviceAccount%3Aservice-HOST_PROJECT_ACCOUNT_NUMBER@service-networking.iam.gserviceaccount.com) \
  --role=roles/servicenetworking.serviceAgent
```

**Closed** 2022-10-12 18:21 UTC
Labels: bug
