### ISSUE TITLE
Datastream private connection and connection profile

### ISSUE THREAD

**Issue by marcusricardoaguiar** [hashicorp/terraform-provider-google#14051] opened 2023-03-21 13:37 UTC
Terraform Version: 1.3.7

I've been trying to create the following resources. However, when I apply for the first time, it creates the resources on GCP, but it crashed the terraform apply command, like below:
![image2](https://user-images.githubusercontent.com/8216333/226619972-933300a0-36bf-4bdf-8beb-71c5eeb2f79d.png)

When I manually delete the resource and try again, it works fine.

### Affected Resource(s)
 - google_datastream_connection_profile
 - google_datastream_private_connection

**Comment by edwardmedia** [comment] 2023-04-02 13:50
@marcusricardoaguiar thanks for the config. Due to unknown values for the variables, not sure how to run it. Below is the config I have tested. It works fine. Can you try to see if that works for you? Do you see any difference from yours?

```tf
resource "google_datastream_private_connection" "private_connection" {
    display_name          = "issue14051"
    location              = "us-central1"
    private_connection_id = "issue14051-connection"

    labels = {
        key = "value"
    }

    vpc_peering_config {
        vpc = google_compute_network.default.id
        subnet = "10.0.0.0/29"
    }
}

resource "google_compute_network" "default" {
    name = "issue14051"
}

resource "google_datastream_connection_profile" "default" {
    display_name          = "issue14051"
    location              = "us-central1"
    connection_profile_id = "issue14051-profile"

    bigquery_profile {}

    private_connectivity {
        private_connection = google_datastream_private_connection.private_connection.id
    }
}
```

**Comment by rileykarson** [comment] 2023-04-03 23:15
Based on the information in this ticket so far there's no clear provider bug. Closing.

> When I had this issue, both resources were created in GCP, but terraform wasn't able to store the state.

If Terraform is succeeding & not preserving the resource in state that *is* a bug. Could you file a new bug if you're able to reproduce this?

**Closed by rileykarson** 2023-04-03 23:15 UTC
Labels: bug, waiting-response
