### ISSUE TITLE
feat: add schema update functionality for Big Query tables

### ISSUE THREAD

**Issue by terekete** [hashicorp/terraform-provider-google#14769] opened 2023-05-31 12:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

With Big Query tables if a schema is updated the complete tables needs to be replaced. BQ is now supporting in GA the ability to rename column and drop columns. Is it possible to enable this same functionality from terraform such that schema changes are handled for updates/patches.

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_column_statement

### New or Affected Resource(s)

google_bigquery_table

### Potential Terraform Configuration

The change on schema upon apply should handle these updates to the schema without recreating the table.
Cases are add table column, drop table column, rename table column, shuffle table schema.

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_column_statement
* b/298496481

**Comment by rileykarson** [comment] 2023-06-05 17:04
Note: Nothing in the API indicates this wouldn't be updatable using standard update methods

**Comment by terekete** [comment] 2023-06-23 02:20
@rileykarson are you saying this looks doable or this already should work with present tf versions?

**Comment by yi-wei-neo-db** [comment] 2023-07-27 08:28
This will not work with present tf version.

**Comment by terekete** [comment] 2024-01-27 04:07
Any update on this feature?

**Comment by obada-ab** [comment] 2024-02-01 19:05
Picking this up.

I looked into allowed table modifications (https://cloud.google.com/bigquery/docs/managing-table-schemas), and I did some testing with terraform 1.7.2, it looks like at least some types of schema updates work fine, for example adding a column:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_bigquery_table.test will be updated in-place
  ~ resource "google_bigquery_table" "test" {
        id                       = "projects/xxxxx/datasets/random_foo_bar/tables/random_foo_bar"
      ~ schema                   = jsonencode(
          ~ [
                # (1 unchanged element hidden)
                {
                    name = "column2"
                    type = "STRING"
                },
              + {
                  + name = "column3"
                  + type = "STRING"
                },
            ]
        )
        # (18 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Likewise, relaxing a field mode from `REQUIRED` to `NULLABLE` happens in-place.

As for renaming and dropping columns, I need to check if these types of in-place updates are allowed through the API, the page I linked above mentions the DDL commands as the only option for these types of changes.

**Comment by RomeoAva** [comment] 2024-02-01 22:58
+1 on this. In the past had to handle Bigquery tables outside of Terraform with migrations handled with Alembic. Which made it awkward since everything else was defined in Terraform..

This would be awesome if it works!

**Comment by terekete** [comment] 2024-02-02 02:14
Just like to add there is a patch and update call on the API. Unsure if
they allow for schema updates without recreation.

https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/update

**Comment by terekete** [comment] 2024-02-20 17:26
@obada-ab - any luck on this issue?

**Comment by obada-ab** [comment] 2024-02-21 15:01
@terekete we're still verifying internally whether the API supports this, but so far it doesn't seem to be the case. I'm also looking into other possible workarounds for renaming/dropping columns.

**Comment by obada-ab** [comment] 2024-03-12 13:48
Working on a PR for in-place column dropping, renaming nullable columns would technically happen in-place but TF would detect it as a column being dropped and a new column being added, which would delete existing data for that column.

For general column renaming backend support would likely be needed since detecting all cases can add a lot of complexity.

**Comment by PabloPardoGarcia** [comment] 2024-03-15 13:03
@obada-ab I recently face unexpected behavior adding a new column to an existing table. I added a column to the middle of the schema, however when applying terraform, the new column was added to the end of the columns list. 

According to the [documentation](https://cloud.google.com/bigquery/docs/managing-table-schemas#bq), new columns added not at the end should raise an error:

> Add the new columns to the end of the schema definition. If you attempt to add new columns elsewhere in the array, the following error is returned: `BigQuery error in update operation: Precondition Failed`.

It is also not super clear in BQ documentation, since this is only mentioned in the bq section and not in any of the other languages.

**Comment by obada-ab** [comment] 2024-04-08 08:46
Added in-place column drop functionality, column renaming is more complicated and we might have to wait for backend support.

@rileykarson I think we can close this issue and track column renaming in https://github.com/hashicorp/terraform-provider-google/issues/17787

**Comment by obada-ab** [comment] 2024-04-15 13:25
Closing this issue, column renaming tracked in https://github.com/hashicorp/terraform-provider-google/issues/17787

**Closed** 2024-04-16 16:00 UTC
Labels: enhancement, size/s, forward/linked, service/bigquery
