### ISSUE TITLE
Composer unable to use new Airflow 2.0.1 image version due to regex constraint

### ISSUE THREAD

**Issue by dan-ladd** [hashicorp/terraform-provider-google#9229] opened 2021-05-25 18:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

14.1

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
resource "google_composer_environment" "composername" {
  provider = google
  name = "composername"
  region = gcp_region

  config {
    node_count = 3

      image_version = "composer-1.17.0-preview.1-airflow-2.0.1"

    }
  }

}
```

### Debug Output

Error: "config.0.software_config.0.image_version" ("composer-1.17.0-preview.0-airflow-2.0.1") doesn't match regexp "composer-([0-9]+\\.[0-9]+\\.[0-9]+|latest)-airflow-([0-9]+\\.[0-9]+(\\.[0-9]+.*)?)"

### Expected Behavior

Create an instance on composer-1.17.0-preview.0-airflow-2.0.1 as that is a valid version https://cloud.google.com/composer/docs/concepts/versioning/composer-versions

### Actual Behavior

Cannot create composer instance

### References

Regex constraint is set here https://github.com/hashicorp/terraform-provider-google/blob/9bbb4a84022f7513ce969891a5675d912955f7f0/google/resource_composer_environment.go#L19

* #0000

**Comment by melinath** [comment] 2021-05-26 19:03
This looks like a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9201

**Closed by melinath** 2021-05-26 19:03 UTC
Labels: bug
