### ISSUE TITLE
google_cloud_run_v2_service resource do not detect docker image changes in version "latest"

### ISSUE THREAD

**Issue by dmi-w** [hashicorp/terraform-provider-google#16679] opened 2023-12-05 15:47 UTC
# Background

# What kind of contribution is this issue about?
general contributions

# Related PR(s), if any:

# Details
I am using the latest version of terraform provider (5.8.0 at time of writing).

Initial state: I have created my cloud run service using tf resource "google_cloud_run_v2_service" which is pointing to my docker image in Cloud Artifact in version "latest".

Action: I've pushed a new content of my image still in version "latest" (so its content has changed in Cloud Artifact but not its URL), and now I am launching my terraform pipeline again.

Expected result: I would expect my Cloud Run service to take into account the image change and redeploy the service using the new image content.

Actual result: The service is left unchanged (terraform does nothing) because the image URL hasn't changed (still in version "latest")

The attribute google_cloud_run_v2_service.template.containers.image receives an image URL only which doesn't enable the resource to detect an image content change if the URL doesn't change.

This issue prevents me from running a real CI/CD (GitOps) pipeline as such without developing my own work-around.

**Comment by edwardmedia** [comment] 2023-12-07 17:52
@dmi-w can you share a simple config and detail the steps that we can use to repro the issue?

**Comment by edwardmedia** [comment] 2023-12-11 16:29
@dmi-w is this still an issue?

**Comment by dmi-w** [comment] 2023-12-12 16:25
I think I have detailed the approach above. But anyway, let me describe the steps further:

1. Create artifact registry running the following terraform code:
resource "google_artifact_registry_repository" "repo" {
  location      = local.location
  project       = local.project
  repository_id = local.name
  description   = local.description
  format        = "DOCKER"
  docker_config {
    immutable_tags = true
  }
  lifecycle {
    ignore_changes = [docker_config]
  }
}

2. Push my initial docker image to artifact registry using the following CLI command (with Success): 
docker push europe-docker.pkg.dev/dev-demo/demo-dev-testing/myimage:latest

3. Run terraform to create my Cloud Run service pointing to this image (with Success):
resource "google_cloud_run_v2_service" "frontend" {
  name     = "my-service"
  location = var.region
  ingress  = "INGRESS_TRAFFIC_ALL"
  template {
    execution_environment = "EXECUTION_ENVIRONMENT_GEN2"
    service_account       = module.cloudrun_sa.sa.email
    vpc_access {
      connector = google_vpc_access_connector.connector.id
      egress    = "ALL_TRAFFIC"
    }
    containers {
      name  = "frontend"
      image = "europe-docker.pkg.dev/dev-demo/demo-dev-testing/myimage:latest"
      ports {
        container_port = 3000
      }
    }
  }
}

4. Modify my docker image and push it the same way as step 2 (no image name change but image content change).

5. Run the same terraform as step 3. I would expect resource google_cloud_run_v2_service to redeploy the service with my docker image change (that occured in step 4), but it doesn't because the image has the same name.

In a CI/CD pipeline that I run often while developing my docker container, I would like it to take into account my docker image change even though it remains in version LATEST.

Terraform taint (or replace) is not satisfying as it is a workaround that I have to trigger myself via an additional development in my pipeline, which I will do indeed if you cannot make the terraform resource evolve.

**Comment by edwardmedia** [comment] 2023-12-13 21:24
@dmi-w I think this is by design. Have you seen the behavior like what you expect in other Terraform resources?

Run the same terraform as step 3. I would expect resource google_cloud_run_v2_service to redeploy the service with my docker image change (that occured in step 4), but it doesn't because the image has the same name.

**Comment by dmi-w** [comment] 2023-12-14 09:09
@edwardmedia Some terraform resource use a stronger link than just the name to point to another resource, like an ID. This would allow you to do a check of the image content using its hash (SHA) instead of just the name to detect changes. Because when the image has a different SHA, it is intrinsically a different ressource.

**Comment by edwardmedia** [comment] 2024-01-14 15:16
@dmi-w do you have a specific example that illustrates [the way ](https://github.com/hashicorp/terraform-provider-google/issues/16679#issuecomment-1855456402)it works?

**Comment by edwardmedia** [comment] 2024-01-18 13:17
@dmi-w below is what the api accepts for the [image](https://cloud.google.com/run/docs/reference/rest/v2/Container). Even if all registries expose hash data, considering the terraform is mainly a pass-through tool, I don't believe checking SHA to detect changes for all different registries would be a implemented in the near future.

```
Required. Name of the container image in Dockerhub, Google Artifact Registry, or Google Container Registry. If the host is not provided, Dockerhub is assumed.
```

You may create an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) so the request could be triage. This is not a bug and I close this now

**Closed by edwardmedia** 2024-01-18 13:17 UTC
Labels: bug, waiting-response
