### ISSUE TITLE
Google-Beta Provider FQDN Firewall Quota Exceeded Error

### ISSUE THREAD

**Issue by ZacharyU-1** [hashicorp/terraform-provider-google#15164] opened 2023-07-13 20:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform latest version 

### Affected Resource(s)

google_compute_firewall_policy_rule
google_compute_firewall_policy

### Expected Behavior

I was expecting it to create my firewall policy correctly (which it did). But then also add my FQDN firewall rules to this firewall policy. 

### Actual Behavior

It creates the firewall policy perfectly. It then creates many of the firewall rules correctly. However, after sometime I get the following error: 

```Error: Error creating FirewallPolicyRule: operation received error: error code "QUOTA_EXCEEDED", message: Quota 'FIREWALL_POLICY_FQDNS' exceeded.  Limit: 100.0 globally.```

It appears as if I can not create more than 100 fqdn firewall rules on a firewall policy

### Steps to Reproduce

Create a GCP firewall Policy with terraform
Add over 100 FQDN firewall rules to this policy

### References

This looked rather similar to these issues as well :
https://github.com/hashicorp/terraform-provider-google/issues/14859
https://github.com/hashicorp/terraform-provider-google/issues/10215
https://github.com/hashicorp/terraform-provider-google/issues/9980

**Comment by edwardmedia** [comment] 2023-07-14 15:08
@ZacharyU-1 this looks like an api behavior. Have you checked the quota of `FIREWALL_POLICY_FQDNS` for your project?

**Comment by ZacharyU-1** [comment] 2023-07-14 15:35
@edwardmedia I have been looking to find the quota for the `FIREWALL_POLICY_FQDNS` but haven't been able to find it yet. 

When looking through the google docs I noticed they have a hard limit of 100 `destination domain names per firewall rule`. However, I don't have any firewall rules with more than 100 FQDN domain names.

I have more than 100 firewall rules, which when added together are over 100 FQDN destination domain names. But I don't have 1 single rule with more than 100 destination domain names

Might be more of a google issue, as you are saying.

**Comment by edwardmedia** [comment] 2023-07-14 22:57
@ZacharyU-1 based on what you stated below, it seems the provider works as expected. The issue you were encountering is most likely about how to use the gcp features. Closing this issue now. Feel free to reopen if you believe the issue is in the provider. Thanks 

```
It creates the firewall policy perfectly. It then creates many of the firewall rules correctly.
```

**Closed by edwardmedia** 2023-07-14 22:57 UTC
Labels: bug
