### ISSUE TITLE
Use actual nested objects in resource_cloudiot_registry

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#6085] opened 2020-04-09 17:51 UTC
Several elements in this resource's schema look like this:
```
			"state_notification_config": {
				Type:     schema.TypeMap,
				Optional: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"pubsub_topic_name": {
							Type:             schema.TypeString,
							Required:         true,
							DiffSuppressFunc: compareSelfLinkOrResourceName,
						},
					},
				},
			},
```

This is wrong- it should be a `TypeList` with `MaxItems: 1`. Maps don't actually check nested elem schemas at plan-time, so a user could put anything they want in the map (including omitting required fields) and the plan would still succeed.

**Comment by rileykarson** [comment] 2021-10-19 19:44
Doing this in a compatible way will be a lot more work than `size/S` imo, and I think that a hard break (changing the field types in place) is an unacceptable outcome here. The problem is that the user state will get messed up meaning they need to manually remove the resource from state, then config, then upgrade their provider, then add it back, and then import it.

I'm gonna size it up and disqualify from `4.0.0`, since I don't believe we would have moved it in to the release given the amount of work we'd need. We could consider adding a correct version of the resource under a different Terraform name (`google_cloudiot_device_registry`) and deprecating the current iteration if it proved important.

**Comment by c2thorn** [comment] 2023-05-23 18:08
Closing due to IoT Core retirement and https://github.com/hashicorp/terraform-provider-google/issues/13826

**Closed** 2023-05-23 18:07 UTC
Labels: breaking-change, size/l
