### ISSUE TITLE
Compute instances can't be added to an existing instance group 

### ISSUE THREAD

**Issue by ognemirivanov** [hashicorp/terraform-provider-google#14157] opened 2023-03-31 07:24 UTC
Greetings,

I'm encountering an issue with Terraform GCP. I've successfully created virtual machines from an instance template using the "google_compute_instance_from_template" resource with count= var.num_instances, where the number of instances is set in a .tfvars file. However, I'm having trouble adding these newly created VMs to an existing unmanaged instance group.

To add the new VMs to the instance group, I used the following code:

instances = matchkeys(
   google_compute_instance_from_template.compute_instance.*.self_link,
   google_compute_instance_from_template.compute_instance.*.zone,
   [var.zone_id]
)

Unfortunately, when I applied these changes, the new VMs were not added to the instance group. I had to apply the changes a second time to add the VMs to the instance group.

Can you suggest a solution to this issue so that I can complete all changes with a single "terraform apply" command?

Thank you for your assistance.
 

### Affected Resource(s)

google_compute_instance_group

b/314616700

**Comment by edwardmedia** [comment] 2023-03-31 16:17
It appears there is a bug here. Adding an existing instance isn't working. I can use below steps to repro the issue

steps:
1. terraform apply
2. switching instances (comment and uncomment two lines)
3. terraform apply ---> receiving below error, can't add existing instances
4. terraform destroy & apply ---> works with two instances

```
│ Error: Error invalid instance URLs: [projects/sunedward-tf-host/zones/us-central1-c/instances/issue14157-vm2 projects/sunedward-tf-host/zones/us-central1-c/instances/issue14157-vm1]
│ 
```

```tf
resource "google_compute_instance_group" "staging_group" {
  name      = "issue14157-instance-group"
  zone      = "us-central1-c"
  instances = [google_compute_instance.staging_vm.id]
 // instances = [google_compute_instance.staging_vm.id, google_compute_instance.staging_vm2.id]
  named_port {
    name = "http"
    port = "8080"
  }

  named_port {
    name = "https"
    port = "8443"
  }

  lifecycle {
    create_before_destroy = true
  }
}

data "google_compute_image" "debian_image" {
  family  = "debian-11"
  project = "debian-cloud"
}

resource "google_compute_instance" "staging_vm" {
  name         = "issue14157-vm1"
  machine_type = "e2-medium"
  zone         = "us-central1-c"
  boot_disk {
    initialize_params {
      image = data.google_compute_image.debian_image.self_link
    }
  }

  network_interface {
    network = "default"
  }
}


resource "google_compute_instance" "staging_vm2" {
  name         = "issue14157-vm2"
  machine_type = "f1-micro"
  zone         = "us-central1-c"
  boot_disk {
    initialize_params {
      image = data.google_compute_image.debian_image.self_link
    }
  }

  network_interface {
    network = "default"
  }
}
```

**Comment by edwardmedia** [comment] 2023-03-31 16:20
@rileykarson is this behavior by design?

**Comment by edwardmedia** [comment] 2023-03-31 16:40
@rileykarson below is the plan for the addition

```
  ~ resource "google_compute_instance_group" "staging_group" {
        id        = "projects/sunedward-tf-host/zones/us-central1-c/instanceGroups/issue14157-instance-group"
      ~ instances = [
          - "https://www.googleapis.com/compute/v1/projects/sunedward-tf-host/zones/us-central1-c/instances/issue14157-vm1",
          + "projects/sunedward-tf-host/zones/us-central1-c/instances/issue14157-vm1",
          + "projects/sunedward-tf-host/zones/us-central1-c/instances/issue14157-vm2",
        ]
        name      = "issue14157-instance-group"
        # (5 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

**Comment by rileykarson** [comment] 2023-03-31 16:46
Thanks! This is before the apply that fails (#1) or succeeds (#2)?

**Comment by edwardmedia** [comment] 2023-03-31 16:55
@rileykarson above is for fails (#1) . From the log, I do not see addInstance() is called. 

here is the plan & apply for #2 in creation.

```
  # google_compute_instance_group.staging_group will be created
  + resource "google_compute_instance_group" "staging_group" {
      + id        = (known after apply)
      + instances = (known after apply)
      + name      = "issue14157-instance-group"
      + network   = (known after apply)
      + project   = (known after apply)
      + self_link = (known after apply)
      + size      = (known after apply)
      + zone      = "us-central1-c"

      + named_port {
          + name = "http"
          + port = 8080
        }
      + named_port {
          + name = "https"
          + port = 8443
        }
    }
```

```
 POST /compute/v1/projects/myproject/zones/us-central1-c/instanceGroups/issue14157-instance-group/addInstances?alt=json&prettyPrint=false HTTP/1.1
 Host: compute.googleapis.com
 {
  "instances": [
   {
    "instance": "https://compute.googleapis.com/compute/v1/projects/myproject/zones/us-central1-c/instances/issue14157-vm2"
   },
   {
    "instance": "https://compute.googleapis.com/compute/v1/projects/myproject/zones/us-central1-c/instances/issue14157-vm1"
  }
 ]
}
```

**Comment by rileykarson** [comment] 2023-03-31 16:56
Thanks! This *is* likely an issue on our end in that case as the plan looks correct.

**Comment by zli82016** [comment] 2023-04-03 21:52
Unassigning myself as I wasn't able to work on this one last week

**Comment by dqwork** [comment] 2023-09-29 13:52
Any news on this?

**Comment by Gvantsats** [comment] 2023-12-04 14:46
Problem with `Error: Error invalid instance URLs: [projects/myprojectt/zones/us-central1-c/instances/issue14157-vm2 projects/myproject/zones/us-central1-c/instances/issue14157-vm1]` is that instead of `vm.id` `vm.self_link` should be specified.

As for original issue it seems to be a different problem.
Can you provide your terraform script that creates vms, creates instance group and then adds vms to instance group? Also if you get any error message can you provide it too?

**Comment by yb-jmogavero** [comment] 2024-01-26 18:57
I have a similar issue, though without receiving any error because I'm using `vm.self_link` 

I have an unmanaged instance group, and when the VM in the group is replaced, the instance group is not updated with the new VM until a second plan/apply is run.  The first plan does see that the instance group needs to be updated, and flags the outgoing instances as being removed, with new instances as `known after apply`

From the plan output:

`  # google_compute_instance_group.wazuh_master will be updated in-place
  ~ resource "google_compute_instance_group" "wazuh_master" {
        id          = "projects/my-project/zones/us-west1-a/instanceGroups/wazuh-manager-master"
      ~ instances   = [
          - "https://www.googleapis.com/compute/v1/projects/my-project/zones/us-west1-a/instances/wazuh-manager-master",
        ] -> (known after apply)
        name        = "wazuh-manager-master"
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)`

My instance group `depends_on` the instance that it is a member of, so it should always update after the instance is created, but simply fails to do so until a second plan is run.  

I was able to sort of work around this issue by using a lifecycle `replace_triggered_by` but it's really awkward because I have a whole chain of load balancing resources (backend service, health check, tcp proxy, etc) that also need to be triggered to be replaced just because the instance is replaced.  It's less impactful just to run a second apply, but that makes it not very CI/CD friendly.  

Seems like it's a bug where the provider is not adding the instances after updating in place?

**Comment by Cheriit** [comment] 2024-02-13 15:13
Hi! We've added new `google_compute_instance_group_membership` that's goal is to resolve similar issues ( #9930 and # #8605). @ognemirivanov can you confirm if that's also solving your issue?

**Comment by slevenick** [comment] 2024-02-22 15:03
Closed via https://github.com/GoogleCloudPlatform/magic-modules/pull/9891

**Closed by slevenick** 2024-02-22 15:03 UTC
Labels: size/s, persistent-bug, forward/linked, service/compute-networking-ig
