### ISSUE TITLE
Failing test(s): TestAccSqlDatabaseInstance_ActiveDirectory

### ISSUE THREAD

**Issue by roaks3** [hashicorp/terraform-provider-google#13517] opened 2023-01-18 18:34 UTC
### Affected Resource(s)
* google_sql_database_instance

Failure rate: 100%, for the full history that we can see in TeamCity

Impacted tests:
- TestAccSqlDatabaseInstance_ActiveDirectory

Nightly builds:
- [Link](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=368190&tab=buildResultsDiv&buildTypeId=GoogleCloud_ProviderGoogleCloudGoogleProject#testNameId-5904787966955611785)

Message:

```
------- Stdout: -------
=== RUN   TestAccSqlDatabaseInstance_ActiveDirectory
=== PAUSE TestAccSqlDatabaseInstance_ActiveDirectory
=== CONT  TestAccSqlDatabaseInstance_ActiveDirectory
    provider_test.go:307: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error waiting for Create Instance: 
        
        
          with google_sql_database_instance.instance-with-ad,
          on terraform_plugin_test.tf line 21, in resource "google_sql_database_instance" "instance-with-ad":
          21: resource "google_sql_database_instance" "instance-with-ad" {
        
--- FAIL: TestAccSqlDatabaseInstance_ActiveDirectory (103.41s)
FAIL
```

Internal error message provided by Cloud SQL team:
```
operation.status.message: "404 Not Found\n{\n  \"code\": 404,\n  \"errors\": [\n    {\n      \"domain\": \"global\",\n      \"message\": \"The resource \'projects/w4c1c7f8bbbf17de3p-tp\' was not found\",\n      \"reason\": \"notFound\"\n    }\n  ],\n  \"message\": \"The resource \'projects/w4c1c7f8bbbf17de3p-tp\' was not found\",\n  \"status\": \"NOT_FOUND\"\n}"
operation.type: PREPARE_TENANT_PROJECT
```

Internal ticket with Cloud SQL team (contains some screenshots with slightly more info): b/264929444

Notes:

I was not able to find `w4c1c7f8bbbf17de3p-tp` ever mentioned in our logs, and along with its name and the `PREPARE_TENANT_PROJECT` type, it appears to be a tenant project used internally for the SQL instance.

We don't seem to see this error with the other SQL tests, and one of the main differences with this particular test is the use of `active_directory_config` config. We seem to have trouble with Active Directory in our tests, so this could be related to some of those issues (ie. Active Directory setup might not be working properly prior to the test running).

Other tickets related to Active Directory tests:
* https://github.com/GoogleCloudPlatform/magic-modules/pull/6368
* https://github.com/hashicorp/terraform-provider-google/issues/9238
* https://github.com/hashicorp/terraform-provider-google/issues/8660
* https://github.com/hashicorp/terraform-provider-google/issues/7159

b/299600873

**Comment by roaks3** [comment] 2023-01-18 18:54
^ Note that the PR above will skip this test while it is investigated

**Comment by melinath** [comment] 2023-10-16 17:30
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/16261

**Closed by melinath** 2023-10-16 17:30 UTC
Labels: size/s, test-failure, forward/linked, service/sqladmin, test-failure-100
