### ISSUE TITLE
TF deletes uploaded file

### ISSUE THREAD

**Issue by Vihar1** [hashicorp/terraform-provider-google#16546] opened 2023-11-16 08:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

2023-11-15T07:49:46.701Z [INFO]  CLI command args: []string{"version", "-version"}
2023-11-15T07:49:46.729Z [INFO]  Terraform version: 1.5.7
2023-11-15T07:49:46.729Z [DEBUG] using github.com/hashicorp/go-tfe v1.26.0
2023-11-15T07:49:46.729Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-11-15T07:49:46.729Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-11-15T07:49:46.729Z [DEBUG] using github.com/zclconf/go-cty v1.12.2

### Affected Resource(s)

* google_storage_bucket_object

### Terraform Configuration Files

```tf
module "bucket" {
  source        = "../fabric/modules/gcs"
  project_id    = var.project_id
  name          = "${var.bucket_name}-2tier-webapp-${var.project_id}"
  location      = var.region
  storage_class = "REGIONAL"
}

resource "google_storage_bucket_object" "upload_app_files" {
  for_each = fileset("../app/", "**")
  name     = "2tier-webapp/${each.value}"
  source   = "../app/${each.value}"
  bucket   = module.bucket.name
}
```

### Debug Output

https://gist.github.com/Vihar1/fcae8d0b066a0a352a63c2bef7a324ed

2023-11-15T08:11:40.313Z [TRACE] plan: google_storage_bucket_object.upload_app_files["startup-script.sh"] treating Create change as CreateThenDelete change to match with earlier plan

### Expected Behavior

When a modified version of a file which is already in the bucket is uploaded, the file gets uploaded.

### Actual Behavior

When the file to be uploaded to the bucket has no previous version in the bucket, the uploads always succeed. 
However, when a modified version of a file which is already in the bucket is uploaded, the file gets uploaded and then deleted. 

### Steps to Reproduce

1. Create bucket and upload files to this bucket. 
2. Modify a file and apply TF again to upload the modified file.

### References

* #0000

**Comment by edwardmedia** [comment] 2023-11-16 15:03
@Vihar1 did you enable the [versioning](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#enabled) on the bucket?

**Comment by Vihar1** [comment] 2023-11-16 16:00
> @Vihar1 did you enable the [versioning](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#enabled) on the bucket?
> 
> Instead of the module, can you provide a bucket resource and repro the issue?

Versioning is off, but not needed. We need to remove/overwrite the old file and upload the new one.

I've tested with TF resources, but ended up with the same outcome:

`resource "google_storage_bucket" "bucket" {
  project       = var.project_id
  name          = "${var.bucket_name}-2tier-webapp-${var.project_id}"
  location      = var.region
  storage_class = "REGIONAL"
}`

Gists:
1st upload, success: https://gist.github.com/Vihar1/c9daab0e57ea0ab88527ce3f29194f9c
2nd upload, removed: https://gist.github.com/Vihar1/589972f04953e893a508692a6a3a60d6

**Comment by edwardmedia** [comment] 2023-11-16 18:45
@Vihar1 what do you see if you do this with gsutil?

```
However, when a modified version of a file which is already in the bucket is uploaded, the file gets uploaded and then deleted.
```

**Comment by Vihar1** [comment] 2023-11-16 19:00
gsutil works fine, it doesn't matter if I upload the same file or a modified version.
We configure the bucket as described, really basic config.
If we delete the bucket, recreate it again, and upload to it, it works every time. Also works if we use gcloud copy.

**Comment by edwardmedia** [comment] 2023-11-16 19:39
@Vihar1 I have no clue what the module looks like. Is [google_storage_bucket](google_storage_bucket) the resource we are talking about? Are you able to create a simple config that I can use to repro the issue?

**Comment by Vihar1** [comment] 2023-11-17 08:40
Yes.

I now have created a brand new config with google_storage_bucket and tested the upload 3 times, all succeeded. Then I switched to the Fabric gcs module, tested several times, all succeeded.

Then I modified a file in the existing config, and it first uploaded, then on another modification, it removed the file again. The other solutions involved in the old config are nothing fancy: a VM template, VMs, load balancer, etc. Nothing else to write to the bucket or modify it in any ways, just a startup script to download files from the bucket.

Do you have any idea how to proceed?

**Comment by edwardmedia** [comment] 2023-11-17 14:31
@Vihar1 sorry no clue. You probably want to proceed with baby steps to compare and isolate the changes.

**Comment by edwardmedia** [comment] 2023-11-20 18:30
@Vihar1 closing this now. As you discover, the resource works as by design. Feel free to reopen if you see otherwise.

**Closed by edwardmedia** 2023-11-20 18:30 UTC
Labels: bug, waiting-response, service/storage, forward/review
