### ISSUE TITLE
google_compute_url_map is requiring default_service and will not let me use default_url_redirect

### ISSUE THREAD

**Issue by mwohlin** [hashicorp/terraform-provider-google#7661] opened 2020-10-28 21:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.20
provider.google v2.5.0

### Affected Resource(s)

* google_compute_url_map

### Terraform Configuration Files

```tf
provider "google" {
}

resource "google_compute_url_map" "url_map" {
  name        = join("-", ["http-https-url-map", var.application])
  description = "This is a redirect URL map"

  default_url_redirect {
    redirect_response_code = "PERMANENT_REDIRECT"
    https_redirect         = true
    strip_query            = false
  }
}
```

### Expected Behavior
It should produce a http-https redirect url map. 
Similar to this gcloud command line execution.
```
gcloud compute url-maps import name --global <<END
kind: compute#urlMap
name: http-https-url-map-prometheus
defaultUrlRedirect:
   redirectResponseCode: PERMANENT_REDIRECT
   httpsRedirect: True
END
```

### Actual Behavior
```
$ terraform plan

Error: Missing required argument

  on http-https-redirect.tf line 4, in resource "google_compute_url_map" "url_map":
   4: resource "google_compute_url_map" "url_map" {

The argument "default_service" is required, but no definition was found.


Error: Unsupported block type

  on http-https-redirect.tf line 8, in resource "google_compute_url_map" "url_map":
   8:   default_url_redirect {

Blocks of type "default_url_redirect" are not expected here.

```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment] 2020-10-28 22:00
@mwohlin your version of the provider is pretty old. Can you use the latest version to see if the issue is resolved?
```
provider.google v2.5.0
```

**Comment by mwohlin** [comment] 2020-10-28 22:14
Hi Edward, thank you for the quick response.
I did not provide a version for the Google Provider, so it said it downloaded the latest version available.
Are you aware if there is a more recent version of the Google provider, newer than 2.5?

I can try to upgrade my terraform to v13, but I was not ready to do that yet as we have a good bit of infrastructure already running on 12.

```$ terraform init

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google: version = "~> 2.5"

Terraform has been successfully initialized!
```

**Comment by edwardmedia** [comment] 2020-10-28 22:33
@mwohlin  Here is a [link](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.44.0) you can check what the provider versions are available

**Comment by mwohlin** [comment] 2020-10-29 14:15
@edwardmedia Thank you for the link. I set the google provider version to 3.44 and that did the trick.
```
$ terraform -v
Terraform v0.12.20
+ provider.google v3.44.0
```
I am able to run a plan and apply and create the url-map in a project.

Can you please look into why, as I posted above, without me specifying a version, Terraform told me it had installed the latest provider version of 2.5. This led me to believe I was actually running the latest version, when I was not.

**Comment by edwardmedia** [comment] 2020-10-29 15:51
@mwohlin I don't think Terraform does upgrade  automatically. Thinking of syntax differences between different versions, you might not want it being upgraded for you without your knowledge.... I am glad you found the fix, and I go ahead to close the issue then

**Closed by edwardmedia** 2020-10-29 15:51 UTC
Labels: bug
