### ISSUE TITLE
The `master_authorized_networks_config` block is only returning one `cidr_blocks` when using the google_container_cluster data source

### ISSUE THREAD

**Issue by fallard84** [hashicorp/terraform-provider-google#6128] opened 2020-04-16 15:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.24
+ provider.external v1.2.0
+ provider.google v3.17.0
+ provider.google-beta v3.17.0

### Affected Resource(s)

* data.google_container_cluster

### Terraform Configuration Files

```tf
data "google_container_cluster" "k8s_cluster" {
  name     = var.cluster_name
  project  = var.project
  location = "northamerica-northeast1-c"
}

output "k8s_cluster" {
  value = data.google_container_cluster.k8s_cluster
}

```

### Debug Output

https://gist.github.com/fallard84/31209413c8e2c43f5b64c1a9ff786521

### Expected Behavior

The `master_authorized_networks_config` block should return all `cidr_blocks`.

### Actual Behavior

The `master_authorized_networks_config` block is only returning one `cidr_blocks`

### Steps to Reproduce

1. Have a cluster with master authorized networks config enabled with at least 2 cidr_blocks configured. 
2. Use the code above and run`terraform refresh`

**Comment by edwardmedia** [comment] 2020-04-16 17:10
I can repro this. Below first is from `tf show` followed by its output
```
    master_authorized_networks_config {
        cidr_blocks {
            cidr_block   = "73.35.171.194/32"
            display_name = "net1"
        }
        cidr_blocks {
            cidr_block   = "73.35.171.195/32"
            display_name = "net2"
        }
    }
```
```
  "master_authorized_networks_config" = [
    {
      "cidr_blocks" = [
        {
          "cidr_block" = "73.35.171.195/32"
          "display_name" = "net2"
        },
      ]
    },
  ]
```

**Comment by rileykarson** [comment] 2020-04-16 20:24
@edwardmedia: Can you investigate whether importing a `google_container_cluster` resource has the same behaviour? The datasource keys into the same read method, so I'm surprised this isn't an issue in the resource as well.

**Comment by edwardmedia** [comment] 2020-04-16 21:23
@rileykarson below is from the import state
```
              }
            ],
            "master_authorized_networks_config": [
              {
                "cidr_blocks": [
                  {
                    "cidr_block": "73.35.171.194/32",
                    "display_name": "net1"
                  },
                  {
                    "cidr_block": "73.35.171.195/32",
                    "display_name": "net2"
                  }
                ]
              }
            ],
            "master_version": "1.14.10-gke.27",
```

**Comment by rileykarson** [comment] 2020-04-20 16:42
I couldn't see anything off- it's very unusual that the datasource doesn't work but the resource does, since they share the same code. Filed an issue upstream against the SDK, I'm blocking this issue on that. https://github.com/hashicorp/terraform-plugin-sdk/issues/395

**Comment by baelish** [comment] 2020-06-11 16:10
We're having issues updating the list of authorised networks, I imagine that would be related to this also. When the Terraform has a different list of CIDRs then what is configured on the cluster `terraform plan` doesn't detect differences. When it applies the Terraform for different changes then I can see that it correctly lists the CIDRs as they are configured on the cluster but still no changes are being marked for the authorised networks.

**Comment by roaks3** [comment] 2023-08-17 17:59
Note: It looks like the upstream issue was resolved

**Comment by edwardmedia** [comment] 2023-09-20 18:31
I have verified the issue is fixed. Closing now

**Closed by edwardmedia** 2023-09-20 18:31 UTC
Labels: bug, upstream-terraform, service/container, forward/review
