### ISSUE TITLE
google_bigquery_table import is failing without any meaningful error

### ISSUE THREAD

**Issue by g-nikolay** [hashicorp/terraform-provider-google#10471] opened 2021-11-01 23:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.9
on linux_amd64
provider registry.terraform.io/hashicorp/google v3.90.0

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "dataset_gcp_res_import_test" {
  labels = {
    from = "my-test"
  }
  description = "my test"
  default_table_expiration_ms = 7200000
  location = "us-west1"
  dataset_id = "dataset_gcp_import_test"
}

resource "google_bigquery_table" "table_gcp_res_import_test" {
  dataset_id = google_bigquery_dataset.dataset_gcp_res_import_test.dataset_id
  table_id = "table_gcp_import_test"
}
```

### Debug Output

[gist](https://gist.github.com/g-nikolay/5060775b475b8e4d3b7cfe98bddca4c9)

### Actual Behavior

terraform is failing with the following message
```
│ Error: 1 error occurred:
│       * ForceNew: No changes for schema
│
│
│
│   with google_bigquery_table.table_gcp_res_import_test,
│   on main.tf line 11, in resource "google_bigquery_table" "table_gcp_res_import_test":
│   11: resource "google_bigquery_table" "table_gcp_res_import_test" {
│
```

### Steps to Reproduce

1. Create GCP bq and table
2. Import created resources using attached config
3. `terraform import`
4. `terraform plan`

### References

* #0000

**Comment by edwardmedia** [comment] 2021-11-02 19:46
@g-nikolay what config and command did you use? 

> Import created resources using attached config

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table#import

**Comment by g-nikolay** [comment] 2021-11-02 20:50
@edwardmedia basically I had 2 options - 1 manually created resources, 2 using dm config below:
```yaml
resources:
- type: gcp-types/bigquery-v2:datasets
  name: dataset-gcp-res-import-test
  properties:
    labels:
      from: my-test
    defaultTableExpirationMs: 7200000
    location: us-west1
    description: 'my test'
    datasetReference:
      datasetId: dataset_gcp_import_test
- type: gcp-types/bigquery-v2:tables
  name: table-gcp-res-import-test
  properties:
    datasetId: $(ref.dataset-gcp-res-import-test.datasetReference.datasetId)
    tableReference:
      tableId: table_gcp_import_test
```

**Comment by edwardmedia** [comment] 2021-11-03 17:48
@g-nikolay have you tried `import` following the link I provided [above](https://github.com/hashicorp/terraform-provider-google/issues/10471#issuecomment-958114132)? If it still fails, can you share your config and the command you are using?

**Comment by g-nikolay** [comment] 2021-11-03 17:53
@edwardmedia sure, this is import commands
```
terraform import google_bigquery_dataset.dataset_gcp_res_import_test my-project/dataset_gcp_import_test
terraform import google_bigquery_table.table_gcp_res_import_test my-project/dataset_gcp_import_test/table_gcp_import_test
```

TF config is attached to ticket, DM config is attached to the comment above

**Comment by edwardmedia** [comment] 2021-11-03 18:26
@g-nikolay can you try below config for your import? 

```tf
resource "google_bigquery_dataset" "dataset_gcp_res_import_test" {
}

resource "google_bigquery_table" "table_gcp_res_import_test" {
}
```

**Comment by g-nikolay** [comment] 2021-11-03 18:41
@edwardmedia getting this output
```
│ Error: Missing required argument
│
│   on main.tf line 1, in resource "google_bigquery_dataset" "dataset_gcp_res_import_test":
│    1: resource "google_bigquery_dataset" "dataset_gcp_res_import_test" {
│
│ The argument "dataset_id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on main.tf line 4, in resource "google_bigquery_table" "table_gcp_res_import_test":
│    4: resource "google_bigquery_table" "table_gcp_res_import_test" {
│
│ The argument "table_id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on main.tf line 4, in resource "google_bigquery_table" "table_gcp_res_import_test":
│    4: resource "google_bigquery_table" "table_gcp_res_import_test" {
│
│ The argument "dataset_id" is required, but no definition was found.
```

**Comment by g-nikolay** [comment] 2021-11-03 21:20
@edwardmedia import then plan as it's described in repro steps

**Comment by edwardmedia** [comment] 2021-11-03 21:56
@g-nikolay **import** brings the attributes to the **state**. It does not auto fill the **config**. I guess you need to manually add them into config before you run `plan`. Does that make sense?

**Comment by g-nikolay** [comment] 2021-11-03 22:19
@edwardmedia sorry, I'm a little bit confused. I have created ticket with the config which I used for import and plan, then you asked me test again with empty config. Is there anything wrong with the config from the bug description?

**Comment by edwardmedia** [comment] 2021-11-04 15:57
@g-nikolay the config in this [block](https://github.com/hashicorp/terraform-provider-google/issues/10471#issue-1041727817) is used to create resource (`plan` and `apply`). The config in this [block](https://github.com/hashicorp/terraform-provider-google/issues/10471#issuecomment-959806893) is used to `import`. The subject of this issue is `import is failing`. Which config did you use for the `import`?

**Comment by g-nikolay** [comment] 2021-11-04 18:02
@edwardmedia please create bq dataset and table either using DM config above or manually, then try import and plan using terraform config from the ticket description.

**Comment by edwardmedia** [comment] 2021-11-04 21:19
@g-nikolay what do you mean `import and plan`? I am **not** going to use the **same** config for `terraform import` and `terraform plan`. Like I said [here](https://github.com/hashicorp/terraform-provider-google/issues/10471#issuecomment-961181818), the config code is different. Does this make sense?

>  try import and plan using terraform config from the ticket description.

**Comment by slevenick** [comment] 2021-11-05 17:38
I think the confusion here is that the import command *does* succeed, but the next time `terraform plan` is run it causes the error. This is likely due to some failure in the import function for this resource (or the customize diff that I assume is being called here), and causes the resource to be unmanageable.

Regardless of where exactly the error is happening (import or plan) this is definitely a bug in the provider and should be fixed

**Comment by edwardmedia** [comment] 2021-11-06 12:31
I see where the problem is. Thanks @slevenick

**Closed** 2021-11-08 21:50 UTC
Labels: bug
