### ISSUE TITLE
Error when provision read replica with binary log enabled

### ISSUE THREAD

**Issue by muhammadaldyan** [hashicorp/terraform-provider-google#12148] opened 2022-07-21 02:00 UTC
I used this module to provision my cloudsql https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance

1. Provision master and read replica using terraform module above (version 5.7)
2. Enable binary log on read replica using gcloud command
3. But when running terraform apply, the error occurred :

│ Error: Error, failed to update instance settings for : googleapi: Error 400: Invalid request: Binary log must be disabled when backup is disabled or the instance must be a replica instance with a MySQL 5.7 or above version., invalid
│
│   with module.mysql.google_sql_database_instance.replicas[0],
│   on ../../../../modules/google-cloud-sql/mysql/read_replica.tf line 39, in resource "google_sql_database_instance" "replicas":
│   39: resource "google_sql_database_instance" "replicas" {
│
╵

this issue related to : https://github.com/hashicorp/terraform-provider-google/issues/9371

i  tried using version 3.75.0 and latest version and error still on there.
also tried to create case support on GCP. 

and this is he said :
I have been looking into this matter by attempting to reproduce the behavior you encounter, and I have been able to see the same error message you’re retrieving from executing your Terraform script.

Based on the verbose logs you provided, as well as the findings from the Cloud SQL Product Team, we were able to ascertain that the issue is present on Terraform, as it does not include the “instanceType” parameter which is required in order for the operation to succeed, as this can only be performed for instances of type "READ_REPLICA_INSTANCE", or for instances with binary log disabled.

Given that this issue is caused by the Terraform provider making the API request, I suggest that you open an issue with the Terraform Team in their official GitHub repository [1] so that they may fix this issue in order to include the required “instanceType” parameter.

Alternatively, the Terraform team could switch from using the “PUT” method, which uses the instance.update method [2], to the “PATCH” method, which uses the instances.patch method [3]. The latter automatically populates the fields that aren’t included within the request body, and should not cause the error message you’re encountering when the “instanceType” parameter is missing.

[1]: https://github.com/hashicorp/terraform-provider-google/issues
[2]: https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/update
[3]: https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/patch
[4]: https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#SqlInstanceType

**Comment by edwardmedia** [comment] 2022-07-21 13:37
@muhammadaldyan can you post the terraform config and gcloud command you used so I can repro the issue?

**Comment by muhammadaldyan** [comment] 2022-07-25 04:29
[verbose.txt](https://github.com/hashicorp/terraform-provider-google/files/9178021/verbose.txt)
[tf.txt](https://github.com/hashicorp/terraform-provider-google/files/9178022/tf.txt)
[log.txt](https://github.com/hashicorp/terraform-provider-google/files/9178023/log.txt)
[plan (2).txt](https://github.com/hashicorp/terraform-provider-google/files/9178024/plan.2.txt)
[log-with-verbose.txt](https://github.com/hashicorp/terraform-provider-google/files/9178025/log-with-verbose.txt)

**Comment by muhammadaldyan** [comment] 2022-07-25 04:32
[terraform.txt](https://github.com/hashicorp/terraform-provider-google/files/9178038/terraform.txt)
[terraform-tfvars.txt](https://github.com/hashicorp/terraform-provider-google/files/9178039/terraform-tfvars.txt)
[variables.txt](https://github.com/hashicorp/terraform-provider-google/files/9178040/variables.txt)
[versions.txt](https://github.com/hashicorp/terraform-provider-google/files/9178041/versions.txt)
[main.txt](https://github.com/hashicorp/terraform-provider-google/files/9178042/main.txt)

**Comment by muhammadaldyan** [comment] 2022-07-25 04:41
[main.txt](https://github.com/hashicorp/terraform-provider-google/files/9178062/main.txt)
[terraform.txt](https://github.com/hashicorp/terraform-provider-google/files/9178063/terraform.txt)
[terraform-tfvars.txt](https://github.com/hashicorp/terraform-provider-google/files/9178064/terraform-tfvars.txt)
[variables.txt](https://github.com/hashicorp/terraform-provider-google/files/9178065/variables.txt)
[versions.txt](https://github.com/hashicorp/terraform-provider-google/files/9178066/versions.txt)

gcloud command :

gcloud sql instances patch --enable-bin-log db-replica-1

**Comment by edwardmedia** [comment] 2022-07-25 16:01
@muhammadaldyan I am curious why you want to update the config via gcloud command (step 2)? Was the error from replica instance? What the config for your master? Can you try update the master with below config first to see if your issue is resolved?

```
    backup_configuration {
        binary_log_enabled = true
        enabled = true
    }
```

**Comment by caiodelgadonew** [comment] 2022-07-27 13:00
I can confirm that this happens on any change of the settings for the `google_sql_database_instance` in a read replica, 

We upgraded from provider 4.14 to 4.30, but we also tried lower versions from 4.25 up to 4.30, all them have the same issue.

My solution was to add a `lifecycle` to `ignore_changes` on the changed settings... but it is only a workaround.

Plan
```bash

  # google_sql_database_instance.recruitment-1-ro-1 will be updated in-place
  ~ resource "google_sql_database_instance" "recruitment-1-ro-1" {
        id                            = "recruitment-1-ro-1"
        name                          = "recruitment-1-ro-1"
        # (13 unchanged attributes hidden)

      ~ settings {
            # (10 unchanged attributes hidden)

          - active_directory_config {}

            # (5 unchanged blocks hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
```

This is what solved for us (workaround)
```hcl
  lifecycle {
    ignore_changes = [
      settings["active_directory_config"]
    ]
  }
```

**Comment by edwardmedia** [comment] 2022-07-27 17:04
@muhammadaldyan any change in below statement, which one as an example? In your case, there is a change [here](https://github.com/hashicorp/terraform-provider-google/issues/9561) that might be related to yours

```
I can confirm that this happens on any change of the settings for the google_sql_database_instance in a read replica,
```

**Comment by edwardmedia** [comment] 2022-08-03 17:13
Closing assuming this is no longer an issue

**Closed by edwardmedia** 2022-08-03 17:13 UTC
Labels: bug, waiting-response

**Comment by caiodelgadonew** [comment] 2022-08-03 17:36
Hello @edwardmedia , that is still happening, I did not replied because you where not asking me about it.

I can get a new output if you need..

**Comment by muhammadaldyan** [comment] 2022-08-04 03:17
@edwardmedia yes it's still an issue.  and this is not working.  i used MySQL 5.7 (Cloudsql GCP)
 lifecycle {
    ignore_changes = [
      settings["active_directory_config"]
    ]
  }
