### ISSUE TITLE
Add Support for Integration Connectors

### ISSUE THREAD

**Issue by jenardn** [hashicorp/terraform-provider-google#15192] opened 2023-07-17 09:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Integration Connectors let you connect to various data sources from your integrations. With connectors, both Google Cloud services and other business applications are exposed to your integrations through a transparent, standard interface. As an integration developer, you can quickly connect to a growing pool of applications and systems without the need for protocol-specific knowledge or the use of custom code.

### New or Affected Resource(s)

* google_integration_connectors_connection
### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment] 2023-07-17 16:53
Docs: https://cloud.google.com/integration-connectors/docs/reference/rest

The natural naming of this API would be `google_connectors_connection` & similar

**Comment by bchamby** [comment] 2023-11-13 21:55
Is this a dupe of [16332](https://github.com/hashicorp/terraform-provider-google/issues/16332), which was recently fixed?

**Comment by rileykarson** [comment] 2023-11-13 22:03
Yep, thanks! Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/9328

**Closed by rileykarson** 2023-11-13 22:03 UTC
Labels: enhancement, new-resource, size/m, new-service, forward/review, service/integrationconnectors
