### ISSUE TITLE
Workbench Instance - Metadata forces recreate

### ISSUE THREAD

**Issue by kirksw** [hashicorp/terraform-provider-google#18469] opened 2024-06-18 11:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.5
on aarch64-apple-darwin
+ provider registry.terraform.io/hashicorp/google v5.33.0

### Affected Resource(s)

google_workbench_instance

### Terraform Configuration

```tf
resource "google_workbench_instance" "default" {
  name     = "workbench-test"
  location = "europe-west1-b"

  gce_setup {
    machine_type = "n1-standard-4"

    service_accounts {
      email = google_service_account.default.email
    }

    metadata = {
      idle-timeout-seconds = "3600"
    }
}
```

### Debug Output

-  if resource stopped 
```tf
~ resource "google_workbench_instance" "default" {
      ~ desired_state        = "STOPPED" -> "ACTIVE"
        id                   = "projects/<redacted>/locations/europe-west1-b/instances/<redacted>"
        name                 = "workbench-test"
        # (12 unchanged attributes hidden)

      ~ gce_setup {
          ~ metadata             = {
              - "proxy-byoid-url"            = "<redacted>-dot-europe-west1.notebooks.byoid.googleusercontent.com" -> null
```

- if running already
```tf
  # module.poc_product_categorization[0].google_workbench_instance.default will be updated in-place
  ~ resource "google_workbench_instance" "default" {
        id                   = "projects/<redacted>/locations/europe-west1-b/instances/<redacted>"
        name                 = "<redacted>"
        # (13 unchanged attributes hidden)

      ~ gce_setup {
          ~ metadata             = {
              - "proxy-byoid-url"            = "<redacted>-dot-europe-west1.notebooks.byoid.googleusercontent.com" -> null
                # (16 unchanged elements hidden)
```

### Expected Behavior

- With no desired state defined if instance is active, instance should stay active, likewise if stopped should stay stopped
- No update in-place should occur in relation to metadata.proxy-byoid-url

### Actual Behavior

Starts all instances on every apply, updates metadata.proxy-byoid-url to null.

### Steps to reproduce

1. `terraform apply`

b/348498822

**Comment by ggtisc** [comment] 2024-06-20 22:37
Confirmed issue!

After the resource was created when there aren't changes and ran a 2nd `terraform apply` it detects changes. This looks like a permadiff on `proxy-byoid-url`

**Comment by kirksw** [comment] 2024-06-25 07:50
> Confirmed issue!
> 
> After the resource was created when there aren't changes and ran a 2nd `terraform apply` it detects changes. This looks like a permadiff on `proxy-byoid-url`

I would say there are two issues, what you have referenced - but also the default desired state behavior, which will start or stop all the instances (no possibility to just stay in the current state)

**Comment by bcreddy-gcp** [comment] 2024-07-17 20:16
The issue should be  fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/10900

Verified by the following:
Created a `google_workbench_instance` using the following config.
```
resource "google_workbench_instance" "default" {
  project = "<redacted>"
  name = "workbench-test"
  location = "us-west1-a"

  gce_setup {
    machine_type = "n1-standard-4"
    metadata = {
      idle-timeout-seconds = "3600"
    }
  }

}
```
`terraform plan` on the same config any number of times gave `No changes. Your infrastructure matches the configuration.`.

Added `desired_state        = "ACTIVE"` to the config.
`terraform plan` on the same config any number of times gave `No changes. Your infrastructure matches the configuration.`.

Updated `desired_state        = "STOPPED"` in the config.
```
  ~ update in-place

Terraform will perform the following actions:

  # google_workbench_instance.default will be updated in-place
  ~ resource "google_workbench_instance" "default" {
      ~ desired_state        = "ACTIVE" -> "STOPPED"

```
`terraform plan` on the same config any number of times gave `No changes. Your infrastructure matches the configuration.`.

Updated `desired_state        = "ACTIVE"` in the config.
```
  ~ update in-place

Terraform will perform the following actions:

  # google_workbench_instance.default will be updated in-place
  ~ resource "google_workbench_instance" "default" {
      ~ desired_state        = "STOPPED" -> "ACTIVE"

```
`terraform plan` on the same config any number of times gave `No changes. Your infrastructure matches the configuration.`.

**Closed** 2024-12-17 17:44 UTC
Labels: bug, forward/linked, service/notebooks
