### ISSUE TITLE
google_vpc_access_connector is missing fields for connecting to a subnet within a shared vpc

### ISSUE THREAD

**Issue by jonredmond** [hashicorp/terraform-provider-google#8612] opened 2021-03-04 10:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, there's no way to create a VPC access connector to a shared VPC in another project. There's a parameter for this in the [beta api](https://vpcaccess.googleapis.com/$discovery/rest?version=v1beta1).

### New or Affected Resource(s)

* google_vpc_access_connector

### Potential Terraform Configuration

```tf
  subnet = {
    name = "{SUBNET_NAME}"
    projectId = "{HOST_PROJECT_ID}"
  }
```

**Comment by msb** [comment] 2021-03-04 15:03
I note that [Google's recommended configuration for Static outbound IP addresses](https://cloud.google.com/run/docs/configuring/static-outbound-ip) does not seem to be possible without the suggested field.

**Comment by upodroid** [comment] 2021-03-05 22:16
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/8475

While you are waiting for terraform support, please use the legacy method for making vpc connectors work with shared vpc in the meanwhile.

https://cloud.google.com/functions/docs/networking/connecting-vpc#shared-vpc

**Comment by rileykarson** [comment] 2021-03-08 18:43
Closing, dupes https://github.com/hashicorp/terraform-provider-google/issues/8475 as @upodroid said

**Closed by rileykarson** 2021-03-08 18:43 UTC
Labels: enhancement
