### ISSUE TITLE
Failing test(s): TestAccDataSourceArtifactRegistryDockerImage

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#18955] opened 2024-08-01 16:37 UTC
### Impacted tests

- TestAccDataSourceArtifactRegistryDockerImage

### Affected Resource(s)

- google_artifact_registry_docker_image

### Failure rates

- 100% since 2024-07-13

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccDataSourceArtifactRegistryDockerImage
=== PAUSE TestAccDataSourceArtifactRegistryDockerImage
=== CONT  TestAccDataSourceArtifactRegistryDockerImage
    vcr_utils.go:152: Step 1/1 error: Error running pre-apply refresh: exit status 1
        Error: googleapi: Error 404: Requested entity was not found.
          with data.google_artifact_registry_docker_image.testDigest,
          on terraform_plugin_test.tf line 9, in data "google_artifact_registry_docker_image" "testDigest":
           9: data "google_artifact_registry_docker_image" "testDigest" {
--- FAIL: TestAccDataSourceArtifactRegistryDockerImage (4.12s)
FAIL
```

### Nightly build test history

https://hashicorp.teamcity.com/test/4451008058123925132?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

b/357621304

**Comment by brandonmichigangithub** [comment] 2024-08-15 23:30
We don't have access to this project and can't really see what the failures are caused by. 
Does the project actually have a "testDigest"?

**Comment by SarahFrench** [comment] 2024-08-16 10:24
Here is where [the "testDigest" datasource is in the codebase](https://github.com/GoogleCloudPlatform/magic-modules/blob/015939976ec0c44fd83b98cdff12e3cc6adbc67d/mmv1/third_party/terraform/services/artifactregistry/data_source_artifact_registry_docker_image_test.go#L72-L77)

The problem is that that data source is 404-ing

```
---[ REQUEST ]---------------------------------------
GET /v1/projects/cloudrun/locations/us/repositories/container/dockerImages/hello@sha256:7a6e0dfb0142464ce0ba14a2cfcac75e383e36f39f47539c870132c826314ad6?alt=json HTTP/1.1
Host: artifactregistry.googleapis.com
User-Agent: Terraform/1.8.3 (+https://www.terraform.io) Terraform-Plugin-SDK/2.33.0 terraform-provider-google/dev
Content-Type: application/json
Accept-Encoding: gzip
```

So the test will need to be updated to reference an existing resource

**Comment by melinath** [comment] 2024-11-08 22:51
This was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/11492

**Closed by melinath** 2024-11-08 22:51 UTC
Labels: size/s, test-failure, forward/linked, service/artifactregistry, test-failure-100
