### ISSUE TITLE
Add validation for resource names

### ISSUE THREAD

**Issue by natedogith1** [hashicorp/terraform-provider-google#12378] opened 2022-08-24 19:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Resource names should be validated during a plan.  [Searching the repo for "validateGCEName"](https://github.com/hashicorp/terraform-provider-google/search?q=validateGCEName) finds 19 resources that currently do this.

### New or Affected Resource(s)

* google_compute_disk 
* google_compute_health_check
* probably many others

### References

* #9113

**Comment by rileykarson** [comment] 2022-08-29 17:53
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/3580

**Closed by rileykarson** 2022-08-29 17:53 UTC
Labels: enhancement

**Comment by natedogith1** [comment] 2022-08-30 02:32
I didn't notice #3580.  Should I open a separate issue for each resource that doesn't have its name validated? (or just one for each naming convention, for instance all compute engine resource apparently have the same format: https://cloud.google.com/compute/docs/naming-resources#resource-name-format)

**Comment by rileykarson** [comment] 2022-08-30 17:55
If there are specific resources where you think the additional validation is valuable, please feel free! A general validation backfill isn't something our team is interested in at the moment, however.
