### ISSUE TITLE
Database Encryption Key are available but is not set

### ISSUE THREAD

**Issue by manuelsc0895** [hashicorp/terraform-provider-google#11591] opened 2022-04-26 19:22 UTC
### Community Note
I'm using google-beta providers to deploy a google_sql_database_instance.instance resource with an encryption key, there is no errors displayed executing terraform plan but this configuration doesn't take part of the plan as is showed in the image
![image](https://user-images.githubusercontent.com/104460780/165375770-dc0b96ea-890e-4a3c-b610-ca5f661a4a3d.png)
With the same terraform files but setting the use of the 4.15.0 version of the beta providers, the problem solves
![image](https://user-images.githubusercontent.com/104460780/165375945-f95aeaa9-8c21-42d4-bc43-33311a1526d4.png)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v.1.0.3

### Affected Resource(s)
google_sql_database_instance.instance resource

* google_beta 4.19.0

### Terraform Configuration Files
Asking to use the 4.15.0 google-bet providers version to deploy the resource.
![image](https://user-images.githubusercontent.com/104460780/165376342-5cc76d42-962b-4405-96b8-2297615a8384.png)

```tf
# Copy-paste your Terraform configurations here.
#
![image](https://user-images.githubusercontent.com/104460780/165375144-129e4ea1-149f-4ca1-9480-0eb16c0fc629.png)

# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by megan07** [comment] 2022-04-26 19:49
Closed as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11438

**Closed by megan07** 2022-04-26 19:49 UTC
Labels: bug
