### ISSUE TITLE
Unauthenticated access is disabled upon each Cloud Function replacement

### ISSUE THREAD

**Issue by fathom-piotr** [hashicorp/terraform-provider-google#18308] opened 2024-06-04 06:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.6.3
on linux_arm64
+ provider registry.terraform.io/hashicorp/google v5.25.0
+ provider registry.terraform.io/hashicorp/google-beta v5.30.0
+ provider registry.terraform.io/hashicorp/random v3.6.2

### Affected Resource(s)

google_cloud_run_service_iam_binding
google_cloudfunctions2_function

### Terraform Configuration

I'm using CDK, so here's the JSON output:
```json
{
  "resource": {
    "google_cloud_run_service_iam_binding": {
      "handler-allow-all-iam-binding": {
        "//": {
          "metadata": {
            "path": "smoke-tests-github-handler/handler-allow-all-iam-binding",
            "uniqueId": "handler-allow-all-iam-binding"
          }
        },
        "depends_on": [
          "google_cloudfunctions2_function.smoke-tests-github-handler"
        ],
        "location": "us-west1",
        "members": [
          "allUsers"
        ],
        "project": "...",
        "role": "roles/run.invoker",
        "service": "${google_cloudfunctions2_function.smoke-tests-github-handler.name}"
      }
    },
    "google_cloudfunctions2_function": {
      "smoke-tests-github-handler": {
        "//": {
          "metadata": {
            "path": "smoke-tests-github-handler/smoke-tests-github-handler",
            "uniqueId": "smoke-tests-github-handler"
          }
        },
        "build_config": {
          "entry_point": "handle_request",
          "runtime": "python38",
          "source": {
            "storage_source": {
              "bucket": "${google_storage_bucket.bucket-...-smoke-tests-github-handler-d15bad5a.name}",
              "object": "${google_storage_bucket_object.smoke-tests-github-handler-source.name}"
            }
          }
        },
        "description": "Handles requests from GitHub to schedule smoke DAG tests.",
        "labels": {
          "created-by": "${replace(replace(data.terraform_remote_state.cross-stack-reference-input-terraform-deployer.outputs.cross-stack-output-google_project_iam_memberterraform-service-account_roles-cloudfunctionsadmin-..._A40ED0ACmember, \"serviceAccount:\", \"\"), \"/[@\\\\.]/\", \"-\")}"
        },
        "lifecycle": {
          "replace_triggered_by": [
            "terraform_data.smoke-tests-github-handler_source_code_hash"
          ]
        },
        "location": "us-west1",
        "name": "smoke-tests-github-handler",
        "project": "...",
        "service_config": {
          "available_memory": "256M",
          "ingress_settings": "ALLOW_INTERNAL_AND_GCLB",
          "secret_environment_variables": [
            {
              "key": "WEBHOOK_SECRET",
              "project_id": "...",
              "secret": "...",
              "version": "latest"
            }
          ],
          "service_account_email": "${google_service_account.acct-serviceAccount-smoke-tests-github-handler-...-iam-gserviceaccount-com.email}",
          "timeout_seconds": 60,
          "vpc_connector": "${google_vpc_access_connector.smoke-dag-tests-vpc-connector.id}",
          "vpc_connector_egress_settings": "ALL_TRAFFIC"
        }
      }
    },
    "terraform_data": {
      "smoke-tests-github-handler_source_code_hash": {
        "//": {
          "metadata": {
            "path": "smoke-tests-github-handler/smoke-tests-github-handler_source_code_hash",
            "uniqueId": "smoke-tests-github-handler_source_code_hash"
          }
        },
        "triggers_replace": {
          "source_code_hash": "6b87bd16"
        }
      }
    }
  }
}
```

### Expected Behavior

When `terraform_data.smoke-tests-github-handler_source_code_hash` changes (it's calculated in CDKTF logic), the function is be replaced because we have:

```json
"lifecycle": {
  "replace_triggered_by": [
    "terraform_data.smoke-tests-github-handler_source_code_hash"
  ]
},
```

and the binding of granting `roles/run.invoker` to `allUsers` should still exist. The dependency between the binding and the function is explicitly expressed with:

```json
"depends_on": [
  "google_cloudfunctions2_function.smoke-tests-github-handler"
],
```
so it's weird that TF doesn't make sure the dependency is fulfilled.

### Actual Behavior

When `terraform_data.smoke-tests-github-handler_source_code_hash` changes, the function is replaced and the binding is lost. When retrying the deployment without any config changes, TF notices the binding is missing and offers to add it:

```
# google_cloud_run_service_iam_binding.handler-allow-all-iam-binding (handler-allow-all-iam-binding) will be updated in-place
~ resource "google_cloud_run_service_iam_binding" "handler-allow-all-iam-binding" {
      id       = "v1/projects/.../locations/us-west1/services/smoke-tests-github-handler/roles/run.invoker"
    ~ members  = [
        + "allUsers",
      ]
      # (5 unchanged attributes hidden)
  }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Deploying this plan fixes the issue.

### Steps to reproduce

See the attached config (it's incomplete, only for illustrative purposes).

1. Deploy the infra so that the function and the binding is in place.
2. Change`terraform_data.smoke-tests-github-handler_source_code_hash` and trigger a deployment- it should cause replacement of the function.
3. Observe that the `allUsers` binding is gone - it can be tested by either viewing the function's config in the GCP console, or making an unauthenticated call to the function.
4. Retry the deployment, and observe that the missing binding is added.

### References

* https://github.com/hashicorp/terraform-provider-google/issues/5833

I haven't found any note about this problem there.

b/345308816
b/345309297

**Comment by ggtisc** [comment] 2024-06-05 23:20
Confirmed issue!

This is the terraform code:

```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google-beta"
      version = "5.25.0"
    }
  }
}

resource "google_storage_bucket" "bucket_18308" {
  name     = "bucket-18308"
  location = "US"
}

resource "google_storage_bucket_object" "bucket_object_18308" {
  name   = "index18308.zip"
  bucket = google_storage_bucket.bucket_18308.name
  source = "./utils/google_cloud_repository/index.zip"
}

resource "terraform_data" "terraform_data_18308" {
  #input = 1
  triggers_replace = {
    source_code_hash = "6b87bd16"
  }
}

resource "google_vpc_access_connector" "vpc_access_connector_18308" {
  name          = "vpc-con"
  ip_cidr_range = "10.8.0.0/28"
  network       = "default"
}

resource "google_cloudfunctions2_function" "function_18308" {
  build_config {
    entry_point = "helloGET"
    runtime     = "nodejs16"
    source {
      storage_source {
        bucket = google_storage_bucket.bucket_18308.name
        object = google_storage_bucket_object.bucket_object_18308.name
      }
    }
  }
  description = "Handles requests from GitHub to schedule smoke DAG tests."

  lifecycle {
    replace_triggered_by = [
      terraform_data.terraform_data_18308
    ]
  }
  location = "us-central1"
  name     = "function-18308"
  project  = "my-project"
  service_config {
    available_memory = "256M"
    ingress_settings = "ALLOW_INTERNAL_AND_GCLB"
    timeout_seconds                 = 60
    vpc_connector_egress_settings  = "ALL_TRAFFIC"
    vpc_connector = google_vpc_access_connector.vpc_access_connector_18308.id
  }
}

resource "google_cloud_run_service_iam_binding" "crs_iam_binding_18308" {
  depends_on = [
    google_cloudfunctions2_function.function_18308
  ]
  location = "us-central1"
  members  = [
    "allUsers"
  ]
  project = "my-project"
  role    = "roles/run.invoker"
  service = google_cloudfunctions2_function.function_18308.name
}
```

This is the nodejs function code:

```
exports.helloGET = (req, res) => {
    res.status(200).send('Hello world!');
};
```

Steps to reproduce with terraform:

1. `terraform apply` (to create resources)
2. Uncomment the line that contains `#input = 1` and run a 2nd `terraform apply` (this step is optional)
3. `terraform apply` again

This returns an unexpected change on the `crs_iam_binding_18308` resource attempting to update the attribute `members = allUsers`

**Comment by melinath** [comment] 2024-06-06 22:50
This is unfortunately due to behavior in Terraform core: https://github.com/hashicorp/terraform-plugin-sdk/issues/122

There are some similar issues linked there related to other IAM resources. I believe you should be able to work around the problem by marking the IAM resource as `replace_triggered_by` the cloud function.

**Comment by melinath** [comment] 2024-06-06 22:50
Duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/122

**Closed by melinath** 2024-06-06 22:50 UTC
Labels: bug, forward/linked, service/run, service/cloudfunctions
