### ISSUE TITLE
Removal of google_compute_per_instance_config leaves instance in UNAPPLIED_DELETION state

### ISSUE THREAD

**Issue by przsab** [hashicorp/terraform-provider-google#14065] opened 2023-03-22 13:50 UTC
While adding a new per-instance-config forces creation of new instance, removal of that resource leaves MIG in UNAPPLIED_DELETION state instead of removing the instance as well. This causes discrepancy between local state and target size of MIG. 

Terraform v0.12.31
+ provider.google v4.54.0

### Affected Resource(s)

google_compute_per_instance_config

**Comment by przsab** [comment] 2023-03-23 09:52
Sure, please see the below configuration. Deploy, then reapply with `-var=primary=1`, it will not reapply with below Terraform error.

```
Error: Error waiting to create PerInstanceConfig: Error waiting for Creating PerInstanceConfig: Resource projects/project-1/zones/us-central1-c/instances/mig-inst-1 is already a member of projects/project-1/zones/us-central1-c/instanceGroupManagers/mig-0.
```

This is caused by instance config remaining in **UNAPPLIED_DELETION** state.

```
$ gcloud compute instance-groups managed instance-configs list mig-1 --zone=us-central1-b
---
fingerprint: 42WmSpB8rSM=
name: mig-inst-1
status: UNAPPLIED_DELETION
```

```
data "google_compute_subnetwork" "subnet" {
  name    = "subnet-1"
  project = "network-project-1"
  region  = "us-central1"
}

resource "google_compute_instance_template" "template" {
  machine_type = "f1-micro"
  disk {
    boot         = true
    source_image = "centos-cloud/centos-9"
    device_name  = "boot-disk"
  }

  network_interface {
    subnetwork         = data.google_compute_subnetwork.subnet.self_link
    subnetwork_project = data.google_compute_subnetwork.subnet.project
  }
}

locals {
  zones = ["us-central1-c", "us-central1-b"]
}

resource "google_compute_instance_group_manager" "group" {
  count              = 2
  name               = "mig-${count.index}"
  base_instance_name = "mig-${count.index}"
  wait_for_instances = true
  zone               = local.zones[count.index]
  target_size        = 0

  stateful_disk {
    device_name = "boot-disk"
    delete_rule = "ON_PERMANENT_INSTANCE_DELETION"
  }

  version {
    instance_template = google_compute_instance_template.template.self_link
  }

  update_policy {
    minimal_action                 = "REFRESH"
    most_disruptive_allowed_action = "RESTART"
    type                           = "OPPORTUNISTIC"
    max_unavailable_fixed          = 1
  }

  lifecycle {
    ignore_changes = [target_size]
  }
}

variable "primary" {
  default = 0
}

resource "google_compute_per_instance_config" "state" {
  name                           = "mig-inst-1"
  instance_group_manager         = google_compute_instance_group_manager.group[var.primary].name
  zone                           = local.zones[var.primary]
  minimal_action                 = "REFRESH"
  most_disruptive_allowed_action = "RESTART"
  preserved_state {
    metadata = {
      instance_template = google_compute_instance_template.template.self_link
    }
  }
}

```

**Comment by edwardmedia** [comment] 2023-03-24 02:23
I am able to repro this with below steps
1) tf apply
2) tf apply -var=primary=1
3) tf apply -var=primary=0

**Comment by roaks3** [comment] 2023-03-28 21:06
Unassigning myself because I wasn't able to get to this last week

**Comment by slevenick** [comment] 2023-03-29 19:40
@zli82016 assigning you as the bug on duty this week

**Comment by zli82016** [comment] 2023-04-03 16:44
I tried to add the field `remove_instance_state_on_destroy` to the google_compute_per_instance_config.state config, but got the same error. 

```
resource "google_compute_per_instance_config" "state" {
  name                           = "mig-inst-1"
  instance_group_manager         = google_compute_instance_group_manager.group[var.primary].name
  zone                           = local.zones[var.primary]
  minimal_action                 = "REFRESH"
  most_disruptive_allowed_action = "RESTART"
  remove_instance_state_on_destroy = true
  preserved_state {
    metadata = {
      instance_template = google_compute_instance_template.template.self_link
    }
  }
}
```

**Comment by zli82016** [comment] 2023-04-03 16:53
It looks like setting the update_mask accordingly for a url_param_only is currently not supported in magic-modules and need a workaround.

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/bigquerydatatransfer/Config.yaml#L60

**Comment by zli82016** [comment] 2023-04-03 18:38
Cut a ticket to the service team

https://b.corp.google.com/issues/276766134

**Comment by rileykarson** [comment] 2023-04-10 17:09
@zli82016: Unassigning since I don't think you're holding this anymore, please feel free to reassign yourself if you are!

**Comment by bmenasha** [comment] 2023-04-20 16:34
BTW: This is duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9042

**Comment by ScottSuarez** [comment] 2023-12-02 00:42
Closing as duplicate

**Closed by ScottSuarez** 2023-12-02 00:42 UTC
Labels: upstream, persistent-bug, forward/review, service/compute-managed
