### ISSUE TITLE
google_compute_forwarding_rule description field causes resource replacement

### ISSUE THREAD

**Issue by steven-edgar** [hashicorp/terraform-provider-google#16195] opened 2023-10-10 15:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.0
Google terraform provider v4.84.0

### Affected Resource(s)

* google_compute_forwarding_rule

### Terraform Configuration Files

```tf
resource "google_compute_forwarding_rule" {
  name = "example"
  description = "Forwarding rule description"
  region = "europe-west1"
  network = var.network
  ip_address = "1.2.3.4"
 target = var.cloudsql_psc_instance_attachment
  allow_psc_global_access = true 
}
```

### Expected Behavior

On first apply the forwarding rule is created, on second run the resource is left unchanged.

### Actual Behavior

```
# from https://github.com/hashicorp/terraform-provider-google/issues/16258

resource "google_compute_forwarding_rule" "default" {
  name                    = "psc-endpoint"
  description             = "My description"
  region                  = "us-central1"
  load_balancing_scheme   = ""
  target                  = google_compute_service_attachment.producer_service_attachment.id
  network                 = google_compute_network.consumer_net.name
  ip_address              = google_compute_address.consumer_address.id
  allow_psc_global_access = true
}
```

That can be applied once, causing the resource to be created. But a second tf apply (with no changes to the tf file) causes a plan that includes deletion/recreation, because of description:

```
  # google_compute_forwarding_rule.default must be replaced
-/+ resource "google_compute_forwarding_rule" "default" {
      - all_ports               = false -> null
      - allow_global_access     = false -> null
      + base_forwarding_rule    = (known after apply)
      ~ creation_timestamp      = "2023-10-16T09:32:38.274-07:00" -> (known after apply)
      + description             = "My description" # forces replacement
```

Plan: 1 to add, 0 to change, 1 to destroy.

### Steps to Reproduce

Set the "description" field in the resource. If this field is unset and the configuration is applied, subsequent applies make no changes.

### Important Factoids

This is with a PSC enabled forwarding rule, I've not tried with non-PSC forwarding rules. 

### References

* #0000

b/308569872

**Comment by edwardmedia** [comment] 2023-10-10 15:36
The [description](https://github.com/hashicorp/terraform-provider-google/blob/6a11ae845790c5eebe492043e64d9973b54f940f/google/services/compute/resource_compute_forwarding_rule.go#L215) is set to ForceNew

**Comment by rileykarson** [comment] 2023-10-10 23:04
Update support is an enhancement, not a bug.

**Comment by justinsb** [comment] 2023-10-16 22:11
I don't think this issue is about update behaviour.

The bug is that when you `tf apply` a PSC forwarding rule with a description twice - with no changes - the second `tf apply` forces replacement because TF thinks the description field is changing.

**Comment by rileykarson** [comment] 2023-10-16 22:25
Ah, yep, https://github.com/hashicorp/terraform-provider-google/issues/16258 was more clear (although this issue's parent stated the same if read correctly)

**Comment by rileykarson** [comment] 2023-10-16 22:26
@roaks3 any idea why the robot didn't label this one?

**Comment by roaks3** [comment] 2023-10-19 13:37
Ah yea, there is a manual step where a member of our team needs to update the team enrollment in mmv1 (the canonical source is internal) and then re-run the labeler. This is part of our team's rotation so it should happen weekly until we build automation around that.

**Comment by LucaPrete** [comment] 2024-01-05 15:57
There's something I'm missing...

How is possible that we [set `force_new: true` in the `google_forwarding_rule`](https://github.com/hashicorp/terraform-provider-google/blob/9fecd14751b66a1938642ee09903030e258db2dc/google/services/compute/resource_compute_forwarding_rule.go#L215), while we haven't specified `immutable: true` in the [yaml resource definition](https://github.com/GoogleCloudPlatform/magic-modules/blob/24ff1562fb29e5492f055105c3510580b7a387a1/mmv1/products/compute/ForwardingRule.yaml#L262)?

Am I missing some code somewhere else?

**Comment by LucaPrete** [comment] 2024-01-05 15:58
> There's something I'm missing...
> 
> How is possible that we [set `force_new: true` in the `google_forwarding_rule`](https://github.com/hashicorp/terraform-provider-google/blob/9fecd14751b66a1938642ee09903030e258db2dc/google/services/compute/resource_compute_forwarding_rule.go#L215), while we haven't specified `immutable: true` in the [yaml resource definition](https://github.com/GoogleCloudPlatform/magic-modules/blob/24ff1562fb29e5492f055105c3510580b7a387a1/mmv1/products/compute/ForwardingRule.yaml#L262)?
> 
> Am I missing some code somewhere else?

ah.... from Magic modules doc:

```
immutable [#](https://googlecloudplatform.github.io/magic-modules/develop/field-reference/#immutable)
If true, the field (and any subfields) are considered immutable - that is, only settable on create. If unset or false, the field is still considered immutable if any ancestor field (or the overall resource) is immutable, unless update_url is set.
```

**Comment by LucaPrete** [comment] 2024-01-05 16:22
I'm not 100% sure how the PSC specific thing it's related to the description. In the meantime I tried to make the description argument updatable in place. I think this step is anyway needed and possibly it might also fix the bug.

**Comment by LucaPrete** [comment] 2024-01-06 12:38
It seems tests are failing as we are not (yet) able to patch the description argument. I'll dig into it with product before abandoning the PR.

**Comment by LucaPrete** [comment] 2024-01-11 08:09
I had to abandon the PR as description patching is currently not supported.

**Comment by stenalpjolly** [comment] 2024-03-08 12:36
The same issue is present in the compute_global_forwarding_rule as well.

**Comment by hao-nan-li** [comment] 2024-11-04 22:55
The service team rolled out a product-level fix, should be fixed by now.

**Closed by hao-nan-li** 2024-11-04 22:55 UTC
Labels: bug, forward/linked, service/compute-l7-load-balancer
