### ISSUE TITLE
Generate computed attribute Email for Cloudbuild service account

### ISSUE THREAD

**Issue by cristiani** [hashicorp/terraform-provider-google#5359] opened 2020-01-09 12:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Provide email addresses as calculated attributes for other automatically generated service accounts, like CloudBuild. Currently, afaik, there is no possiblity to obtain an email address like the one generated inside GCP (i.e. 861629943208@cloudbuild.gserviceaccount.com).
It seems that there are only few specific resources for service accounts (google_service_account , google_storage_service_account) that return email address that can be referenced later in other resource like iam_member.
Since, this address cannot be calculated, one has to activate corresponding API manually in Web interface, then insert the generated email as a variable in the terraform script and maintain that variable also manually.

### New or Affected Resource(s)

* google_project_service

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
Instead of creating a separate resource for each service account, maybe one could return an array of email address as a calculated attribute of google_project_service, one email for each service account created as a by product of activating listed APIs.
### References

No
* #0000

**Comment by danawillow** [comment] 2020-01-13 18:53
Note from triage meeting: maybe new data source or maybe generic one with enum, needs a bit of thought

**Comment by Pritilender** [comment] 2020-06-26 13:36
This is also a problem with creating Firebase projects, where new Firebase project creates a service account for Admin SDK. The email for the created service account has following format `firebase-admin-${RANDOM_5_CHAR}@${PROJECT_ID}.iam.gserviceaccount.com`. The problem is how to know this 5 random characters that are added because of email clash on GCP level.

A new data source that would be used for listing all service accounts for the project would work here. There's already [a command](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/list) in GCP for this.

**Comment by upodroid** [comment] 2020-11-13 16:56
@rileykarson We can close this issue as it has been fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/4224

**Comment by rileykarson** [comment] 2020-11-13 18:03
Thanks @upodroid!

**Closed** 2020-11-13 18:03 UTC
Labels: enhancement, new-data-source, size/M
