### ISSUE TITLE
container analysis notes IAM policy support

### ISSUE THREAD

**Issue by mvanholsteijn** [hashicorp/terraform-provider-google#7698] opened 2020-11-04 16:29 UTC
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Each Container Analysis note has an IAM policy, but there is no support in the terraform provider.

### New or Affected Resource(s)

* google_container_analysis_note_iam_policy
* google_container_analysis_note_iam_binding
* google_container_analysis_note_iam_member

### Potential Terraform Configuration

```tf
resource "google_container_analysis_note_iam_binding" "note_viewer" {
  note    = google_container_analysis_note_iam_binding.note.id
  role    = "roles/containeranalysis.notes.occurrences.viewer"
  members = [
    "user:jane@example.com",
  ]
}
```

### References

* https://cloud.google.com/binary-authorization/docs/creating-attestors-cli#set_permissions_on_the_note
* https://cloud.google.com/container-registry/docs/reference/rest/v1/projects.notes/setIamPolicy

**Comment by rileykarson** [comment] 2020-11-09 18:39
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7745- are these issues different?

**Closed by rileykarson** 2020-11-09 18:39 UTC
Labels: enhancement
