### ISSUE TITLE
invalid memory address or nil pointer dereference during plan.

### ISSUE THREAD

**Issue by aloiscochard** [hashicorp/terraform-provider-google#9580] opened 2021-07-19 08:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.75.0
+ provider registry.terraform.io/hashicorp/google-beta v3.75.0
+ provider registry.terraform.io/numtide/secret v1.2.0

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- google_storage_object_acl

### Terraform Configuration Files

```tf
# main.tf
terraform {
  backend "s3" {
    bucket         = "#redacted#"
    dynamodb_table = "#redacted#"
    key            = "#redacted#"
    region         = "#redacted#"
    encrypt        = true
    profile        = "#redacted#"
  }
}

locals {
  project_name = "#redacted#"
  region       = "#redacted#"
}

provider "google" {
  project = local.project_name
  region  = local.region
}

data "terraform_remote_state" "dns" {
  backend = "s3"

  config = {
    bucket         = "#redacted#"
    dynamodb_table = "#redacted#"
    key            = "#redacted#"
    region         = "#redacted#"
    encrypt        = true
    profile        = "#redacted#"
  }
}

locals {
  dns_zone_name     = data.terraform_remote_state.dns.outputs.name
  dns_zone_dns_name = data.terraform_remote_state.dns.outputs.dns_name
}
```

```tf
# gcs.tf
locals {
  nix_cache_name   = "#redacted#"
  nix_cache_domain = "nix-cache.${local.dns_zone_dns_name}"
}

module "nix_cache" {
  source = "git::https://github.com/tweag/terraform-gcp-cdn-bucket.git?ref=469134a35b53aae0fd5283e06cc7a7da147ffc57"

  labels               = {}
  name                 = local.nix_cache_name
  project              = local.project_name
  region               = local.region
  ssl_certificate      = google_compute_managed_ssl_certificate.redacted-nix-cache.self_link
  cache_retention_days = 60
}

resource "google_compute_managed_ssl_certificate" "redacted-nix-cache" {
  name = "heaviside-nix-cache"

  managed {
    domains = [local.nix_cache_domain]
  }
}

resource "google_dns_record_set" "nix_cache" {
  name         = local.nix_cache_domain
  type         = "A"
  ttl          = 300
  managed_zone = local.dns_zone_name
  rrdatas      = [module.nix_cache.external_ip]
}

resource "google_storage_bucket_object" "nix-cache-info" {
  name         = "nix-cache-info"
  bucket       = module.nix_cache.bucket_name
  content_type = "text/plain"

  content = <<EOF
  StoreDir: /nix/store
  WantMassQuery: 1
  Priority: 10
  EOF
}

resource "google_storage_object_acl" "nix-cache-info-acl" {
  bucket         = module.nix_cache.bucket_name
  object         = google_storage_bucket_object.nix-cache-info.name
  predefined_acl = "publicRead"
}
```
### Debug Output

https://pastebin.com/qBPm3ND2

### Expected Behavior

Not throw an exception, and compute the plan.

### Actual Behavior

Throw an exception when running `terraform plan`.

### Steps to Reproduce

1. `terraform plan`

### References

* b/275623127

**Comment by aloiscochard** [comment] 2021-07-19 10:10
After a few more experiments, the resource causing the exception is `google_storage_object_acl`, as commenting it makes plan succeed.

Please note that this problem occur with a fresh and empty remote state.

**Comment by slevenick** [comment] 2021-07-19 17:04
Well that's bad...

I'm unable to reproduce this with the configs provided, but it looks like for some reason the owner of the object is undefined on this line: https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_storage_object_acl.go#L83

I can add a check before that, but I'm not super sure what the right behavior would be if we find that. I'm tempted to just return nil as if we can't find the owner we probably can't do any fancy diffing logic here

**Comment by c2thorn** [comment] 2021-07-19 17:11
> I'm tempted to just return nil as if we can't find the owner we probably can't do any fancy diffing logic here

I agree with that route. I wonder if something changed in the API, this CustomizeDiff is fairly old.

**Comment by aloiscochard** [comment] 2021-07-20 07:46
Thanks for looking into this issue.

Not sure if that helps, but I thought I would share here the output of `gsutil acl get gs://#redacted#/`.

As far as I can see, the owner should be defined on this bucket object.

```
[
  {
    "entity": "project-editors-#REDACTED#",
    "projectTeam": {
      "projectNumber": "#REDACTED#",
      "team": "editors"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-owners-#REDACTED#",
    "projectTeam": {
      "projectNumber": "#REDACTED#",
      "team": "owners"
    },
    "role": "OWNER"
  },
  {
    "entity": "allUsers",
    "role": "READER"
  },
  {
    "entity": "project-viewers-#REDACTED#",
    "projectTeam": {
      "projectNumber": "#REDACTED#",
      "team": "viewers"
    },
    "role": "READER"
  }
]
```

I'm still trying to work out how to manually change the ACL so the provider can run a plan/apply successfully, thanks for the pointer in the code, that will help!

**Comment by aloiscochard** [comment] 2021-07-20 12:51
Just found a workaround by replacing the resource `google_storage_object_acl` with a `google_storage_object_access_control`; this is fine in my case as the ACL is merely about making the bucket object public.

```
resource "google_storage_object_access_control" "nix-cache-info-access-control" {
  bucket = module.nix_cache.bucket_name
  object = google_storage_bucket_object.nix-cache-info.output_name
  role   = "READER"
  entity = "allUsers"
}
```

**Comment by sethvargo** [comment] 2023-03-30 16:09
I believe this was fixed as of https://github.com/hashicorp/terraform-provider-google/commit/834c4b94998f49110fe67caf707401111f829151

**Comment by melinath** [comment] 2023-03-30 17:04
Closing as fixed - please open a new bug if you're still seeing this issue.

**Closed by melinath** 2023-03-30 17:04 UTC
Labels: bug, crosslinked, services/storage
