### ISSUE TITLE
containerd_config in resource google_container_cluster is not working

### ISSUE THREAD

**Issue by tduverge** [hashicorp/terraform-provider-google#19056] opened 2024-08-09 11:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.2
on 
+ provider registry.terraform.io/hashicorp/google v5.40.0
+ provider registry.terraform.io/hashicorp/google-beta v5.40.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration

```tf
resource "google_service_account" "default" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_container_cluster" "primary" {
  name               = "marcellus-wallace"
  location           = "us-central1-a"
  initial_node_count = 3
  node_config {
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    containerd_config {
      private_registry_access_config {
        enabled = true
        certificate_authority_domain_config" {
          fqdns = ["example.com"]
          gcp_secret_manager_certificate_config {
            secret_uri = "secret link"
          }
        }
      }
    }
    labels = {
      foo = "bar"
    }
    tags = ["foo", "bar"]
  }
  timeouts {
    create = "30m"
    update = "40m"
  }
}
```

### Expected Behavior

As a declared available argument of `node_config` ([see there](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#containerd_config)), I expected `containerd_config` modify the resource but it does nothing. I finally found that the block `containerd_config ` do the job when you put it in `node_config_defaults`.

Since the  `containerd_config` apply for the whole cluster and not for the node pool ([as you can see there](https://cloud.google.com/kubernetes-engine/docs/how-to/customize-containerd-configuration)), documentation should evolve to remove the argument from `node_config` and add it only in `node_config_defaults` section.

### Actual Behavior

`containerd_config`  doesn't change anything on resource but still appear in change.

### Steps to reproduce

1. `terraform apply`
2. Accept changes
3. `terraform plan`. Changes are there, previous apply does nothing.

b/359218687

**Comment by ggtisc** [comment] 2024-08-12 04:51
Hi @tduverge!

I tried to replicate this issue, but everything was successful without errors. Maybe you could provide more information about this  issue.

- Do you have an initial configuration before this (other initial terraform code)?
- What are you trying to modify?
- Are you having an error message? If that is the case please share with us that message

**Comment by tduverge** [comment] 2024-08-12 06:39
Hello @ggtisc !

Thanks to answer 😃 

My problem isn't that there's an error, but that a change hasn't been taken into account.

My objective is to add a certificate authority for a private container registry, which should be done with an argument `containerd_config ` in the block `node_config` [according to the documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#containerd_config) (it's the only place where the argument is supported, again according to the documentation).

```hcl
  node_config {
    containerd_config {
      private_registry_access_config {
        enabled = true
        certificate_authority_domain_config" {
          fqdns = ["example.com"]
          gcp_secret_manager_certificate_config {
            secret_uri = "secret link"
          }
        }
      }
    }
  }
```

But when I'm applying this configuration, nothing append in my cluster. Whereas I'm putting the same configuration in the block `node_pool_defaults.node_config_defaults` like that :

```hcl
  node_pool_defaults {
    node_config_defaults {
      containerd_config {
        private_registry_access_config {
          enabled = true
          certificate_authority_domain_config" {
            fqdns = ["example.com"]
            gcp_secret_manager_certificate_config {
              secret_uri = "secret link"
            }
          }
        }
      }
    }
  }
```

Everything is working very well.

I'm surprised that everything is working well on your side cause I've seen this bug with different version of terraform. And there is no doubt when I [look at the code there](https://github.com/hashicorp/terraform-provider-google/blob/fefe09ae6fae8652c34bfbdb650732c908836772/google/services/container/resource_container_cluster.go#L3922) that the argument `containerd_config` must be in `node_pool_defaults.node_config_defaults` and not in `node_config` contrary to what the documentation says.

Moreover the [documentation says](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_config_defaults) that `node_config_defaults ` only support `logging_variant` and `gcfs_config` which is also an error, since `containerd_config` is supported and should be set only there. And it describes `node_config_defaults` as a `Subset of NodeConfig message that has defaults.` which is also false, since `containerd_config` is only supported in `node_pool_defaults` and not in `node_config`.

**Comment by ggtisc** [comment] 2024-08-12 16:20
After running a `terraform apply` resources were created and the change is visible on `tfstate` file but user is reporting that this is not affecting the cluster and the change is not implemented

**Comment by wyardley** [comment] 2024-09-28 22:59
> Since the containerd_config apply for the whole cluster and not for the node pool

It's worth reading the docs on `node_config` within `google_container_cluster` carefully:

> [node_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_config) - (Optional) Parameters used in creating the default node pool. Generally, this field should not be used at the same time as a google_container_node_pool or a node_pool block; this configuration manages the default node pool, which isn't recommended to be used with Terraform.

`node_config_defaults` will _only_ affect the behavior of newly created nodepools, as I understand it.

If the issue is with the default nodepool created by the cluster (`remove_default_node_pool` is not set), If the value is being changed after cluster creation, it's possible that this issue is due to #19225. I'm trying to work on a longer term fix for that, but pretty sure it will not work to update that value in place.

Worth being in mind that if you _also_ have additional node pools, the setting needs to be explicitly set on those too, if they were created before `node_config_defaults` was set.

**Comment by wyardley** [comment] 2024-10-23 21:20
re: @roaks3's comments, I think my PR will not fix this after all.

The schema doesn't seem to have it marked as `ForceNew`:
https://github.com/GoogleCloudPlatform/magic-modules/blob/075e1514533b67c29fb661b7d07e050384dc6f56/mmv1/third_party/terraform/services/container/node_config.go.tmpl#L33-L39

Top level `schemaNodeConfig` does:
https://github.com/GoogleCloudPlatform/magic-modules/blob/075e1514533b67c29fb661b7d07e050384dc6f56/mmv1/third_party/terraform/services/container/node_config.go.tmpl#L129
but I don't think that affects resources under it

So I think maybe this is, in fact, a bug, and that updates were just never supported in _either_place for `containerd_config`, and that it wasn't marked to force replacement of the node pool either?

**Comment by wyardley** [comment] 2024-10-24 15:09
Now that we have a better understanding of the issue, it might be good to edit this issue title to describe the problem slightly differently: specifically, updating `node_config.containerd_config` in either `google_container_cluster` or `google_container_node_pool` doesn't work (but creating a new cluster or node pool with it configured should).

**Comment by wyardley** [comment] 2024-10-24 23:52
I have a working fix locally, and can open a PR or draft once https://github.com/GoogleCloudPlatform/magic-modules/pull/12014 ships

**Closed** 2024-10-30 19:10 UTC
Labels: bug, forward/linked, service/container
