### ISSUE TITLE
Increase name_prefix/name size for google_compute_instance_template

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/terraform-provider-google#17899] opened 2024-04-18 13:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Hello guys,

When using `google_compute_instance_template`, we need to defined the `name_prefix` who will end up having a `name` with 63 characters lengh. The thing is for our use cases (and I believe many customer too) need to have more characters.
Here is my error:
```bash
Error: "name_prefix" cannot be longer than 37 characters, name is limited to 63
```
Our current `name_prefix` 43 characters long so it's exploding the final `name` who will be suffixed by a date/id `20240418123904392300000001` like `xxx-xxxxx-xxxx-xxxx-xxxxx-xxxx-xxxx-xxx-20240418123904392300000001`.

According to RFC 1035 the length of a FQDN is limited to 255 characters, and each label (node delimited by a dot in the hostname) is limited to 63 characters.

So our server hostname length will be inferior to 63 characters as it's based on the `name_prefix`.

Is it something feasible?
Thanks.

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

```tf 
```

**Comment by melinath** [comment] 2024-04-22 16:59
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/15374

**Closed by melinath** 2024-04-22 16:59 UTC
Labels: enhancement, forward/review, service/compute-instances
