### ISSUE TITLE
google_container_cluster: support workloadPool and identityProvider

### ISSUE THREAD

**Issue by jcanseco** [hashicorp/terraform-provider-google#8129] opened 2021-01-06 23:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It seems that GKE deprecated `identityNamespace` in favor of `workloadPool` and `identityProvider` (see [this](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.WorkloadIdentityConfig)). The request here is to update `google_container_cluster` to more closely match the underlying API.

### New or Affected Resource(s)

* google_container_cluster

### References

* https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/361

b/359383717

**Comment by rileykarson** [comment] 2021-01-19 18:35
Note: potentially a breaking change depending how the API has done this

**Comment by jcanseco** [comment] 2021-01-19 18:54
Oh I see. Please let us know if you've confirmed that this would be a breaking change then. We would like for it to be implemented in such a way that it won't be breaking, but we'll wait for your investigation.

**Comment by ahmedtd** [comment] 2021-04-02 22:33
The GKE v1beta1 API supports all three fields (identity_namespace, workload_pool, and identity_provider).  identity_namespace and workload_pool have the same effect (set to `<project_id>.svc.id.goog` to enable Workload Identity, set to empty string to disable Workload Identity).

The GKE v1 API only has workload_pool, which is the interface for enabling and disabling Workload Identity.

We are unsure if identity_provider will be promoted as-is to the v1 API, because of some unfortunate behavior we discovered in the v1beta1 API.  Basically, if you send an v1beta1 UpdateCluster request with only identity_provider set, you are **actually** requesting that Workload Identity be disabled (since workload_pool is empty).  To properly use the API, you have to use it in a read-modify-write cycle, and we think that counts as a breaking change if we promote that behavior to the v1 API surface.

**Comment by rileykarson** [comment] 2021-10-08 22:14
@ahmedtd: Would it be safe to remap `identity_namespace` onto the `workload_pool` field in the provider given the only difference is the read-modify-write requirement change? I'm doing https://github.com/hashicorp/terraform-provider-google/issues/8696 to remove beta clients in the GA provider, and we're in a bit of a rough spot- we GA'ed the feature based on a user asking for it to get GA'ed, but didn't notice that `identity_namespace` wasn't GA. This would have been caught by the client we were using, except we were using the beta one 🙃 

I think there are a few options:

1. Yank the `workload_metadata_config` field from GA, add it back later when this issue is resolved

2. Remap `identity_namespace` onto the `workload_pool` field for both the beta+ga provider (it's not a change in behaviour b/c we always read-modify-write). Deal with the naming correction later.

3. Add the `workload_pool` field, deprecate `identity_namespace`, remove it, change the clients. This is the best option correctness-wise, but has a lot more to do mechanically than 1 or 2 and https://github.com/hashicorp/terraform-provider-google/issues/8696 already has a lot going on.

**Comment by roaks3** [comment] 2023-08-17 16:47
This looks like it was addressed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5317, but I can't tell if the issue is completely resolved now. Adding review label to hold off on forwarding.

**Comment by ggtisc** [comment] 2024-08-13 01:43
I see many arguments with multiple options about `workloadPool` and `identity` but not sure if they are achieving the objective especially those that are from `identity`, it is not clear if they are from `identityProvider`

**Comment by roaks3** [comment] 2024-09-24 20:31
I think this was fully resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/5262 with the 4.0.0 release

**Closed by roaks3** 2024-09-24 20:31 UTC
Labels: enhancement, size/m, forward/linked, service/container
