### ISSUE TITLE
Unable to create a encrypted Cross region mysql replica in Google CloudSQL

### ISSUE THREAD

**Issue by DmytroMorhulDevPro** [hashicorp/terraform-provider-google#11805] opened 2022-06-02 12:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform 0.13.5

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "instance" {
  provider            = google-beta
  name                = "${var.ace_project}-${var.sql_instance_name}-${var.location}-${random_id.db_name_suffix.hex}"
  database_version    = var.database_version
  project             = var.project_id
  region              = var.location
  deletion_protection = var.deletion_protection
  encryption_key_name = var.encryption_key_name

  settings {
    availability_type = var.availability_type
    disk_autoresize   = var.disk_autoresize
    disk_size         = var.disk_size
    disk_type         = var.disk_type
    tier              = var.tier
    user_labels       = local.labels
    dynamic "database_flags" {
      for_each = var.database_flags
      content {
        name  = lookup(database_flags.value, "name", null)
        value = lookup(database_flags.value, "value", null)
      }
    }

    dynamic "backup_configuration" {
      for_each = [var.backup_configuration]
      content {
        binary_log_enabled             = local.binary_log_enabled
        enabled                        = local.backups_enabled
        start_time                     = lookup(backup_configuration.value, "start_time", null)
        location                       = lookup(backup_configuration.value, "location", null)
        transaction_log_retention_days = lookup(backup_configuration.value, "transaction_log_retention_days", null)

        dynamic "backup_retention_settings" {
          for_each = local.retained_backups != null || local.retention_unit != null ? [var.backup_configuration] : []
          content {
            retained_backups = local.retained_backups
            retention_unit   = local.retention_unit
          }
        }
      }
    }

    ip_configuration {
      ipv4_enabled       = var.ipv4_enabled
      private_network    = var.network
      allocated_ip_range = var.allocated_ip_range
    }
  }
}

resource "google_sql_database_instance" "read_replica" {
  provider             = google-beta
  count                = var.create_read_replica ? 1 : 0
  name                 = "${google_sql_database_instance.instance.name}-replica"
  master_instance_name = google_sql_database_instance.instance.name
  project              = var.project_id
  region               = var.replica_location != null ? var.replica_location : var.location
  database_version     = var.database_version
  deletion_protection  = var.deletion_protection
  encryption_key_name  = var.replica_encryption_key_name

  replica_configuration {
    failover_target = false
  }

  settings {
    tier              = var.tier
    availability_type = "ZONAL"
    disk_size         = var.disk_size
    user_labels = merge(
      {
        db-type = "read-replica"
      },
      local.labels
    )

    ip_configuration {
      ipv4_enabled    = var.ipv4_enabled
      private_network = var.network
    }
  }

  depends_on = [google_sql_database_instance.instance]
}
```

### Debug Output

module.cloud_sql_secondary["oltp-instance"].google_sql_database_instance.read_replica[0]: Creating...

Error: Error, failed to create instance engage-oltp-instance-us-east1-d2fc7f52-replica-1: googleapi: Error 400: Invalid request: Disk encryption config is not specified for the cross region replica.., invalid

### Expected Behavior

terraform plan shows `encryption_key_name` value for new resource 

module.cloud_sql_secondary["oltp-instance"].google_sql_database_instance.read_replica[0]

Cross region replica been built in us-central1 with master instance in us-east1

### Actual Behavior

terraform plan shows module.cloud_sql_secondary["oltp-instance"].google_sql_database_instance.read_replica[0] resource without key `encryption_key_name` and it's value from variables

terraform fails to apply changes with following issue

Error: Error, failed to create instance engage-oltp-instance-us-east1-d2fc7f52-replica-1: googleapi: Error 400: Invalid request: Disk encryption config is not specified for the cross region replica.., invalid

### Steps to Reproduce

1. create sql services account
2. create CMAK keys for us-east1 and us-central1 and give access to the key for user from step 1
3. create SQL instance in us-east1 with replica in us-central1. no specific settings (code above is a module and can be reused for testing.)

1. `terraform apply`

### References

* #7107

**Comment by megan07** [comment] 2022-06-06 16:49
This appears to be a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11644.

**Closed by megan07** 2022-06-06 16:49 UTC
Labels: bug
