### ISSUE TITLE
Terrafrom recreates bigquery table on schema updates while bq cli updates properly 

### ISSUE THREAD

**Issue by milosbackonja** [hashicorp/terraform-provider-google#8710] opened 2021-03-17 17:36 UTC
### Terraform Version
Terraform v0.14.8
provider registry.terraform.io/hashicorp/google v3.60.0

### Affected Resource(s)
google_bigquery_table

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "default" {
  dataset_id                  = "foo"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "EU"
  default_table_expiration_ms = 3600000

  labels = {
    env = "default"
  }
}

resource "google_bigquery_table" "default" {
  dataset_id = google_bigquery_dataset.default.dataset_id
  table_id   = "bar"

  time_partitioning {
    type = "DAY"
  }

  labels = {
    env = "default"
  }

  schema = <<EOF
[
  {
    "name": "permalink",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "The Permalink"
  },
  {
    "name": "state",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "State where the head office is located"
  }
]
EOF

}

```

### Expected Behavior

It should update resource and  schema since bq cli does it without problem with same change

### Actual Behavior

It forces resource replacement

### Steps to Reproduce

1. Update schema

2. `terraform apply`

### References
#8630

**Comment by venkykuberan** [comment] 2021-03-18 16:29
Looks like the fix applied for @https://github.com/hashicorp/terraform-provider-google/issues/8337 isn't covering this case probably. @c2thorn any thoughts ?

**Comment by c2thorn** [comment] 2021-03-18 16:46
> Looks like the fix applied for @#8337 isn't covering this case probably. @c2thorn any thoughts ?

That seemed to have covered a specific use case. This seems to be about updates in general? Is this not a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8630

**Comment by milosbackonja** [comment] 2021-03-18 16:59
Thing is that in the past with older provider versions I was able to update schema, so it cant be threated as enhancement/feature, its a bug. In #8630 its asked for new feature since whoever posted that didn't know that it was working before...

**Comment by c2thorn** [comment] 2021-03-18 18:08
@milosbackonja I see, are referring specifically to adding a nullable column? Essentially reopening https://github.com/hashicorp/terraform-provider-google/issues/8503 ?

**Comment by milosbackonja** [comment] 2021-03-18 21:40
@c2thorn For me its happening even if I add required, nullable or repeated column.

**Comment by jacques-** [comment] 2021-03-29 11:41
Same here, no matter what options I select for new column

**Closed** 2021-03-30 21:01 UTC
Labels: bug
