### ISSUE TITLE
Cloud SQL - Postgres Instance - Deletion Protection stuck on disabled

### ISSUE THREAD

**Issue by 4TT1L4** [hashicorp/terraform-provider-google#13398] opened 2023-01-06 08:57 UTC
I have noticed that the deletion protection is not enabled for one of my Cloud SQL instances.

I have explicitly enabled the deletion protection for a Cloud SQL instance created using Terraform, as described in the 
documentation under [google_sql_database_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance) (although the default value should be `true` = enabled):

```
resource "google_sql_database_instance" "my_db_instance" {
  name             = "my_db_instance"
  database_version = "POSTGRES_14"
  region           = var.region
  deletion_protection = true

  settings {
    tier = var.mainnet_db_instance_type
    availability_type = "REGIONAL"
    
    ip_configuration {
           # some config 
    }
    
    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    backup_configuration {
      # some config 
    }
  }
}
```

Even after applying these changes the GCP Console shows "Instance deletion protection is disabled":

![image](https://user-images.githubusercontent.com/2914096/210967584-348f7c1e-4e33-4c73-aa11-6a70889fe4b7.png)

How could I enable deletion protection for my Cloud SQL instance?

Used GCP provider versions:
 - hashicorp/google v4.10.0 (current version: v4.47.0)
 - hashicorp/google-beta v4.28.0 (current version: v4.47.0)

**Comment by 4TT1L4** [comment] 2023-01-06 08:58
Since the used GCP provider versions are not up-to-date, first I am going to try to update to the most recent versions.

**Comment by edwardmedia** [comment] 2023-01-06 10:13
@4TT1L4 after you set deletion_protection with true, did you re-apply the config?

```
deletion_protection = true
```

**Comment by 4TT1L4** [comment] 2023-01-06 15:24
> did you re-apply the config?

@edwardmedia Yes. The config has been already applied several times since the change.

The configuration setting `deletion_protection = true` was introduced on Nov 29, 2022.

Interestingly the change does not show up in the `tf plan` output, which was printed by our CI system before applying the changes on Nov 29 2022.

Which might make sense... since this is the default value as well. There was actually no value change. We just added the `true` value explicitly.... (since this is the default value as well, if I am not mistaken.)

**Comment by edwardmedia** [comment] 2023-01-06 18:07
@4TT1L4 this feature is only for terraform. Take a look at below issue. There are two different delete_ protection. One is at the client side which is the terraform uses and the other is implemented on the API side. The one you use is on the client side, which works on the terraform. There is on impact on the server side where you want to verify on the console. Does this make sense?

https://github.com/hashicorp/terraform-provider-google/issues/11969

**Comment by 4TT1L4** [comment] 2023-01-13 08:15
@edwardmedia 

Thank you for the clarification.

If I understand correctly, there are two different features with similar goal and the same name:
 - **_The Terraform deletion protection_**; which is for Terraform only, so the google_sql_database_instance could not be deleted by Terraform. This was set by me as described in the description and it is actually working as expected.
 - **_The GCP Cloud SQL deletion protection_**; as documented here, which is a different feature (using the same name):
   - [Cloud SQL Documentation / PostgreSQL / Prevent deletion of an instance](https://cloud.google.com/sql/docs/postgres/deletion-protection#gcloud)

I am still wondering, if it is possible to enable the GCP deletion protection feature for the instance via terraform.

This should be possible via the gcloud CLI and via the REST API, as described in the [official GCP documentation of the Cloud SQL deletion protection feature for Postgres DB instances](https://cloud.google.com/sql/docs/postgres/deletion-protection#setting-or-removing).

Is this feature supported by Terraform? I have noticed that the Terraform example is missing in the official documentation for this change. I guess with a reason.... 

I would like to enable the GCP Cloud SQL instance deletion protection for my existing Postgres Cloud SQL instance. Is this possible with the Terraform GCP provider?

**Comment by c2thorn** [comment] 2023-01-18 18:35
> I would like to enable the GCP Cloud SQL instance deletion protection for my existing Postgres Cloud SQL instance. Is this possible with the Terraform GCP provider?

@4TT1L4 This should be possible with the field `deletion_protection_enabled`: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection_enabled

**Comment by 4TT1L4** [comment] 2023-01-19 17:49
@c2thorn 

Thank you for the hint.

This seems to be a new feature, that was recently introduced, based on the change notes:
https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.48.0

The feature was added in [v4.48.0](https://github.com/hashicorp/terraform-provider-google/tree/v4.48.0).

Before I could test the feature, I need to update the used provider version.

As already mentioned in the description, I am using an older version at the moment.

With my current version (as expected), I am getting en error message:

```
│ Error: Unsupported argument
│ 
│   on database-mainnet.tf line 35, in resource "google_sql_database_instance" "some_db_instance":
│   35:     deletion_protection_enabled = true
│ 
│ An argument named "deletion_protection_enabled" is not expected here.
```

I am going to update the provider version and get back to you. This new feature should solve my issue.

**Comment by Rycieos** [comment] 2023-01-20 18:03
@4TT1L4 thanks for opening this issue, or I might never have figured out what was going on. I was getting the same error you were when trying to set `deletion_protection_enabled`. Turns out I was using version v4.46.0 of this provider. Once I updated to v4.49.0, it worked perfectly. I can confirm that this flag works as expected.

On a related note, Terraform documentation for providers should include "New in version:" information (like [how the Python docs do it](https://docs.python.org/3/library/os.path.html#os.path.commonpath)), so it's clear that a field is new, and the version we are using might not support it.

**Comment by c2thorn** [comment] 2023-01-20 18:30
With confirmation from at least one user, I'll close this issue for now.

Thanks for the suggestion on our documentation @Rycieos. I think it is interesting and created an issue suggesting it for my team. https://github.com/hashicorp/terraform-provider-google/issues/13538

**Closed by c2thorn** 2023-01-20 18:30 UTC
Labels: question

**Comment by 4TT1L4** [comment] 2023-01-21 16:16
@Rycieos 
> On a related note, Terraform documentation for providers should include "New in version:" information (like [how the Python docs do it](https://docs.python.org/3/library/os.path.html#os.path.commonpath)), so it's clear that a field is new, and the version we are using might not support it.

I have created a PR with the proposed changes and added a note about the version, where the deletion_protection_enabled support was introduced:
 - https://github.com/hashicorp/terraform-provider-google/pull/13544
