### ISSUE TITLE
Persistent terraform plan Changes with google_compute_region_disk Labels Including goog-gke-volume

### ISSUE THREAD

**Issue by inobu** [hashicorp/terraform-provider-google#16528] opened 2023-11-14 12:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- terraform version: 1.6.3
- provider version: 5.6.0

### Affected Resource(s)

* google_compute_region_disk

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
resource "google_compute_region_disk" "example" {
  # ... other configuration ...

  labels = {
    goog-gke-volume = ""
  }
}
```

### Expected Behavior
The terraform apply should recognize the applied label configuration and not propose any changes on subsequent terraform plan executions when no changes are made to the labels.

### Actual Behavior
Even after applying the configuration with the goog-gke-volume label, every execution of terraform plan suggests that there are changes to be made to the terraform_labels.

### Steps to Reproduce

1. Define a google_compute_region_disk resource with a goog-gke-volume label.
2. Run terraform apply to apply the configuration.
3. Run terraform plan again, and observe that it suggests changes to the terraform_labels, even though there were no changes to the labels.

### References

* #0000

b/311366422

**Comment by trodge** [comment] 2023-11-16 19:40
@zli82016 would this be an example of an issue that will be fixed in the next release by [your pull request](https://github.com/GoogleCloudPlatform/magic-modules/pull/9438)?

**Comment by zli82016** [comment] 2023-11-16 19:43
It is a separate issue. I will look into it.

**Comment by zli82016** [comment] 2023-11-20 19:03
This is a regression introduced in provider 5.x due to the labels rework and cannot be resolved. Please see more details in [the provider 5.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade#provider).

It is caused by the empty string label value. Can you please replace the label value empty string with `_` or `true`?

**Comment by steffencircle** [comment] 2023-12-20 08:22
Hey,

as the label is originally set by the Platform, i am a bit worried that changing it's value has some sort of side-effect.
Therefore i am wondering if there is a better approach to this....

**Comment by zli82016** [comment] 2023-12-20 17:04
> Hey,
> 
> as the label is originally set by the Platform, i am a bit worried that changing it's value has some sort of side-effect. Therefore i am wondering if there is a better approach to this....

Do you know which platform the label is set by? Do you have more details?

The label is set in the configuration, and not returned as the system label by API.

**Comment by steffencircle** [comment] 2023-12-20 18:35
Hi,

sorry by "platform" i meant Google Cloud itself, but more precisely the GKE Service.
`goog-gke-volume` is a label that gets automatically assigned to Disks that are used as Persistent Volumes.
Which is exactly what we do here. we create Regional Disks via Terraform and then use it as volumes in GKE.

You can read more about this here https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels#automatically-applied-labels

Hope this clarifies

**Comment by zli82016** [comment] 2023-12-20 19:12
Thanks for the information.

You can use `ignore_changes` to ignore the change of this label. 
```
  lifecycle {                     
    ignore_changes = [
      terraform_labels["goog-gke-volume"],
    ]
  }
```

Sorry for the issue.

**Closed** 2023-12-20 19:37 UTC
Labels: bug, forward/linked, service/compute-pd
