### ISSUE TITLE
Documentation: Service account member still using `.email` opposed to `member`

### ISSUE THREAD

**Issue by userbradley** [hashicorp/terraform-provider-google#15126] opened 2023-07-11 15:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

In the documentation any time we're using a service account and then binding or using the `member` block, it still uses `serviceAccount:` oppoed to using the `member` from sa output

### Terraform Version

```
1.5.2
```

### Affected Resource(s)

Example: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam

Example 

```hcl
resource "google_service_account_iam_member" "gce-default-account-iam" {
  service_account_id = data.google_compute_default_service_account.default.name
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:${google_service_account.sa.email}"
}
```

### Terraform Configuration Files

```diff
resource "google_service_account_iam_member" "gce-default-account-iam" {
  service_account_id = data.google_compute_default_service_account.default.name
  role               = "roles/iam.serviceAccountUser"
-  member             = "serviceAccount:${google_service_account.sa.email}"
+ member             = google_service_account.sa.member
}
```

**Comment by edwardmedia** [comment] 2023-07-11 17:38
@userbradley I am not sure if I understand what the problem is. Using the [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#google_service_account_iam_member) as below, I do not see a problem. Can you provide the details?

```tf
data "google_compute_default_service_account" "default" {
}

resource "google_service_account" "sa" {
  account_id   = "issue15126"
  display_name = "issue15126"
}

# Allow SA service account use the default GCE account
resource "google_service_account_iam_member" "gce-default-account-iam" {
  service_account_id = data.google_compute_default_service_account.default.name
  role               = "roles/iam.serviceAccountUser"
  member             = "serviceAccount:${google_service_account.sa.email}"
}
```

**Comment by userbradley** [comment] 2023-07-11 17:46
Hey yeah, it's just a nomenclature thing that I explained really badly. 

I think that it's too much effort to be using the whole interpolation `"serviceAccount:${google_service_account.sa.email}"`  when it's easier to use `google_service_account.sa.member`

What I find the issue with is that the block `google_service_account` exposes `member` which does the whole `serviceAccount:issue15126@issue15126.iam.gserviceaccount.com`

**Comment by edwardmedia** [comment] 2023-07-11 17:58
@userbradley I see what you mean now. [member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account#member) is an readonly attribute of google_service_account. You are free to use `google_service_account.sa.member`. But for a iam resource, [serviceAccount (or user, etc.)](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_iam#member/members) are required for member field. This is cross the board. I see the example in the doc is still correct. Closing the issue now. Feel free to reopen if you disagree

**Closed by edwardmedia** 2023-07-11 17:58 UTC
Labels: bug
