### ISSUE TITLE
CMEK support for google_logging_project_bucket_config 

### ISSUE THREAD

**Issue by brettcurtis** [hashicorp/terraform-provider-google#12275] opened 2022-08-06 17:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In Google I'd prefer to disable org level _Default logging buckets in favor of a central logging bucket. I'd also like that bucket to use a CMEK as described here: https://cloud.google.com/logging/docs/routing/managed-encryption-storage#enable

I was digging into this issue all tho not exactly the same intent the idea of CMEK is there: https://github.com/hashicorp/terraform-provider-google/issues/11572

### New or Affected Resource(s)

* google_logging_project_bucket_config 

### Potential Terraform Configuration

```tf
resource "google_logging_project_bucket_config" "cis_2_1_logging" {
  project        = google_project.this.project_id
  location       = "global"
  retention_days = 30
  bucket_id      = "cis-2-1-logging-sink"
  
 encryption {
   default_kms_key_name = google_kms_crypto_key.cis_2_1[0].id
 }
}
```

**Comment by melinath** [comment] 2022-10-14 22:22
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12123

**Closed by melinath** 2022-10-14 22:22 UTC
Labels: enhancement, size/s
