### ISSUE TITLE
Inconsistent final plan updating labels in google_dataproc_cluster

### ISSUE THREAD

**Issue by alfonso2009** [hashicorp/terraform-provider-google#15108] opened 2023-07-10 14:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.2.9

### Affected Resource(s)

google_dataproc_cluster

### Expected Behavior

Update value of labels.

### Actual Behavior

When one label is updated, It seems like the provider not recognize the created labels and try to delete and recreate them. The following error is the same for all labels created.

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.dataproc.google_dataproc_cluster.dataproc to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google" produced an invalid new value for .labels: new element "enterprise" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce
In main.tf:

labels = merge(
    var.labels,
    {
      "resource_name"   = local.name,
      "deployment_date" = formatdate("DD-MM-YYYY", timestamp()),
      "resource_type"   = "dataproc",
    }
  )

But if I put "labels = var.labels" and the subblock are part of the variable labels it's work.

**Comment by alfonso2009** [comment] 2023-07-11 06:36
Yo have to do an apply with the first block of code and create the cluster. Once the cluster is created and the apply finished, you can modify some label value (Second block) and then when you apply the changes the errors are given by de provider. 

##########Start code##########

terraform {
  required_version = ">= 0.15"
  required_providers {
    google = "~> 4.0"
  }
  experiments = [module_variable_optional_attrs]
}

locals {
  labels = {
    "provider"                = "go",
    "region"                  = "euw1",
    "enterprise"              = "vvv",
    "account"                 = "poc",
    "system"                  = "tst"
    "environment"             = "poc",
    "cmdb_name"               = "",
    "security_exposure_level" = "mz",
    "status"                  = "",
    "on_service"              = "yes",
  }
}

resource "google_dataproc_cluster" "dataproc" {
  region  = "europe-west1"
  project = "myproject"
  name    = "dummy"
  labels = merge(
    local.labels,
    {
      "resource_name"   = "dummy",
      "deployment_date" = formatdate("DD-MM-YYYY", timestamp()),
      "resource_type"   = "dataproc",
    }
  )
}

##########End code##########


One example modifying el status to running:

##########Start code Modifying Status##########


terraform {
  required_version = ">= 0.15"
  required_providers {
    google = "~> 4.0"
  }
  experiments = [module_variable_optional_attrs]
}

locals {
  labels = {
    "provider"                = "go",
    "region"                  = "euw1",
    "enterprise"              = "vvv",
    "account"                 = "poc",
    "system"                  = "tst"
    "environment"             = "poc",
    "cmdb_name"               = "",
    "security_exposure_level" = "mz",
    "status"                  = "running",
    "on_service"              = "yes",
  }
}

resource "google_dataproc_cluster" "dataproc" {
  region  = "europe-west1"
  project = "practica-cloud-286009"
  name    = "dummy"
  labels = merge(
    local.labels,
    {
      "resource_name"   = "dummy",
      "deployment_date" = formatdate("DD-MM-YYYY", timestamp()),
      "resource_type"   = "dataproc",
    }
  )
}
##########End code##########

Yo receive multiple errors in variable .labels:

Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for google_dataproc_cluster.dataproc to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/google" produced an invalid new value for
│ .labels: new element "account" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.


Thanks!

**Comment by edwardmedia** [comment] 2023-07-11 17:28
@alfonso2009 do you have to use `locals`? Can you use `variables` instead? Do you want to try if below code works for you? 

```tf
resource "google_dataproc_cluster" "dataproc" {
    region = "europe-west1"
    name = "yourproject"
    labels = var.labels
}

variable "labels" {
  type = map(string)
  default = {
    provider = "gs",
    region = "euw1",
    enterprise = "vvv"
  }
}
```

**Comment by alfonso2009** [comment] 2023-07-12 06:12
I can use variable, the problem is the **merge function** when I want to merge the default labels (provider, region, enterprise, account, system, environment, cmdb_name, security_exposure_level, status, on_service) with mandatory labels (resource_name, deployment_date, resource_type). 

For my use case, I need that the merge function works with labels and not give me a error in the provider, because your solutions works, but I need to add the mandatory labels always, even if a user forgets to add them. 

My solution have to work with this solution or some similar:

`
labels = merge(
    var.labels,
    {
      "resource_name"   = local.name,
      "deployment_date" = formatdate("DD-MM-YYYY", timestamp()),
      "resource_type"   = "dataproc",
    }
  )
`

**Comment by edwardmedia** [comment] 2023-07-12 21:57
@alfonso2009 you may review the difference between `locals` and `variables`, and when you could use which. You should be able to see one of the diffs from the **plan**, which is the value from variables are **known** while the other is **unknown** which is the cause of the problem you are facing. Again this is the feature beyond the provider can offer. Does this make sense?

**Comment by alfonso2009** [comment] 2023-07-15 10:41
I have test both solutions with locals and variables and I get the same error, I think that there is an error in the provider merging labels with Unknown plan until apply. Can be this scenario possible? Remember that I need to merge in main resource this labels, and variable lables declaration will be located in a variables.tf file, then when I merge the two list of labels is when the error occurre:

variable "labels" {
  type = map(string)
  default = {
    provider = "gs",
    region = "euw1",
    enterprise = "vvv"
  }

labels = merge(
   var.labels,
  {
     "resource_name" = "dummy",
     "deployment_date" = formatdate("DD-MM-YYYY", timestamp()),
     "resource_type" = "dataproc",
  }
)

Thanks!

**Comment by edwardmedia** [comment] 2023-07-20 17:38
@alfonso2009 I believe the feature you were asking is outside of individual resource. There is little the provider can do. Close this issue now. Feel free to reopen if you see it differently

**Closed by edwardmedia** 2023-07-20 17:38 UTC
Labels: bug, waiting-response
