### ISSUE TITLE
source key/cryptoKeyVersions/1 has value DESTROYED in field crypto_key_version.state., failedPrecondition

### ISSUE THREAD

**Issue by jsoref** [hashicorp/terraform-provider-google#7044] opened 2020-08-17 20:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform 0.12.26
provider.google current

### Affected Resource(s)

* google_kms_crypto_key
* google_kms_crypto_key_version

### Terraform Configuration Files

Before:
```json
{
  "version": 4,
  "terraform_version": "0.12.26",
  "resources": [
    {
      "mode": "managed",
      "type": "google_kms_crypto_key",
      "name": "some_auth0_key",
      "provider": "provider.google",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "id": "projects/some-project/locations/global/keyRings/default-keyring/cryptoKeys/some-auth0-key",
            "key_ring": "projects/some-project/locations/global/keyRings/default-keyring",
            "labels": {},
            "name": "some-auth0-key",
            "purpose": "ENCRYPT_DECRYPT",
            "rotation_period": "604800s",
            "self_link": "projects/some-project/locations/global/keyRings/default-keyring/cryptoKeys/some-auth0-key",
            "timeouts": null,
            "version_template": [
              {
                "algorithm": "GOOGLE_SYMMETRIC_ENCRYPTION",
                "protection_level": "SOFTWARE"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

After:
```json
{
  "version": 4,
  "terraform_version": "0.12.26",
  "resources": [
  ]
}
```
### Debug Output

https://gist.github.com/jsoref/a62546711d25c652f74d5a6220af690f

### Expected Behavior

Delete the KMS object / Terraform description of said object

### Actual Behavior

It fails

### Steps to Reproduce

1. Maybe delete the keys or part of the keys in some other manner (?)
1. Delete the keys from the terraform plan
1. `terraform apply`

### Important Factoids

I suspect we already deleted these resources partially, probably behind terraform's back

### References

* https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2968
* https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3554

**Comment by edwardmedia** [comment] 2020-08-17 21:57
@jsoref can you specify steps how I can repro the issue? Can you share the log that contains the other calls that might be helpful?

**Comment by jsoref** [comment] 2020-08-17 23:11
I'm working on it. But I've hit a number of other bugs in this provider trying to get there, so it'll take me a bit +filing them.

**Comment by edwardmedia** [comment] 2020-08-18 04:53
@jsoref please post the steps whenever you have them.

**Comment by jsoref** [comment] 2020-08-18 18:00
So... I suspect a significant portion of our problem is:
```
terraform.pruneUnusedNodesTransformer
pruneUnusedNodes
```

@edwardmedia: I don't suppose you know of an easy way to prevent that code from running?

**Comment by edwardmedia** [comment] 2020-08-18 18:44
@jsoref I am not clear what you are trying to do from your above comment. Can you explain a little more detail? If you have other questions as opposed to this particular issue, I would suggest you file other issues so we can track issues properly. I need repro steps from you so I can understand more about this issue.

**Comment by jsoref** [comment] 2020-08-18 18:47
Right now in the other issue, it looks like terraform decides it isn't interested in creating the nodes -- afaict it seems to have decided nothing is using them, and therefore instead of creating them, it decides not to.

It's pretty hard to get all these pieces to cooperate when they actively fight that.

**Comment by edwardmedia** [comment] 2020-08-18 19:19
@jsoref if there are anything we can help, let us know. Regarding this issue, if you can provide the repro steps, that can help address the issue. If you don't what the issue is, I would suggest to close the issue at this moment and you can always to reopen it if you have the answer.

**Comment by edwardmedia** [comment] 2020-08-20 01:34
@jsoref I am closing this issue at this moment. Please reopen it once you figure out the steps about how to repro the issue. Thank you

**Closed by edwardmedia** 2020-08-20 01:34 UTC
Labels: bug, waiting-response

**Comment by jsoref** [comment] 2020-08-27 18:43
The steps are:
1. define a keyring and a key in terraform.tf (see the various tickets I've filed)
1. `terraform apply -auto-approve`
1. delete the key from the terraform.tf
1. `terraform apply -auto-approve`
1. If this actually does successfully remove the key from the terraform state, then restore the terraform state to the state from before asking terraform to delete the key -- otherwise, if you like, you could construct a terraform plan which will fail (e.g. there's a second already deleted key in the state) -- for the next step, the terraform state just needs to continue to reference the deleted key
1. wait 48 hours (or a week whichever makes this ticket happier)
1. `terraform apply -auto-approve` to try to delete the key again

expected results: as the `PRIMARY_STATE` of `DESTROYED` is a terminal state, asking terraform to forget about the key from its terraform state by removing it from the plan should work without error.

**Comment by jsoref** [comment] 2020-08-27 18:43
@edwardmedia: GitHub won't let me reopen this ticket.
