### ISSUE TITLE
BigQuery Table are force to recreate 

### ISSUE THREAD

**Issue by niraj06** [hashicorp/terraform-provider-google#9626] opened 2021-07-23 19:20 UTC
Below logs will have a comparison between provider version 3.76.0(BUG) and 3.55.0(works as expected)
### Terraform Version 1.0.1 and provider version 3.76.0

First Imported existing BigQuery table to terraform state.

terraform import module.bq_create_table.google_bigquery_table.main <Project_ID>/staging_area/delete_customers_list

then terraform plan

Here is the log
 # module.bq_create_table.google_bigquery_tab**le.main must be replaced**
-/+ resource "google_bigquery_table" "main" {
      ~ creation_time       = 1586446645634 -> (known after apply)
      ~ etag                = "DHC+2IWVVB8YD/sb8Yuiig==" -> (known after apply)
      ~ expiration_time     = 0 -> (known after apply)
      ~ id                  = "projects/<Project_ID/datasets/staging_area/tables/delete_customers_list" -> (known after apply)
      ~ labels              = {
          + "deployment-tool" = "terraform"
          + "environment"     = "dev"
          + "product-name"    = "cust-del"
        }
      ~ last_modified_time  = 1627065503097 -> (known after apply)
      ~ location            = "EU" -> (known after apply)
      ~ num_bytes           = 12994196063 -> (known after apply)
      ~ num_long_term_bytes = 0 -> (known after apply)
      ~ num_rows            = 22988100 -> (known after apply)
      ~ schema              = jsonencode(
          ~ [ # forces replacement
                # (3 unchanged elements hidden)
                {
                    description = "The customer Type in the json request"
                    mode        = "REQUIRED"
                    name        = "type"
                    type        = "STRING"
                },
              ~ {
                  ~ name        = "deletedFlag" -> "deletedflag"
                    # (3 unchanged elements hidden)
                } # forces replacement,
                {
                    description = "CustomerId"
                    mode        = "REQUIRED"
                    name        = "partyUId"
                    type        = "STRING"
                },
                # (1 unchanged element hidden)
            ]
        )
      ~ self_link           = "https://bigquery.googleapis.com/bigquery/v2/projects/ingka-icf-analytics-prod/datasets/staging_area/tables/delete_customers_list" -> (known after apply)
      ~ type                = "TABLE" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

**### Terraform Version 1.0.1 and provider version 3.55.0** with this version it works as expected update.

# module.bq_create_table.google_bigquery_table.main **will be updated in-place**
  ~ resource "google_bigquery_table" "main" {
        id                  = "projects/ingka-icf-analytics-prod/datasets/staging_area/tables/delete_customers_list"
      ~ labels              = {
          + "deployment-tool" = "terraform"
          + "environment"     = "dev"
          + "product-name"    = "cust-del"
        }
      ~ schema              = jsonencode(
          ~ [
                # (3 unchanged elements hidden)
                {
                    description = "The customer Type in the json request"
                    mode        = "REQUIRED"
                    name        = "type"
                    type        = "STRING"
                },
              ~ {
                  ~ name        = "deletedFlag" -> "deletedflag"
                    # (3 unchanged elements hidden)
                },
                {
                    description = "CustomerId"
                    mode        = "REQUIRED"
                    name        = "partyUId"
                    type        = "STRING"
                },
                # (1 unchanged element hidden)
            ]
        )
        # (13 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by edwardmedia** [comment] 2021-07-23 21:51
@niraj06 it looks like it is by design. Looking at below code. Should the name be case sensitive? 

```
~ name = "deletedFlag" -> "deletedflag"
```

**Comment by niraj06** [comment] 2021-07-23 22:08
ok, now it makes sense, Thanks

**Comment by edwardmedia** [comment] 2021-07-23 22:13
@niraj06 closing this. Feel free to reopen or file another issue if you have more things to discuss.

**Closed** 2021-07-23 22:24 UTC
Labels: bug
