### ISSUE TITLE
Support for VPC-SC supported services as data element

### ISSUE THREAD

**Issue by timdzbank** [hashicorp/terraform-provider-google#20775] opened 2024-12-23 13:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Add support for [VPC-SC supported services](https://cloud.google.com/access-context-manager/docs/reference/rest/v1/services/list) as data element in provider

### New or Affected Resource(s)

* google_access_context_manager_supported_services

### Potential Terraform Configuration

```tf
data "google_access_context_manager_supported_services" "default" {
  available_on_restricted_vip = optional(bool)
  supported_stage = optional(string) # GA, EARLY_ACCESS, ALPHA, BETA, DEPRECATED
}
```

* It would be create to get for each service the supported methods, supported stage and the known limitations

### References

https://cloud.google.com/access-context-manager/docs/reference/rest/v1/services/list
https://cloud.google.com/access-context-manager/docs/reference/rest/v1/services

**Comment by timdzbank** [comment] 2024-12-23 13:18
#18783

**Comment by roaks3** [comment] 2024-12-26 21:39
@timdzbank is there anything uniquely being requested here? It appears this should be marked as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/18783.

**Closed** 2024-12-27 08:46 UTC
Labels: enhancement, waiting-response, service/accesscontextmanager, forward/review
