### ISSUE TITLE
google_cloudfunctions2_function - generation modify always

### ISSUE THREAD

**Issue by millouzgc** [hashicorp/terraform-provider-google#15405] opened 2023-08-04 15:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.76.0

### Affected Resource(s)

* google_cloudfunctions2_function

### Terraform Configuration Files

```tf
resource "google_cloudfunctions2_function" "cloud_function" {
...
  build_config {
    source {
      storage_source {
        bucket = var.bucket_name
        object = google_storage_bucket_object.archive_cf_job.name
      }
    }
  }
...
}
```

### Debug Output

```tf
  # google_cloudfunctions2_function.cloud_function will be updated in-place
  ~ resource "google_cloudfunctions2_function" "cloud_function" {
        id          = "xxxx"
        name        = "xxxx"
        # (7 unchanged attributes hidden)

      ~ build_config {
            # (4 unchanged attributes hidden)

          ~ source {
              ~ storage_source {
                  - generation = 16XXXXXXXXXXXX76 -> null
                    # (2 unchanged attributes hidden)
                }
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

`generation` is optional and it should not generate systematic modification during plan and apply

### Actual Behavior

`generation` is optional (and currently I haven't found a way to retrieve this information via the google terraform provider)
This value systematically generates a change in the google_cloudfunctions2_function

### Steps to Reproduce

1. `terraform apply`

**Comment by mattstabeler** [comment] 2023-08-07 13:26
workaround: 

```
resource "google_cloudfunctions2_function" "cloud_function" {
...
  build_config {
    source {
      storage_source {
        bucket = var.bucket_name
        object = google_storage_bucket_object.archive_cf_job.name
      }
    }
  }

  lifecycle {
    ignore_changes = [
      # Ignore changes to generation
      build_config[0].source[0].storage_source[0].generation
    ]
  }
...
}

```

**Comment by edwardmedia** [comment] 2023-08-07 21:52
b/294903127

**Comment by shuyama1** [comment] 2023-08-07 21:59
This should be fixed in 4.77.0 (https://github.com/hashicorp/terraform-provider-google-beta/pull/5992), which is just released a few hours ago. Would you mind upgrading to the latest version and see if it still occurs? Thanks

**Comment by pfilourenco** [comment] 2023-09-18 09:14
Hi,

We have the same issue with V4.82.0

**Comment by haizaar** [comment] 2023-11-24 13:52
@oleksii-ovdak thanks for the detailed explanation. I'm hitting this one as well. While waiting for bucket's `generation` output to be implemented, I'm trying the [workaround](https://github.com/hashicorp/terraform-provider-google/issues/14117#issuecomment-1678737305) and experiencing the same issue - the function is always modified on `apply`.

I think there is a conceptual issue here: that "unknown" generation number we see is coming from the cloudbuild object:

```
$ gsutil stat gs://my-source-bucket/cloud-functions/func/source.zip
...
    Generation:             1700832928749763

$ terraform apply; terraform plan
...
      ~ build_config {
            # (4 unchanged attributes hidden)

          ~ source {
              ~ storage_source {
                  ~ generation = 1700833012018851 -> 1700832928749763
                    # (2 unchanged attributes hidden)
                }
            }

$ gcloud functions describe func
buildConfig:
  source:
    storageSource:
      bucket: gcf-v2-sources...
      generation: '1700833012018851'
      object: func/function-source.zip
```

Note the 1700833012018851 number - Cloud Function takes our source zip, passes it through Cloud Build and records generation of the resulting copy.

It looks like the concept of the `generation` attribute is currently broken (by design?)

**Comment by HeangSok-2** [comment] 2024-06-09 14:29
Correct me if I am wrong, but I think this may work.

When creating a Cloud Function V2, GCP creates another bucket starting with gcf-v2-sources....

Please go to this link: https://github.com/hashicorp/terraform-provider-google/blob/1d1a50adf64af60815b7a08ffc5e9d3e856d2e9c/google/services/cloudfunctions2/resource_cloudfunctions2_function.go#L665 and look for the function resourceCloudfunctions2functionRead(d *schema.ResourceData, meta interface{}). You will see that the code tries to get the generation from the gcf-v2-sources... bucket instead of the user given bucket and object. This causes it to modify the Cloud Function each time we run terraform apply.

Here's the relevant code snippet where the API attempts to get the object generation from the gcf-v2-sources... bucket:

````go
url, err := tpgresource.ReplaceVars(d, config, "{{Cloudfunctions2BasePath}}projects/{{project}}/locations/{{location}}/functions/{{name}}")
````
If you get the generation from the user-provided bucket and object instead, and after running this block of code:

````go
res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
    Config:    config,
    Method:    "GET",
    Project:   billingProject,
    RawURL:    url,
    UserAgent: userAgent,
    Headers:   headers,
})
````
Replace the bucket information in source.storageSource to the user's bucket information. It might work as expected.

Here is a more detailed approach for implementing this change in the code:

Construct the URL using the user-provided bucket and object:

````go
userBucket, userObject := d.Get("user_bucket").(string), d.Get("user_object").(string)
userBucketURL := fmt.Sprintf("https://storage.googleapis.com/storage/v1/b/%s/o/%s?fields=generation", userBucket, userObject)
````
Send a request to get the generation from the user-provided bucket and object:

````go
generationRes, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
    Config:    config,
    Method:    "GET",
    Project:   billingProject,
    RawURL:    userBucketURL,
    UserAgent: userAgent,
    Headers:   headers,
})
if err != nil {
    return fmt.Errorf("Error getting generation from user bucket: %s", err)
}
userBucketGeneration := generationRes["generation"]
````
Replace the generation in source.storageSource with the user-provided generation:

````go
source := res["source"].(map[string]interface{})
storageSource := source["storageSource"].(map[string]interface{})
storageSource["generation"] = userBucketGeneration
````
This approach ensures that Terraform gets the correct generation from the user-provided bucket and object, preventing unnecessary modifications during terraform apply.

**Closed** 2024-08-07 19:14 UTC
Labels: bug, forward/linked, service/cloudfunctions
