### ISSUE TITLE
Enhancement: google_data_catalog_tag_template: visibility support

### ISSUE THREAD

**Issue by scudellari** [hashicorp/terraform-provider-google#13598] opened 2023-01-29 20:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Specifying the visibility (private / public) of a tag template is not currently supported by the terraform provider. (It is supported in the SDK (python) and web UI.) Is this a feature that can be added?

### New or Affected Resource(s)

* google_data_catalog_tag_template

### References
[Provider docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_tag_template#argument-reference)
[Python SDK docs](https://cloud.google.com/python/docs/reference/datacatalog/latest/google.cloud.datacatalog_v1.types.TagTemplate)

**Comment by drandell** [comment] 2023-02-15 14:49
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12894 ?

**Comment by melinath** [comment] 2023-09-07 22:41
yes, this seems to be a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12894

**Closed by melinath** 2023-09-07 22:41 UTC
Labels: enhancement, size/s, forward/review, service/datacatalog
