### ISSUE TITLE
Add Ingress and Egress functionality to VPC Service Controls

### ISSUE THREAD

**Issue by ngodec** [hashicorp/terraform-provider-google#8722] opened 2021-03-18 16:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is a new feature in VPC Service Controls that allows configuring extra rules for the service perimeters: [https://cloud.google.com/vpc-service-controls/docs/ingress-egress-rules](https://cloud.google.com/vpc-service-controls/docs/ingress-egress-rules). This solves a number of immediate needs for everyone who has a more complex setup, and would be great to have it in terraform!  

### New or Affected Resource(s)

* google_access_context_manager_service_perimeter
* google_access_context_manager_access_level

Or new resources:
* google_access_context_manager_ingress_rule
* google_access_context_manager_egress_rule

### Potential Terraform Configuration

```tf
resource "google_access_context_manager_egress_rule" "allow-aggregated-logging" {
  parent        = "accessPolicies/${google_access_context_manager_access_policy.access-policy.name}"
  perimeter   = "accessPolicies/${google_access_context_manager_access_policy.access-policy.name}/perimeters/sensitive1"
  egressto = {
      serviceName = "logging.googleapis.com"
      methodsSelectors = [
        "LoggingServiceV2.WriteLogEntries",
        "LoggingService.WriteLogEntries",
      ]
      resources =  [ "projects/999" ]
  }
  egressFrom = {
    identityType = "ANY_IDENTITY"
  }
}
```

**Comment by apereira** [comment] 2021-03-18 21:57
See https://github.com/GoogleCloudPlatform/magic-modules/pull/4509

**Comment by ngodec** [comment] 2021-03-22 13:59
Found that this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8412

**Comment by ngodec** [comment] 2021-03-22 14:09
Thanks for that @apereira ! I guess now to wait for https://github.com/hashicorp/terraform-provider-google/pull/8723 to be released :)

**Comment by rileykarson** [comment] 2021-03-22 17:40
Closing as dupe of https://github.com/hashicorp/terraform-provider-google/issues/8412

**Closed by rileykarson** 2021-03-22 17:40 UTC
Labels: enhancement
