### ISSUE TITLE
[New resource] - AlloyDB Users

### ISSUE THREAD

**Issue by bschaatsbergen** [hashicorp/terraform-provider-google#15287] opened 2023-07-25 19:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_alloydb_user

### Potential Terraform Configuration

```tf
resource "google_alloydb_user" "test" {
  name           = "test"
  password       = "test"
  database_roles = ["test"]
  user_type      = "ALLOYDB_IAM_USER"
}
```

### References

* https://cloud.google.com/alloydb/docs/database-users/about#gcloud
* https://cloud.google.com/alloydb/docs/reference/rest/v1/projects.locations.clusters.users#User

**Comment by bschaatsbergen** [comment] 2023-07-25 20:38
Ah seems, this is addressed by my colleague already... 🤣 https://github.com/GoogleCloudPlatform/magic-modules/pull/8431

**Comment by shuyama1** [comment] 2023-07-27 23:45
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/14272

**Closed by shuyama1** 2023-07-27 23:45 UTC
Labels: enhancement, service/alloydb, forward/review
