### ISSUE TITLE
Terraform crash when trying to plan for configuration (v0.14.11) 

### ISSUE THREAD

**Issue by guidodl** [hashicorp/terraform-provider-google#11486] opened 2022-04-13 09:46 UTC
### Terraform Version

```
$ terraform0_14.exe --version
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/google v4.17.0

Your version of Terraform is out of date! The latest version
is 1.1.8. You can update by downloading from https://www.terraform.io/downloads.html
...
```
Hi everybody,

I am trying to plan for a terraform configuration which has already been applied by a colleague of my team. 
I encountered the following error:

```
module.external-glb.google_compute_health_check.lb_http_hc_443: Refreshing state... [id=projects/infoblu-access-prod/global/healthChecks/prod-external-armor-lb-http-hc-443]
module.external-glb.google_compute_global_address.lb_external_addr: Refreshing state... [id=projects/infoblu-access-prod/global/addresses/prod-external-armor-lb-ext-addr]
module.external-glb.panic: Error reading level state: strconv.ParseInt: parsing "8168926262889361640": value out of range
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: goroutine 120 [running]:
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x152afb30, 0x154920c8, 0x1, 0x1, 0x1491db08, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:553 +0x2ba
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x152afb30, 0x152afb30)
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:351 +0x288
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x14b837a0, 0x2c336dc, 0x14d2f8d0, 0x2403700, 0x1548c960, 0x2c336dc, 0x14d2f8d0, 0x2403700)
2022-04-12T10:29:34.843+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:263 +0x191
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14db29c0, 0x2c3323c, 0x14d30c40, 0x14d30ca0, 0x27baa12, 0x12, 0x0)
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:550 +0x1ea
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14894280, 0x2c3329c, 0x14d30c40, 0x1488f950, 0x0, 0x0, 0x0)      
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x288
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x2770ba0, 0x14894280, 0x2c3329c, 0x15062870, 0x1488f920, 0x0, 0x2c3329c, 0x15062870, 0x15482000, 0x2f0)
2022-04-12T10:29:34.844+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x199
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0x1491c120, 0x2c47708, 0x1491c240, 0x148e85a0, 0x14c98858, 0x3986908, 0x0, 0x0, 0x0)
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:1282 +0x4ea
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0x1491c120, 0x2c47708, 0x1491c240, 0x148e85a0, 0x0)
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:1616 +0xa71
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14a0e140, 0x1491c120, 0x2c47708, 0x1491c240, 0x148e85a0)
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:921 +0x92
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-04-12T10:29:34.845+0200 [DEBUG] plugin.terraform-provider-google_v4.17.0_x5.exe:   google.golang.org/grpc@v1.44.0/server.go:919 +0x1b0
2022-04-12T10:29:34.848+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_image.ntt-eap (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_url_map.lb_http_url_map (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy[0]": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_target_http_proxy.lb_http_target_proxy (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_subnetwork.network (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_default_service_account.default (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_project.project (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_global_address.lb_external_addr (expand)": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_global_forwarding_rule.lb_http_fw_rule (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443 (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_443 (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_security_policy.policy (expand)": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-proxy-armor.data.google_compute_network.network (expand)": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor.google_compute_instance_template.instance_template (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor.google_compute_region_instance_group_manager.default (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor.output.migSelfLink (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.var.igs (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80": visit complete
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80 (expand)": dynamic subgraph encountered errors
2022/04/12 10:29:34 [TRACE] vertex "module.external-glb.google_compute_health_check.lb_http_hc_80 (expand)": visit complete
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_backend_service.lb_be_svc_80 (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-proxy-armor (close)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_backend_service.lb_be_svc_443 (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_url_map.lb_url_map (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_target_https_proxy.lb_https_target_proxy (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb.google_compute_global_forwarding_rule.lb_https_fw_rule (expand)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/google\"] (close)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "module.external-glb (close)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2022/04/12 10:29:34 [TRACE] dag/walk: upstream of "root" errored, so skipping
2022/04/12 10:29:34 [INFO] backend/local: plan operation completed
2022/04/12 10:29:34 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2022/04/12 10:29:34 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
2022-04-12T10:29:34.865+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.17.0/windows_386/terraform-provider-google_v4.17.0_x5.exe pid=11024 error="exit status 2"
2022-04-12T10:29:34.865+0200 [DEBUG] plugin: plugin exited

google_compute_health_check.lb_http_hc_80: Refreshing state... [id=projects/infoblu-access-prod/global/healthChecks/prod-external-armor-lb-http-hc-80]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


module.external-glb.google_compute_url_map.lb_http_url_map: Refreshing state... [id=projects/infoblu-access-prod/global/urlMaps/prod-external-armor-lb-http-url-map]
Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing

```

I attach also the crash.log generated.

[crash.log](https://github.com/hashicorp/terraform/files/8471232/crash.log)
Thanks,
Guido

**Comment by melinath** [comment] 2022-04-14 21:36
@guidodl it sounds like that was a Terraform crash (rather than a Terraform provider crash) so I think you might want to report it at https://github.com/hashicorp/terraform

**Comment by melinath** [comment] 2022-04-14 21:37
Actually this seems to be due to a panic in the google provider - reopening

**Comment by melinath** [comment] 2022-04-14 21:42
It looks like the important part of the error is:

```
module.external-glb.panic: Error reading level state: strconv.ParseInt: parsing "8168926262889361640": value out of range
```

It looks like this is probably caused by using a 64-bit terraform (or provider?) binary on a 32-bit system - see https://github.com/hashicorp/terraform-plugin-sdk/issues/469

attn @megan07 

That does mean that this is probably not an issue with the provider, so I'm going to re-close this issue :-)

**Closed by melinath** 2022-04-14 21:42 UTC
Labels: bug, crash

**Comment by guidodl** [comment] 2022-04-15 07:05
Hi @melinath ,

I have tried to open the issue here too https://github.com/hashicorp/terraform/issues/30842 .
I have noticed that one of my collegues has successfully planned and applied the configuration with the same version of Terraform binary. 
Mine is this: https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_windows_386.zip 

Do i need to use the amd_64 version?

Thanks

**Comment by melinath** [comment] 2022-04-18 16:58
@guidodl if your system is a 32-bit system, you need to make sure that both the TF binary and the installed provider binary are 32-bit binaries. (I think you should only be seeing this error if you're on a 32-bit system.)

Possibly helpful: https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d
