### ISSUE TITLE
`google_container_engine_versions` or `google_compute_network`  does not plan  [3.40.0 → 3.41.0] 

### ISSUE THREAD

**Issue by miseyu** [hashicorp/terraform-provider-google#7379] opened 2020-09-29 01:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
- Terraform v0.13.0
- provider.google v3.41.0

### Affected Resource(s)
* google_container_engine_versions
* google_compute_network

### Terraform Configuration Files

```tf

data "google_container_engine_versions" "version" {
  location       = local.zones.tokyo-a
  project        = var.pjname
  version_prefix = "1.16."
}

resource "google_compute_network" "network" {
  name    = "${var.pjname}-network"
  project = var.pjname

  auto_create_subnetworks = "false"

  routing_mode = "REGIONAL"
}
```

### Debug Output
```
Error: Invalid resource instance data in state

  on cluster.tf line 1:
   1: data "google_container_engine_versions" "version" ***

Instance data.google_container_engine_versions.version data could not be
decoded from the state: unsupported attribute "region".


Error: Invalid resource instance data in state

  on cluster.tf line 1:
   1: data "google_container_engine_versions" "version" ***

Instance data.google_container_engine_versions.version data could not be
decoded from the state: unsupported attribute "region".


Error: Invalid resource instance data in state

  on network.tf line 1:
   1: resource "google_compute_network" "network" ***

Instance google_compute_network.network data could not be decoded from the
state: unsupported attribute "ipv4_range".


Error: Invalid resource instance data in state

  on network.tf line 1:
   1: resource "google_compute_network" "network" ***

Instance google_compute_network.network data could not be decoded from the
state: unsupported attribute "ipv4_range".
```

**Comment by essjayhch** [comment] 2020-09-29 09:06
For clarity, this effects v0.12 as well as 0.13, but that is probably self-evident as it will have been a change in the provider configuration

**Comment by Jean-Mercier** [comment] 2020-09-29 10:16
same root cause than issue 
https://github.com/hashicorp/terraform-provider-google/issues/7381

**Comment by slevenick** [comment] 2020-09-29 21:48
Hey @miseyu I believe this is an issue with Terraform core, and I believe it was fixed in version 0.13.1 by this PR: https://github.com/hashicorp/terraform/pull/25779

Can you (or anyone else seeing this bug) try upgrading your version of Terraform to see if it works for you?

I can reproduce by using 0.13.0 but not 0.13.3.

**Comment by slevenick** [comment] 2020-09-30 22:57
Closing as I believe this is not a provider bug. Please reopen this if upgrading Terraform to 0.13.1+ does not fix the issue for you

**Comment by jamesyale** [comment] 2020-10-01 09:49
> Closing as I believe this is not a provider bug. Please reopen this if upgrading Terraform to 0.13.1+ does not fix the issue for you

Just to check, we're saying this provider as of 3.41.0 no longer supports TF 0.12?

**Comment by slevenick** [comment] 2020-10-01 17:54
@jamesyale good point. The tricky thing is that the cause of this issue was upgrading to the terraform-sdk v2: https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html

SDK v2 claims to work with 0.12.0+, but in this case that doesn't seem to be the case. I'll bring this up for discussion

**Comment by slevenick** [comment] 2020-10-01 18:33
I'm actually unable to reproduce this using 0.12.x

Are you able to get this error specifically when using 0.12? It seems like it was specific to 0.13.0

There is a similar looking issue around fields being removed, but that should be fixed by updating configs to use the correct field

**Comment by jamesyale** [comment] 2020-10-01 18:47
Yep, you're right - I've got the wrong issue here and the one we're hitting is the same as https://github.com/hashicorp/terraform-provider-google/issues/7381 where `region` is removed ala https://github.com/GoogleCloudPlatform/magic-modules/pull/2436.

Thanks for looking into it!

**Comment by slevenick** [comment] 2020-10-01 18:50
Great!

**Closed by slevenick** 2020-10-01 18:50 UTC
Labels: bug
