### ISSUE TITLE
Label resources at provider level

### ISSUE THREAD

**Issue by Ameausoone** [hashicorp/terraform-provider-google#9067] opened 2021-05-04 14:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Like for AWS : https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#propagating-tags-to-all-resources 

It would be very practical to define `default_labels` at provider level, then every ("labelisable") resources under this provider will be automatically labelled. 

### New or Affected Resource(s)

* provider google
* every "lableable" resource 

### Potential Terraform Configuration

```tf
provider "google" {
  # ... other configuration ...
  default_labels {
    labels = {
      Environment = "Production"
      Owner       = "Ops"
    }
  }
}

resource "google_compute_instance" "example" {
  # ... other configuration ...

  # This configuration by default will internally combine labels defined
  # within the provider configuration block and those defined here
  labels = {
    Name = "MyVPC"
  }
}
```

### References
N/A

**Comment by upodroid** [comment] 2021-05-10 23:12
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/7325

**Comment by upodroid** [comment] 2021-05-10 23:13
Please close this issue and add thumbs up to #7325

**Closed** 2022-06-06 16:00 UTC
Labels: enhancement, size/xl
