### ISSUE TITLE
Adding Monitoring Scopes in Google Cloud 

### ISSUE THREAD

**Issue by amitcodex** [hashicorp/terraform-provider-google#9850] opened 2021-08-18 15:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I’m trying to provision the metric scope of a Google Cloud project through Terraform. I'm looking for functionality like [this](https://cloud.google.com/monitoring/api/ref_v3/rest/v1/locations.global.metricsScopes.projects/create) API. Does it exist already?

This feature would allow people to monitor projects from a centralized project. 

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```
```
resource google_metric_scope "metric scope" {
    project = sample_project
    monitored_projects = [
        monitored_project_1,
        monitored_project_2,
    ]
}
```

**Comment by slevenick** [comment] 2021-08-23 17:56
I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/2605 as monitored projects is now referred to as monitored scopes

**Closed by slevenick** 2021-08-23 17:56 UTC
Labels: enhancement
