### ISSUE TITLE
Destroying metadata_startup_script without destroying instance

### ISSUE THREAD

**Issue by kwri-avongluck** [hashicorp/terraform-provider-google#8846] opened 2021-04-05 22:31 UTC
Is it possible to destroy the existing "really destructive" metadata_startup_script state on deployed infrastructure?

We're using Terraform cloud, and are trying to migrate some systems from metadata_startup_script to metadata.startup-script. We can't "just change" since erasing metadata_startup_script means a destructive infrastructure change.

Destroying live infrastructure on startup-script modification is problematic. Here's my current solution for context... and it isn't great.

```diff
+  lifecycle {
+    ignore_changes = ["metadata_startup_script"]
+  }
+
   metadata = {
     enable-oslogin = "TRUE"
+    startup-script = file("bootstrap/appcfg.sh")
   }
 
   boot_disk {
@@ -28,8 +35,6 @@ resource "google_compute_instance" "app-cfg-zone" {
     }
   }
 
-  metadata_startup_script = file("bootstrap/appcfg.sh")
```

**Comment by slevenick** [comment] 2021-04-05 23:32
Hmmmm, so you want to change a ForceNew field without actually recreating the resource.

This won't be super possible with Terraform, but your current example seems ok? What is not ideal about it?

You could manually change the value in your [Terraform state file](https://www.terraform.io/docs/language/state/index.html), but that is dangerous and not usually recommended, and would likely be more difficult than adding the lifecycle ignore_changes block

**Comment by kwri-avongluck** [comment] 2021-04-06 13:06
The main problem is:

1) We have one set of TF and one set of bootstrap (metadata_startup) scripts.
2) We went live in dev.
3) We realized we can't make modifications / improvements to the bootstrap scripts without the change destroying "live" infrastructure
4) We tried to move from the metadata_startup_script to the non-destructive metadata.startup-script.. however since metadatadata_startup_script is in the state file, we can't get rid of it since it'll still destroy the infrastructure.

I hate to leave the ignore_changes block indefinitely since it's operating purely in the state file.  With the future TF API changes, it's going to want a resource specified in ignore_state directly instead of an arbitrary name as well which will get... bad.

If there's no good solution here beyond modifying the TF state file directly, take this as feedback that the nuances between metadata_startup_script and metadata.startup-script are a bit unclear (yes the documentation mentions it... but if you miss that section you're going to have a *really* irreversible bad time.)

**Comment by kwri-avongluck** [comment] 2021-04-06 19:42
I was able to finally straighten this one out..

1. terraform state pull > mystate
2. cp mystate mystate.original
3. edit mystate, remove all references to metadata_startup_script
4. bump the version by one
5. terraform state push mystate
6. go to google cloud, delete all startup-script metadata
7.  just remote metadata_startup_script, and move it to metadata.startup-script in our IaC
8. remote terraform plan

Anyway, if this is valuable in any way to highlight a potential enhancement let me know.  Otherwise I can just close :-)

**Comment by venkykuberan** [comment] 2021-04-07 19:51
@kwri-avongluck i am marking this as an enhancement request, let the team triage it and will update the outcome.

**Comment by slevenick** [comment] 2021-04-12 17:57
I don't think we want to change anything here. metadata_startup_script is designed specifically to force recreation on change, so this is working as intended

**Closed by slevenick** 2021-04-12 17:57 UTC
Labels: enhancement
