### ISSUE TITLE
BigQuery table schema diff trigger patch instead of recreating the table

### ISSUE THREAD

**Issue by robertsahlin** [hashicorp/terraform-provider-google#8630] opened 2021-03-09 15:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current logic checks for a schema diff and if found tries to recreate the table (update request). In most cases a schema diff is due to schema evolution and hence a patch of schema would be the correct action (patch request).

https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch 

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by D3nn3** [comment] 2021-03-11 12:32
Would this explain the behavior that adding a new nullable column to an existing schema triggers a recreation of a table? This is the case with v3.58.0 but not with v3.53.0. I know that there was a bug in v3.54.0 which was fixed later but I still have experienced that recreation of tables are triggered (with e.g. v3.58.0) when adding nullable columns (which seemed weird because this isn't the case with older versions).

**Comment by tpolekhin** [comment] 2021-03-15 20:54
I did some analysis with this in a different issue that was closed, so possibly no one have seen it. Posting here just for reference https://github.com/hashicorp/terraform-provider-google/issues/8503#issuecomment-790684226

**Comment by terekete** [comment] 2023-03-01 12:50
Like to add a note that BQ is now supporting in GA the ability to rename column and drop columns. Is it possible to enable this same functionality from terraform ?

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_column_statement

**Comment by gatzlaff-mms** [comment] 2023-04-26 07:30
I'd like to ask if the discussed feature is considered in the future roadmap?

**Comment by obada-ab** [comment] 2024-04-11 09:59
This Issue is a bit outdated, the schema diff function does not always force replacement now:

- Adding columns and relaxing column mode happen in-place ([reference](https://github.com/hashicorp/terraform-provider-google/issues/14769#issuecomment-1922031208))
- Dropping columns happens in-place after: https://github.com/GoogleCloudPlatform/magic-modules/pull/10170
- Renaming columns tracked in https://github.com/hashicorp/terraform-provider-google/issues/14769

@melinath I think we can close this issue or mark it as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/14769

**Comment by melinath** [comment] 2024-04-12 21:14
Seems reasonable. If anyone ends up here because of a specific case not covered by the above, please open a new tickets with details. Thanks!

**Closed by melinath** 2024-04-12 21:14 UTC
Labels: enhancement, size/m, service/bigquery, forward/review
