### ISSUE TITLE
GCP - "Terraform Import" on VPC SC Perimeter removing Access List

### ISSUE THREAD

**Issue by amar2k05** [hashicorp/terraform-provider-google#13317] opened 2022-12-21 19:11 UTC
### Affected Resource(s)

* google_access_context_manager_service_perimeter

Hi,

I am trying to import VPC SC Perimeter in to terraform state, but the plan shows removing one Access Level(test_ent_perim_access_002) in the perimeter, not sure why. Also Access List "test_ent_perim_access_001" is getting removed and again added. Kindly suggest.

Below is the resource

resource "google_access_context_manager_service_perimeter" "test-ent-prod-perim-001" {
    parent         = "accessPolicies/263896276372"
    name           = "accessPolicies/263896276372/servicePerimeters/test_ent_prod_perim_001"
    title          = "test_ent_prod_perim_001"
    description = "Test Org VPC SC perimeter"
    perimeter_type = "PERIMETER_TYPE_REGULAR"
    status {
      resources = ["7654356728263"]
      restricted_services = ["bigquery.googleapis.com"]
          access_levels       = [
              "accessPolicies/263896276372/accessLevels/test_onprem_ipwhitelist",
              "accessPolicies/263896276372/accessLevels/test_ent_cmn_perim_access_001",
              "accessPolicies/263896276372/accessLevels/test_ent_perim_access_001",
              "accessPolicies/263896276372/accessLevels/test_ent_perim_access_002",
              ]
    }
  }

Below is the import command

- terraform import --var-file=$VARS --var-file=$BACKEND --var-file=vars/$ENV/terraform.tfvars google_access_context_manager_service_perimeter.test-ent-prod-perim-001 accessPolicies/263896276372/servicePerimeters/test_ent_prod_perim_001 

Below is the plan where it shows the removal of Access Level

Terraform will perform the following actions:
  # google_access_context_manager_service_perimeter.test-ent-prod-perim-001 will be updated in-place
  ~ resource "google_access_context_manager_service_perimeter" "test-ent-prod-perim-001" {
      ~ description               = "Perimeter shielding projects" -> "Prod VPC perimeter"
        id                        = "accessPolicies/263896276372/servicePerimeters/test_ent_prod_perim_001"
        name                      = "accessPolicies/263896276372/servicePerimeters/test_ent_prod_perim_001"
        # (4 unchanged attributes hidden)
      ~ status {
          ~ access_levels       = [
              - "accessPolicies/263896276372/accessLevels/test_ent_perim_access_001",
                "accessPolicies/263896276372/accessLevels/test_onprem_ipwhitelist",
                # (1 unchanged element hidden)
                "accessPolicies/263896276372/accessLevels/test_ent_perim_access_002",
              - "accessPolicies/263896276372/accessLevels/test_ent_perim_access_002",
              + "accessPolicies/263896276372/accessLevels/test_ent_perim_access_001",
            ]
            # (2 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.

Expected Behaviour:
No Infrastructure chnages

**Comment by edwardmedia** [comment] 2022-12-25 22:52
@amar2k05  I am not sure why it showed the plan when you ran `terraform import`. Can you share the full debug log? Also you may try a blank resource for import.

```tf
resource "google_access_context_manager_service_perimeter" "test-ent-prod-perim-001" {
 }
```

**Comment by amar2k05** [comment] 2022-12-26 18:59
Hi Edward,
Thank you very much for your response.
I am running Terraform plan after importing the resource to double check my import is correct. Ideally plan should show **"No changes. Your infrastructure matches the configuration."**, that means the imported resource is exactly matching with the resource I imported.
I am attaching the full log (plan)
[forums_tf_import_removing_acces_level_latest.txt](https://github.com/hashicorp/terraform-provider-google/files/10304534/forums_tf_import_removing_acces_level_latest.txt)


As you suggested, I have imported using blank resource, import is successful, but when I ran plan, same issue, it's trying to remove and add access level **"test_ent_perim_access_001"** and completely removing access level **"test_ent_perim_access_002"**

Kindly help.

Thanks,
Amarnath.

**Comment by amar2k05** [comment] 2022-12-26 19:02
Just wanted to mention that I have tried maximum possible ways as below
1. Tried upgrading/downgrading the google provider version
2. Upgrading TF version
3. Changing the order of access lists in the resource code
4. Created a new VPC SC perimeter with same access lists and tried to import, which is perfectly working fine.

**Comment by edwardmedia** [comment] 2022-12-27 17:52
@amar2k05 glad you are succeeded in importing. Do you still leave the config blank when you do the comparison (tf plan)? You need to update the config to match the imported so no diff will show up. Does this make sense?

**Comment by amar2k05** [comment] 2022-12-28 11:17
Hi Edward,
Thank for your response.
Blank import succeeded, infact import never failed earlier as well, it's that it doesn't work as expected.
After the blank import was successful, I have added the config, but again the same issue where the plan was showing removing & adding back one Access List and totally removing the other Access list, same can be seen in the attached plan with earlier reply. In a  nut shell import is not working as expected. Is there any reason for this? Note that my config exactly matches with what's there in console, still plan shows removing/adding. Is there any possibility of having a call with you so that I can show a demo on the issue quickly?


Regards,
Amarnath.

**Comment by edwardmedia** [comment] 2022-12-29 00:09
@amar2k05 I think what the problem is. It is the server side re-ordering which keeps changing. To solve that, we need to change [its type](https://github.com/hashicorp/terraform-provider-google/blob/3339c721c92a71207a8f124b872158588c7faa5d/google/resource_access_context_manager_service_perimeter.go#L105) to set. Unfortunately it is a breaking change. Mark it accordingly.

**Comment by amar2k05** [comment] 2022-12-29 00:26
Hi Edward,
Thanks for your reply, I have gone through the link provided,but can't get on where to change the type. Is it I need to mention somewhere in the resource, can you give an example please?

Regards,
Amarnath.

**Comment by amar2k05** [comment] 2022-12-29 09:20
Hi Edward,
Good Morning.
When you mentioned "breaking change", is it a bug and that need to be fixed by you/hashicorp and this cannot be solved by any alternative?

I just used "toset" function on access_lists and tried, but it didn't work, I mean plan is showing removing/adding one access list and totally removing another.

Regards,
Amarnath.

**Comment by amar2k05** [comment] 2023-01-03 13:32
Hi Edward,
Happy new year.
Can you kindly let me know any tentative plan to fix this bug so that I can plan accordingly?

Thanks,
Amarnath.

**Comment by c2thorn** [comment] 2023-07-26 19:46
b/293329486

**Comment by Charlesleonius** [comment] 2023-08-31 16:22
Hello @amar2k05, I know its been a long time but I am working on this issue and wanted to check in if you can still reproduce it. 

I see in your output:
```
          ~ access_levels       = [
              - "accessPolicies/263896276372/accessLevels/test_ent_perim_access_001",
                "accessPolicies/263896276372/accessLevels/test_onprem_ipwhitelist",
                "accessPolicies/263896276372/accessLevels/core_int_cmn_perim_access_001",
              + "accessPolicies/263896276372/accessLevels/test_ent_perim_access_001",
                "accessPolicies/263896276372/accessLevels/test_ent_perim_access_002",
              - "accessPolicies/263896276372/accessLevels/test_ent_perim_access_002",
            ]
```
Its clear that `accessPolicies/263896276372/accessLevels/test_ent_perim_access_001` is changing its order but `- accessPolicies/263896276372/accessLevels/test_ent_perim_access_002` looks like its being removed. I think its order is actually just changing as well because there is another line `accessPolicies/263896276372/accessLevels/test_ent_perim_access_002` which does not have a minus so I believe its not being deleted. Did you ever actually apply the plan to see if it was created as you expected.

**Comment by Charlesleonius** [comment] 2023-08-31 17:54
Thank you Amar for your quick reply!

After the fix is in place, the ordering change should no longer cause an issue. For the mean time, applying the changes as is should not cause any interruption as it would be done in place rather than one operation for removing the fields and one operation for adding them.

**Comment by amar2k05** [comment] 2023-08-31 19:07
Thanks Charles.
Can you please let me know when the fix will be live?

Regards,
Amarnath.

**Comment by Charlesleonius** [comment] 2023-09-05 18:56
The change will be part of the next major release which may take a few weeks. I will keep you updated on the release.

**Comment by amar2k05** [comment] 2023-09-05 20:24
Ok, thanks for the update Charles.

**Comment by c2thorn** [comment] 2023-09-11 19:48
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8788

This will release with v5.0.0. Check https://github.com/hashicorp/terraform-provider-google/issues/15582 for more details on the major release.

**Closed by c2thorn** 2023-09-11 19:48 UTC
Labels: breaking-change, persistent-bug, forward/linked, service/accesscontextmanager
