### ISSUE TITLE
Terraform resource to promote cloud sql replica to primary

### ISSUE THREAD

**Issue by kp250278** [hashicorp/terraform-provider-google#10486] opened 2021-11-03 15:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Current Terraform Version
[vagrant@centos7 ~]$ terraform version
Terraform v0.12.31

Checked with the Existing provider/versions this feature is not available with latest as well
We are using cloud sql postgres with cross region read replica option and there is option to enable automatic failover using terraform but there is no option to failover that using terraform resource/settings/option.

Currently we are suing Gcloud API commands to promote the replica for DR testing. As we are using gcloud command to promote the replica our cloud sql instance created using terraform no longer sync with statefile(terraform)

Autofailover option not feasible as if there is any other issue with primary it will promote the replica in that case. also we need to update the connections strings into applications as application is still pointing to primary instance connection string.

### New or Affected Resource(s)

* google_sql_database
* google_sql_database_instance

### Potential Terraform Configuration

Attempted Solutions
Created ansible role using gcloud command to promote replica. due to this instance going out of sync with statefile and we unable to update using TF.
referance - https://cloud.google.com/sql/docs/mysql/replication/manage-replicas#:~:text=gcloud%20sql%20instances%20promote

Proposal
if there is a TF resource/settings/option available that we can use for promote read replica to primary that will be good.
so state file will not out of sync with the promoted instance and we are good to use this clous sql instance under terraform

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

referance - https://cloud.google.com/sql/docs/mysql/replication/manage-replicas#:~:text=gcloud%20sql%20instances%20promote

* b/257028890

**Comment by kp250278** [comment] 2021-11-10 07:09
Can you please help on above we are stuck due to this issue

**Comment by c2thorn** [comment] 2021-11-10 20:57
@kp250278 Given that this is represented in the API via another endpoint (https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/promoteReplica), this seems like an imperative action that won't fit into Terraform's declarative schema. How would you expect this to look like as Terraform configuration?

Alternatively, have you attempted to promote to primary outside of Terraform, and then import the resource back into state? That would reset the state file.

**Comment by kp250278** [comment] 2021-11-11 08:18
> @kp250278 Given that this is represented in the API via another endpoint (https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/promoteReplica), this seems like an imperative action that won't fit into Terraform's declarative schema. How would you expect this to look like as Terraform configuration?
> 
> Alternatively, have you attempted to promote to primary outside of Terraform, and then import the resource back into state? That would reset the state file.

We are thinking there would be some settings under google_sql_database_instance resource that we can use to promote the replica or if you would suggest best way that would be great

I will try the import option

**Comment by c2thorn** [comment] 2021-11-12 20:21
@kp250278 please try out the import method, as I do not think that this action can be represented in Terraform in a declarative way with the way the API represents it.

**Comment by c2thorn** [comment] 2021-11-30 20:12
Hey @cb250373, thanks for the feedback. You're right, and I should correct my statement above to "I do not think this can be represented in the provider easily based on how it is represented in the API".

You are correct that the use cases themselves are considered declarative, however the provider is usually limited to what is available from the API. The resource schema in Terraform essentially mirrors the API schema, and deviating from it often leads to problems. My concern was that there wasn't a field that gave us a direct indication of whether something was intended to be a primary instance vs a replica (`replication_config` didn't seem great because we've already set that to [default to the API's current value](https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_sql_database_instance.go#L513)).

**BUT** after spending more time browsing the API I found a field that makes it pretty explicit and declarative-friendly: https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#sqlinstancetype

This could allow us to check the type set in the backend and demote/promote based on how that compares to the value set by user configuration.

I'll open this back up for triage to be discussed with the team.

**Comment by kp250278** [comment] 2021-12-07 15:32
Hi Team, Any update on this

**Comment by kp250278** [comment] 2022-01-27 14:09
@rileykarson @c2thorn Hi Team, Can we have update on this

**Comment by c2thorn** [comment] 2022-01-27 17:56
@kp250278 while acknowledging this is possible to do, our team does not have plans to implement this anytime soon due to prioritization. From what I understand, reimporting the resource is still a viable workaround. Has this option failed for you?

**Comment by enocom** [comment] 2022-06-15 04:01
I've written up a short explanation of how to do this by reimporting the resource here: https://stackoverflow.com/a/72625750/927514.

**Comment by n-oden** [comment] 2022-08-01 18:10
Possibly worth mentioning in terms of prioritization: google seems to have recently (and silently) made a change that has resulted CloudSQL backups becoming instantly unavailable when an instance is deleted.  While this admittedly aligns with what the documentation has always said, the actual observed reality until this month was that as long as you had a record of the deleted database instance ID, you could restore from any of its backups for 6-48 hours after it was deleted.  This no longer being the case, any DR/failover workflows that depended on this behavior (ahem, ask me now I know) are broken and I suspect that a lot of people who had previously not had any need to manage primary/replica failover in terraform will be in some need of this.

**Comment by c2thorn** [comment] 2023-02-08 15:57
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/7190

**Closed by c2thorn** 2023-02-08 15:57 UTC
Labels: enhancement, size/m, priority/1
