### ISSUE TITLE
 GCP: Bigquery: Remove existing column or Change to the column name causes the entire table to be re-created

### ISSUE THREAD

**Issue by murlik1** [hashicorp/terraform-provider-google#16874] opened 2023-12-28 04:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.6.6
on linux_amd64

### Affected Resource(s)

google_bigquery_table

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
#################################################################################
main.tf --> Initial main.tf
provider "google" {
    project = "gcp-sandbox-1-359004"
	region = "us-central1"
	zone = "us-central1-a"
}

resource "google_bigquery_table" "bigquery_table" {
    dataset_id = "us_dataset"
    table_id = "test_table"
    deletion_protection = false
    labels = {
        env = "development"
    }
    schema = <<EOF
    [
        {
            "name": "id",
            "type": "INT64"
        },
        {
            "name": "name",
            "type": "STRING",
            "description": "name"
        },
        {
            "name": "address",
            "type": "STRING",
            "description": "Address"
        }
    ]
    EOF
}

#################################################################################

Case 1 - Removing a column from table
If a column is removed from the schema (example - address column is removed), terraform plan shows the entire table is to be re-created when bigquery supports removing of column without dropping the entire table.

provider "google" {
    project = "gcp-sandbox-1-359004"
	region = "us-central1"
	zone = "us-central1-a"
}

resource "google_bigquery_table" "bigquery_table" {
    dataset_id = "us_dataset"
    table_id = "test_table"
    deletion_protection = false
    labels = {
        env = "development"
    }
    schema = <<EOF
    [
        {
            "name": "id",
            "type": "INT64"
        },
        {
            "name": "name",
            "type": "STRING",
            "description": "name"
        }
    ]
    EOF
}

terraform plan
google_bigquery_table.bigquery_table: Refreshing state... [id=projects/gcp-sandbox-1-359004/datasets/us_dataset/tables/test_table]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_bigquery_table.bigquery_table must be replaced
-/+ resource "google_bigquery_table" "bigquery_table" {
      ~ creation_time       = 1670412117689 -> (known after apply)
      ~ etag                = "b1oiOr/j+y7JNvy/hGvIhQ==" -> (known after apply)
      ~ expiration_time     = 0 -> (known after apply)
      ~ id                  = "projects/gcp-sandbox-1-359004/datasets/us_dataset/tables/test_table" -> (known after apply)
      ~ last_modified_time  = 1670412232655 -> (known after apply)
      ~ location            = "US" -> (known after apply)
      ~ num_bytes           = 0 -> (known after apply)
      ~ num_long_term_bytes = 0 -> (known after apply)
      ~ num_rows            = 0 -> (known after apply)
      ~ project             = "gcp-sandbox-1-359004" -> (known after apply)
      ~ schema              = jsonencode(
          ~ [
              ~ {
                    name = "id"
                  ~ type = "INTEGER" -> "INT64"
                },
                {
                    description = "name"
                    name        = "name"
                    type        = "STRING"
                },
              - {
                  - description = "Address"
                  - name        = "address"
                  - type        = "STRING"
                },
            ] # forces replacement
        )
      ~ self_link           = "https://bigquery.googleapis.com/bigquery/v2/projects/gcp-sandbox-1-359004/datasets/us_dataset/tables/test_table" -> (known after apply)
      ~ type                = "TABLE" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

#################################################################################
Case 2 - Changing a column name in table
If a column is renamed in the schema (example - address column is renamed as address_1), terraform plan shows the entire table is to be re-created when bigquery supports renaming of column without dropping the entire table.

provider "google" {
    project = "gcp-sandbox-1-359004"
	region = "us-central1"
	zone = "us-central1-a"
}

resource "google_bigquery_table" "bigquery_table" {
    dataset_id = "us_dataset"
    table_id = "test_table"
    deletion_protection = false
    labels = {
        env = "development"
    }
    schema = <<EOF
    [
        {
            "name": "id",
            "type": "INT64"
        },
        {
            "name": "name",
            "type": "STRING",
            "description": "name"
        },
        {
            "name": "address_1",
            "type": "STRING",
            "description": "Address"
        }
    ]
    EOF
}

terraform plan
google_bigquery_table.bigquery_table: Refreshing state... [id=projects/gcp-sandbox-1-359004/datasets/us_dataset/tables/test_table]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_bigquery_table.bigquery_table must be replaced
-/+ resource "google_bigquery_table" "bigquery_table" {
      ~ creation_time       = 1670412117689 -> (known after apply)
      ~ etag                = "b1oiOr/j+y7JNvy/hGvIhQ==" -> (known after apply)
      ~ expiration_time     = 0 -> (known after apply)
      ~ id                  = "projects/gcp-sandbox-1-359004/datasets/us_dataset/tables/test_table" -> (known after apply)
      ~ last_modified_time  = 1670412232655 -> (known after apply)
      ~ location            = "US" -> (known after apply)
      ~ num_bytes           = 0 -> (known after apply)
      ~ num_long_term_bytes = 0 -> (known after apply)
      ~ num_rows            = 0 -> (known after apply)
      ~ project             = "gcp-sandbox-1-359004" -> (known after apply)
      ~ schema              = jsonencode(
          ~ [
              ~ {
                    name = "id"
                  ~ type = "INTEGER" -> "INT64"
                },
                {
                    description = "name"
                    name        = "name"
                    type        = "STRING"
                },
              ~ {
                  ~ name        = "address" -> "address_1"
                    # (2 unchanged attributes hidden)
                },
            ] # forces replacement
        )
      ~ self_link           = "https://bigquery.googleapis.com/bigquery/v2/projects/gcp-sandbox-1-359004/datasets/us_dataset/tables/test_table" -> (known after apply)
      ~ type                = "TABLE" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
#################################################################################

```

### Expected Behavior

The expected behavior for case 1 (removing of column) and case 2 (renaming of the column) should be modification on existing table without dropping the entire table as Bigquery supports altering a column name and dropping a column without dropping entire table.

### Actual Behavior

On Terraform apply, the table gets dropped and recreated.

### Steps to Reproduce

1. Run the main.tf to create the base table 
2. Case 1 -  Edit the main.tf with removing the address column in schema json and run terraform apply
3. Case 2 - Edit the main.tf with renaming the address as address_1 in schema json and run terraform apply.

### References

* #0000

b/318064430

**Comment by shuyama1** [comment] 2023-12-28 22:50
I can reproduce this. I don't think the API supports column rename or deletion for Bigquery table when it was implemented (not sure if these two actions are supported now). Therefore, change this to feature request(enhancement) and forward the ticket to the service team.

**Comment by murlik1** [comment] 2024-01-02 04:49
Hi Could you please let me know how to change this request to feature request ?

**Comment by melinath** [comment] 2024-01-02 18:06
No action needed on your end. Note from triage: this would likely mean modifying `resourceBigQueryTableSchemaCustomizeDiffFunc` to capture this case as "changeable", which may be tricky since it's a json blob.

**Comment by obada-ab** [comment] 2024-04-11 12:00
@melinath this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/14769

**Comment by melinath** [comment] 2024-04-12 21:10
Agreed. Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/14769

**Closed by melinath** 2024-04-12 21:10 UTC
Labels: enhancement, size/s, forward/linked, service/bigquery
