### ISSUE TITLE
Investigate reworking `primary_resource_name`

### ISSUE THREAD

**Issue by trodge** [hashicorp/terraform-provider-google#13983] opened 2023-03-14 01:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

`primary_resource_name` in resource yamls and `terraform.yaml` should be split into two fields. `primary_resource_name` should apply to the resource name in generated tests and `primary_resource_iam_name` should be the resource name in iam tests. Currently both these values use the same field, which is confusing. See [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/healthcare/ConsentStore.yaml#L41-L43).

### New or Affected Resource(s)

`google_healthcare_consent_store`
`google_workstations_workstation_cluster`
Probably others as well

**Comment by melinath** [comment] 2023-03-14 18:13
See https://github.com/GoogleCloudPlatform/magic-modules/pull/7393#pullrequestreview-1331344501 for an example of why the iam name is confusing.

**Comment by rileykarson** [comment] 2023-03-20 16:50
I'm not sure this needs to be split- it should be used just for IAM, I think?

**Comment by c2thorn** [comment] 2024-05-20 21:30
It seems like `primary_resource_name` is actually only used for IAM generated tests, which means we should probably rename it to be more specific.

**Comment by melinath** [comment] 2024-05-20 22:38
Ideally we would be able to remove `primary_resource_name` in most cases and autogenerate the value instead, as described in https://github.com/hashicorp/terraform-provider-google/issues/8712

**Comment by c2thorn** [comment] 2024-05-20 22:42
Agreed, that does sound like a better solution. Should we close this then? The original bug (splitting the name) doesn't seem like a viable path.

**Comment by melinath** [comment] 2024-05-20 22:44
Sure, we could track the rename of the field (if it's still necessary anywhere, which it may not be) in that ticket.

**Comment by melinath** [comment] 2024-05-20 22:44
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8712

**Closed by melinath** 2024-05-20 22:44 UTC
Labels: enhancement, size/m, technical-debt, mmv1-generator, service/terraform
