### ISSUE TITLE
Failing test(s): TestAccCloudFunctionsFunction_firestore

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#18075] opened 2024-05-09 22:42 UTC
### Impacted tests

- TestAccCloudFunctionsFunction_firestore

### Affected Resource(s)

- google_cloudfunctions_function

### Failure rates

- 100% since 2024-03-29

### Message(s)

```
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error waiting for Creating CloudFunctions Function: Error code 5, message: Firestore database 'projects/ci-test-project-nightly-beta/databases/(default)' does not exist. Please create a "(default)" Firestore Native database first.
          with google_cloudfunctions_function.function,
          on terraform_plugin_test.tf line 13, in resource "google_cloudfunctions_function" "function":
          13: resource "google_cloudfunctions_function" "function" {
--- FAIL: TestAccCloudFunctionsFunction_firestore (59.08s)
FAIL
```

### Nightly build test history

- [TestAccCloudFunctionsFunction_firestore](https://hashicorp.teamcity.com/test/9141074835059145619?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true)

**Comment by melinath** [comment] 2024-05-09 23:02
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/18072

**Closed** 2024-05-10 16:36 UTC
Labels: test-failure, service/cloudfunctions, forward/exempt
