### ISSUE TITLE
dial tcp [::1]:80: connect: connection refused when modifying google_container_cluster

### ISSUE THREAD

**Issue by buildwithjz** [hashicorp/terraform-provider-google#13790] opened 2023-02-21 00:04 UTC
I am following the pattern described in the following example:
https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_examples/gke/main.tf

Essentially I am creating a GKE cluster and associated resources in the same Terraform config, while passing the data source of the Kubernetes cluster into the provider args for the Kubernetes provider. This has been working well as I have not made any changes to the cluster itself since create.

After attempting to modify a non-destructive property on the cluster control plane, the associated plan will result in the following error message when refreshing the state of `kubernetes_*` resources.

```
dial tcp [::1]:80: connect: connection refused when modifying google_container_cluster
```

I am using latest versions of both google and kubernetes providers at the time of writing.

The reason why I am raising this issue here is because I believe that the `google_container_cluster` resource is somehow 'marking' its change as a change that will ultimately invalidates its datasource, therefore reverting the `kubernetes` provider settings back to localhost:80. I have attempted to modify properties such as `maintenance_policy` and `min_master_version` (e.g. to upgrade the minor version of the control plane manually).

The provider should not 'invalidate' or 'refresh' the data source in such scenarios, and allow the `kubernetes` provider to continue using previous values for subsequent plans and runs to work. Also I would appreciate hearing about any interim workarounds.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.0.0 (Terraform Cloud)

### Affected Resource(s)

* google_container_cluster
* kubernetes_*

### Terraform Configuration Files

```tf
provider "kubernetes" {
  host  = "https://${data.google_container_cluster.main.endpoint}"
  token = data.google_client_config.current.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.main.master_auth[0].cluster_ca_certificate)
}

data "google_client_config" "current" {
}

data "google_container_cluster" "main" {
  name = google_container_cluster.main.name
  location = var.region
}

resource "google_container_cluster" "main" {
  // redacted ...
  /*
  maintenance_policy {
    recurring_window {
      start_time = "2023-02-26T14:00:00Z"
      end_time = "2023-02-26T19:00:00Z"
      recurrence = "FREQ=WEEKLY;BYDAY=SUN,MON"
    }
  }
  */
}

resource "kubernetes_namespace" "foo" {
  // redacted ...
}
```

### Expected Behavior

Terraform creates a maintenance window on my cluster without destroying or recreating the cluster

### Actual Behavior

Terraform plan fails with the following output:

```
│ Error: Get "http://localhost/api/v1/namespaces/foo": dial tcp [::1]:80: connect: connection refused
│
│   with kubernetes_namespace.foo,
│   on k8s-namespaces.tf line 3, in resource "kubernetes_namespace" "foo":
│    3: resource "kubernetes_namespace" "foo" {
```

### Steps to Reproduce

1. Create a GKE cluster and kubernetes resources in the same terraform config 
2. Update a property on the `google_container_cluster` resource
3. `terraform plan`

### Important Factoids

I am running in Terraform cloud, and therefore I cannot use `kube_config` 

### References

* #0000

**Comment by edwardmedia** [comment] 2023-03-08 14:39
@buildwithjz I do not fully understand what the problem is. Did you say changing `maintenance_policy` or/and `min_master_version` triggers recreating the cluster? This is not by design. I need the details about how you repro this. Also why do you need `data.google_container_cluster.main.endpoint`? Can't you use `google_container_cluster.main.endpoint` directly?

**Comment by buildwithjz** [comment] 2023-03-15 21:59
Hi @edwardmedia, thanks for taking a look.

> Did you say changing `maintenance_policy` or/and `min_master_version` triggers recreating the cluster? 

Not exactly - what I mean is that changes to `maintenance_policy` or/and `min_master_version` results in the connection refused error. The same is true for all other non-destructive changes to the `google_container_cluster`, for example `logging_config`, `monitoring_config`. 

> Also why do you need data.google_container_cluster.main.endpoint?

The reference to the cluster's datasource in the Kubernetes provider configuration is in the example here :
https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_examples/gke/main.tf#L39-L45

Funnily enough, using the resource attributes directly like so, works fine

```
provider "kubernetes" {
  host  = "https://${google_container_cluster.main.endpoint}"
  token = data.google_client_config.current.access_token
  cluster_ca_certificate = base64decode(google_container_cluster.main.master_auth[0].cluster_ca_certificate)
}
```

**Comment by edwardmedia** [comment] 2023-04-09 13:49
@buildwithjz is this still an issue?

**Comment by edwardmedia** [comment] 2023-04-14 22:18
@buildwithjz closing assuming this is no longer an issue

**Closed by edwardmedia** 2023-04-14 22:18 UTC
Labels: bug, waiting-response
