### ISSUE TITLE
BigQuery TransferConfig should support notification fields

### ISSUE THREAD

**Issue by jaketf** [hashicorp/terraform-provider-google#6412] opened 2020-05-19 01:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

BigQuery Transfer config should support all fields in the transfer config proto.

This is currently causing user pain as you cannot set notifications for scheduled queries via [notification_pubsub_topic](https://googleapis.dev/python/bigquerydatatransfer/latest/gapic/v1/types.html#google.cloud.bigquery_datatransfer_v1.types.TransferConfig.notification_pubsub_topic) or [email_preferences](https://googleapis.dev/python/bigquerydatatransfer/latest/gapic/v1/types.html#google.cloud.bigquery_datatransfer_v1.types.TransferConfig.notification_pubsub_topic) from this resource.

There may be other useful fields in the TransferConfig such as schedule_options.

### New or Affected Resource(s)

* google_bigquery_data_transfer_config

**Comment by pythonrocks** [comment] 2020-08-13 11:04
Sorry if this comment violates some rules, but we're also interested in having ability to set up notifications for scheduled queries. Are there plans on fixing this issue?

**Comment by samhumphreys-2sixty** [comment] 2020-08-13 11:10
Duplicate of #5866

**Comment by samhumphreys-2sixty** [comment] 2020-08-13 11:14
@danawillow /other - Is there any update on this?

**Comment by danawillow** [comment] 2020-08-17 21:26
Thanks, closing as a duplicate. If anyone is subscribed to this and +1'd this but not the other, please go +1 the other issue so we have an accurate check.

**Closed by danawillow** 2020-08-17 21:26 UTC
Labels: enhancement, size/S
