### ISSUE TITLE
Add data list Networks, List subnets, similar to AWS hashcorp providers

### ISSUE THREAD

**Issue by brunotorrente** [hashicorp/terraform-provider-google#12067] opened 2022-07-09 06:13 UTC
Currently the provider only provides information about a subnet or network if you have their names previously.

My suggestion, add an option similar to another Hashcorp provider ( AWS )

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets

Google API

https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/list?hl=pt-br

Via Gcloud CLI

  gcloud compute networks subnets list --project haha-project-name

**Comment by rileykarson** [comment] 2022-07-11 17:42
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8255

**Closed by rileykarson** 2022-07-11 17:42 UTC
Labels: enhancement
