### ISSUE TITLE
Provider crash when importing secret version with wrong format

### ISSUE THREAD

**Issue by Kaawin1** [hashicorp/terraform-provider-google#13725] opened 2023-02-13 17:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.4
terragrunt version v0.38.9

### Affected Resource(s)

google_secret_manager_secret_version

### Terraform Configuration Files
```tf
resource "google_secret_manager_secret" "this" {
  for_each = local.secrets_name

  project   = var.project_id
  secret_id = each.key

  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "this" {
  for_each = local.secrets_name

  secret      = google_secret_manager_secret.this[each.key].id
  secret_data = local.secrets[each.key].value
}

```

### Panic Output

Terraform crashes when importing a secret version with the wrong format
```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may
│ contain more details.
╵


Stack trace from the terraform-provider-google_v4.47.0_x5 plugin:

panic: Version name does not fit the format `projects/{{project}}/secrets/{{secret}}/versions/{{version}}`

goroutine 48 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceSecretManagerSecretVersionImport(0xc000158f80, {0x2d84b40?, 0xc0005ba800})
	github.com/hashicorp/terraform-provider-google/google/resource_secret_manager_secret_version.go:290 +0x2c5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc000098360, {0x3318d98, 0xc001495470}, 0xc00098b5e0, {0xc0002fecc0, 0x27})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/provider.go:387 +0x1ce
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc0006d8f48, {0x3318d98?, 0xc001495350?}, 0xc000d56120)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1088 +0xf4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc0001c0280, {0x3318d98?, 0xc001494bd0?}, 0xc000f139f0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:848 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0x2d17140?, 0xc0001c0280}, {0x3318d98, 0xc001494bd0}, 0xc00002a310, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x331e400, 0xc000bd4820}, 0xc0002d7c20, 0xc000964d50, 0x44af1b8, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x331e400, 0xc000bd4820}, 0xc0002d7c20, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-google_v4.47.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```
### Expected Behavior

Terraform crashes

### Actual Behavior

Terraform should not crash and just print error message

### Steps to Reproduce

1.``` terragrunt import 'google_secret_manager_secret_version.this' projects/projectId/test-secret/versions/1```

**Comment by edwardmedia** [comment] 2023-02-13 18:43
@Kaawin1 I think this is by design which was introduced by below PR. Can you check it out to see if that make sense? 

https://github.com/GoogleCloudPlatform/magic-modules/pull/6569/files

**Comment by Kaawin1** [comment] 2023-02-14 13:26
You are right. But I don't see why panic is necessary. For me only the error message `Version name does not fit the format projects/{{project}}/secrets/{{secret}}/versions/{{version}}` is useful

**Comment by edwardmedia** [comment] 2023-02-14 14:52
@Kaawin1 can you try below? `secrets` might be needed

```
projects/projectId/secrets/test-secret/versions/1
```

**Comment by Kaawin1** [comment] 2023-02-14 14:56
Yes `secrets` is needed. On the first try, I forgot it and the provider crashed with the stack trace. I think an error message is enough and the stacktrace/panic output is not necessary

**Comment by edwardmedia** [comment] 2023-02-14 17:20
@Kaawin1 I am closing this issue now, as the panic is by design. Feel free to reopen if you see it differently. Thanks

**Closed by edwardmedia** 2023-02-14 17:20 UTC
Labels: bug, crash
