### ISSUE TITLE
Unable to apply manged_prometheus to google_container_cluster

### ISSUE THREAD

**Issue by felipepazsquid** [hashicorp/terraform-provider-google#12325] opened 2022-08-17 04:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`Terraform v1.2.7
on linux_amd64
`

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "primary" {
  name     = var.cluster_name
  location = var.zone_location

  initial_node_count = var.initial_node_count

  remove_default_node_pool = true
  release_channel {
    channel = "REGULAR"
  }

  network    = var.network
  subnetwork = var.subnetwork

  logging_service    = var.logging_service
  monitoring_service = var.monitoring_service

  monitoring_config {
    enable_components = ["SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER"]

    managed_prometheus {
      enabled = true
    }
  }

  vertical_pod_autoscaling {
    enabled = true
  }
}
```

### Expected Behavior

Creating a cluster on GCP with prometheus monitoring enabled

### Actual Behavior

It returns an error with
`Unsupported argument`

### Steps to Reproduce

1. Create a file with the above code
2. Run `terraform apply`

### Important Factoids

I've updated the cluster directly in the GCP console and tried to import this configuration by the terraform cli. Even so I couldn't get this configuration, it seems the code hasn't been merged to the main branch.

I'm actually using the google provider version `4.32.0`

**Comment by nokernel** [comment] 2022-08-17 14:13
I believe that this is not a bug, this feature is in the google beta provider. Try using google-beta provider instead.

**Comment by edwardmedia** [comment] 2022-08-17 15:23
@felipepazsquid that is true. The feature is beta. Can you try `google-beta`?

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#managed_prometheus

**Comment by edwardmedia** [comment] 2022-08-30 13:47
@felipepazsquid closing this now

**Closed by edwardmedia** 2022-08-30 13:47 UTC
Labels: bug, waiting-response
