### ISSUE TITLE
Add IAM resources for Pub/Sub schema

### ISSUE THREAD

**Issue by EricStG** [hashicorp/terraform-provider-google#16334] opened 2023-10-23 15:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Pub/Sub supports IAM at the schema level, but there are no existing resources that allow us to assign them

### New or Affected Resource(s)

* google_pubsub_schema_iam_policy
* google_pubsub_schema_iam_binding
* google_pubsub_schema_iam_member

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_pubsub_topic_iam_policy" "policy" {
  project = google_pubsub_schema.example.project
  schema = google_pubsub_schema.example.name
  policy_data = data.google_iam_policy.admin.policy_data
}

resource "google_pubsub_topic_iam_binding" "binding" {
  project = google_pubsub_schema.example.project
  schema = google_pubsub_schema.example.name
  role = "roles/viewer"
  members = [
    "user:jane@example.com",
  ]
}

resource "google_pubsub_topic_iam_member" "member" {
  project = google_pubsub_schema.example.project
  schema = google_pubsub_schema.example.name
  role = "roles/viewer"
  member = "user:jane@example.com"
}
```

### References

* Same pattern as [google_pubsub_topic_iam_* resources](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic_iam)
* [Access control reference](https://cloud.google.com/pubsub/docs/access-control)

**Comment by melinath** [comment] 2023-10-23 16:56
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/14934

**Closed by melinath** 2023-10-23 16:56 UTC
Labels: enhancement, forward/review, service/pubsub
