### ISSUE TITLE
Changing subnet to Regional Managed Proxy forces replacement

### ISSUE THREAD

**Issue by jawnsy** [hashicorp/terraform-provider-google#12469] opened 2022-09-04 17:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.34.0
+ provider registry.terraform.io/hashicorp/google-beta v4.34.0
+ provider registry.terraform.io/hashicorp/random v3.4.2
```

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

I'm using the [Cloud Foundation Toolkit network module](https://github.com/terraform-google-modules/terraform-google-network) to manage my subnets, so it's not straightforward to copy/paste. Here's a redacted form of the `terraform show` output that should give an idea. The initial configuration should look similar to this:

```tf
# module.network.module.subnets.google_compute_subnetwork.subnetwork["us-central1/proxy-only-us-central1"]:
resource "google_compute_subnetwork" "subnetwork" {
    description                = "Proxy-only network for secondary region"
    name                       = "proxy-only-us-central1"
    private_ip_google_access   = false
    private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS"
    purpose                    = "INTERNAL_HTTPS_LOAD_BALANCER"
    region                     = "us-central1"
    role                       = "ACTIVE"
    secondary_ip_range         = []
    stack_type                 = "IPV4_ONLY"
}
```

And the "after" form should look like this (note the change from INTERNAL_HTTPS_LOAD_BALANCER to REGIONAL_MANAGED_PROXY:

```tf
# module.network.module.subnets.google_compute_subnetwork.subnetwork["us-central1/proxy-only-us-central1"]:
resource "google_compute_subnetwork" "subnetwork" {
    description                = "Proxy-only network for secondary region"
    name                       = "proxy-only-us-central1"
    private_ip_google_access   = false
    private_ipv6_google_access = "DISABLE_GOOGLE_ACCESS"
    purpose                    = "REGIONAL_MANAGED_PROXY"
    region                     = "us-central1"
    role                       = "ACTIVE"
    secondary_ip_range         = []
    stack_type                 = "IPV4_ONLY"
}
```

After updating it manually using `gcloud`, Terraform does pick up the change:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # module.network.module.subnets.google_compute_subnetwork.subnetwork["us-central1/proxy-only-us-central1"] has changed
  ~ resource "google_compute_subnetwork" "subnetwork" {
        name                       = "proxy-only-us-central1"
      ~ purpose                    = "INTERNAL_HTTPS_LOAD_BALANCER" -> "REGIONAL_MANAGED_PROXY"
        # (13 unchanged attributes hidden)
    }
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

I expected that the gcloud functionality and Terraform functionality would match -- thus I expected the Terraform provider to perform an in-place update rather than requiring a replacement.

### Steps to Reproduce

1. Define a proxy-only subnet with the legacy INTERNAL_HTTPS_LOAD_BALANCER type in Terraform code
2. Run `terraform apply`
3. Change the type to REGIONAL_MANAGED_PROXY, since the documentation states that this is the new/preferred subnet type: https://cloud.google.com/load-balancing/docs/proxy-only-subnets#migrate-purpose
4. Run `terraform apply` again

I would expect Terraform to offer an in-place update, because `gcloud` can do it trivially:

```
$ gcloud compute networks subnets update proxy-only-us-central1 --region us-central1 --purpose REGIONAL_MANAGED_PROXY
Updated [https://www.googleapis.com/compute/v1/projects/prefect-vault/regions/us-central1/subnetworks/proxy-only-us-central1].
```

After doing this, Terraform detects the change and offers to update the statefile

### Important Factoids

This may be intended behavior of the provider, since it looks like we need different proxy-only subnets for the legacy internal HTTPS load balancers that GKE creates by default and the new Envoy-based load balancers:

>A forwarding rule, which has the internal IP address of your load balancer, to forward each incoming request to the target proxy.
>
>The internal IP address associated with the forwarding rule can come from any subnet in the same network and region. Note the following conditions:
>
> * The IP address can (but does not need to) come from the same subnet as the backend instance groups.
> * The IP address must not come from a reserved proxy-only subnet that has its --purpose flag set to REGIONAL_MANAGED_PROXY.
> * If you want to share the internal IP address with multiple forwarding rules, set the IP address's --purpose flag to SHARED_LOADBALANCER_VIP.

The docs are a little bit confusing now given the two flavors of load balancer currently offered

https://cloud.google.com/load-balancing/docs/l7-internal/setting-up-l7-internal

### References

Not that I could find

**Comment by edwardmedia** [comment] 2022-09-06 23:11
@jawnsy this is the intended behavior. Below is where the provider code is. Do you see anywhere you can update the field without recreating the resource?

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_compute_subnetwork.go#L199

**Comment by jawnsy** [comment] 2022-09-07 02:01
@edwardmedia Thanks for the reply! Do you know why `gcloud` seems to allow an in-place update? Are there issues with doing that?

I didn't explain very well in the issue, but if you create a subnet using the legacy purpose field (`INTERNAL_HTTPS_LOAD_BALANCER`) and then update it to `REGIONAL_MANAGED_PROXY` using the Google Cloud SDK (gcloud), it seems able to make the change. If it were to require a replacement, then I'd have expected to need to delete the load balancer and re-create it in the new type (i.e. I'd expect the purpose to be an immutable field, then)

I'm not too sure how things work internally on the Google Cloud side, so it's possible that the safer way to make this change in a production system would be to create a new subnet in backup mode, promote it to active, and then use this module to destroy and re-create the backup subnet, then promote the backup back to active. If so, the behavior of the provider makes sense as it is, but the behavior/divergence from gcloud does not seem to be documented anywhere that I could find

**Comment by edwardmedia** [comment] 2022-09-11 15:35
@jawnsy Can you share the whole gcloud command for updating the `purpose`?

**Comment by jawnsy** [comment] 2022-09-11 15:38
@edwardmedia Sure.

```
gcloud compute networks subnets update proxy-only-us-central1 --region us-central1 --purpose REGIONAL_MANAGED_PROXY
```

**Comment by edwardmedia** [comment] 2022-09-25 14:28
@jawnsy are you able to change `purpose` back without recreating the resource? I think Patching is limited to certain condition. Please let me know what you see.

```
gcloud compute networks subnets update proxy-only-us-central1 --region us-central1 --purpose INTERNAL_HTTPS_LOAD_BALANCER
```

**Comment by edwardmedia** [comment] 2022-10-04 23:01
@jawnsy is this still an issue?

**Comment by edwardmedia** [comment] 2022-10-06 22:25
@jawnsy I believe this is not an issue. Closing this now

```
Patching purpose is supported only for subnets with purpose INTERNAL_HTTPS_LOAD_BALANCER.
```

**Closed by edwardmedia** 2022-10-06 22:25 UTC
Labels: bug, waiting-response

**Comment by jawnsy** [comment] 2022-10-08 20:08
Thanks Edward. I understand that the validation logic is not stateful, so there's no straightforward way for you to resolve this in code (i.e. there's no way to indicate that a one-way transition from INTERNAL_HTTPS_LOAD_BALANCER to REGIONAL_MANAGED_PROXY is allowed, but REGIONAL_MANAGED_PROXY to INTERNAL_HTTPS_LOAD_BALANCER requires replacement).

I think that the workaround for people encountering this behavior is for users to do a one-time upgrade to change the purpose manually, which is fine as this should be very rare.

Thanks for taking a look!
