### ISSUE TITLE
cloud router import fails for bgp.0.asn == 0

### ISSUE THREAD

**Issue by samveen** [hashicorp/terraform-provider-google#15191] opened 2023-07-15 17:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.3
on linux_arm64
+ provider registry.terraform.io/hashicorp/google v4.73.1
```

### Affected Resource(s)

* google_compute_router

### Terraform Configuration Files

```tf
resource "google_compute_router" "myvpc-router" {
  bgp {
    advertise_mode = "CUSTOM"
    advertised_ip_ranges {
      range = "10.161.0.0/16"
    }
    asn                = "0"
    keepalive_interval = "20"
  }

  encrypted_interconnect_router = "false"
  name                          = "myvpc-router"
  network                       = data.terraform_remote_state.common.outputs.network_myvpc_link
  project                       = var.project
  region                        = var.region
}
```

### Output

```
╷
│ Error: expected "bgp.0.asn" to be a RFC6996-compliant Local ASN:
│ must be either in the private ASN ranges: [64512..65534], [4200000000..4294967294];
│ or be the value of [16550], got 0
│ 
│   with module.routers.google_compute_router.myvpc-router,
│   on google/routers/compute_router.tf line 9, in resource "google_compute_router" "myvpc-router":
│    9:     asn                = "0"
│ 
╵
```

### Expected Behavior

- `tf plan` should accept the router definition in the tf code, because the router exists, exactly as described by the TF code:

   ```
   samveen@zero2w:~ $ gcloud compute routers describe myvpc-router
   bgp:
     advertiseMode: CUSTOM
     advertisedIpRanges:
     - description: ''
       range: 10.161.0.0/16
     asn: 0
     keepaliveInterval: 20
   creationTimestamp: '2022-01-20T06:18:09.403-08:00'
   description: ''
   encryptedInterconnectRouter: false
   id: '2137032174711656910'
   kind: compute#router
   name:myvpc-router
   nats:
   - enableEndpointIndependentMapping: false
     endpointTypes:
     - ENDPOINT_TYPE_VM
     icmpIdleTimeoutSec: 30
     logConfig:
       enable: false
       filter: ALL
     minPortsPerVm: 64
     name: myvpc
     natIpAllocateOption: MANUAL_ONLY
     natIps:
     - https://www.googleapis.com/compute/v1/projects/gr-eat-69/regions/asia-south1/addresses/myvpc-nat-1
     sourceSubnetworkIpRangesToNat: LIST_OF_SUBNETWORKS
     subnetworks:
     - name: https://www.googleapis.com/compute/v1/projects/gr-eat-69/regions/asia-south1/subnetworks/myvpc-priv-1
       sourceIpRangesToNat:
       - PRIMARY_IP_RANGE
     tcpEstablishedIdleTimeoutSec: 1200
     tcpTransitoryIdleTimeoutSec: 30
     udpIdleTimeoutSec: 30
   network: https://www.googleapis.com/compute/v1/projects/gr-eat-69/global/networks/myvpc
   region: https://www.googleapis.com/compute/v1/projects/gr-eat-69/regions/asia-south1
   selfLink: https://www.googleapis.com/compute/v1/projects/gr-eat-69/regions/asia-south1/routers/myvpc-router
   ```

### Actual Behavior
Terraform throws an error.

### Steps to Reproduce

1. Router as described in terraform
2. `terraform plan` to check against actual definition before `terraform import`

### Important Factoids
- I am using my google account for the actions instead of a service account.

### References

* #5381 
* #5524  - PR that introduced this issue.

**Comment by edwardmedia** [comment] 2023-07-15 19:57
@samveen it looks like there is a specific [rule](https://github.com/hashicorp/terraform-provider-google-beta/blob/6d409c57d93a64b3d19cbef2d9c1003ba5fc1998/google-beta/verify/validation.go#L95) that is applied on asn field. How did you create that router? If it is by gcloud, can you share the full command statement?

**Comment by samveen** [comment] 2023-07-16 02:36
@edwardmedia 
- The router was created before I joined the organization/project (or even started working on GCP cloud). 
- The YAML description of the router as given above.
- As per my understanding/knowledge, this router was created via the web interface.

**Comment by edwardmedia** [comment] 2023-07-17 13:25
@samveen I don't understand how asn = 0 was got in for the router as it seems invalid. Are you able to update it to 16550 via the web interface? 

I don't think we could make code change such as removing the validation to support your case. I think the validation is valid. You may need to work around it. Can you recreate the router?

**Comment by samveen** [comment] 2023-07-19 03:07
@edwardmedia I will check on it with my team. In the meantime, I can confirm that this is valid, as things work as expected. However, I concede that internally a zero  value is probably getting corrected to 16550 when being utilized or applied, inside the GCP black box.

Lastly, before you write this off as invalid, would you see if you can create an analogue in your test environment to check if a blank value is accepted by the ASN field or not. (I'm equating 0 to a blank value as can be seen in the screenshot attached above)

**Comment by edwardmedia** [comment] 2023-07-19 15:27
@samveen Can you clarify ` internally a zero value is probably getting corrected to 16550 when being utilized or applied`?

Below is from the[ api doc](https://cloud.google.com/compute/docs/reference/rest/v1/routers) about `bgp.asn`.  Its value must be an [RFC6996](https://www.ietf.org/rfc/rfc6996.txt) private ASN. In the provider, it is set as required.  I think you may need fix it on your side

integer ([uint32](https://developers.google.com/discovery/v1/type-format) format)

Local BGP Autonomous System Number (ASN). Must be an [RFC6996](https://www.ietf.org/rfc/rfc6996.txt) private ASN, either 16-bit or 32-bit. The value will be fixed for this router resource. All VPN tunnels that link to this router will have the same local ASN.

**Comment by edwardmedia** [comment] 2023-07-20 17:45
@samveen I think the resource behaves by design. Close this issue now. Feel free to reopen if you see it differently.

**Closed by edwardmedia** 2023-07-20 17:45 UTC
Labels: bug, waiting-response

**Comment by samveen** [comment] 2023-07-24 04:27
> @samveen Can you clarify ` internally a zero value is probably getting corrected to 16550 when being utilized or applied`?

As I understand it, the GCP web console allowed this field to be blank. As ASN as "numbers", on an implementation level, a blank should correspond to either a zero value or a NULL value. My observation is that the routing works even with a blank value (or zero value), which implies that there is some form of logic in the GCP system somewhere such that a zero/NULL value in the ASN field is corrected to the Google ASN.

> Below is from the[ api doc](https://cloud.google.com/compute/docs/reference/rest/v1/routers) about `bgp.asn`. Its value must be an [RFC6996](https://www.ietf.org/rfc/rfc6996.txt) private ASN. In the provider, it is set as required. I think you may need to fix it on your side to match the requirement. Another word, I don't think the provider will make a move to support your case.
> 
> ```
> Local BGP Autonomous System Number (ASN). Must be an [RFC6996](https://www.ietf.org/rfc/rfc6996.txt) private ASN, either 16-bit or 32-bit. The value will be fixed for this router resource. All VPN tunnels that link to this router will have the same local ASN.
> ```

Yes. I am starting to think that this field was left blank erroneously when the infra was created, despite it working (thanks to GCP's robust defaults). I'm working to get this fixed on our end.
