### ISSUE TITLE
google_compute_network_endpoint_group missing cloud_functions / cloud_run support

### ISSUE THREAD

**Issue by EduardJoy** [hashicorp/terraform-provider-google#17587] opened 2024-03-14 18:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Currently only google_compute_region_network_endpoint_group supports the arguments
`cloud_function` and `cloud_run` in order to setup a serverless backend. However official documentation presents that global load balancers can be used for server less loads.

https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless#gcloud_1

### New or Affected Resource(s)

google_compute_network_endpoint_group

### References

[Google Documentation](https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless#gcloud_1)
[google_compute_network_endpoint_group](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_endpoint_group) 
[google_compute_region_network_endpoint_group](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#nested_cloud_run)

b/330175181

**Comment by Cheriit** [comment] 2024-03-20 09:03
Hi @EduardJoy!

The serverless NEGs are supported only within regional scope, that's why we only have those fields in the `google_compute_region_network_endpoint_group`. In the documentation that You've linked, the NEG that is used is also a regional NEG and you should be using the global load balancers with them.

Does that resolves your issue?

**Comment by roaks3** [comment] 2024-03-28 20:49
Closing this as Working as Intended, but please add a comment if there is still an issue

**Closed by roaks3** 2024-03-28 20:49 UTC
Labels: enhancement, size/s, forward/linked, service/compute-networking-neg
