### ISSUE TITLE
Magic modules generates conditions in all IAM resources

### ISSUE THREAD

**Issue by trodge** [hashicorp/terraform-provider-google#14284] opened 2023-04-11 23:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.2

### Affected Resource(s)

`google_*_iam_binding`
`google_*_iam_member`

Only [these resources](https://cloud.google.com/iam/docs/conditions-overview#resources) should have a `condition` field in their iam binding and member resources, but currently all binding and member resources have this field.

**Comment by rialg** [comment] 2023-04-13 06:06
+1, I think that I am facing the same issue. Currently, the provider is using version `4.35.0` and every `terraform plan` run has produced an output similar to what is shown below for every role biding (`google_project_iam_binding` resource):
```
   + condition { # forces replacement
          + description = (known after apply)
          + expression  = (known after apply)
          + title       = (known after apply)
        }
```

Furthemore, all the principals are being removed.

**Comment by rileykarson** [comment] 2023-05-08 17:20
Marking size/L due to needing to verify which ones are correct / which aren't

**Comment by rileykarson** [comment] 2023-05-16 17:45
Talking about this in fixit kickoff- we're not sure how to verify which resources support conditions. We don't especially trust central lists of these things (they're often out of date) but individual resource pages are also often wrong.

**Comment by melinath** [comment] 2024-06-17 21:17
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/18412

**Closed by melinath** 2024-06-17 21:17 UTC
Labels: size/l, technical-debt
