### ISSUE TITLE
google_vpc_access_connector getting re-created without changes in configuration due to unspecified `network` field

### ISSUE THREAD

**Issue by zinizhu** [hashicorp/terraform-provider-google#11352] opened 2022-03-25 01:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/google v3.74.0
+ provider registry.terraform.io/hashicorp/google-beta v3.74.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

google_vpc_access_connector

### Terraform Configuration Files

```tf
resource "google_vpc_access_connector" "connector" {
  provider = google-beta
  project = "test-project"
  name    = "test_vpc_connector"

  subnet {
    name = "projects/test-project/regions/us-central1/subnetworks/test-subnet"
  }
  region       = "us-central1"
  machine_type = "e2-standard-4"
}
```

### Expected Behavior

After the connector is successfully created, when running `terraform plan` without any configuration change, the output should be `No changes. Infrastructure is up-to-date.`

### Actual Behavior

```
  # module.app_infra.google_vpc_access_connector.connector must be replaced
-/+ resource "google_vpc_access_connector" "connector" {
        name           = "test_vpc_connector"

      - network        = "ai-net" -> null # forces replacement
      .......
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. Create a VPC serverless connector

2. Without any change in the TF configuration, run `terraform plan` again

### References

Noticed a similar issue [here](https://github.com/hashicorp/terraform-provider-google/issues/9228)

**Comment by slevenick** [comment] 2022-03-25 15:14
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11304

**Closed by slevenick** 2022-03-25 15:14 UTC
Labels: bug
