### ISSUE TITLE
On DLP job trigger, rows_limit and rows_limit_percent not able to set to scan all BigQuery

### ISSUE THREAD

**Issue by Samir-Cit** [hashicorp/terraform-provider-google#13451] opened 2023-01-11 13:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.90.1
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_data_loss_prevention_job_trigger

### Terraform Configuration Files

```tf
resource "google_data_loss_prevention_job_trigger" "basic" {
    parent = "projects/${var.project_id}"
    description = "Description"
    display_name = "Displayname"

    triggers {
        schedule {
            recurrence_period_duration = "86400s"
        }
    }

    inspect_job {
        inspect_template_name = google_data_loss_prevention_inspect_template.basic.id
        actions {
            save_findings {
                output_config {
                    table {
                        project_id = var.project_id
                        dataset_id = "auto_dlp_output"
                    }
                }
            }
        }

        storage_config {
          big_query_options {
            table_reference {
              project_id = var.project_id
              dataset_id = google_bigquery_dataset.default.dataset_id
              table_id   = local.table_id
            }

            rows_limit = 0
            rows_limit_percent = 100
            sample_method = "TOP"
          }
        }
    }
}
```

### Debug Output

```
Error: Error creating JobTrigger: googleapi: Error 400: `rows_limit` or `rows_limit_percent` must be greater than zero when sample method is specified.
│ 
│   with google_data_loss_prevention_job_trigger.basic,
│   on automatic_dpl.tf line 7, in resource "google_data_loss_prevention_job_trigger" "basic":
│    7: resource "google_data_loss_prevention_job_trigger" "basic" {
```

### Expected Behavior

Should create a DLP job trigger to run through the whole BigQuery.

### Actual Behavior

It's only possible to scan 99% of the BigQuery. **_rows_limit = 0_** doesn't work and also **_rows_limit_percent = 0_** OR **_rows_limit_percent = 100_** doesn't work.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment] 2023-01-31 23:21
@Samir-Cit this is an API rule. Can you review its [doc](https://cloud.google.com/dlp/docs/reference/rest/v2/InspectJobConfig#BigQueryOptions) to see if if that makes sense?

**Comment by Samir-Cit** [comment] 2023-02-02 19:04
@edwardmedia the real problem is that I want to scan 100% of the table.
But using any of the options bellows is throwing that error showed on **Debug Output**:
- _rows_limit = 0_
- _rows_limit_percent = 0_
- _rows_limit_percent = 100_

The only possible way I found to work is using **_rows_limit_percent = 99_**, but this limits the scan to 99% of the table.

**Comment by Wallace99** [comment] 2023-02-03 02:47
Ah yes I think this is a bug. You should be able to at least omit `rows_limit` or `rows_limit_percent` to scan the entire table. I think the issue is because `sample_method` is defaulting to `TOP` when it should default to `SAMPLE_METHOD_UNSPECIFIED` perhaps? It's giving the same error you posted @Samir-Cit even when I remove `sample_method`. The API docs aren't particularly clear, but I'm guessing if the default value of `TOP` is removed from `sample_method`, you'll be able to omit `rows_limit` or `rows_limit_percent` entirely or set them to 0 or 100 if desired.

https://github.com/GoogleCloudPlatform/magic-modules/blob/1d912e7cae5e1da6951db6385fde88f7392bd90a/mmv1/products/dlp/api.yaml#L303-L311

I'm try make a PR for this over the weekend if nobody gets to it sooner

**Comment by Wallace99** [comment] 2023-02-03 02:55
A workaround until then could be to use a version of the Terraform provider earlier than 4.44.0. I added `row_limit`, `row_limit_percent`, and `sample_method` in that release so prior to that you could only scan the entire table. 

https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.44.0

**Comment by shuyama1** [comment] 2023-04-10 23:35
@Samir-Cit Could you try specifying `sample_method = ""`? This should allow you to explicitly set one of the followings:
- `rows_limit = 0`
- `rows_limit_percent = 0`
- `rows_limit_percent = 100`

**Comment by edwardmedia** [comment] 2023-04-30 15:18
@Samir-Cit Is this still an issue? As @shuyama1 suggested, have you tried below setting? It works for me. 

```          
            rows_limit = 0
            rows_limit_percent = 100
            sample_method = ""
```

**Comment by edwardmedia** [comment] 2023-07-30 22:24
@Samir-Cit closing this assume it is no longer an issue

**Closed by edwardmedia** 2023-07-30 22:24 UTC
Labels: bug, waiting-response
