### ISSUE TITLE
`google_service_account_key` - Key not usable immediately after Terraform creation

### ISSUE THREAD

**Issue by ari-becker** [hashicorp/terraform-provider-google#12915] opened 2022-10-30 09:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
N/A

### Affected Resource(s)

* `google_service_account_key`

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Either:
* The key created by `google_service_account_key` is usable immediately after creation finishes.
* A configuration field is added to the `google_service_account_key` resource to either (a) wait until the key is reliably usable or to (b) create the key and return immediately, without waiting for confirmation that the key is usable.

### Actual Behavior

In [`resourceGoogleServiceAccountKeyCreate`](https://github.com/hashicorp/terraform-provider-google/blob/3458a7ff3f69bd3a5402c844b40e5b80e0c54c83/google/resource_google_service_account_key.go#L96), the resource only calls [`config.NewIamClient(userAgent).Projects.ServiceAccounts.Keys.Create`](https://github.com/hashicorp/terraform-provider-google/blob/3458a7ff3f69bd3a5402c844b40e5b80e0c54c83/google/resource_google_service_account_key.go#L123) and then [waits for the public key to be available](https://github.com/hashicorp/terraform-provider-google/blob/3458a7ff3f69bd3a5402c844b40e5b80e0c54c83/google/resource_google_service_account_key.go#L141).

As per the note in https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating :

> Note: After you create a key, you might need to wait for 60 seconds or more before you perform another operation with the key. If you try to perform an operation with the key immediately after you create the key, and you receive an error, you can [retry the request with exponential backoff](https://cloud.google.com/iam/docs/retry-strategy).

Because the Terraform resource does not check to see if the service account key is actually usable, downstream clients (e.g. the [DataDog GCP integration Terraform resource](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_gcp)) are required to poll until GCP's eventual consistency resolves.

The current situation is:
* Poor developer experience (DX). When I create a Terraform resource, I expect that resource to be ready and usable. If it is not, this can break downstream Terraform resources that *do* expect upstream resources, already created, to be usable.
* Inefficient. If every downstream resource is required to poll until the service account key is usable, then this polling represents additional load on GCP infrastructure, false-positive "forbiddens" in audit logging, etc.

### Steps to Reproduce

See above links in `Actual Behavior`.

### Important Factoids

Workaround: use https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep to implement a 60+ second sleep before attempting to use the key.

### References

N/A

**Comment by edwardmedia** [comment] 2022-10-31 15:03
@ari-becker you are right and I understand what you listed in the situation. I took a look at the code below, and the resource has already implemented the polling logic which waits until the api returns `done`. It is now up to the api whether the key really is available to use, and the provider has no control over that. There are several resources (like several services to be enabled) that share the same experience. Sorry about that, but I think there is not much we can do at the provider level. Do you have any suggestions for improving this?

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_google_service_account_key.go#L141

**Comment by ari-becker** [comment] 2022-11-01 11:51
@edwardmedia I appreciate that this provider can't fix the shortcomings in the upstream GCP API. Couldn't the provider attempt to authenticate to GCP (i.e. getting an identity token) using the provided key, and repeat such attempts until success or timeout? Essentially, moving the polling from downstream providers (each of which rediscover this need) into the GCP provider. After successfully authenticating, the token can be discarded, having never been written to disk.

**Comment by edwardmedia** [comment] 2022-11-02 16:40
@ari-becker Thanks for the suggestions, but I think that seems to be off the pattern. Each individual resource cloud behavior differently. The provider offers a layer to call each API. To make all things together, you might need to use other available tools. `Sleep` is the one, and it is common to be used for such cases. You may want to file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) for your suggestion so it can be triaged. But for this, I think it is by design, and I am closing this right now. Thank you again for your suggestions

**Closed by edwardmedia** 2022-11-02 16:40 UTC
Labels: bug
