### ISSUE TITLE
google_firebase_web_app import requires ID instead of (display) name

### ISSUE THREAD

**Issue by jasperroel** [hashicorp/terraform-provider-google#7204] opened 2020-09-07 13:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.29
+ provider.google v3.36.0
+ provider.google-beta v3.36.0
```

### Affected Resource(s)

* google_firebase_web_app

### Terraform Configuration Files

```tf
resource "google_firebase_web_app" "default" {
  provider     = google-beta
  display_name = "my-app"

  depends_on = [google_firebase_project.default]
}
```

### Debug Output

Not working: https://gist.github.com/jasperroel/0542929436f9dc92467185a320770b0c
Working: https://gist.github.com/jasperroel/a0f139c0dcb19a068a804b71d9ee68ec

### Expected Behavior

I expected that I could import a `google_firebase_web_app` via its (display) name (`my-app` in this example).

### Actual Behavior

I needed to lookup the App ID and import via the full app URI.

### Steps to Reproduce

This fails:
1. `terraform import google_firebase_web_app.default my-app`

This is the command used that will actually import the Firebase app:
1. `terraform import google_firebase_web_app.default projects/PROJECT_NAME/webApps/1:1234567890:web:123abcsomehash`

### Important Factoids

The documentation states that a `{{name}}` should be used (https://www.terraform.io/docs/providers/google/r/firebase_web_app.html#import). I assumed (by not reading correctly) that this meant the App Display Name of the Firebase Hosting App, but what is actually meant is the full project path, including the App ID.

Can the import for this module be extended with importing via the App Display Name (which is actually unique within the project, since it also part of the public subdomain for that project).

Since the (display) name is something that is generally well-known and easily discoverable, whereas the App ID is something you can generally only find via APIs (such as the Firebase CLI: `firebase --project PROJECT_NAME apps:list`).

**Comment by edwardmedia** [comment] 2020-09-07 13:47
@jasperroel I think you have found below definition in the doc. The behavior you was seeing is by design. I am closing this issue then. Regarding the request of support using `display name`, I would suggest to file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?template=enhancement.md) instead and it will be triaged. 
```
name - The fully qualified resource name of the App, for example: projects/projectId/webApps/appId
```

**Closed by edwardmedia** 2020-09-07 13:47 UTC
Labels: bug
