### ISSUE TITLE
google-beta 3.68.0 provider is not found

### ISSUE THREAD

**Issue by jwtracy** [hashicorp/terraform-provider-google#9177] opened 2021-05-18 22:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

cli version: 0.13.4

providers:
- Installing hashicorp/google v3.68.0...
- Installed hashicorp/google v3.68.0 (self-signed, key ID 34365D9472D7468F)

### Affected Resource(s)

google-beta provider

### Terraform Configuration Files

```tf
# Namely, there's no upper bound on required_providers here.

terraform {  
  backend "gcs" {    
     ...
  }
}
provider "google" {  version = "~>3.0"}
provider "google-beta" {  version = "~>3.0"}
```

### Debug Output

https://gist.github.com/jwtracy/6ea9e3908f9b05ba3be37fe92bd3603e

### Expected Behavior

Successful install of the latest provider version, https://registry.terraform.io/providers/hashicorp/google-beta/latest.

### Actual Behavior

Failed to find the latest google-beta provider 3.68.0

### Steps to Reproduce

1. Use provider and terraform blocks as specified above.
2. `terraform init`

### Important Factoids

The latest release of the repository itself is still referencing 3.67.0 while the terraform provider in the registry is 3.68.0. It seems that the "google" provider is in the same situation but perhaps the execution did not reach that point. My organization has seen this issue in several instances, all using the same provider and terraform blocks.

### References

* https://registry.terraform.io/providers/hashicorp/google-beta/latest
* https://github.com/hashicorp/terraform-provider-google-beta/releases

**Comment by rujieyin** [comment] 2021-05-18 22:09
+1 getting the same error on failure to load `google-beta` provider with `provider "google-beta" {  version = "~>3.0"}`.

**Comment by rileykarson** [comment] 2021-05-18 22:44
Updating the respository involves some minor manual processes, that's done now. The release was cut from a branch, `release-3.68.0`.

That shouldn't cause this issue, though which I can't reproduce:

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/google-beta versions matching "~> 3.0"...
- Finding hashicorp/google versions matching "~> 3.0"...
- Installing hashicorp/google v3.68.0...
- Installed hashicorp/google v3.68.0 (unauthenticated)
- Installing hashicorp/google-beta v3.68.0...
- Installed hashicorp/google-beta v3.68.0 (unauthenticated)

Terraform has been successfully initialized!
```

I'm on `darwin_amd64`, although there's no good reason for that to matter. @megan07 is this something you've seen before?

**Comment by megan07** [comment] 2021-05-19 18:38
@jwtracy I'm sorry you're running into this. I was also unable to reproduce it. Are you able to set `TF_LOG=DEBUG` and send the output along.  Thanks!

**Comment by definitelynotskylarc** [comment] 2021-05-19 20:13
We're encountering the same issue, debug logs below:

```
2021/05/19 20:11:51 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/google/3.68.0/download/linux/amd64
- Installed hashicorp/tls v3.1.0 (self-signed, key ID 34365D9472D7468F)
2021/05/19 20:11:51 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-google/3.68.0/terraform-provider-google_3.68.0_SHA256SUMS
2021/05/19 20:11:51 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-google/3.68.0/terraform-provider-google_3.68.0_SHA256SUMS.72D7468F.sig
- Installing hashicorp/google v3.68.0...
2021/05/19 20:11:51 [DEBUG] Provider signed by 34365D9472D7468F HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
- Installed hashicorp/google v3.68.0 (self-signed, key ID 34365D9472D7468F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/google-beta v3.68.0: provider
registry.terraform.io/hashicorp/google-beta 3.68.0 is not available for
linux_amd64

make: *** [Makefile:36: init] Error 1
```

**Comment by rileykarson** [comment] 2021-05-19 20:20
I double checked on my linux machine, since these have said `linux_amd64` but I checked on `darwin_amd64` originally. It still succeeded, logs below in case a success is helpful!

```
provider "google" {
  version = "~> 3.68.0"
}
```

```
$ terraform -v
Terraform v0.14.9

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html
```

```
$ TF_LOG=DEBUG terraform init
2021/05/19 13:18:20 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/05/19 13:18:20 [INFO] Terraform version: 0.14.9
2021/05/19 13:18:20 [INFO] Go runtime version: go1.15.6
2021/05/19 13:18:20 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2021/05/19 13:18:20 [DEBUG] Attempting to open CLI config file: /usr/local/google/home/rileykarson/.terraformrc
2021/05/19 13:18:20 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/05/19 13:18:20 [DEBUG] checking for credentials in "/usr/local/google/home/rileykarson/.terraform.d/plugins"
2021/05/19 13:18:20 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/05/19 13:18:20 [DEBUG] will search for provider plugins in /usr/local/google/home/rileykarson/.terraform.d/plugins
2021/05/19 13:18:20 [WARN] ignoring file "google.com/google/google-private/index.json" as possible package for google.com/google/google-private: filename lacks expected prefix "terraform-provider-google-private_"
2021/05/19 13:18:20 [WARN] ignoring file "registry.terraform.io/hashicorp/google-beta/3.65.0.json" as possible package for registry.terraform.io/hashicorp/google-beta: filename lacks expected prefix "terraform-provider-google-beta_"
2021/05/19 13:18:20 [WARN] ignoring file "registry.terraform.io/hashicorp/google-beta/index.json" as possible package for registry.terraform.io/hashicorp/google-beta: filename lacks expected prefix "terraform-provider-google-beta_"
2021/05/19 13:18:20 [DEBUG] ignoring non-existing provider search directory /usr/local/google/home/rileykarson/.local/share/terraform/plugins
2021/05/19 13:18:20 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021/05/19 13:18:20 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021/05/19 13:18:20 [INFO] CLI command args: []string{"init"}
2021/05/19 13:18:20 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...
2021/05/19 13:18:20 [DEBUG] New state was assigned lineage "5e3eea90-bf08-c13a-d497-26a60b02ffa8"
2021/05/19 13:18:20 [DEBUG] checking for provisioner in "."
2021/05/19 13:18:20 [DEBUG] checking for provisioner in "/usr/local/bin"
2021/05/19 13:18:20 [DEBUG] checking for provisioner in "/usr/local/google/home/rileykarson/.terraform.d/plugins"
2021/05/19 13:18:20 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory

Initializing provider plugins...
2021/05/19 13:18:20 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
- Finding hashicorp/google versions matching "~> 3.68.0"...
2021/05/19 13:18:21 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/05/19 13:18:21 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/google/versions
2021/05/19 13:18:21 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/05/19 13:18:21 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/google/3.68.0/download/linux/amd64
2021/05/19 13:18:21 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-google/3.68.0/terraform-provider-google_3.68.0_SHA256SUMS
2021/05/19 13:18:21 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-google/3.68.0/terraform-provider-google_3.68.0_SHA256SUMS.72D7468F.sig
- Installing hashicorp/google v3.68.0...
2021/05/19 13:18:21 [DEBUG] Provider signed by 34365D9472D7468F HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
- Installed hashicorp/google v3.68.0 (self-signed, key ID 34365D9472D7468F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.


Warning: Version constraints inside provider configuration blocks are deprecated

  on main.tf line 2, in provider "google":
   2:   version = "~> 3.68.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by rileykarson** [comment] 2021-05-19 20:27
Never mind, the `google` provider works but I tried `google-beta` and it fails for `3.66.0+`.

```
$ TF_LOG=DEBUG terraform init
2021/05/19 13:27:03 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/05/19 13:27:03 [INFO] Terraform version: 0.14.9
2021/05/19 13:27:03 [INFO] Go runtime version: go1.15.6
2021/05/19 13:27:03 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2021/05/19 13:27:03 [DEBUG] Attempting to open CLI config file: /usr/local/google/home/rileykarson/.terraformrc
2021/05/19 13:27:03 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/05/19 13:27:03 [DEBUG] checking for credentials in "/usr/local/google/home/rileykarson/.terraform.d/plugins"
2021/05/19 13:27:03 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/05/19 13:27:03 [DEBUG] will search for provider plugins in /usr/local/google/home/rileykarson/.terraform.d/plugins
2021/05/19 13:27:03 [WARN] ignoring file "google.com/google/google-private/index.json" as possible package for google.com/google/google-private: filename lacks expected prefix "terraform-provider-google-private_"
2021/05/19 13:27:03 [WARN] ignoring file "registry.terraform.io/hashicorp/google-beta/3.65.0.json" as possible package for registry.terraform.io/hashicorp/google-beta: filename lacks expected prefix "terraform-provider-google-beta_"
2021/05/19 13:27:03 [WARN] ignoring file "registry.terraform.io/hashicorp/google-beta/index.json" as possible package for registry.terraform.io/hashicorp/google-beta: filename lacks expected prefix "terraform-provider-google-beta_"
2021/05/19 13:27:03 [DEBUG] ignoring non-existing provider search directory /usr/local/google/home/rileykarson/.local/share/terraform/plugins
2021/05/19 13:27:03 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021/05/19 13:27:03 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021/05/19 13:27:03 [INFO] CLI command args: []string{"init"}
2021/05/19 13:27:03 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

2021/05/19 13:27:03 [DEBUG] New state was assigned lineage "0ba568e3-c231-84ff-73e1-925dcc5e3e64"
Initializing the backend...
2021/05/19 13:27:03 [DEBUG] checking for provisioner in "."
2021/05/19 13:27:03 [DEBUG] checking for provisioner in "/usr/local/bin"
2021/05/19 13:27:03 [DEBUG] checking for provisioner in "/usr/local/google/home/rileykarson/.terraform.d/plugins"
2021/05/19 13:27:03 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory

2021/05/19 13:27:03 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
Initializing provider plugins...
- Finding hashicorp/google versions matching "~> 3.68.0"...
2021/05/19 13:27:03 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/05/19 13:27:03 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/google/versions
2021/05/19 13:27:03 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
- Finding hashicorp/google-beta versions matching "~> 3.66.0"...
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/05/19 13:27:03 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/google/3.68.0/download/linux/amd64
2021/05/19 13:27:03 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-google/3.68.0/terraform-provider-google_3.68.0_SHA256SUMS
2021/05/19 13:27:03 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-google/3.68.0/terraform-provider-google_3.68.0_SHA256SUMS.72D7468F.sig
- Installing hashicorp/google v3.68.0...
2021/05/19 13:27:03 [DEBUG] Provider signed by 34365D9472D7468F HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
- Installed hashicorp/google v3.68.0 (self-signed, key ID 34365D9472D7468F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Warning: Version constraints inside provider configuration blocks are deprecated

  on main.tf line 2, in provider "google":
   2:   version = "~> 3.68.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

(and one more similar warning elsewhere)


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/google-beta: no available releases match the given constraints ~>
3.66.0
```

**Comment by andy-caruso** [comment] 2021-05-19 20:28
We're using terraform 0.13.4, not v0.14. If that matters.

**Comment by andy-caruso** [comment] 2021-05-19 23:43
We're able to work around this currently by adding this to our terraform files, 
```
 required_providers {
    google      = "<= 3.67.0"
    google-beta = "<= 3.67.0"
  }
```

It looks like the debugging [here](https://github.com/hashicorp/terraform-provider-aws/issues/19435) has yielded some additional details, I'm not enough of a terraform expert to know how to workaround this in terraform init.

**Comment by jwtracy** [comment] 2021-05-20 16:55
Could this be a Hashicorp registry issue rather than a google-beta provider issue?

Sorry for the confusion on providers. The google-beta repo doesn't have issues enabled so I figured this repo would be the next best place to escalate.

**Comment by megan07** [comment] 2021-05-21 13:43
Hi everyone! The registry team cleared the cache last night in attempt to resolve this issue. Would you please try again and let us know if the problem persists? Thank you all for your patience!

**Comment by definitelynotskylarc** [comment] 2021-05-21 14:36
Issue is resolved for me, thanks!

**Comment by jwtracy** [comment] 2021-05-21 16:21
Issue is also resolved for me! Thanks a bunch!

**Comment by megan07** [comment] 2021-05-21 17:11
Great! I'll close this issue. Thanks again for your patience!

**Closed by megan07** 2021-05-21 17:11 UTC
Labels: bug, upstream-terraform
