### ISSUE TITLE
Error when using email alias with Google account.

### ISSUE THREAD

**Issue by Frazer-4c** [hashicorp/terraform-provider-google#8136] opened 2021-01-07 16:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.13.5
terraform-provider-google_v3.51.0

### Affected Resource(s)

google_project_iam_member.member-iam

### Terraform Configuration Files

provider "google" {
}
   resource "google_project_iam_member" "member-iam" {
       member  = "user:test@test.com"
       project = "fcng-local"
       role    = "roles/viewer"
    }

### Debug Output

<script src="https://gist.github.com/Frazer-4c/54450375e9f5c11d639a0225a4aca4c9.js"></script>

### Expected Behavior

For the user to be created in IAM in the GCP

### Actual Behavior

it produces an error message:

Error: Provider produced inconsistent result after apply

When applying changes to google_project_iam_member.member-iam, provider
"registry.terraform.io/hashicorp/google" produced an unexpected new value:
Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am authenticating as a user who has owner rights to the project

When running the command with 1 email address it seems to display a different email address.

The user has 2 different emails accounts however it looks like they have been linked together maybe by an alias?

### References

* #0000

**Comment by edwardmedia** [comment] 2021-01-07 22:03
@Frazer-4c can you share the debug log?

**Comment by Frazer-4c** [comment] 2021-01-08 13:42
I had add a gist link but it was not showing.  I have amended that so it is now showing under the debug output section

**Comment by edwardmedia** [comment] 2021-01-08 13:54
@Frazer-4c was this the initial apply? If not, can you provide the steps to reach this, and was it successful? I don't understand what you meant below. Where is another email, alias?
>When running the command with 1 email address it seems to display a different email address.

>The user has 2 different emails accounts however it looks like they have been linked together maybe by an alias?

**Comment by Frazer-4c** [comment] 2021-01-08 16:22
no this was not the initial apply.  The user was added in via terraform
code before me and then manually removed via the google console.  I ran
some terraform code and did not realise it wanted to add back in this
user.  The code in the ticket is what was causing the issue.

the terraform code says to create IAM user called user1, however it would
fail with the terraform bug message.  However if ran it again it would
still fail but I notice a user account had been created but with username
of user2.

Speaking to the user he saids he owns user1 and user2 accounts, however he
is not sure what happened with the accounts he thinks there are linked
maybe with an alias.

**Comment by edwardmedia** [comment] 2021-01-08 20:48
@Frazer-4c terraform code does not have knowledge about email or account alias. It expects a full email in the member field. Unless providing a clear config code and steps to repro, I can't explain 
>However if ran it again it would still fail but I notice a user account had been created but with username of user2.
You may run `import` to sync the Terraform state before proceed "apply"

**Comment by edwardmedia** [comment] 2021-01-11 13:55
@Frazer-4c is this still an issue?

**Comment by edwardmedia** [comment] 2021-01-16 18:41
@Frazer-4c closing this assuming it is no longer an issue. Feel free to reopen it if the issue is not resolved.

**Closed by edwardmedia** 2021-01-16 18:41 UTC
Labels: bug, waiting-response
