### ISSUE TITLE
GKE Workload Identity: Migrate from IdentityNamespace to WorkloadPool

### ISSUE THREAD

**Issue by ahmedtd** [hashicorp/terraform-provider-google#8652] opened 2021-03-11 00:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The standard and beta providers for GKE Workload Identity uses the IdentityNamespace field on the google.golang.org/api/container/v1beta1.WorkloadIdentityConfig object [1,2].  In the transition to the v1 API, this field was renamed to WorkloadPool, and backported [3] to the v1alpha1 and v1beta1 APIs.

The IdentityNamespace field will eventually be cleaned up from the v1alpha1 and v1beta1 APIs, but there's no specific timeline for that to happen.

The new field has the exact same behavior, and I believe we fill out both on the return from ClusterCreate/ClusterUpdate.

[1] https://github.com/hashicorp/terraform-provider-google/blob/dcf0ffc0b627dad505e3d31e928032f53d7cf9fb/google/resource_container_cluster.go#L2790
[2] https://github.com/hashicorp/terraform-provider-google-beta/blob/55ecbe75b19687cc683d65f69a97ecb2865b493d/google-beta/resource_container_cluster.go#L3190
[3] https://pkg.go.dev/google.golang.org/api/container/v1beta1#WorkloadIdentityConfig

### New or Affected Resource(s)

* google_container_cluster.workload_identity_config

**Comment by upodroid** [comment] 2021-03-12 10:32
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/8129

**Comment by rileykarson** [comment] 2021-03-12 19:10
Yup, closing as dupe.

**Closed by rileykarson** 2021-03-12 19:10 UTC
Labels: enhancement
