### ISSUE TITLE
modifying a cluster to enable workload identity doesn't work correctly

### ISSUE THREAD

**Issue by tibers** [hashicorp/terraform-provider-google#8223] opened 2021-01-14 22:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

12

### Affected Resource(s)

* google_container_cluster

Specifically...
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#identity_namespace

### Terraform Configuration Files

Nothing special, copy and pasting the example will suffice.

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Adding:
```
workload_identity_config {
  identity_namespace = "${data.google_project.project.project_id}.svc.id.goog"
}
```
Should enable workload identity.

This works correctly on **new** clusters, but not **modifying an existing cluster**.

### Actual Behavior

It just fails silently.

### Steps to Reproduce

1. Create a GKE cluster with the TF module. 
1. Then add the workload identity line and the relevant GKE metadata stuff
1. Then try to add a service account which uses workload identity. Terraform will fail with...

```
Error: Error applying IAM policy for service account 'projects/mybeautifulproject/serviceAccounts/frontendsa@mybeautifulproject.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/mybeautifulproject/serviceAccounts/frontendsa@mybeautifulproject.iam.gserviceaccount.com': googleapi: Error 400: Identity Pool does not exist (mybeautifulproject.svc.id.goog). Please check that you specified a valid resource name as returned in the `name` attribute in the configuration API., badRequest
```

### Important Factoids

Running the command to enable workload identity in cloudshell (without terraform) will cause terraform to be able to continue.

**Comment by edwardmedia** [comment] 2021-01-14 23:37
@tibers instead of modules, can you repro the issue with a minimum google_container_cluster (single config)? If yes, please provide the detailed steps along with the config and the debug log.

**Comment by edwardmedia** [comment] 2021-01-16 18:47
@tibers is this still an issue?

**Comment by tibers** [comment] 2021-01-18 21:40
Yeah I didn't get time to do it this weekend but a coworker just got bit by it working on the same codebase. I forwarded him the link to the issue too so he can comment if he wants.

**Comment by edwardmedia** [comment] 2021-01-24 15:49
@tibers does your coworker have a chance to respond?

**Comment by gnarea** [comment] 2021-01-25 14:15
I'm running into the same issue whilst trying to update an existing cluster to enable workload identity.

My Terraform code is open source:

- https://github.com/relaycorp/cloud-gateway/blob/f76684fc1be5bd7d5e1816bd01048bb768c68f7b/environments/_modules/gateway/gateway.tf#L5-L18
- https://github.com/relaycorp/cloud-gateway/blob/6910e007d080db15663435320d51ed5063355dc7/environments/_modules/gateway/gke.tf#L41-L43
- https://github.com/relaycorp/cloud-gateway/blob/6910e007d080db15663435320d51ed5063355dc7/environments/_modules/gateway/gke.tf#L74-L76

Here's an example of the error I get:

```
Error: Error applying IAM policy for service account 'projects/relaycorp-cloud-gateway/serviceAccounts/gateway-frankfurt-app@relaycorp-cloud-gateway.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/relaycorp-cloud-gateway/serviceAccounts/gateway-frankfurt-app@relaycorp-cloud-gateway.iam.gserviceaccount.com': googleapi: Error 400: Identity Pool does not exist (relaycorp-cloud-gateway.svc.id.goog). Please check that you specified a valid resource name as returned in the `name` attribute in the configuration API., badRequest
```

However, if I inspect the GCP service account from the web console, I can see the binding appears to have been successfully set up:

![wi](https://user-images.githubusercontent.com/369863/105717250-cf325180-5f17-11eb-9925-e909c7adb9da.png)

Could this be a bug in the GCP API?

**Comment by gnarea** [comment] 2021-01-25 14:41
Sorry, please scratch my previous message: I had a few Terraform Cloud tabs open and got confused.

The service account binding did fail with the error above, but it succeeded in a subsequent attempt I made a couple of minutes later. I missed the second run, which presumably is the one that created the binding shown in the screenshot.

**Comment by edwardmedia** [comment] 2021-01-25 22:02
@gnarea how can I relate your case to the issue originally reported? Help me to understand if I have missed their relationship. If your case is different, do you mind if filing a different issue so it would be better tracked?  

>modifying a cluster to enable workload identity doesn't work correctly

**Comment by gnarea** [comment] 2021-01-25 22:16
@edwardmedia, the OP described exactly the issue I ran into: Adding workload identity to an existing, Terraform-managed GKE cluster led to the error we both quote above.

The difference seems to be that, in my case, the issue fixed itself after a couple of minutes. Presumably because that's how long it took for the workload identity pool to become available.

**Comment by edwardmedia** [comment] 2021-01-26 14:08
@gnarea @tibers I am glad `the issue is fixed`. Is there anything left that needs to be addressed?

> the issue fixed itself after a couple of minutes.

**Comment by edwardmedia** [comment] 2021-02-07 18:01
@gnarea @tibers Closing this issue then. Feel free to reopen if this is still an issue

**Closed by edwardmedia** 2021-02-07 18:01 UTC
Labels: bug, waiting-response
