### ISSUE TITLE
resource_bigquery_table schema evolution

### ISSUE THREAD

**Issue by dlesco** [hashicorp/terraform-provider-google#12588] opened 2022-09-19 16:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Affects head of main branch.

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Expected Behavior

The BigQuery API allows you to alter a table's schema, so that the data type is changed to a "Coercible Type":
https://cloud.google.com/bigquery/docs/managing-table-schemas#change_a_columns_data_type

In terraform with this provider, we tried to change an INT64 to a NUMERIC field.  According to the docs, this is a coercible type:
https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_rules

Does not work with the Terraform provider.

However, we successfully did this schema update outside of Terraform.

### Actual Behavior

Provider code does not allow you to change the type of an existing table field to a coercible type.

**Comment by edwardmedia** [comment] 2022-09-19 16:57
@dlesco can you provide a terraform config that shows what the problem is? Along with the debug log.

**Comment by edwardmedia** [comment] 2022-10-04 23:18
@dlesco this looks like a new feature. Please file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=01_enhancement.md) instead. Closing this now

**Closed by edwardmedia** 2022-10-04 23:18 UTC
Labels: bug, waiting-response
