### ISSUE TITLE
Creating a Vertex AI Endpoint with  a name other than a number will result in 400 error. 

### ISSUE THREAD

**Issue by enku-io** [hashicorp/terraform-provider-google#12963] opened 2022-11-07 21:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_vertex_ai_endpoint

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
resource "google_vertex_ai_endpoint" "endpoint" {
  name         = "endpoint-name"
  display_name = "sample-endpoint"
  description  = "A sample vertex endpoint"
  location     = "us-central1"
  labels       = {
    label-one = "value-one"
  }
  network      = "projects/${data.google_project.project.number}/global/networks/${data.google_compute_network.vertex_network.name}"
}
```

### Debug Output

```
│ Error: Error creating Endpoint: googleapi: Error 400: List of found errors:   1.Field: endpoint_id; Message: endpoint_id can only contain numbers and must not have leading zeros.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "endpoint_id can only contain numbers and must not have leading zeros.",
│         "field": "endpoint_id"
│       }
│     ]
│   }
│ ]
```
### Expected Behavior

The expected behavior is that the endpoint should have been created without a problem. 

### Actual Behavior

The endpoint fails to be created. 
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment] 2022-11-07 21:28
https://github.com/hashicorp/terraform-provider-google/issues/12944

**Comment by edwardmedia** [comment] 2022-11-08 00:19
@enku-io below is what the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_endpoint#name) specify. Looks like this is by design

[name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vertex_ai_endpoint#name) - (Required) The resource name of the Endpoint. The name must be numeric with no leading zeros and can be at most 10 digits.

**Comment by edwardmedia** [comment] 2022-11-14 20:12
@enku-io closing this as it appears to be by design. Feel free to reopen if you see it differently.

**Closed by edwardmedia** 2022-11-14 20:12 UTC
Labels: bug, waiting-response
