### ISSUE TITLE
Failing test(s): TestAccVmwareengineCluster_vmwareEngineClusterUpdate (Beta)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16751] opened 2023-12-08 16:53 UTC
### Failure rates

- 46% since 2023-11-01

### Impacted tests

- TestAccVmwareengineCluster_vmwareEngineClusterUpdate (Beta)

### Affected Resource(s)

* google_vmwareengine_cluster

### Nightly build test history

- [TestAccVmwareengineCluster_vmwareEngineClusterUpdate (Beta)
](https://hashicorp.teamcity.com/test/-1736928788925031626?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

This test failure is most recent:
```
        Error: Error creating Network: googleapi: Error 400: Legacy VMware Engine network creation is not allowed on this project. Use a Standard VMware Engine network instead.
```

Previously this test failure occurred: 

```
        Error: Error creating Network: googleapi: Error 400: Requesting to create a legacy VMware Engine network which is not allowed because a legacy network is already present in same region in the project.
```

b/315876364

**Comment by mendonza-gcp** [comment] 2023-12-14 21:10
This is working as intended, we have changed to the Standard network model in GCVE which is the only supported model for new projects.

**Comment by melinath** [comment] 2023-12-18 21:49
Information on Standard networks vs Legacy: https://cloud.google.com/vmware-engine/docs/networking/vmware-engine-network

We are already creating STANDARD networks in this test: https://github.com/hashicorp/terraform-provider-google-beta/blob/7f65a118111152cd758023aa498e528f7756cb91/google-beta/services/vmwareengine/resource_vmwareengine_cluster_test.go#L73

**Comment by melinath** [comment] 2023-12-18 22:23
It looks like this was probably resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9550

**Closed by melinath** 2023-12-18 22:23 UTC
Labels: test-failure, forward/linked, test-failure-0, service/vmwareengine
