### ISSUE TITLE
`google_cloudfunctions_function` resource creates topic if not exist but does not destroy it

### ISSUE THREAD

**Issue by jeremietharaud** [hashicorp/terraform-provider-google#12780] opened 2022-10-13 08:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`1.2.7`

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "bucket" {
  name          = "my-bucket"
  location      = "asia-northeast1"
}

resource "google_storage_bucket_object" "archive" {
  name   = "index.zip"
  bucket = google_storage_bucket.bucket.name
  source = "${path.module}/index.zip"
}
# The Cloud function
resource "google_cloudfunctions_function" "function" {
  name        = "my-function"
  runtime     = "python39"

  available_memory_mb   = "128"
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  entry_point           = "function_handler"

  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = "blablaeverythingisfine"
  }
}
```

### Expected Behavior

If the Pub/Sub topic does not exist, the `terraform apply` command should fail.
Note that using the console you have to choose an existing topic when you create a cloud function with a Pub/Sub trigger.

### Actual Behavior

The cloud function is created without error, the non-existing topic is also created and a subscription to the cloud function is also set.
But the topic is not deleted when the stack is destroyed.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by edwardmedia** [comment] 2022-10-13 16:00
@jeremietharaud how to repro the issue? Are you able to share the object of `index.zip`? Because the resources like topics are not managed in your config, the terraform has no knowledge of them. It is expected they are not destroyed via `terraform destroy` Does this make sense?

**Comment by jeremietharaud** [comment] 2022-10-13 16:11
@edwardmedia 
The content of index.zip file is not related to the issue (just zip a main.py with a handler endpoint). 

The problem is that although the topic does not exist at all (no Terraform resource, nothing in pubsub console) Terraform creates it automatically.
The fact is that Terraform should not create unmanaged resources (e.g. outside of its configuration) since it will be not able to destroy them.

**Comment by edwardmedia** [comment] 2022-10-13 16:15
@jeremietharaud agree with below statement. But in some cases, API could create other underline resources for you. Can you share your full debug log so we can inspect if the topics were created by Terraform?

```
The fact is that Terraform should not create unmanaged resources
```

**Comment by jeremietharaud** [comment] 2022-10-14 09:53
OK here are the DEBUG logs:

[debug.log](https://github.com/hashicorp/terraform-provider-google/files/9784740/debug.log)

**Comment by edwardmedia** [comment] 2022-10-14 14:15
@jeremietharaud I see below code in the log and your config. Don't you need to create `"projects/my-project/topics/blablaeverythingisfine"` in advance? 

```
   "eventTrigger": {
    "eventType": "google.pubsub.topic.publish",
    "resource": "projects/my-project/topics/blablaeverythingisfine"
   },
```

```
resource "google_cloudfunctions_function" "function" {
  name        = "my-function"
  runtime     = "python39"

  available_memory_mb   = "128"
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  entry_point           = "function_handler"

  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = "blablaeverythingisfine" <---- here. How 
  }
}
```

**Comment by jeremietharaud** [comment] 2022-10-14 14:47
@edwardmedia it looks like the topic is automatically created by Terraform (provider or gcp api?), which is to my mind not correct. There is no verification of the existence of the topic.
The `plan` or the `apply` should fail if the topic does not exist, what do you think?

**Comment by edwardmedia** [comment] 2022-10-20 18:39
@jeremietharaud I am not sure if there is a use case that `event_trigger.resource` should be provided with a non-existing `topic`. Anyway, the provider is a pass-through, and it does not add the extra resources. As you have discovered, this is likely the API's behavior, and the provider has no knowledge about its creation. Thus, it is impossible the extra resources can be destroyed at the provider level. Does this make sense?

**Comment by edwardmedia** [comment] 2022-10-20 18:41
This is not a bug and there is not much we can do at the provider level. Closing the issue now

**Closed by edwardmedia** 2022-10-20 18:41 UTC
Labels: bug
