### ISSUE TITLE
Usability issue with disabled project APIs

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-provider-google#16883] opened 2024-01-02 15:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_*

### Provider version

`5.10.0`

### Problem description

Right now if you create a resource that requires a service API that isn't enabled it fails with an error like
```
Error: Error creating Service: googleapi: Error 403: Cloud Run Admin API has not been used in project ... before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/run.googleapis.com/overview?project=... then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

This is normal and expected.

The issue is that the resources now exist in the state file and subsequent runs and during the read step they fail with the same error, preventing creating new resources.  This means even if you subsequently add the `ProjectService` to the terraform stack it cannot be applied.

### Workarounds

There are only two ways to proceed in this situation:

1. Delete the broken resources from the state file manually
2. Manually enable the APIs via the web UI

### Proposed solution

I think either of the following would work:

- Somehow ignore the error if a resource is not yet fully created during the read step or
- Automatically enable services or
- Make the service a required parameter for any resource that needs a service API, forcing users to make the ProjectService before the resource and avoiding the need for "depends on"

**Comment by ggtisc** [comment] 2024-03-01 20:58
@andrewbaxter Could you provide more info like the resources you are working on or some code to replicate the issue and the steps to reproduce?

Did you comment or delete some resources that were previously created with `terraform apply`?

**Comment by ggtisc** [comment] 2024-03-07 19:21
Hi @andrewbaxter I have replicated this scenario, I suggest you to use `depends_on` like this:

```
resource "google_project_service" "cloudrun" {
  service = "run.googleapis.com"

  timeouts {
    create = "30m"
    update = "40m"
  }

  disable_dependent_services = true
}

resource "google_cloud_run_v2_service" "default" {
  name     = "cloudrun-service"
  location = "us-central1"
  ingress = "INGRESS_TRAFFIC_ALL"

  template {
    containers {
      image = "us-docker.pkg.dev/cloudrun/container/hello"
    }
  }

  depends_on = [google_project_service.cloudrun]
}
```

Please tell me if after this you are still having issues

**Comment by andrewbaxter** [comment] 2024-03-09 15:13
Thanks for the suggestion! Can you explain what problem you resolved by using `depends_on` here? I'm not sure we're talking about the same issue.

**Comment by andrewbaxter** [comment] 2024-03-12 12:36
Ah thanks! Right, I'm aware of what `depends_on` does.

I believe that is addressing a different issue.  The problem in this issue is that the (for example) cloudrun service gets created in a broken state.

In a subsequent run I add the `depends_on` to the `google_project_service` resource, but that doesn't fix the issue - before the create and update, while generating the plan, there's a _read_.  The read fails, because the cloudrun service failed to be created due to the missing service.  Because this happens before the application of changes, the `depends_on` does not resolve the situation.

If you create the resource initially with `depends_on` this doesn't occur.  This is a quality of life issue when there are mistakes in the initial stack definition.

I might be missing something here, but I'd like to make sure we're on the same page first.

**Comment by ggtisc** [comment] 2024-03-12 18:51
Please confirm if the process is the next:

1. Having a terraform code that create a new resource (for example cloud run), but it's API isn't enabled in GCP
2. Execute the `terraform apply`
3. Get the error that says `Error: Error creating Service: googleapi: Error 403: Cloud Run Admin API has not been used in project ... before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/run.googleapis.com/overview?project=... then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`
4. Enable the API
5. Execute the `terraform apply` again and then it crashes because the resource with the 1st `terraform apply` saved the resource on the `terraform state`

**Comment by andrewbaxter** [comment] 2024-03-13 18:09
Ah right, no the process is slightly different:  At 4, I add the `google_project_service` resource and set `depends_on` but I do not manually enable the API.  The rest is the accurate.

**Comment by ggtisc** [comment] 2024-03-14 20:11
@andrewbaxter I've replicated the steps as you told. at point 4th if you don't enable the API you will always receive the same message:

`Error: Error creating Service: googleapi: Error 403: Cloud Run Admin API has not been used in project ... before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/run.googleapis.com/overview?project=... then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`

Even if the API isn't enabled the resources aren't saved in the `terraform state` until you enable the API and run the `terraform apply`. So please if you are following different steps provide us more info and the same with code and other involved resources.

**Comment by andrewbaxter** [comment] 2024-03-15 02:21
It sounds like you've replicated the issue.

> Even if the API isn't enabled the resources aren't saved in the `terraform state` until you enable the API and run the `terraform apply`

I believe this is incorrect and is the crux of the issue. The resources are saved, that's why the error appears _before_ displaying the `apply` plan and requesting confirmation.

> at point 4th if you don't enable the API you will always receive the same message

This is the problematic behavior.  `google_project_service` will enable the api, so adding it to the stack should be enough to resolve the issue.  But as it is it requires manual intervention to get the stack to apply (manually enabling the service or deleting the broken resources from the state file).

**Comment by roaks3** [comment] 2024-03-15 18:44
@andrewbaxter from reading the discussion here, it sounds like you have some sort of partially created resource (like `google_cloud_run_v2_service`) that is in Terraform state and causing the read to fail. Do I have that right?

When a resource is successfully created, it should then be added to Terraform state, but not before then. When you get an error during creation it (typically) shouldn't add anything to state. This would normally allow future plans to work as expected, which is why I'm wondering about your case specifically. Perhaps some of our resources are able to partially create resources even when the service is disabled, and then they fail after that point?

If I'm correct about the above assumptions, I think we would need a few more details around which resource specifically you are using (is it `google_cloud_run_v2_service`?), and verify you are able to reproduce this yourself. The only issue I was able observe was a race condition (when `depends_on` is not used), which could be resolved by a second apply.

**Comment by andrewbaxter** [comment] 2024-03-18 09:46
Okay right, I think we're all on the same page now.  Yes, that was my expectation too and that's not what I observed in the initial report... unfortunately it's been several months so I might have lost some details.

I just tried reproducing it now and encountered two similar issues before getting to cloud run:

1. Enabling the service usage api fails
```json
{
  "provider": {
    "google": [
      {
        "credentials": ...,
        "project": "test5-417608"
      }
    ]
  },
  "resource": {
    "google_project_service": {
      "z81XDKWRI": {
        "depends_on": [
          "google_project_service.zOSJATSNC"
        ],
        "service": "iam.googleapis.com"
      },
      "zOSJATSNC": {
        "service": "serviceusage.googleapis.com"
      }
    }
  },
  "terraform": {
    "backend": {
      "local": {
        "path": "..."
      }
    },
    "required_providers": {
      "google": {
        "source": "hashicorp/google",
        "version": "5.10.0"
      }
    }
  }
}
```
```
│ Error: Error when reading or editing Project Service : Request `List Project Services test5-417608` returned error: Failed to list enabled services for project test5-417608: googleapi: Error 403: Service Usage API has not been used in project 321157631455 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=321157631455 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.Help",
│     "links": [
│       {
│         "description": "Google developers console API activation",
│         "url": "https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=321157631455"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/321157631455",
│       "service": "serviceusage.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ , accessNotConfigured
│ 
│   with google_project_service.zOSJATSNC,
│   on stack.tf.json line 20, in resource.google_project_service.zOSJATSNC:
│   20:       }
│ 
```
This does not affect read, the error occurs after typing `yes` at the apply prompt.

After manually enabling the serviceusage api it is unable to reach the plan confirmation during apply with the following error about the cloudresourcemanager api, which is the behavior I encountered that led to me making this issue.

2. Enabling the resource manager api fails
```json
{
  "provider": {
    "google": [
      {
        "credentials": "...",
        "project": "test6-417609"
      }
    ]
  },
  "resource": {
    "google_project_service": {
      "zOSJATSNC": {
        "depends_on": [
          "google_project_service.zUSKCVXCT"
        ],
        "service": "serviceusage.googleapis.com"
      },
      "zUSKCVXCT": {
        "service": "cloudresourcemanager.googleapis.com"
      }
    }
  },
  "terraform": {
    "backend": {
      "local": {
        "path": "..."
      }
    },
    "required_providers": {
      "google": {
        "source": "hashicorp/google",
        "version": "5.10.0"
      }
    }
  }
}
```
```
│ Error: Error when reading or editing Project Service : Request `List Project Services test6-417609` returned error: Failed to list enabled services for project test6-417609: googleapi: Error 403: Service Usage API has not been used in project 782431615660 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=782431615660 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.Help",
│     "links": [
│       {
│         "description": "Google developers console API activation",
│         "url": "https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=782431615660"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/782431615660",
│       "service": "serviceusage.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ , accessNotConfigured
│ 
│   with google_project_service.zUSKCVXCT,
│   on stack.tf.json line 20, in resource.google_project_service.zUSKCVXCT:
│   20:       }
│ 
```

It appears that project service requires the serviceusage and cloudresourcemanager apis internally, so enabling either of those via project service itself in terraform is impossible.

It's possible the issues I encountered were with the cloudresourcemanager apis.

**Comment by roaks3** [comment] 2024-03-19 16:07
Thank you for the additional info.

> 1. Enabling the service usage api fails

Yea, as you saw, this is expected. There is no way around the chicken-and-egg problem where this API needs to be enabled outside of this Terraform resource. It appears that the Service Usage API is [enabled by default](https://cloud.google.com/service-usage/docs/enabled-service) (although I don't know that this was always the case), so this generally shouldn't be a problem for users moving forward.

> 2. Enabling the resource manager api fails

From the error you've shared, it looks like the Service Usage API was probably not yet available (it can take a couple minutes). https://github.com/hashicorp/terraform-provider-google/issues/6101 appears to be fixed, so hopefully it is still possible to control the cloudresourcemanager API from this resource.

> It appears that project service requires the serviceusage [...] apis internally, so enabling either of those via project service itself in terraform is impossible

Yes, I believe that is correct. Validation would probably not make sense here though (it could change over time), and the error message seems to provide sufficient documentation. We also already have a note in the resource documentation that the Service Usage API is a requirement, so I think adding an additional note for how this API acts within the resource is probably more than we need.

I'm tempted to close this as Working as Intended, but want to be sure I haven't missed something. In particular, I want to be sure the `project_service` resource is not responding improperly to previous failures.

**Comment by roaks3** [comment] 2024-03-20 15:14
Correction on my previous comment: per https://github.com/hashicorp/terraform-provider-google/issues/14174, it appears that Service Usage API is not enabled by default for Terraform-created projects. So it may be best to mark this as a duplicate of that issue.

**Closed** 2024-03-22 21:16 UTC
Labels: bug, forward/review, service/serviceusage
