### ISSUE TITLE
google_sql_database_instance incorrectly handles optional insights_config

### ISSUE THREAD

**Issue by dbason** [hashicorp/terraform-provider-google#18918] opened 2024-07-31 00:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v2.26.1
+ provider registry.terraform.io/hashicorp/aws v2.70.4
+ provider registry.terraform.io/hashicorp/google v5.39.1
+ provider registry.terraform.io/hashicorp/google-beta v5.39.1

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration

```
resource "google_sql_database_instance" "bug" {
  provider            = google
  name                = "bug"
  region              = "us-east1"
  database_version    = "POSTGRES_15"
  project             = local.project_id
  deletion_protection = true

  settings {
    disk_autoresize             = true
    disk_type                   = "PD_HDD"
    tier                        = redacted
    deletion_protection_enabled = true

    activation_policy = "ALWAYS"
    availability_type = "REGIONAL"

    edition = "ENTERPRISE"

    ip_configuration {
      ipv4_enabled                                  = false
      require_ssl                                   = false
      private_network                               = data.google_compute_network.bug_project.self_link
      enable_private_path_for_google_cloud_services = true
    }

    location_preference {
      zone = "us-east1-b"
    }

    backup_configuration {
      enabled                        = true
      start_time                     = "13:00"
      point_in_time_recovery_enabled = true
      location                       = "us"
    }

    maintenance_window {
      day          = 7
      hour         = 14
      update_track = "stable"
    }

    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }
  }
}
```

### Expected Behavior

Expect the terraform plan to show no changes

### Actual Behavior

Plan shows changes to be applied:
```
  # google_sql_database_instance.test will be updated in-place
  ~ resource "google_sql_database_instance" "bug" {
        id                             = "bug"
        name                           = "bug"
        # (18 unchanged attributes hidden)

      ~ settings {
            # (16 unchanged attributes hidden)

          - insights_config {
              - query_insights_enabled  = false -> null
              - query_plans_per_minute  = 0 -> null
              - query_string_length     = 0 -> null
              - record_application_tags = false -> null
              - record_client_address   = false -> null
            }

            # (5 unchanged blocks hidden)
        }
    }

```

### Steps to reproduce

1. `terraform plan`

### Important Factoids

If we set the `insights_config` block to be what is shown in the changes to be applied the plan errors because `query_string_length` must be between 256 - 4500.

If we then remove the `query_string_length` from the `insights_config` section we get the following:
```
 # google_sql_database_instance.test will be updated in-place
~ resource "google_sql_database_instance" "bug" {
        id                             = "bug"
        name                           = "bug"
        # (18 unchanged attributes hidden)

      ~ settings {
            # (16 unchanged attributes hidden)

          ~ insights_config {
              ~ query_string_length     = 0 -> 1024
                # (4 unchanged attributes hidden)
            }

            # (5 unchanged blocks hidden)
        }
    }
``` 
However in the documentation it states that updating the query_string_length requires an instance restart so this is not something we want to apply without verification

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#query_string_length

https://cloud.google.com/sql/docs/postgres/using-query-insights

b/356874854

**Comment by longpaul** [comment] 2024-07-31 15:26
The workaround is to enable query insights via Web GUI (it doesn't mention restart on Save )
Then you can add the following config in Terraform (shouldn't make any changes)
```
  insights_config = {
    query_insights_enabled  = true
    query_string_length     = 1024
    record_application_tags = false
    record_client_address   = false
  }
```
Nevertheless... still a bug of course.

**Comment by dbason** [comment] 2024-07-31 19:38
We want it left disabled, the major issue for us is that this is showing up as drift in our internal systems

**Comment by longpaul** [comment] 2024-07-31 20:06
> We want it left disabled, the major issue for us is that this is showing up as drift in our internal systems

Yes, unfortunately I don't see the possibility to use
`query insights enabled = false`
(without configuration drift)
so that definitely should be fixed.

**Comment by lra** [comment] 2024-07-31 20:50
Same issue using google sql db tf module: the https://github.com/terraform-google-modules/terraform-google-sql-db/issues/623
Our only workaround with the module is to enable insights on every database.

**Comment by mike-code** [comment] 2024-07-31 22:53
> Another workaround that works for me is to add a block inside the resource of Terraform:
> 
> ```
>   lifecycle {
>     ignore_changes = [ 
>       settings[0].insights_config 
>     ]
>   }
> ```

This unfortunately won't work for modules

**Comment by SarahFrench** [comment] 2024-08-01 15:06
For the person who works on this ticket, the cause is described in this comment: https://github.com/hashicorp/terraform-provider-google/issues/18943#issuecomment-2262683642

**Comment by c2thorn** [comment] 2024-08-01 18:34
Hey folks, apologies for the perma-diff here. 

I've reached out internally to see if we can get the API change that caused this rolled back. In the meantime, https://github.com/GoogleCloudPlatform/magic-modules/pull/11327 should fix this in the next release.

To mitigate this now in current and previous provider versions, the lifecycle argument mentioned in https://github.com/hashicorp/terraform-provider-google/issues/18918#issuecomment-2261454456 is available. Unfortunately this will not apply for modules due to https://github.com/hashicorp/terraform/issues/27360

**Comment by c2thorn** [comment] 2024-08-05 17:56
[v5.40.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.40.0) has the fix in the provider

The internal backend team is investigating a backend fix as well that would be able to resolve for older provider versions. (b/356874854 for internal people)

**Comment by c2thorn** [comment] 2024-08-08 16:52
I've received word from the internal team that a fix preventing this behavior in the API has also rolled out.

**Closed by c2thorn** 2024-08-08 16:52 UTC
Labels: bug, forward/review, service/sqladmin-cp
