### ISSUE TITLE
google_cloudbuild_trigger missing "filter" field

### ISSUE THREAD

**Issue by finlaye** [hashicorp/terraform-provider-google#10387] opened 2021-10-25 13:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The cloud build API has the option to specify a filter string https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers

```
"filter": string
```

This seems to be missing from the google terraform provider.

### New or Affected Resource(s)

`google_cloudbuild_trigger`

* google_XXXXX

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "filename-trigger" {
  trigger_template {
    branch_name = "master"
    repo_name   = "my-repo"
  }

  substitutions = {
    _FOO = "foo-bar"
    _BAZ = "qux"
  }

  filter = "_FOO.matches(\".*-bar\")"

  filename = "cloudbuild.yaml"
}
```

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger
* https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers

**Comment by smorenburg** [comment] 2021-12-20 13:48
I'm looking forward to this enhancement. Creating the Cloud Build triggers using Terraform ain't an option right now.

**Comment by aucampia** [comment] 2021-12-26 20:26
See also: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers#resource:-buildtrigger

**Comment by abhinavrau** [comment] 2022-02-22 20:25
I would like to work on this issue. I have added support for it on my fork of magic-modules [here](https://github.com/abhinavrau/magic-modules/tree/cloudbuild_filter). I will be submitting a PR soon

**Comment by abhinavrau** [comment] 2022-02-23 19:23
Duplicate of #9755

**Closed** 2022-03-04 17:25 UTC
Labels: enhancement, size/s
