### ISSUE TITLE
Service Account data resource fails with 403 instead of 404 when Service Account not present

### ISSUE THREAD

**Issue by pratikmallya** [hashicorp/terraform-provider-google#3349] opened 2019-03-31 21:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13

### Affected Resource(s)

* google_service_account 

### Terraform Configuration Files

```tf
provider "google" {
  version = "~> 2.0.0"
  region  = "us-central1"
}


data "google_service_account" "object_viewer" {
  account_id = "test-1"
  project = "primeval-sweep-225822"
}


```

### Debug Output

https://gist.github.com/pratikmallya/7a49893efa8c62ab4f06834f1a98e95a

### Panic Output

None

### Expected Behavior

The error message should have said 404 not found; instead it misleadingly mentions the issue as a 403.

### Actual Behavior

The error message should have said 404 not found; instead it misleadingly mentions the issue as a 403.

### Steps to Reproduce

1. Use the tf code snippet above.
2. Change the project id to a project that exists, but the service account with that account id does not exist in that project.
3. Run `terraform plan`. The plan should fail with a 403 for every non-existing service account in the project.

### Important Factoids

None. Authenticated as a user with viewer role over the project

### References
None
b/299683661

**Comment by rileykarson** [comment] 2019-04-02 23:07
This is an issue where the underlying API returns a 403 instead of a 404, so Terraform isn't able to do much. I'd suggest filing an issue at https://cloud.google.com/support/docs/issue-trackers, and linking that issue here so that the provider maintainers can keep track as well.

**Comment by pratikmallya** [comment] 2019-04-02 23:53
What underlying API returns a 403? I would like to know more info before filing a ticket with Google, as I'm pretty sure they will ask me the same q

**Comment by rileykarson** [comment] 2019-04-03 14:38
Ah! My apologies, service accounts are part of the IAM API; you can file the issue on this component: https://issuetracker.google.com/issues/new?component=187161&template=0.

**Comment by pratikmallya** [comment] 2019-04-04 01:45
Filed here: https://issuetracker.google.com/issues/129901031

**Comment by benhxy** [comment] 2023-10-04 19:50
Looks like https://issuetracker.google.com/issues/129901031 is closed. Is this issue still reproducible? I suspect https://github.com/hashicorp/terraform-provider-google/issues/15042 is the cause and it's been fixed in TF.

**Comment by rileykarson** [comment] 2023-10-04 20:05
Agreed, seems to work as intended now- I see GETs receiving 404s in test logs.

**Closed by rileykarson** 2023-10-04 20:05 UTC
Labels: bug, upstream, forward/linked, service/iam-serviceaccount
