### ISSUE TITLE
google_cloud_run_v2_service: when `resources` are specified `cpu_idle` defaults to false

### ISSUE THREAD

**Issue by mattmoor** [hashicorp/terraform-provider-google#17246] opened 2024-02-10 16:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

TF: 1.5, 1.6

I think we're on ~5.14 of the Google provider.

### Affected Resource(s)

google_cloud_run_v2_service

### Terraform Configuration

```tf
resource "google_cloud_run_v2_service" "foo" {
  name     = "foo"
  project  = var.project_id
  location = var.region

  template {
    containers {
      image = "..."

      resources {
        limits = {
          cpu    = "2000m"
          memory = "8Gi"
        }
      }
    }
  }
}
```

### Expected Behavior

When the above is applied, it shows up in the console as idling the CPU when requests aren't in flight.

### Actual Behavior

When the above is applied, it shows up in the console as an ALWAYS ON CPU.

### Steps to reproduce

1. Apply the above,
2. Check the console for whether the CPU is "always allocated",
3. Remove the resource block above, and apply again,
4. Check the console again.

### Important Factoids

IMO it violates the principle of least surprise for the default of a knob I am not turning to CHANGE when I am turning other knobs (which is why this smells like a provider bug).  I can see a 20-50x improvement in the CPU allocation metrics in some of our environments after correcting this for just a handful of services (still waiting to see the billing impact).

This is the past ~week's CPU allocation in one environment, where we fixed this for the handful of services that were specifying resources last night:
![image](https://github.com/hashicorp/terraform-provider-google/assets/2442466/464d9b8a-ffc4-4384-a2e8-95c7dd591e8b)

cc @steren 

b/324764802

**Comment by steren** [comment] 2024-02-10 19:11
Unfortunately, this is consistent with the default CPU allocation of Cloud Run services. CPU is throttled outside of requests.

Jobs and future non-request based workloads default to CPU always on.

**Comment by steren** [comment] 2024-02-10 19:11
Unless Cloud Run API changes its behavior, this is Working As Intended for the terraform module

**Comment by mattmoor** [comment] 2024-02-10 19:39
> Unfortunately, this is consistent with the default CPU allocation of Cloud Run services. CPU is throttled outside of requests

@steren what I am seeing is that when resources are explicitly specified that CPU **_stops_** being throttled outside of requests.

**Comment by edwardmedia** [comment] 2024-02-10 22:37
This behavior is controlled by the api. Forward the issue to the service team

**Comment by yanweiguo** [comment] 2024-02-16 18:10
The problem is `cpu_idle` is defined as a boolean proto in cloud run API. If `resources` is not set, `resources.cpu_idle` defaults to `true`. If `resources` is set, we don't know a `false` value of `resources.cpu_idle` is set by the user explicitly or is from the default value of proto boolean type. So the API just accepts the input value.

I'll update the document to call this out. Unfortunately it can't be improved without API change or a breaking change in TF side to set client side default value to `true`.

**Comment by mattmoor** [comment] 2024-02-16 19:25
I get it.  It's an unfortunate design choice that creates a "footgun" where customers hoping to just express resource bounds end up potentially 10x-ing their bill. After finding this issue, I flagged a whole bunch of places where our folks were holding this wrong, and in all of them the bill dropped by a significant multiple.

Like I said, I think this violates the "principle of least surprise" and you are likely to end up with surprised and grumpy customers as a result of this, so you should think about ways to mitigate this if you can't change this.

We've worked around this ourselves, and I think you've heard the feedback, so we can close this issue out.

**Comment by melinath** [comment] 2024-02-22 19:28
Resolved with improved documentation via https://github.com/GoogleCloudPlatform/magic-modules/pull/10005. Thanks!

**Closed by melinath** 2024-02-22 19:28 UTC
Labels: bug, forward/linked, service/run
