### ISSUE TITLE
Promote `google_compute_backend_service.customResponseHeaders` to GA

### ISSUE THREAD

**Issue by glerchundi** [hashicorp/terraform-provider-google#9360] opened 2021-06-14 13:59 UTC
[This PR in `GoogleCloudPlatform/magic-modules`](https://github.com/GoogleCloudPlatform/magic-modules/pull/4286) moved `customResponseHeaders` from official branch to the beta one.

As far as I can see, it seems like that header is no longer beta. At least, I'm not able to find out any reference which is stating that.

Would it be possible to revert the changes in #7943 to bring back those to the official branch?

Thanks!

**Comment by glerchundi** [comment] 2021-06-14 14:02
Pinging @c2thorn as he was the one who did the changes in `magic-modules`.

**Comment by edwardmedia** [comment] 2021-06-14 14:52
@glerchundi I am not super clear what the problem is. Can you add details about what it is?

**Comment by glerchundi** [comment] 2021-06-14 17:14
Sorry for not giving you more details in the very beginning.

Due to certification concerns we're not allowed to use beta features in our infrastructure.  This extends also to the terraform provider.

I would like to see this feature promoted in order to start using this in our infrastructures.

Does it makes sense?

**Comment by c2thorn** [comment] 2021-06-14 17:19
Edited the title to be consistent with other similar requests. Also applied the enhancement label since removing the feature from the GA provider was intentional. 

Since the original PR, it looks like the field has been moved to the GA API, so it is reasonable to do the same in the GA provider.

**Comment by glerchundi** [comment] 2021-06-14 19:38
@c2thorn I can work on this, what do you think?

**Comment by glerchundi** [comment] 2021-06-14 20:24
I took the opportunity to send a PR as I found a free time slot to work on this. Let me know if it's OK or you prefer to do by yourselves, no problem at all.

Thanks!

**Comment by c2thorn** [comment] 2021-06-14 20:31
@glerchundi We have it as a Near-Term goal, but it isn't yet pulled into an upcoming sprint. If you are able to manage a PR that would speed up the process considerably. I'll take a look at your PR.

**Comment by glerchundi** [comment] 2021-06-14 20:34
Really appreciated @c2thorn!

**Comment by upodroid** [comment] 2021-06-23 22:39
Cameron, the MM PR has been merged. Can you close this?

**Comment by c2thorn** [comment] 2021-06-24 15:40
Thanks for pointing this out @upodroid

**Closed by c2thorn** 2021-06-24 15:40 UTC
Labels: enhancement, size/s
