### ISSUE TITLE
Add tests.headers to google_compute_url_map

### ISSUE THREAD

**Issue by segevfiner** [hashicorp/terraform-provider-google#19237] opened 2024-08-23 10:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

A google_compute_url_map test can specify custom headers, but the field is currently missing from the provider.

### New or Affected Resource(s)

* google_compute_url_map

### Potential Terraform Configuration

```tf 
resource "google_compute_url_map" {
test {
    service = google_compute_backend_bucket.static.id
    host    = "example.com"
    path    = "/home"
    headers = [
      {
        name = "User-Agent"
        value = "Banana/1.0"
      }
    ]
  }
```

### References

https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps

https://github.com/pulumi/pulumi-gcp/issues/2337

b/362278389

**Comment by pawelJas** [comment] 2024-08-27 12:29
dupilcate to: https://github.com/hashicorp/terraform-provider-google/issues/9536

**Comment by melinath** [comment] 2024-08-27 17:00
@pawelJas thanks for catching that!

Closing as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9536.

**Closed by melinath** 2024-08-27 17:00 UTC
Labels: enhancement, size/s, forward/linked, service/compute-l7-load-balancer
