### ISSUE TITLE
google_compute_disk wants to recreate disk due to adding "interface"

### ISSUE THREAD

**Issue by GavBurke** [hashicorp/terraform-provider-google#8457] opened 2021-02-12 11:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

My issue is yet again another one of these forever ongoing things with Google API changes not being reflected in latest TF provider.  My latest issue is my data disks are wanting to be recreated because it wants to add the "interface" option.

Steps to replicate?  Create a data disk with the 3.0.0 provider, then update to 3.56.0 and do a `terraform plan` and you'll see it wants to **destroy** the _data_ disk!!

```
  # module.data_disk.google_compute_disk.default must be replaced
+/- resource "google_compute_disk" "default" {
      ~ creation_timestamp        = "2020-02-19T23:53:09.472-08:00" -> (known after apply)
      ~ id                        = "projects/<my_project>/zones/<my_zone>/disks/dev-data-disk" -> (known after apply)
      + interface                 = "SCSI" # forces replacement
```

I am guessing broken from 3.45.0 onwards with this PR https://github.com/hashicorp/terraform-provider-google/pull/7554

**Comment by GavBurke** [comment] 2021-02-12 15:24
Actually, I was trying to my own "steps to replicate" method, but it doesn't break that way.  For it to be an issue, it seems you'd need a data disk that was deployed possibly pre-Sept 2020 (whenever this "interface" change was made to data disks), to then see 3.45.0 onwards wanting to trash the disk.

**Comment by edwardmedia** [comment] 2021-02-12 16:02
@GavBurke I agreed it becomes a little hard once API updates its behavior. One suggestion to handle your case is to add below block to prevent recreation. 

```
  lifecycle {
    ignore_changes = [interface,]
  }
```

**Comment by GavBurke** [comment] 2021-02-22 15:07
Sorry for the delay answering @edwardmedia - I was on a weeks leave.

I've tried that today, which was a bit higgidy piggidy as we make our own modules in my team which then used our own organization modules, so I change my local copies of a couple of modules, but the output error seems to suggest that won't work because I don't currently set the "interface" attribute of the compute disk....?

```
Error: Unsupported attribute

  on ../../../../cloud-service-registry/registry/services/storage/csr-compute-disk/compute_disk.tf line 24, in resource "google_compute_disk" "default":
  24:     ignore_changes = [interface,]

This object has no argument, nested block, or exported attribute named
"interface".
```

**Comment by slevenick** [comment] 2021-02-22 20:15
@GavBurke I think the actual directive you want is like this:
```
  lifecycle {
    ignore_changes = [interface]
  }
```

That should prevent Terraform from seeing this change and attempting to recreate the disk

**Comment by slevenick** [comment] 2021-02-22 20:43
Looks like this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7908

That also lists a workaround of setting `interface = ""` to avoid recreating these disks.

I think this is an unfortunate interaction with the API and a field we don't support yet. Ideally supporting the guestOsFeatures field would fix this as suggested here: https://github.com/hashicorp/terraform-provider-google/issues/8012

**Comment by GavBurke** [comment] 2021-02-23 09:29
@slevenick I tried the `ignore_changes = [interface,]` already per Edwards suggestion, and was pretty certain if `ignore_changes = [interface,]` failed then so would your `ignore_changes = [interface]` suggestion, but I tried anyways.  And yup, it fails with the same error!

I followed your `interface = ""` workaround instead, though to no joy as that gave a very similar error of
```
Error: Unsupported argument

  on ../../../../cloud-service-registry/registry/services/storage/csr-compute-disk/compute_disk.tf line 22, in resource "google_compute_disk" "default":
  22:   interface = ""

An argument named "interface" is not expected here.
```

This is using Google provider 3.57.0 with the following resource definition
```
resource "google_compute_disk" "default" {
  name    = "${var.environment}-${var.name}"
  project = var.project
  zone    = var.zone
  size    = var.disk_size
  type    = var.disk_type
  labels  = merge(local.default_labels, var.labels)

  depends_on = [google_compute_resource_policy.default-snapshot-schedule]
  interface = ""
}
```

**Comment by slevenick** [comment] 2021-02-23 16:48
Ah, it looks like the `interface` field is only available for the `beta` provider. Have you been using the google-beta provider or the google provider, because the google provider should not know about the `interface` field at all

**Comment by GavBurke** [comment] 2021-02-24 08:38
That's weird, as we do have the google-beta provider defined but not set for that resource block, which I assume them using the google provider?

Saying this, according to the release notes, the interface google_compute_disk change was added to _both_ the beta and mainstream, as can be seen https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3450-october-28-2020 for the mainstream, via PR [7554](https://github.com/hashicorp/terraform-provider-google/pull/7554)

**Comment by GavBurke** [comment] 2021-02-24 10:56
@slevenick Here's what I've tried further, with the workaround now working using beta provider.  For my module that creates the disk, added

```
provider "google-beta" {
  version = ">= 3.45.0"
  project = var.project
  region  = var.region
}
```

And then in the resource block for the disk added the provider, so 
```
resource "google_compute_disk" "default" {
  provider = "google-beta"
```

Then tried with `interface=""` in that resource block and it now doesn't wanna replace the disk.  I assume though now using the google-beta that the original lifecycle ignore_changes workaround would also work?

**Comment by slevenick** [comment] 2021-02-25 00:48
Ah yeah that changelog note probably was a mistake. If you look at the PR it only updates the docs page for the resource, not the resource itself. The update is present in the GA documentation due to some arcane reasons, but you'll notice the resource in the `google` provider does not have any code around the `interface` field, indicating that it doesn't exist in that provider.

The lifecycle ignore_changes should work now that you are using the beta provider, as well as setting interface="". I'll close this as the underlying cause is only due to an API-side detail with the migration, and not a problem for any disks created outside of that time period

**Comment by ScottSuarez** [comment] 2021-05-19 23:02
pushing a fix forward for this issue that **should** resolve this if anyone is still encountering it

**Closed** 2021-05-20 00:24 UTC
Labels: bug
