### ISSUE TITLE
[Cloud Run] apply continues to fail due to a revision mismatch

### ISSUE THREAD

**Issue by kmtym1998** [hashicorp/terraform-provider-google#14404] opened 2023-04-23 11:42 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
- Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment.
- If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform: v1.4.5
google provider: v4.62.1

### Affected Resource(s)

- `google_cloud_run_service`

### Terraform Configuration Files

```tf
resource "google_cloud_run_service" "bookmark_api" {
  name     = var.name
  location = var.region

  metadata {
    annotations = {
      generated-by                 = "magic-modules"
      "run.googleapis.com/ingress" = "all"
    }
  }
  template {
    spec {
      service_account_name = google_service_account.bookmark.email
      containers {
        image = "asia.gcr.io/${var.project_id}/bookmark-api:latest"
        resources {
          limits = {
            "cpu" : "1"
            "memory" : "128Mi"
          }
        }

        env {
          name  = "ENV"
          value = "production"
        }
      }
    }

    metadata {
      annotations = {
        "autoscaling.knative.dev/minScale" = "0"
        "autoscaling.knative.dev/maxScale" = "1"
        "run.googleapis.com/front-name"    = "terraform"
      }
    }
  }
  autogenerate_revision_name = true

  depends_on = [
    google_secret_manager_secret_version.bookmark_api_key_version
  ]
}
```

### Debug Output

https://gist.github.com/kmtym1998/7e14588af2302bf8b5ad76b06622bb47

### Expected Behavior

I expect one of the following:

Execution terminates abnormally soon after failing to update revisions
A new revision is created

### Actual Behavior

The attempt to create a revision failed with `409 Conflict`, but it keeps retrying. Even if I interrupt by entering ^C, it continues to fail, so I have no choice but to enter ^C again to force cancel it.

Here is the error response returned from the Cloud Run API:

```json
{
  "error": {
    "code": 409,
    "message": "Conflict for resource '<resource name>': version '1682215607250822' was specified but current version is '1682246255991863'.",
    "status": "ABORTED"
  }
}
```

### Steps to Reproduce

1. `terraform apply`
2. Create a new revision using the Google Cloud console
3. type `yes` to apply changes
4. The error shown above occurs. You can check the details of the error in Cloud Logging.

**Comment by kmtym1998** [comment] 2023-04-30 02:31
@edwardmedia 

Hello,

Regarding the error, It's caused by retrying the request when receiving a 409 error from the Cloud Run API.

https://github.com/hashicorp/terraform-provider-google/blob/ab761cde8a4084e738b222a49cc5550c55ad9f9d/google/resource_cloud_run_service.go#L1334

The function `IsCloudRunCreationConflict` is passed as the `RetryErrorPredicateFunc` of `SendRequestWithTimeout`, expecting it to be used only for create operations. Therefore, I think it should not be passed for update operations.

https://github.com/hashicorp/terraform-provider-google/blob/ab761cde8a4084e738b222a49cc5550c55ad9f9d/google/error_retry_predicates.go#L193-L197C1



```diff
- res, err := SendRequestWithTimeout(config, "PUT", billingProject, url, userAgent, obj, d.Timeout(schema.TimeoutUpdate), IsCloudRunCreationConflict)
+ res, err := SendRequestWithTimeout(config, "PUT", billingProject, url, userAgent, obj, d.Timeout(schema.TimeoutUpdate))
```

Assuming there are no issues with this change, I would like to submit a Pull Request with some refactoring.

**Comment by kmtym1998** [comment] 2023-04-30 02:45
I made the above changes in the source code and ran terraform in development mode. I have confirmed that it does not continue to retry after failure.

```sh
$ terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/google in /Users/kmtym1998/go/bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published
│ releases.
╵
Acquiring state lock. This may take a few moments...

# ...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.XXXX.google_cloud_run_service.XXXX will be updated in-place
  ~ resource "google_cloud_run_service" "XXXX" {
    # some changes
  }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes # create new revision by GUI before typing `yes`

module.XXXX.google_cloud_run_service.XXXX: Modifying... [id=locations/asia-northeast1/namespaces/my-project/services/XXXX]
╷
│ Error: Error updating Service "locations/asia-northeast1/namespaces/my-project/services/XXXX": googleapi: Error 409: Conflict for resource 'XXXX': version '1682818102904140' was specified but current version is '1682819419507757'.
│
│   with module.XXXX.google_cloud_run_service.XXXX,
│   on XXXX/cloud_run.tf line 1, in resource "google_cloud_run_service" "XXXX":
│    1: resource "google_cloud_run_service" "XXXX" {
│
╵
```

**Comment by kmtym1998** [comment] 2023-06-24 02:32
@yanweiguo 

> Have you been consistently running into this problem?

Yes, I am running into this problem consistently. Even with the latest terraform and google-provider we keep failing.

> It seems like you already have an idea to fix this. Are you planning to submit a PR?

I'd like to submit a PR, but I'm struggling to disable `IsCloudRunCreationConflict` only when updating a resource on `magic-modules.`

**Comment by yanweiguo** [comment] 2023-06-27 22:35
@kmtym1998 since I couldn't reproduce this issue, would you mind providing your project number, region, service where you hit the issue? Or you can report this issue to Google Support team with the information.

**Comment by kmtym1998** [comment] 2023-07-05 00:27
I will report this for Google Support team.

**Comment by melinath** [comment] 2024-01-30 21:16
Closing since this was not reproducible - if anyone is experiencing this issue, please open a new ticket with a minimal reproducible case. Thanks!

**Closed by melinath** 2024-01-30 21:16 UTC
Labels: bug, forward/linked, service/run
