### ISSUE TITLE
google_compute_instance_group instances count not updated  when apply the terraform resource

### ISSUE THREAD

**Issue by ops18** [hashicorp/terraform-provider-google#7339] opened 2020-09-23 14:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
terraform version
Terraform v0.12.29
+ provider.google v2.20.3
+ provider.template v2.1.2

### Affected Resource(s)
google_compute_instance_group
google_compute_instance

* google_XXXXX

### Terraform Configuration Files

```tf
provider "google" {
  project = "xxxx"
  credentials = file(/home/xxx/xxx.json)
  region  = "europe-west4"
  version = "~>2.7"
}

data "template_file" "nginx" {
  template = "${file("${path.module}/template/install_nginx.tpl")}"
}

resource "google_compute_instance_group" "ig_gw_group" {
  name = "xxxx-vm-group"
  description = "instance group"
  network = "projects/xxxx/global/networks/xxxx-xxxx"
  zone = "europe-west4-a"
  instances = [
  "${google_compute_instance.default.self_link}"
 ]
  named_port {
    name = "http8000"
    port = "8000"
  }
}

resource "google_compute_address" "static" {
  name = "test-xxxx"
  address_type = "INTERNAL"
  region = "europe-west4" 
  subnetwork = "projects/xxxx/regions/europe-west4/subnetworks/xxxx-xxxxx"
}
resource "google_compute_instance" "default" {
  name         = "test-instance"
  machine_type = "n1-standard-1"
  zone         = "europe-west4-a"

  tags = ["foo", "bar"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  // Local SSD disk
  scratch_disk {
    interface = "SCSI"
  }

network_interface {
    subnetwork = "projects/xxxx/regions/europe-west4/subnetworks/xxxx-xxxx"
    network_ip = "xxxxxxx"
    access_config {}
  }
  metadata = {
    foo = "bar"
  }

  metadata_startup_script = data.template_file.nginx.rendered

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
}
```

### Debug Output
2020-09-23T13:48:43.798Z [DEBUG] plugin: plugin process exited: path=/home/xxxx/test-code/.terraform/plugins/linux_amd64/terraform-provider-template_v2.1.2_x4 pid=19996
2020-09-23T13:48:43.798Z [DEBUG] plugin: plugin exited
2020/09/23 13:48:43 [WARN] Provider "registry.terraform.io/-/google" produced an invalid plan for google_compute_instance.default, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .scheduling: block count in plan (1) disagrees with count in config (0)
2020/09/23 13:48:43 [DEBUG] ReferenceTransformer: "google_compute_instance_group.ig_gw_group" references: []
2020/09/23 13:48:43 [WARN] Provider "registry.terraform.io/-/google" produced an invalid plan for google_compute_instance_group.ig_gw_group, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .instances: planned value cty.UnknownVal(cty.Set(cty.String)) does not match config value cty.SetVal([]cty.Value{cty.UnknownVal(cty.String)}) nor prior value cty.SetVal([]cty.Value{cty.StringVal("https://www.googleapis.com/compute/v1/projects/xxxx/zones/europe-west4-a/instances/test-instance")})
2020-09-23T13:48:43.843Z [DEBUG] plugin: plugin process exited: path=/home/xxxx/test-code/.terraform/plugins/linux_amd64/terraform-provider-google_v2.20.3_x4 pid=19989
2020-09-23T13:48:43.843Z [DEBUG] plugin: plugin exited'

### Panic Output

Unable to apply the changes  part when run the terraform apply 
terraform apply
xxxxx
xxxxx
xxxxx

Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_compute_instance.default: Destroying... [id=test-instance]
google_compute_instance.default: Still destroying... [id=test-instance, 10s elapsed]
google_compute_instance.default: Still destroying... [id=test-instance, 20s elapsed]
google_compute_instance.default: Destruction complete after 26s
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Still creating... [20s elapsed]
google_compute_instance.default: Creation complete after 26s [id=test-instance]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

### Expected Behavior

Terraform apply command need to apply all changes which shown in plan output
and need to update the instances value in the google_compute_instace_group resource.

Plan: 1 to add, 1 to change, 1 to destroy.

Apply complete! Resources: 1 added, 1 changed, 1 destroyed.

### Actual Behavior
Terraform apply , Change the resource defination whatever changes in plan , When terraform is able to identify changes then it should apply that change in actual infrastructure resource

Plan: 1 to add, 1 to change, 1 to destroy.

Apply complete! Resources: 1 added, 1 changed, 1 destroyed.

### Steps to Reproduce

Create a terraform resource for google_compute_instance and then add it to google_compute_instance_group 

and then update some instance configuration and re-run the terraform apply then at that time unable to apply the 

changed part when run the terraform apply command
```
  # google_compute_instance.default must be replaced
-/+ resource "google_compute_instance" "default" {
        can_ip_forward          = false
      ~ cpu_platform            = "Intel Skylake" -> (known after apply)
        deletion_protection     = false
      - enable_display          = false -> null
      ~ guest_accelerator       = [] -> (known after apply)
      ~ id                      = "test-instance" -> (known after apply)
      ~ instance_id             = "2720508029211962550" -> (known after apply)
      ~ label_fingerprint       = "42WmSpB8rSM=" -> (known after apply)
      - labels                  = {} -> null
        machine_type            = "n1-standard-1"
        metadata                = {
            "foo" = "bar"
        }
      ~ metadata_fingerprint    = "-oT9_scl80o=" -> (known after apply)
      ~ metadata_startup_script = <<~EOT # forces replacement
            #!/bin/bash
            set -e
            echo "*****    Installing Nginx    *****" > /tmp/nginx1
          - echo "hello xxxx testing" > /tmp/nginx_test
          + echo "hello xxxx testing" > /tmp/nginx_test2
            echo "Welcome to Terraform World !!!" > /tmp/nginx
        EOT
        name                    = "test-instance"
      ~ project                 = "xxxxx" -> (known after apply)
      ~ self_link               = "https://xxxxxx" -> (known after apply)
        tags                    = [
            "bar",
            "foo",
        ]
      ~ tags_fingerprint        = "1gqCRgrww4E=" -> (known after apply)
        zone                    = "europe-west4-a"
	 ~ boot_disk {
            auto_delete                = true
          ~ device_name                = "persistent-disk-0" -> (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
            mode                       = "READ_WRITE"
          ~ source                     = "https://www.googleapis.com/compute/v1/projects/xxxxx/zones/europe-west4-a/disks/test-instance" -> (known after apply)

          ~ initialize_params {
              ~ image  = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-9-stretch-v20200910" -> "debian-cloud/debian-9"
              ~ labels = {} -> (known after apply)
              ~ size   = 10 -> (known after apply)
              ~ type   = "pd-standard" -> (known after apply)
            }
        }

      ~ scheduling {
          ~ automatic_restart   = true -> (known after apply)
          ~ on_host_maintenance = "MIGRATE" -> (known after apply)
          ~ preemptible         = false -> (known after apply)

          + node_affinities {
              + key      = (known after apply)
              + operator = (known after apply)
              + values   = (known after apply)
            }
        }

        scratch_disk {
            interface = "SCSI"
        }

      ~ service_account {
          ~ email  = "xxxxxx-compute@developer.gserviceaccount.com" -> (known after apply)
            scopes = [
                "https://www.googleapis.com/auth/compute.readonly",
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/userinfo.email",
            ]
        }
    }

  # google_compute_instance_group.ig_gw_group will be updated in-place
  ~ resource "google_compute_instance_group" "ig_gw_group" {
        description = "instance group"
        id          = "europe-west4-a/xxxx-vm-group"
      ~ instances   = [
          - "https://www.googleapis.com/compute/v1/projects/xxxx/zones/europe-west4-a/instances/test-instance",
        ] -> (known after apply)
        name        = "xxxx-vm-group"
        network     = "https://www.googleapis.com/compute/v1/projects/xxxxx/global/networks/xxxx-euw4-ctf-vpc"
        project     = "xxxxx"
        self_link   = "https://www.googleapis.com/compute/v1/projects/xxxxx/zones/europe-west4-a/instanceGroups/xxxx-vm-group"
        size        = 1
        zone        = "europe-west4-a"

        named_port {
            name = "http8000"
            port = 8000
        }
    }
```
Plan: 1 to add, 1 to change, 1 to destroy.

1st time it will deploy all IAC to actual infrastructure , but when there is any change in compute instance code , terraform compute_instance_group configuration is not updated when run the terraform apply

1. `terraform apply`
Here in Plan Section we have 3 resource 1 to add/change/destroy respectively  but when apply and approve the changes it will only apply the 1 add and 1 destroy , unable to perform 1 change action when there is any change in compute instance code,and at that time instance_group_manager unable to update the instances.

Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_compute_instance.default: Destroying... [id=test-instance]
google_compute_instance.default: Still destroying... [id=test-instance, 10s elapsed]
google_compute_instance.default: Still destroying... [id=test-instance, 20s elapsed]
google_compute_instance.default: Destruction complete after 26s
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Creation complete after 16s [id=test-instance]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
### References

* #0000

**Comment by edwardmedia** [comment] 2020-09-23 15:34
@ops18 did you expect below change? If yes, what new value should it be? 

```
      ~ instances   = [
          - "https://www.googleapis.com/compute/v1/projects/xxxx/zones/europe-west4-a/instances/test-instance",
        ] -> (known after apply)
```

**Comment by ops18** [comment] 2020-09-24 05:13
Here the new value is when the same instance when created again

**Comment by edwardmedia** [comment] 2020-09-24 15:23
@ops18 I have tried using your code, and can't repro the issue. The version of your provider is pretty old. Can you try the latest version? If the issue still exist, can you post Terraform debug log?

**Comment by ops18** [comment] 2020-09-28 07:28
can you try with some metadata_startup_script

**Comment by edwardmedia** [comment] 2020-09-28 16:09
@ops18 can you share the debug log when you can repro the issue?

**Comment by ops18** [comment] 2020-09-29 07:13
To Reproduce issue: Change configuration in startup-script and run the plan again and then apply and apply 
   
               Plan with Debug Mode


2020-09-29T06:57:06.318Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [INFO] Instantiating Google Cloud Healthcare client for path https://healthcare.googleapis.com/
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_address.static" references: []
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_instance.web_private_1" references: []
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_health_check.healthcheck" references: []
2020/09/29 06:57:06 [WARN] Provider "registry.terraform.io/-/google" produced an invalid plan for google_compute_instance.web_private_1, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .scheduling: block count in plan (1) disagrees with count in config (0)
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_instance_group.web_private_group" references: []
2020/09/29 06:57:06 [WARN] Provider "registry.terraform.io/-/google" produced an invalid plan for google_compute_instance_group.web_private_group, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .instances: planned value cty.UnknownVal(cty.Set(cty.String)) does not match config value cty.SetVal([]cty.Value{cty.UnknownVal(cty.String)}) nor prior value cty.SetVal([]cty.Value{cty.StringVal("https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1")})
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_backend_service.backend_service" references: []
2020-09-29T06:57:06.387Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] hashing map[balancing_mode:RATE capacity_scaler:1 description: group:https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group max_connections:0 max_connections_per_endpoint:0 max_connections_per_instance:0 max_rate:0 max_rate_per_endpoint:0 max_rate_per_instance:100 max_utilization:0.8]
2020-09-29T06:57:06.388Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] writing description 
2020-09-29T06:57:06.388Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] computed hash value of 3514313238 from projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group-RATE-1.000000--0-100.000000-0-0-100.000000-0-0.000000-
2020-09-29T06:57:06.388Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] hashing map[balancing_mode:RATE capacity_scaler:1 description: group:https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group max_connections:0 max_connections_per_endpoint:0 max_connections_per_instance:0 max_rate:0 max_rate_per_endpoint:0 max_rate_per_instance:100 max_utilization:0.8]
2020-09-29T06:57:06.388Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] writing description 
2020-09-29T06:57:06.388Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] computed hash value of 3514313238 from projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group-RATE-1.000000--0-100.000000-0-0-100.000000-0-0.000000-
2020-09-29T06:57:06.389Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] hashing map[balancing_mode:RATE capacity_scaler:1 description: group:https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group max_connections:0 max_connections_per_endpoint:0 max_connections_per_instance:0 max_rate:0 max_rate_per_endpoint:0 max_rate_per_instance:100 max_utilization:0.8]
2020-09-29T06:57:06.389Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] writing description 
2020-09-29T06:57:06.389Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:57:06 [DEBUG] computed hash value of 3514313238 from projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group-RATE-1.000000--0-100.000000-0-0-100.000000-0-0.000000-
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_url_map.url_map" references: []
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_target_http_proxy.target_http_proxy" references: []
2020/09/29 06:57:06 [DEBUG] ReferenceTransformer: "google_compute_global_forwarding_rule.global_forwarding_rule" references: []
2020-09-29T06:57:06.558Z [DEBUG] plugin: plugin process exited: path=/home/xxxxxx/test-code/new-code/.terraform/plugins/linux_amd64/terraform-provider-google_v3.40.0_x5 pid=30185
2020-09-29T06:57:06.559Z [DEBUG] plugin: plugin exited
2020/09/29 06:57:06 [INFO] backend/local: plan operation completed

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_compute_instance.web_private_1 must be replaced
-/+ resource "google_compute_instance" "web_private_1" {
        allow_stopping_for_update = true
        can_ip_forward            = false
      ~ cpu_platform              = "Intel Skylake" -> (known after apply)
      ~ current_status            = "RUNNING" -> (known after apply)
        deletion_protection       = false
      - enable_display            = false -> null
      ~ guest_accelerator         = [] -> (known after apply)
        hostname                  = "front-end-vm1.web-server"
      ~ id                        = "projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1" -> (known after apply)
      ~ instance_id               = "xxxxxxx1515541722" -> (known after apply)
      ~ label_fingerprint         = "42WmSpBxxxx=" -> (known after apply)
      - labels                    = {} -> null
        machine_type              = "n1-standard-1"
      - metadata                  = {} -> null
      ~ metadata_fingerprint      = "ZAWqq7xxxx=" -> (known after apply)
      ~ metadata_startup_script   = <<~EOT # forces replacement
            #!/bin/bash
            set -e
            echo "*****    Installing Nginx    *****"
            apt update
            apt install -y nginx
            systemctl enable nginx
            systemctl restart nginx
            
            echo "*****   Installation Complteted!!   *****"
          - echo "welcome 2nd change" > /tmp/test
          + echo "welcome 3rd change" > /tmp/test
            echo "Welcome to Google Compute VM Instance deployed using Terraform!!!" > /var/www/html
            
            echo "*****   Startup script completes!!    *****"
        EOT
      + min_cpu_platform          = (known after apply)
	          name                      = "front-end-vm1"
      ~ project                   = "xxxxxx" -> (known after apply)
      - resource_policies         = [] -> null
      ~ self_link                 = "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1" -> (known after apply)
        tags                      = [
            "http-server",
            "https-server",
            "sh-kong-2-1",
        ]
      ~ tags_fingerprint          = "X6uOeXpCJq0=" -> (known after apply)
        zone                      = "europe-west4-a"

      ~ boot_disk {
            auto_delete                = true
          ~ device_name                = "persistent-disk-0" -> (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
            mode                       = "READ_WRITE"
          ~ source                     = "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/disks/front-end-vm1" -> (known after apply)

          ~ initialize_params {
              ~ image  = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-9-stretch-v20200910" -> "debian-cloud/debian-9"
              ~ labels = {} -> (known after apply)
              ~ size   = 10 -> (known after apply)
              ~ type   = "pd-standard" -> (known after apply)
            }
        }

      ~ network_interface {
          ~ name               = "nic0" -> (known after apply)
          ~ network            = "https://www.googleapis.com/compute/v1/projects/xxxxxx/global/networks/xxxxxx-euw4-ctf-vpc" -> "projects/xxxxxx/global/networks/xxxxxx-euw4-ctf-vpc"
            network_ip         = "1xx.xx.xx.x"
          ~ subnetwork         = "https://www.googleapis.com/compute/v1/projects/xxxxxx/regions/europe-west4/subnetworks/xxxxxx-euwest-xxxxxx-control-sub-prim" -> "projects/xxxxxx/regions/europe-west4/subnetworks/xxxxxx-euwest-xxx-control-sub-prim"
          ~ subnetwork_project = "xxxxxx" -> (known after apply)

          ~ access_config {
              ~ nat_ip       = "xx.xx.xx.xxx" -> (known after apply)
			  }
			}
			
			      ~ scheduling {
          ~ automatic_restart   = true -> (known after apply)
          ~ on_host_maintenance = "MIGRATE" -> (known after apply)
          ~ preemptible         = false -> (known after apply)

          + node_affinities {
              + key      = (known after apply)
              + operator = (known after apply)
              + values   = (known after apply)
            }
        }

      ~ service_account {
          ~ email  = "xxxxxxxx-compute@developer.gserviceaccount.com" -> (known after apply)
            scopes = [
                "https://www.googleapis.com/auth/compute.readonly",
                "https://www.googleapis.com/auth/devstorage.read_only",
                "https://www.googleapis.com/auth/userinfo.email",
            ]
        }
    }
  # google_compute_instance_group.web_private_group will be updated in-place
  ~ resource "google_compute_instance_group" "web_private_group" {
        description = "Web servers instance group"
        id          = "projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group"
      ~ instances   = [
2020/09/29 06:58:57 [DEBUG] command: asking for input: "Do you want to perform these actions?"
          - "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1",
        ] -> (known after apply)
        name        = "front-end-vm-group"
        network     = "https://www.googleapis.com/compute/v1/projects/xxxxxx/global/networks/xxxxxx-euw4-ctf-vpc"
        project     = "xxxxxx"
        self_link   = "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group"
        size        = 1
        zone        = "europe-west4-a"

        named_port {
            name = "http"
            port = 80
        }
    }

Plan: 1 to add, 1 to change, 1 to destroy.

 
               Apply with debug mode

2020-09-29T06:59:33.348Z [DEBUG] plugin.terraform-provider-google_v3.40.0_x5: 2020/09/29 06:59:33 [DEBUG] Retry Transport: Returning after 1 attempts
google_compute_instance.web_private_1: Creation complete after 12s [id=projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1]
2020/09/29 06:59:33 [WARN] Provider "registry.terraform.io/-/google" produced an unexpected new value for google_compute_instance.web_private_1, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .description: was null, but now cty.StringVal("")
      - .enable_display: was null, but now cty.False
      - .boot_disk[0].disk_encryption_key_raw: inconsistent values for sensitive attribute
      - .boot_disk[0].initialize_params[0].image: was cty.StringVal("debian-cloud/debian-9"), but now cty.StringVal("https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-9-stretch-v20200910")
      - .network_interface[0].network: was cty.StringVal("projects/xxxxxx/global/networks/xxxxxx-euw4-ctf-vpc"), but now cty.StringVal("https://www.googleapis.com/compute/v1/projects/xxxxxx/global/networks/xxxxxx-euw4-ctf-vpc")
      - .network_interface[0].subnetwork: was cty.StringVal("projects/xxxxxx/regions/europe-west4/subnetworks/xxxxxx-euwest-ctef-control-sub-prim"), but now cty.StringVal("https://www.googleapis.com/compute/v1/projects/xxxxxx/regions/europe-west4/subnetworks/xxxxxx-euwest-ctef-control-sub-prim")
2020/09/29 06:59:33 [DEBUG] After incorporating new values learned so far during apply, google_compute_instance_group.web_private_group change has become NoOp
2020-09-29T06:59:33.365Z [DEBUG] plugin: plugin process exited: path=/home/xxxxxx/test-code/new-code/.terraform/plugins/linux_amd64/terraform-provider-google_v3.40.0_x5 pid=30293
2020-09-29T06:59:33.366Z [DEBUG] plugin: plugin exited

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.


                 2nd apply with debug mode

Terraform will perform the following actions:

  # google_compute_instance_group.web_private_group will be updated in-place
  ~ resource "google_compute_instance_group" "web_private_group" {
        description = "Web servers instance group"
        id          = "projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group"
      ~ instances   = [
          + "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1",
        ]
        name        = "front-end-vm-group"
        network     = "https://www.googleapis.com/compute/v1/projects/xxxxxx/global/networks/xxxxxx-euw4-ctf-vpc"
        project     = "xxxxxx"
        self_link   = "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group"
        size        = 0
        zone        = "europe-west4-a"

        named_port {
            name = "http"
            port = 80
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

2020-09-29T07:00:54.549Z [DEBUG] plugin: plugin process exited: path=/home/shubham/test-code/new-code/.terraform/plugins/linux_amd64/terraform-provider-google_v3.40.0_x5 pid=30366
2020-09-29T07:00:54.549Z [DEBUG] plugin: plugin exited
2020/09/29 07:00:54 [DEBUG] command: asking for input: "Do you want to perform these actions?"
  Enter a value: yes
2020/09/29 07:02:46 [INFO] backend/local: apply calling Apply

google_compute_instance_group.web_private_group: Modifications complete after 1s [id=projects/xxxxxx/zones/europe-west4-a/instanceGroups/front-end-vm-group]
2020/09/29 07:02:48 [WARN] Provider "registry.terraform.io/-/google" produced an unexpected new value for google_compute_instance_group.web_private_group, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .size: was cty.NumberIntVal(0), but now cty.NumberIntVal(1)
2020-09-29T07:02:48.568Z [DEBUG] plugin: plugin process exited: path=/home/shubham/test-code/new-code/.terraform/plugins/linux_amd64/terraform-provider-google_v3.40.0_x5 pid=30389
2020-09-29T07:02:48.569Z [DEBUG] plugin: plugin exited

**Comment by slevenick** [comment] 2020-09-29 23:12
One possible way to resolve this is to add the following block to your `google_compute_instance`:
```
  lifecycle {
    create_before_destroy = true
  }
```

This would require you to change the name of the instance every time you make an update that requires recreation though.

The problem is that Terraform only applies changes to a resource once during a single `terraform apply`. We have to remove the instance group's reference to the instance that is being deleted prior to deleting the instance, but then we cannot add the reference to the new instance after it has been successfully created.

I don't think this is possible to solve from the provider side though.

Heres a similar issue from way back: https://github.com/hashicorp/terraform/issues/10896

**Comment by ops18** [comment] 2020-10-01 08:02
I try with lifecycle block but it is not working for me 

Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_compute_instance.web_private_1: Creating...

Error: Error creating instance: googleapi: Error 409: The resource 'projects/xxxxxx/zones/europe-west4-a/instances/front-end-vm1' already exists, alreadyExists

  on main.tf line 24, in resource "google_compute_instance" "web_private_1":
  24: resource "google_compute_instance" "web_private_1" {


But whatever input you provide i found solution on that part. I used the code like below 

    resource "random_id" "id" {
      byte_length = 5
          keepers = {
            hash-check = "${sha256(file("${path.module}/template/install_nginx.tpl"))}"
      }  
   }

And to change the name of instance i used this resource refer in name of compute instance 

   resource "google_compute_instance" "web_private_1" {
        name  = "${var.app_name}-${random_id.id.hex}"
     }

This solution work for me .

And when ever i change in startup-script it will have a new name to instance and that new name will add to instance group and it work for me .

**Comment by slevenick** [comment] 2020-10-01 21:10
Glad you've got a workaround. I'll close this as there isn't a provider-level solution to this problem

**Closed by slevenick** 2020-10-01 21:10 UTC
Labels: bug
