### ISSUE TITLE
Issue with import statement of google_compute_region_instance_group_manager

### ISSUE THREAD

**Issue by rahulagragoogle** [hashicorp/terraform-provider-google#15121] opened 2023-07-11 09:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.13.7

### Affected Resource(s)

* google_compute_region_instance_group_manager

### Terraform Configuration Files

- metadata:
    dependsOn:
    - cb-server-instance-template
  name: cb-server-instance-group
  properties:
    baseInstanceName: cb-server
    instanceTemplate: $(ref.cb-server-instance-template.selfLink)
    region: us-central1
    targetSize: 3
  type: compute.v1.regionInstanceGroupManager

### Debug Output
Error: project: required field is not set
Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

### Expected Behavior

Import should have succeeded.

### Actual Behavior
Import failed

### Steps to Reproduce

terraform import google_compute_region_instance_group_manager.cb_server_instance_group  cb-server-instance-group
For this to work, we require provider level project name and region.

terraform import google_compute_region_instance_group_manager.cb_server_instance_group  {{project}}/{{region}}/cb-server-instance-group 
This should work fine.
Link :https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_region_instance_group_manager#import

### References

* #0000

**Comment by edwardmedia** [comment] 2023-07-11 13:22
@rahulagragoogle I am not clear what the problem is. Can you share the debug log for the import execution?

**Comment by rahulagragoogle** [comment] 2023-07-11 15:47
```
google_compute_region_instance_group_manager.[RESOURCE_NAME]: Importing from ID "[RESOURCE_NAME]"...

Error: project: required field is not set
```

When we set provider level project info, then the error says,
```
google_compute_region_instance_group_manager.[RESOURCE_NAME]: Importing from ID "[RESOURCE_NAME]"...

Error: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```

When we set the provider level region, import becomes  successful.

The import statement used is:
terraform import google_compute_region_instance_group_manager.[RESOURCE_NAME]  [RESOURCE_NAME]
as given in https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_region_instance_group_manager#import

However, if we use the import statement as:
terraform import google_compute_region_instance_group_manager.[RESOURCE_NAME]  [PROJECT]/[REGION]/[RESOURCE_NAME]
import becomes successful without adding any provider level info.
So, I think we should add PROJECT and REGION also in the import statement.

**Comment by edwardmedia** [comment] 2023-07-11 17:47
@rahulagragoogle `project`, `region` and `zone`, etc. are optional IF you have them in the provider [configuration](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#provider-default-values-configuration). For most gcp resources, they are required. You may see this behavior for other resources. Please review below doc for the details. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#provider-default-values-configuration

Both methods are working depending upon how you config the provider. Closing this issue now.

**Closed by edwardmedia** 2023-07-11 17:47 UTC
Labels: bug
