### ISSUE TITLE
Support user-managed service account for app engine

### ISSUE THREAD

**Issue by edwardsPaul421** [hashicorp/terraform-provider-google#12234] opened 2022-08-03 07:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

By default, when creating app engine, a default service account with roles/editor permission.
Google's best practice is to create a custom service account with minimal permissions, and deploy the app using this service account instead of the default service account.

Google has now added a 'serviceAccount' field to their app engine REST api (Link in references).

### New or Affected Resource(s)

* google_app_engine_flexible_app_version
* google_app_engine_standard_app_version

### Potential Terraform Configuration

```tf
resource "google_app_engine_flexible_app_version" "app_engine" {
   service_account = "<CUSTOM_SERVICE_ACCOUNT_EMAIL>"
}
```

### References

* [serviceAccount as something that can be set via the API](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions#Version.FIELDS.service_account)

**Comment by SarahFrench** [comment] 2022-08-03 15:23
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11813

I'm planning to make a PR for that issue soon, but it's a question of fitting it into my next sprint! If you'd like to have a go, the new feature would require changes in [these files](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/appengine) and these READMEs cover contributions ([magic-modules](https://github.com/GoogleCloudPlatform/magic-modules/#readme), [mmv1](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1#readme))

**Closed by SarahFrench** 2022-08-03 15:23 UTC
Labels: enhancement

**Comment by edwardsPaul421** [comment] 2022-08-07 09:07
> Duplicate of #11813
> 
> I'm planning to make a PR for that issue soon, but it's a question of fitting it into my next sprint! If you'd like to have a go, the new feature would require changes in [these files](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/appengine) and these READMEs cover contributions ([magic-modules](https://github.com/GoogleCloudPlatform/magic-modules/#readme), [mmv1](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1#readme))

I would like if this issue can be solved soon. 
Thank you :)

**Comment by ranjithkumar-glean** [comment] 2022-08-08 16:59
> Duplicate of #11813
> 
> I'm planning to make a PR for that issue soon, but it's a question of fitting it into my next sprint! If you'd like to have a go, the new feature would require changes in [these files](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/appengine) and these READMEs cover contributions ([magic-modules](https://github.com/GoogleCloudPlatform/magic-modules/#readme), [mmv1](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1#readme))

I can take a go at fixing this, Thanks!
