### ISSUE TITLE
Error when using CLOUD_IAM_GROUP as google_sql_user type

### ISSUE THREAD

**Issue by haraldhaas** [hashicorp/terraform-provider-google#17040] opened 2024-01-18 15:41 UTC
The [google_sql_user](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user) resource in the provider document explains the example of using the the type [CLOUD_IAM_GROUP](https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#add-iam-group-db) for [google_sql_user](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user). However, creating this resource always fails with either of the errors that can be seen below.

### Terraform Version
```
Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.12.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Affected Resource(s)
* google_sql_user

### Terraform Configuration Files
```
resource "google_sql_database_instance" "main" {
  name             = "main-instance"
  project          = "<project-id>"
  region           = "europe-west1"
  database_version = "MYSQL_8_0"

  settings {
    tier = "db-f1-micro"

    database_flags {
      name  = "cloudsql_iam_authentication"
      value = "on"
    }
  }
}

resource "google_sql_user" "iam_group_user" {
  name     = "<group@domain.com>"
  project  = "<project-id>"
  instance = google_sql_database_instance.main.name
  type     = "CLOUD_IAM_GROUP"
}
```

### Debug Output
```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_sql_user.iam_group_user, provider
│ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present,
│ but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

```
google_sql_user.iam_group_user: Creating...
╷
│ Error: Error, failure waiting for insertion of group@domain.com into main-instance-3c1f9de9:
│
│
│   with google_sql_user.iam_group_user,
│   on main.tf line 21, in resource "google_sql_user" "iam_group_user":
│   21: resource "google_sql_user" "iam_group_user" {
```

### Expected Behavior

Group should have been added to the database, as per [documentation](https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#add-iam-group-db).

### Actual Behavior

Terraform apply failed.

### Steps to Reproduce

1. `terraform apply`

b/321524487

**Comment by edwardmedia** [comment] 2024-01-18 17:16
@haraldhaas can you share the [debug log](https://developer.hashicorp.com/terraform/internals/debugging)

**Comment by haraldhaas** [comment] 2024-01-18 17:56
Of course, @edwardmedia, please find the debug log in this [gist](https://gist.github.com/haraldhaas/bbd1304c4ddf8021f68dc9bb98a6b799).

I have just realized that also the equivalent gcloud command is broken, hence I assume this is a general issue with the recently introduced feature, that is under preview still. Also see the following [gist](https://gist.github.com/haraldhaas/52892f14d551d83f95e4b5f213a01cc3).

Users, Domains and Project IDs have been redacted.

**Comment by edwardmedia** [comment] 2024-01-20 15:47
@haraldhaas I do see the error returned from the api below. 

```
"error": {
 "kind": "sql#operationErrors",
 "errors": [
  {
   "kind": "sql#operationError",
   "code": "INTERNAL_ERROR"
  }
 ]
},
```

Your config [here](https://github.com/hashicorp/terraform-provider-google/issues/17040#issue-2088554623) is almost identical to the example provided [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user) which is applied in the daily tests. No issue is found. 

I am not sure what happened in your case as the api reveal little. I would suggest to apply a fresh example again to see if you can repro.

**Comment by RonaldGalea** [comment] 2024-01-29 10:59
Just wanted to mention that I got the same error, but happened to me in a more convoluted way. The resource somehow initially became tainted, I couldn't untaint it after. Then I ended up deleting the group from the SQL instance directly - after which is when I got the exact `unexpected new value: Root object was present, but now absent.` error.

Then I took a break for a couple of hours - nobody touched nothing - and then it just worked again...

**Comment by RonaldGalea** [comment] 2024-01-29 15:45
Update: I now know exactly how to reproduce my case. The Google CloudSQL [docs](https://cloud.google.com/sql/docs/mysql/iam-authentication#user_and_service_account_administration) say:

"After you've added the IAM user to the database, you need to grant database privileges manually. Use the MySQL [GRANT](https://dev.mysql.com/doc/refman/5.7/en/grant.html) command to [grant other database privileges](https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#grant-db-privileges)."

(or specifically for [groups](https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#grant-db-priv-to-group))

I haven't seen any way of granting the MySQL DB access (not CloudSQL access) via Terraform, which means I must do it manually. But as soon as I do it manually, Terraform no longer recognises the user group.

Am I missing something perhaps?

**Comment by itspngu** [comment] 2024-03-04 15:16
This definitely is a Terraform provider issue, as the groups' database users are created and shown in `gcloud sql users list` despite an error being thrown. Subsequent attempts to import these database users into tfstate as `google_sql_user` fail with `Error: Cannot import non-existent remote object` - I tried `terraform import google_sql_user.example project-id/instance/example.com/my-group` as well as `terraform import google_sql_user.example project-id/instance/%/my-group` (the latter is how it shows up in `gcloud sql users list` despite the `host` being `example.com` when looking up users via native MySQL tooling).

Is this a possible hint at the underlying problem? Creation works, but subsequent lookup fails, because there's a mismatch in expected hostname?

**Comment by k4leung4** [comment] 2024-03-26 22:23
here to report the same thing

works in gcloud, failed in terraform.

```
 Error: Error, failure waiting for insertion of enforce-oncall-team@chainguard.dev into cr-dev-datastore-e9a6d327: 
│ 
│ 
│   with google_sql_user.cloudsql-group-iam,
│   on test.tf line 1, in resource "google_sql_user" "cloudsql-group-iam":
│    1: resource "google_sql_user" "cloudsql-group-iam" {
```

**Comment by k4leung4** [comment] 2024-03-27 03:00
after successfully creating the user with gcloud, trying to import the user results in this error

```
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "module.datastore-cloudrun.google_sql_user.cloudsql-group-iam", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵
```

```
terraform import 'module.datastore-cloudrun.google_sql_user.cloudsql-group-iam' '[project]/[instance]/test-group@testdomain.com'
```

seems like it is failing to handle the `@` character in the user name

**Comment by ChhajedRonak** [comment] 2024-05-07 10:09
Getting same error while trying to add SQL user of type CLOUD_IAM_GROUP using google_sql_user resource


```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_sql_user.iam_group_user, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

**Comment by mike-marcacci** [comment] 2024-07-02 16:54
I'm seeing this identical behavior using the latest version of terraform and providers:

```
Terraform v1.9.0
on linux_arm64
+ provider registry.terraform.io/hashicorp/google v5.36.0
```

The user _is_ successfully created in Google.

Attempting to import the created user fails with:

```
"module.accounts_service_dev.module.database.google_sql_user.group[\"group:redacted@example.com\"]", the provider detected that no object exists with the given id. Only
│ pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
```

**Comment by nika-pr** [comment] 2024-08-23 13:56
As others have pointed out, the resource is created but it does not get added to the state correctly.

Are there any plans on fixing this? I would rather not have to fall back to individual users or gcloud commands for this.

**Comment by pratikgarg10** [comment] 2024-09-10 17:10
Hi @shuyama1 Could you please close this issue as the fix is submitted in the pull request 
https://github.com/GoogleCloudPlatform/magic-modules/pull/11466

**Comment by shuyama1** [comment] 2024-09-10 21:46
This is likely fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/11466. Closing the issue now. Please reopen this issue or create a new one if this error still occurs in v6.1.0+ providers. Thanks!

**Closed by shuyama1** 2024-09-10 21:46 UTC
Labels: bug, forward/linked, service/sqladmin-infra
