### ISSUE TITLE
`google_compute_subnetwork` - `ipv6_access_type` is always shown as "changed" in `REGIONAL_MANAGED_PROXY`

### ISSUE THREAD

**Issue by Samir-Cit** [hashicorp/terraform-provider-google#16801] opened 2023-12-14 19:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.0
on linux_amd64
* provider registry.terraform.io/hashicorp/google v5.9.0

### Affected Resource(s)

* google_compute_subnetwork

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "proxy_only_subnet" {
  name             = "some-name"
  description      = "some-description"
  ip_cidr_range    = "0.0.0.0/0"
  project          = "PROJECT_ID"
  region           = "REGION"
  network          = "projects/{PROJECT}/global/networks/{NETWORK}"
  purpose          = "REGIONAL_MANAGED_PROXY"
  role             = "ACTIVE"
}
```

### Expected Behavior

After running `terraform apply` in the configuration it should apply successfully.
A second execution of `terraform plan` or `terraform apply` should show **no** changes.

### Actual Behavior

A `terraform plan` or `terraform apply` after the initial execution **always** show an in-place change in the field `ipv6_access_type` from `INTERNAL` to `null`.

```
Terraform will perform the following actions:

  # google_compute_subnetwork.proxy_only_subnet will be updated in-place
  ~ resource "google_compute_subnetwork" "proxy_only_subnet" {
        ...
      - ipv6_access_type           = "INTERNAL" -> null
        ...
        # (13 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. Run `terraform apply`
2. Run `terraform plan`
3. Check the output of the command

### Important Factoids

* This **only** happens when network _purpose_ is set to _REGIONAL_MANAGED_PROXY_.
* It is **not** possible to set the field `ipv6_access_type` to `INTERNAL`. Doing so generates the following error:
```
google_compute_subnetwork.proxy_only_subnet: Creating...
╷
│ Error: Error creating Subnetwork: googleapi: Error 400: Invalid value for field 'resource.ipv6AccessType': 'INTERNAL'. The IPv6 access type of a proxy-only subnet is implicitly set to INTERNAL and is not configurable., invalid
│ 
│   with google_compute_subnetwork.proxy_only_subnet,
│   on main.tf line 1, in resource "google_compute_subnetwork" "proxy_only_subnet":
│    1: resource "google_compute_subnetwork" "proxy_only_subnet" {
```

**Comment by melinath** [comment] 2023-12-14 21:59
I can confirm this permadiff using this example from the docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#example-usage---subnetwork-internal-l7lb

We are generating a test based on that example: TestAccComputeSubnetwork_subnetworkInternalL7lbExample - but it's only generated for the beta provider. BUT it's also been failing since 2023-12-12 with this same permadiff. So this is likely due to an API change.

**Comment by melinath** [comment] 2023-12-14 22:01
I'm going to close this as a duplicate of the test failure for clarity. Thanks for reporting you were experiencing this issue!

Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/16804

**Closed by melinath** 2023-12-14 22:01 UTC
Labels: bug, service/compute-vpc
