### ISSUE TITLE
Add google_storage_transfer_job support for AWS RoleArn for temporary credentials

### ISSUE THREAD

**Issue by lanreogunmola** [hashicorp/terraform-provider-google#10880] opened 2022-01-10 18:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud storage transfer job [module](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job#aws_access_key) does not support using [Role_Arn for AWSS3Data](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#AwsS3Data). The Amazon Resource Name (ARN) of the role to support temporary credentials via AssumeRoleWithWebIdentity. Transfer Service fetches temporary credentials for the session using a AssumeRoleWithWebIdentity call for the provided role using the GoogleServiceAccount for this project.

### New or Affected Resource(s)

* google_storage_transfer_job

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

    aws_s3_data_source {
      bucket_name = var.aws_s3_bucket
      roleArn = var.role_arn
    }
```

### References

* [GCP TransferSpec](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#AwsS3Data)
* [GCP storage_transfer_job](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job#aws_access_key)
* [GCP Federated Identity](https://cloud.google.com/storage-transfer/docs/configure-access?&_ga=2.118057035.-358559383.1636648711#federated-identity)

**Comment by upodroid** [comment] 2022-01-11 22:16
This is duplicate of #10844

**Comment by shuyama1** [comment] 2022-01-18 05:16
Thanks @upodroid! Looks like it is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/10844, and I am closing this issue. @Jseph Thank you for your contribution and would you mind link your PR against https://github.com/hashicorp/terraform-provider-google/issues/10844. Simply modify your PR description would work. Thanks a lot!

**Closed by shuyama1** 2022-01-18 05:16 UTC
Labels: enhancement
