### ISSUE TITLE
google_apigee_envgroup attach environment

### ISSUE THREAD

**Issue by cerasmus-booking** [hashicorp/terraform-provider-google#8776] opened 2021-03-26 14:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The `google_apigee_envgroup` resource provider does not have the ability to attach an environment. It would be helpful to also specify the environments that should be attached to the environment group. 

The workflow would look something like this:

- create resource for the organization: `google_apigee_organization`
- create resources for the environments in the organizations: `google_apigee_environment`
- create resources for the environment groups: `google_apigee_envgroup`
- attach the `env` and `envgroup`

Similar to how you need to specify the `hostnames` on the `google_apigee_envgroup` resource, the same might be done for environments.

https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.envgroups.attachments
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_envgroup

### New or Affected Resource(s)

* google_apigee_envgroup

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_apigee_envgroup" "env_grp" {
  name      = "tf-test%{random_suffix}"
  hostnames = ["abc.foo.com"]
  envs      = ["foo"]
  org_id    = google_apigee_organization.apigee_org.id
}
```

### References

* #8641

**Comment by rileykarson** [comment] 2021-03-29 17:39
Note: this is pairing the environment and envgroup together, possibly through a fine-grained resource like instance <> disk attachment

**Comment by xuchenma** [comment] 2022-08-25 17:54
This seems to be a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8804 and is already live: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_envgroup_attachment

**Closed** 2022-08-25 18:59 UTC
Labels: enhancement, size/m
