### ISSUE TITLE
Adding support for updating resilience_mode field in cloud composer

### ISSUE THREAD

**Issue by Khaledmohamedrefaat** [hashicorp/terraform-provider-google#15040] opened 2023-07-04 09:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Adding support for resilience_mode updates in cloud composer

### New or Affected Resource(s)

google_composer_environment

### References
* #0000

b/291653782

**Comment by Khaledmohamedrefaat** [comment] 2023-07-04 09:03
I wish to work on this item.

**Comment by roaks3** [comment] 2023-07-14 18:48
@Khaledmohamedrefaat is there already an internal ticket for this? If not I will forward per go/terraform-ticket-forwarding

**Comment by PeWu** [comment] 2023-10-10 09:53
This functionality has been implemented. The issue can be closed.

**Comment by melinath** [comment] 2023-11-13 23:03
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/14751

**Closed by melinath** 2023-11-13 23:03 UTC
Labels: enhancement, size/s, forward/linked, service/composer
