### ISSUE TITLE
Enhancements to google_tags_location_tag_binding

### ISSUE THREAD

**Issue by LucaPrete** [hashicorp/terraform-provider-google#14100] opened 2023-03-27 08:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In order to make the resource usable, we'll need the following modifications:

- Change the readme to have a compute-vm example (Cloud Run shouldn't even be supported at the moment)
- Allow users to use project id (and not just number) to refer to compute_vms. Today you can use the project_id but project number is automatically populated by the API, causing drifts in the next terraform plan/apply
- Allow users to use the id of the vm, as opposed to the instance_id

### New or Affected Resource(s)

* google_tags_location_tag_binding

### Potential Terraform Configuration

```tf
resource "google_tags_location_tag_binding" "network_binding" {
  location  = "europe-west1-b"
  parent    = "//compute.googleapis.com/projects/my_project_id/zones/europe-west1-b/instances/my_instance_id"
  tag_value = "tagValues/123456"
}
```

**Comment by LucaPrete** [comment] 2023-03-27 08:27
I'll try to take care of this

**Comment by rileykarson** [comment] 2023-03-27 17:27
I'm leaving this open at "Backlog" rather than closing it so it reaches the service team as part of self-service; otherwise I'd close this as working as intended.

Tags are attached generically to their target resources, and we should avoid customizations in our client. The problems here are in the API:

* For the project id, see https://google.aip.dev/cloud/2510. There's a specific callout of desired behaviour here: "If a service receives a resource name for a resource that the service does not own, it should not perform any translation between project IDs and project numbers for those resource names.
". They should return the user-specified format.
* For the resource name / id, see https://google.aip.dev/122#full-resource-names. The full resource name of a GCE instance is presumably its `name` field, not its `id` field. See the `self_link`, a predecessor to a full resource name: "https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/instances/my-instance"

> Change the readme to have a compute-vm example (Cloud Run shouldn't even be supported at the moment)

We're not going to reference every possible target resource in our examples. What's there is presumably fine.

**Comment by ghabian** [comment] 2023-03-27 22:15
while I agree with the first points, I think providing a zonal resource and a regional resource as examples to a location-scoped binding is .. ok? 

it works out in our favor specifically here because the main zonal resource is a compute VM, and the regional example is already there. 

I know I'll have to give customers a working example of a compute VM tag binding many times if not in the public doc page already. 

my 2c

**Comment by rileykarson** [comment] 2023-03-28 00:19
I read "change" as "replace the current one", whoops! Yeah, having both seems fine.

**Comment by LucaPrete** [comment] 2023-03-30 07:41
Sounds good. I'll then open a PR to ADD the example for compute vm.

-Luca

Il giorno mar 28 mar 2023 alle ore 02:19 Riley Karson <
***@***.***> ha scritto:

**Comment by alexbacchin-asx** [comment] 2023-04-23 12:01
Similar #14210

**Comment by LucaPrete** [comment] 2023-05-02 12:57
Sent [this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/7860)

**Closed** 2023-05-03 18:20 UTC
Labels: enhancement, size/s
