### ISSUE TITLE
Dataproc Metastore Service & IAM

### ISSUE THREAD

**Issue by krishna4ldw** [hashicorp/terraform-provider-google#11664] opened 2022-05-08 01:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Why google dont keep up to date with terraform this is must for CICD
1) Refer to gcloud commands make sure all arguments  are available through terraform  
https://cloud.google.com/sdk/gcloud/reference/metastore/services/create
Eg: [release-channel](https://cloud.google.com/sdk/gcloud/reference/metastore/services/create#--release-channel)
2) Add Data proc metastore IAM binding resource this is not available in terraform
Refer to this link 
https://cloud.google.com/sdk/gcloud/reference/metastore/services/add-iam-policy-binding

### New or Affected Resource(s)
Datproc 
Dataproc metastore

### References
https://cloud.google.com/sdk/gcloud/reference/metastore/services/create
https://cloud.google.com/sdk/gcloud/reference/metastore/services/add-iam-policy-binding
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_metastore_service

* #0000

**Comment by DrFaust92** [comment] 2022-06-25 10:33
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11534 i think

**Closed** 2022-06-27 21:26 UTC
Labels: enhancement, size/s

**Comment by krishna4ldw** [comment] 2022-06-27 21:38
I see changes were merged but who will be updating documentation in terraform 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/data_source_dataproc_metastore_service ? 
Is this not by google ? 
If i need terraform gcp resource details where can i get?

**Comment by megan07** [comment] 2022-06-28 14:45
Sorry for the confusion, @krishna4ldw, this was merged yesterday and will be available in the next release, docs will be updated then as well. Thanks!
