### ISSUE TITLE
Cloud build private pools `google_cloudbuild_worker_pool` not available in google provider

### ISSUE THREAD

**Issue by finlaye** [hashicorp/terraform-provider-google#10041] opened 2021-09-09 10:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.82.0
+ provider registry.terraform.io/hashicorp/google-beta v3.82.0

### Affected Resource(s)

* google_cloudbuild_worker_pool

### Terraform Configuration Files

```tf
resource "google_cloudbuild_worker_pool" "pool" {
  project = var.project_id
  name = var.pool_name
  location = var.pool_location
  worker_config {
    disk_size_gb = 100
    machine_type = "e2-standard-4"
    no_external_ip = true
  }
  network_config {
    peered_network = data.google_compute_network.network.id
  }
}
```

### Debug Output

```
╷
│ Error: Invalid resource type
│ 
│   on main.tf line 21, in resource "google_cloudbuild_worker_pool" "pool":
│   21: resource "google_cloudbuild_worker_pool" "pool" {
│ 
│ The provider hashicorp/google does not support resource type
│ "google_cloudbuild_worker_pool".
╵
ERRO[0002] 1 error occurred:
        * exit status 1

```

### Expected Behavior

The resource is available - private pools have been released and is no longer a beta feature https://cloud.google.com/blog/products/devops-sre/cloud-build-private-pools-offers-cicd-for-private-networks

### Actual Behavior

The resource is unavailable with the following error

```
╷
│ Error: Invalid resource type
│ 
│   on main.tf line 21, in resource "google_cloudbuild_worker_pool" "pool":
│   21: resource "google_cloudbuild_worker_pool" "pool" {
│ 
│ The provider hashicorp/google does not support resource type
│ "google_cloudbuild_worker_pool".
╵
ERRO[0002] 1 error occurred:
        * exit status 1
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment] 2021-09-09 13:49
@finlaye below is what it says in the [warning](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_worker_pool) section of the resource. Let me know if you have trouble in using the beta version. 

> This resource is in beta, and should be used with the terraform-provider-google-beta provider. See Provider Versions for more details on beta resources.

**Comment by finlaye** [comment] 2021-09-09 13:59
Hey - thanks for getting back to me! yes - so when I use the beta version I get the following error:

```
│ Error: Error creating WorkerPool: googleapi: Error 403: project is not allowlisted for this feature, please contact Google Cloud Support at https://cloud.google.com/support-hub
│ 
│   with google_cloudbuild_worker_pool.pool,
│   on main.tf line 21, in resource "google_cloudbuild_worker_pool" "pool":
│   21: resource "google_cloudbuild_worker_pool" "pool" {
│ 
╵
ERRO[0039] 1 error occurred:
        * exit status 1
```

However, if I create a google cloud build private pool via the UI console, it works fine! I don't think you need to be allowlisted for the feature anymore as it is now GA release

**Comment by edwardmedia** [comment] 2021-09-09 18:24
@finlaye The error was from api. You might need to follow the error message to contact Google Cloud Support at https://cloud.google.com/support-hub. Below is what it says in the Terraform resource in note section. There is not much the provider can do about it. Let me know if you still face problems after you contact the support 

> This resource is not currently public, and requires allow-listing of projects prior to use.

**Comment by edwardmedia** [comment] 2021-09-13 19:45
@finlaye is this still an issue?

**Comment by mikouaj** [comment] 2021-09-14 14:28
@edwardmedia the point here is that `google_cloudbuild_worker_pool` should not be beta anymore.
CloudBuild Private pools feature is already generally available as stated in [Cloud Build Release Notes](https://cloud.google.com/build/release-notes#July_27_2021).

Therefore, this resource should be part of stable provider already.
The error provided by @finlaye comes from beta provider that uses beta APIs that should be no longer used.

**Comment by edwardmedia** [comment] 2021-09-14 14:47
@mikouaj from `beta` to `ga`, there is a process. You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) for it.  This is not a bug. Does this make sense?

**Comment by mikouaj** [comment] 2021-09-14 14:58
@edwardmedia yeah, I just found it. This issue is a duplicate of #9684

**Comment by edwardmedia** [comment] 2021-09-14 17:49
@mikouaj closing this issue then. Cheers!

**Closed by edwardmedia** 2021-09-14 17:49 UTC
Labels: bug
