### ISSUE TITLE
What would cause TF/GCP to purge the whole BQ dataset IAM policy on an update?

### ISSUE THREAD

**Issue by mheing-epro** [hashicorp/terraform-provider-google#13823] opened 2023-02-23 18:51 UTC
I'm here because I'm actually not sure whether we have a bug or need a better use. Setup is as follows:

1. We have a bunch of BigQuery datasets.
2. We DO NOT employ `access` on these resources, instead we do `google_bigquery_dataset_iam_member`.

Looks roughly like:
```tf
resource "google_bigquery_dataset" "google_sa360_transfer" {
    dataset_id = "SA360Transfer"
    friendly_name = "SA360Transfer"
    location = "europe-west3"
}

resource "google_bigquery_dataset_iam_member" "google_sa360_transfer_owner_bq" {
    dataset_id = google_bigquery_dataset.google_sa360_transfer.dataset_id
    role = "roles/bigquery.dataOwner"
    member = "serviceAccount:..."
}
# ... and many more like this
```

This has two reasons:
1. Sometime we don't have all users available, or do not known them at the state of creation. This is because of stuff like Google Ads BQ data transfer, Google Ads Data Hub, that need manual (service) activation by authorized users first. They are added to the IAM policy later, by Google or manually.
2. We have a highly modularized TF setup so that additional child modules' permissions don't trash the parent's previous permissions on one resource but instead simply append their IAM policy members.

With a recent upgrade of Terraform v1.3.5 to v1.3.9 & GCP provider v4.41 to v4.53.1, some unwarranted diff appeared on _some_ (!) of the datasets, not all the ones in use:
```
~ resource "google_bigquery_dataset" "google_sa360_transfer" {
     id                              = "projects/xxx/datasets/SA360Transfer"
   + labels                          = (known after apply)
   # (11 unchanged attributes hidden)

   # (4 unchanged blocks hidden)
}
```
`labels`? I've seen new defaults and fields and stuff over time here and there, so no big deal -- what was I wrong.

Essentially, all `google_bigquery_dataset_iam_member` GONE, leaving the Terraform state diverged to the GCP w. r. t. given IAM member resources. I've had the GCP log showing this:
```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {},
    "authenticationInfo": {
      "principalEmail": "deployment@zzz.iam.gserviceaccount.com",
      "serviceAccountKeyName": "//iam.googleapis.com/projects/xxx/serviceAccounts/deployment@zzz.iam.gserviceaccount.com/keys/yyy"
    },
    "requestMetadata": {
      "callerIp": "172.176....",
      "callerSuppliedUserAgent": "Terraform/1.3.9 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/4.53.1,gzip(gfe)",
      "requestAttributes": {},
      "destinationAttributes": {}
    },
    "serviceName": "bigquery.googleapis.com",
    "methodName": "datasetservice.update",
    "authorizationInfo": [
      {
        "resource": "projects/xxx/datasets/SA360Transfer",
        "permission": "bigquery.datasets.update",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "projects/xxx/datasets/SA360Transfer",
    "serviceData": {
      "@type": "type.googleapis.com/google.cloud.bigquery.logging.v1.AuditData",
      "datasetUpdateRequest": {
        "resource": {
          "datasetName": {
            "projectId": "xxx",
            "datasetId": "SA360Transfer"
          },
          "info": {
            "friendlyName": "SA360Transfer"
          },
          "acl": {
            "entries": [
              {
                "role": "READER",
                "specialGroup": "PROJECT_READERS",
                "viewName": {}
              },
              {
                "role": "WRITER",
                "specialGroup": "PROJECT_WRITERS",
                "viewName": {}
              },
              {
                "role": "OWNER",
                "userEmail": "deployment@zzz.iam.gserviceaccount.com",
                "specialGroup": "PROJECT_OWNERS",
                "viewName": {}
              },
              {
                "role": "OWNER",
                "specialGroup": "PROJECT_OWNERS",
                "viewName": {}
              }
            ]
          }
        }
      },
      "datasetUpdateResponse": {
       ...
      }
    }
  },
  "insertId": "-susiwodbudd",
  "resource": {
    "type": "bigquery_resource",
    "labels": {
      "project_id": "xxx"
    }
  },
  "timestamp": "2023-02-23T09:21:07.621501Z",
  "severity": "NOTICE",
  "logName": "projects/xxx/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2023-02-23T09:21:08.307669586Z"
}
```
As you can see, this tiny change on `label` made an update on said BQ dataset and apparently trashed the whole IAM policy with a blank one (see `acl`) with the deployement service user as new owner.

So my questions:
* Is this supposed to happen with that setup? Or is this a bug?
* What can we do to prevent this while maintaining IAM extensibility?
* Is there a better approach?
* Why did the `label` appear out of thin air, and only as a diff on some of the datasets?

First thing that comes to my mind: Ignore all changes on BQ datasets that are unwarranted by GCP/TF, like this new `label`.

**Comment by edwardmedia** [comment] 2023-02-23 23:40
@mheing-epro do you see anywhere [google_bigquery_dataset_iam_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam#google_bigquery_dataset_iam_policy) is used?

**Comment by mheing-epro** [comment] 2023-02-24 09:21
@edwardmedia Nope, as this is documented to be incompatible with `google_bigquery_dataset_iam_member` as far as I see. We exclusively use `google_bigquery_dataset_iam_member` to specify IAM members on BQ datasets.

**Comment by edwardmedia** [comment] 2023-03-08 14:42
I do not think of anything that could cause this @slevenick do you have any idea?

**Comment by slevenick** [comment] 2023-03-08 17:05
I would need to see logs of the run or a config/steps that is able to reproduce the issue. That's definitely not supposed to happen and would be concerning.

**Comment by mheing-epro** [comment] 2023-03-10 14:44
Checking [access entries](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.dataset.Dataset#google_cloud_bigquery_dataset_Dataset_access_entries) by hand looks good.

So a general fix strategy here was to find and refresh the datasets from the remote state.

But then I'm still wondering how the updates did not and _do not_ make the state of the BQ dataset update its `access` field?  I can still see newly deployed datasets showing the same empty access tables despite having despite seeing them in GCP _and_ seeing their respective `google_bigquery_dataset_iam_member` right below in the `tfstate`, like this:

```json
{
  "module": "module.gads_transfer",
  "mode": "managed",
  "type": "google_bigquery_dataset_iam_member",
  "name": "google_sa360_transfer_editor",
  "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "condition": [],
        "dataset_id": "SA360Transfer",
        "etag": "",
        "id": "projects/xxx/datasets/SA360Transfer/roles/bigquery.dataEditor/serviceAccount...",
        "member": "serviceAccount:...",
        "project": "xxx",
        "role": "roles/bigquery.dataEditor"
      },
      "sensitive_attributes": [],
      "private": "...",
      "dependencies": [
        "module.gads_transfer.google_bigquery_dataset.google_sa360_transfer"
      ]
    }
  ]
}
```

By this we can for sure rule out that we did forget to apply these IAM resources, they are there. Just not in the `access` field of the dataset.

I'll try to find anything reproducing this with `TF_LOG=DEBUG` set.

**Comment by mheing-epro** [comment] 2023-03-10 15:19
I can reproduce this easily:

1. Start a `main.tf` like this, `init` and `apply`:

```tf
resource "google_service_account" "dummy_service_account" {
    account_id = "dummy-account"
}

resource "google_service_account" "dummy_service_account2" {
    account_id = "dummy-account2"
}

resource "google_service_account" "dummy_service_account3" {
    account_id = "dummy-account3"
}

provider "google" {
    project     = "some-demo-project"
    region      = "europe-west3"
}

terraform {
    required_providers {
        google = {
            source = "hashicorp/google"
            version = "4.53.1"
        }
    }
}

terraform {
  backend "gcs" {
    bucket  = "some-demo-project-terraform-state"
  }
}
```

2. Append the following to `main.tf` and `apply`:

```tf
resource "google_bigquery_dataset" "dummy_bq_dataset" {
    dataset_id = "DummyDataset"
    friendly_name = "DummyDataset"
    location = "europe-west3"
}

resource "google_bigquery_dataset_iam_member" "dummy_bq_dataset_editor_member" {
    dataset_id = google_bigquery_dataset.dummy_bq_dataset.dataset_id
    role = "roles/bigquery.dataEditor"
    member = "serviceAccount:${google_service_account.dummy_service_account.email}"
}

resource "google_bigquery_dataset_iam_member" "dummy_bq_dataset_viewer_member" {
    dataset_id = google_bigquery_dataset.dummy_bq_dataset.dataset_id
    role = "roles/bigquery.dataViewer"
    member = "serviceAccount:${google_service_account.dummy_service_account2.email}"
}

resource "google_bigquery_dataset_iam_member" "dummy_bq_dataset_owner_member" {
    dataset_id = google_bigquery_dataset.dummy_bq_dataset.dataset_id
    role = "roles/bigquery.dataOwner"
    member = "serviceAccount:${google_service_account.dummy_service_account3.email}"
}
```

Expected (I guess): Both the BQ dataset and the `tfstate` correctly represent matching `access` data.

Actually happening: BQ dataset looks good, the `tfstate` show no signs of these IAM members in `access`.

**Comment by slevenick** [comment] 2023-03-10 19:17
So, this is a little bit expected.

On the first `terraform apply` with the full config present we would expect the BQ dataset in state to not fully match the current values. That's because the BQ dataset is created first and saved to state with the initial values for `access` which correspond to the 4 mostly empty objects that include projectOwners, projectReaders etc.

The BQ IAM resources are created after that, and the dataset doesn't refresh itself at the end of the apply because Terraform thinks the dataset is already up-to-date. The next time you run `terraform refresh` will update state to match the actual full values in `access`.

I'm seeing `terraform plan` not actually refresh the values in state, which is a little unexpected for me but `terraform refresh` does update them

**Comment by slevenick** [comment] 2023-03-10 20:01
I'm going to close this as it's fairly expected and state does update if you run `terraform refresh`

**Closed by slevenick** 2023-03-10 20:01 UTC
Labels: question

**Comment by mheing-epro** [comment] 2023-03-11 11:01
I know that BQ datasets are a little tricky with their double bookkeeping of their IAM policy, so I see the why here.

Then wouldn't it be an idea to potentially think of one of these things here?

1. GCP provider knows implicitly, by hardcoding, that IAM policy resource changes require a refresh of the respective dataset state -- only if it's managed by TF as well, of course.
2. Have a formalism inside of HCL to explicitly request a refresh of the dependency/dataset state after application? I'm currently not aware of such a thing.
3. At least make [the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam) explicit about this? It's just because we have lost IAM policies temporarily because of too much faith in TF/GCP provider handling this.

The reason I'm asking is that the refresh mechanism [sounds discouraged](https://developer.hashicorp.com/terraform/cli/commands/refresh) for regular use and we've gladly never need to use it so far.

Then again, I'm a little hesitant right now to just blindly refresh the whole landscape every time, so our toolchain probably needs some kind of dataset-only refresh, preferably only on changing any related IAM resources.

**Comment by slevenick** [comment] 2023-03-13 15:51
> At least make [the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam) explicit about this? It's just because we have lost IAM policies temporarily because of too much faith in TF/GCP provider handling this.

I'm pretty sure that this behavior did not cause the lost IAM policies. It may show up in state as not having them, but the BQ Dataset itself won't try to modify the `access` field which contains the IAM policies unless you set the access field in the config. The state representation doesn't mean it will try to make the actual GCP values look like the state

**Comment by mheing-epro** [comment] 2023-03-13 16:17
I cannot fully confirm: I just tried changing `friendlyName` of the example above into something else _and again_ lost the IAM policy. **But** our CD pipeline has `--refresh=false` set. Otherweise and by default, this cancels out the said problem since TF/provider would refresh the state first. This is what I can also reproduce to be working then.

I remember the need to have this set in order to avoid some oscillating diff on some resource some time ago.

**Comment by slevenick** [comment] 2023-03-13 16:21
That doesn't quite make sense to me, as Terraform shouldn't try to modify the `access` field if it isn't specified in the config. Are you sure there are no other IAM resources acting on this dataset?

If you can provide a debug log where the dataset is changing the access field I can look into it

**Comment by slevenick** [comment] 2023-03-13 16:22
I just tested locally and can change the friendly_name on the dataset without the IAM members being modified

**Comment by mheing-epro** [comment] 2023-03-13 16:32
Have you tried `apply` vs `plan --refresh=false`+`apply`?

Anyway, find attached (with some minor ID masking):

1. [Output of plan (for changing `friendlyName`)](https://github.com/hashicorp/terraform-provider-google/files/10959487/out_plan_refresh_false.txt)
2. [Output of application](https://github.com/hashicorp/terraform-provider-google/files/10959489/out_apply_plan.txt)
3. [Latest state file](https://github.com/hashicorp/terraform-provider-google/files/10959501/default.tfstate.txt)

**Comment by slevenick** [comment] 2023-03-13 16:43
Ok, specifying --refresh=false during the apply does reproduce it. I still don't think it's an issue.

The `access` field is controlled outside of the `google_bigquery_dataset` resource, so it's expected that the resource needs to refresh it's state representation prior to apply. It would be better if we could not send that value in the HTTP request, but I don't think that's an option, so we need the current API value if haven't set one in the config

Why do you plan & apply with refresh false?

**Comment by slevenick** [comment] 2023-03-13 16:45
> I remember the need to have this set in order to avoid some oscillating diff on some resource some time ago.

I think this is the root problem here. It's expected that Terraform does a refresh at some point in the apply cycle, or else it really isn't tracking the current state of the resources in GCP. I'd track down and fix the issue causing the oscillating diff so you can refresh within the pipeline.

It's fairly common to run a plan, evaluate it and then apply that plan without refreshing at apply-time, but in my understanding refresh is recommended at plan-time

**Comment by mheing-epro** [comment] 2023-03-13 16:51
Ok, thanks for the analysis so far. We will conduct a research of the impact of what the plan will yield when dropping `--refresh=false` and try to leave that away then.
