### ISSUE TITLE
RateLimitExceeded errors when applying several google_bigquery_dataset_iam_member resources

### ISSUE THREAD

**Issue by tminusplus** [hashicorp/terraform-provider-google#19655] opened 2024-09-26 22:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v6.3.0

### Affected Resource(s)

google_bigquery_dataset_iam_member

### Terraform Configuration

```tf
locals {
  wif_ids = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
}

resource "google_bigquery_dataset_iam_member" "test_wif" {
  for_each = {
    for id in local.wif_ids : id => {
      member = "principal://iam.googleapis.com/locations/global/workforcePools/abc-workforce-pool/subject/name-${id}@example.com"
    }
  }

  project    = "test-project-id"
  dataset_id = "test_dataset"
  role       = "roles/bigquery.dataViewer"
  member     = format("iamMember:%s", each.value.member)
}
```

### Debug Output

Terraform output will include rate-limit errors:
```
Error: Error applying IAM policy for Bigquery Dataset test-project-id/test_dataset:  Error creating DatasetAccess: googleapi: Error 403: Exceeded rate limits: too many dataset metadata update operations for this dataset. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas, rateLimitExceeded
```

### Expected Behavior

The provider can gracefully handle rate-limits for `google_bigquery_dataset_iam_member` (it seems specific to this resource).

### Actual Behavior

The provider will apply a single resource successfully, and then fails the rest due to rate limit exceeded errors.

### Steps to reproduce

Terraform apply several `google_biggquery_dataset_iam_member` resources against a single dataset.

b/371085410

**Comment by tminusplus** [comment] 2024-09-26 22:50
Sorry this isn't a rate-limit not being handled right. I did more digging and discovered there was a service account which was deleted, but was still attached to the dataset's IAM policy:
```
2024-09-26T15:43:05.128-0700 [ERROR] vertex "google_bigquery_dataset_iam_member.dataset_read[\"wif-a"]" error: Error applying IAM policy for Bigquery Dataset <PROJECT_ID>/<REDACTED>: Error creating DatasetAccess: googleapi: Error 400: IAM setPolicy failed for Dataset <PROJECT_ID>:<REDACTED>: The member deleted:serviceaccount:<SERVICE_ACCOUNT>?uid=<UID> is of an unknown type. Please set a valid type prefix for the member., invalid
```

Note that this service account has `?uid=<UID>` at the end of it's name. I'm not sure how it got into this state. But this appears to be the root cause.

**Comment by ggtisc** [comment] 2024-10-03 00:57
Confirmed issue!

This looks like an intermittent issue because the 1st time I get the same Error:

`Error: Error applying IAM policy for Bigquery Dataset my-project/bigquery_dataset_19655: Error creating DatasetAccess: googleapi: Error 403: Exceeded rate limits: too many dataset metadata update operations for this dataset. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas`

But it takes a long time, more than 1 hour to process the creation and result in a different error:

`Error: Error applying IAM policy for Bigquery Dataset my-project/bigquery_dataset_19655: Error creating DatasetAccess: googleapi: Error 500: An internal error occurred and the request could not be completed. This is usually caused by a transient issue. Retrying the job with back-off as described in the BigQuery SLA should solve the problem: https://cloud.google.com/bigquery/sla. If the error continues to occur please contact support at https://cloud.google.com/support. Error: 1001262`

This is the used code:

```
locals {
  wif_ids = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
}

resource "google_bigquery_dataset" "bigquery_dataset_19655" {
  dataset_id = "bigquery_dataset_19655"
}

resource "google_bigquery_dataset_iam_member" "bq_ds_iam_member_19655" {
  for_each = {
    for id in local.wif_ids : id => {
      member = "principal://iam.googleapis.com/locations/global/workforcePools/abc-workforce-pool/subject/name-${id}@example.com"
    }
  }

  project    = "my-project"
  dataset_id = google_bigquery_dataset.bigquery_dataset_19655.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = format("iamMember:%s", each.value.member)
}
```

**Comment by wj-chen** [comment] 2024-10-03 22:16
> Sorry this isn't a rate-limit not being handled right. I did more digging and discovered there was a service account which was deleted, but was still attached to the dataset's IAM policy:
> 
> ```
> 2024-09-26T15:43:05.128-0700 [ERROR] vertex "google_bigquery_dataset_iam_member.dataset_read[\"wif-a"]" error: Error applying IAM policy for Bigquery Dataset <PROJECT_ID>/<REDACTED>: Error creating DatasetAccess: googleapi: Error 400: IAM setPolicy failed for Dataset <PROJECT_ID>:<REDACTED>: The member deleted:serviceaccount:<SERVICE_ACCOUNT>?uid=<UID> is of an unknown type. Please set a valid type prefix for the member., invalid
> ```
> 
> Note that this service account has `?uid=<UID>` at the end of it's name. I'm not sure how it got into this state. But this appears to be the root cause.

This should be fixed once https://github.com/GoogleCloudPlatform/magic-modules/pull/11898 is merged and released.

Meanwhile I think the rate limiting is working as intended. Each `google_bigquery_dataset_iam_member` update sends one API request to update dataset access. To bulk update, consider using other [`google_bigquery_dataset_iam`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam) resources, or [`google_bigquery_dataset.access`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset#access).

**Comment by wj-chen** [comment] 2024-10-10 20:35
Requesting @rileykarson the current terraform-team-oncall to close this issue as the rate limiting is working as intended.

**Closed** 2024-10-10 21:05 UTC
Labels: bug, forward/linked, service/bigquery
