### ISSUE TITLE
Stateful MIG with 2 instance is created setting target_size=1 in google_compute_instance_group_manager

### ISSUE THREAD

**Issue by pbonito** [hashicorp/terraform-provider-google#15911] opened 2023-09-20 09:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.77.0
+ provider registry.terraform.io/hashicorp/google-beta v4.77.0

### Affected Resource(s)

* google_compute_instance_group_manager
* google_compute_per_instance_config

### Terraform Configuration Files

```tf
data "google_compute_image" "my_image" {
  family  = "debian-11"
  project = "debian-cloud"
}

resource "google_compute_instance_template" "igm-basic-zonal" {
  region =  "europe-west2"
  name           = "my-template-zonal"
  machine_type   = "e2-medium"
  can_ip_forward = false
  tags           = ["foo", "bar"]

  disk {
    source_image = data.google_compute_image.my_image.self_link
    auto_delete  = true
    boot         = true
  }

  network_interface {
    network = "default"
  }

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
}


resource "google_compute_instance_group_manager" "igm-no-tp" {
  description = "Terraform test instance group manager"
  name        = "my-igm"

  version {
    name              = "prod"
    instance_template = google_compute_instance_template.igm-basic-zonal.self_link
  }

  base_instance_name = "igm-no-tp"
  zone               = "europe-west2-a"
  target_size        = 1
}

resource "google_compute_disk" "default" {
  name  = "my-disk-name"
  type  = "pd-ssd"
  zone  = google_compute_instance_group_manager.igm-no-tp.zone
  image = "debian-11-bullseye-v20220719"
  physical_block_size_bytes = 4096
}

resource "google_compute_per_instance_config" "with_disk" {
  zone = google_compute_instance_group_manager.igm-no-tp.zone
  instance_group_manager = google_compute_instance_group_manager.igm-no-tp.name
  name = "instance-1"
  preserved_state {
    metadata = {
      foo = "bar"
      // Adding a reference to the instance template used causes the stateful instance to update
      // if the instance template changes. Otherwise there is no explicit dependency and template
      // changes may not occur on the stateful instance
      instance_template = google_compute_instance_template.igm-basic-zonal.self_link
    }

    disk {
      device_name = "my-stateful-disk"
      source      = google_compute_disk.default.id
      mode        = "READ_ONLY"
    }
  }
}
```

### Expected Behavior

Mig with one instance and stateful config should be created,

### Actual Behavior

Created MIG with 2 instance, one named instance-1 with stateful disk and metadata, another named igm-no-tp-nhrj with no stateful configuration.
Note: changing num of instance manually in console fixes the problem

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment] 2023-09-20 15:18
I can repro this. This behavior is controlled by the api. Reaching out to the api team to see if this is expected.  

b/301253498

**Comment by pasquale-bonito-db** [comment] 2023-10-04 14:22
Hi any progress on this. Behaviour is quite unpredictable.

**Comment by edwardmedia** [comment] 2023-10-04 16:18
@pbonito the api team has responded that creating two instances is the intended behavior, though I am not super clear why. It is controlled by the api.  What do you mean by below? 

```
Behaviour is quite unpredictable.
```

Keep in mind the provider does not have much control over it.

**Comment by pbonito** [comment] 2023-10-05 10:36
@edwardmedia  I don't think that create 2 instance is the expected behaviour when target_size        = 1. 
In fact updating some parameter (i.e. a metadata value) and executing the plan again it will set instance back to 1 deleting the extra instance.

**Comment by pbonito** [comment] 2023-10-05 12:12
@edwardmedia  This command add only one instance
 gcloud beta compute instance-groups managed create test-mig --template my-template-zonal --size 1 --instance-redistribution-type NONE --stateful-internal-ip enabled

**Comment by an-wlu** [comment] 2023-10-06 15:20
@pbonito 

Hi Pasquale,

This works as expected: 
1. the instance group manager is created with target_size 1 which creates a group with an instance (the name of this instance will be igm-no-tp-XXXX - where XXX is some suffix)
It is this part:
```resource "google_compute_instance_group_manager" "igm-no-tp" {
  description = "Terraform test instance group manager"
[...]  
  target_size        = 1
}
```
2.  The following command creates another instance with disk and name "instance-1". This instance is added to the MIG "igm-no-tp" (so the size after the operation is 2): 

```
resource "google_compute_per_instance_config" "with_disk" {
  zone = google_compute_instance_group_manager.igm-no-tp.zone
  instance_group_manager = google_compute_instance_group_manager.igm-no-tp.name
  name = "instance-1"
 [...]
}
```

If you do not need the instance created automatically by MIG ("igm-no-tp-XXXX"), please try to set target_size to 0.

**Comment by pbonito** [comment] 2023-10-06 16:48
Hi @an-wlu 
" after the operation is 2" but stage would have target_size=1 and rerunning same plan l delete one instance. Not sure target_size = 0 would help here.

**Comment by pbonito** [comment] 2023-10-07 08:09
Hi @an-wlu , I tested following your suggestion and it seems to work. 
I set target-size = 0 than associated  multiple instance config to MIG and after that adjusted target-size to the number of instance created.Running apply once again will adjust the state but won't impact any resource.

**Comment by edwardmedia** [comment] 2023-10-17 13:51
@pbonito closing this now. Feel free to reopen if you still see an issue

**Closed by edwardmedia** 2023-10-17 13:51 UTC
Labels: bug, upstream
