### ISSUE TITLE
Support Anthos as a deployment platform for Cloud Run

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/terraform-provider-google#8085] opened 2020-12-26 02:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

As I understand it, there are [3 main platforms](https://cloud.google.com/anthos/run#resources-and-integrations) for Cloud Run. Those are fully managed, Anthos on GKE, and Anthos on VMWare. In the cloud console, this is transparent to the user. The Cloud Run reosurces in the provider currently only support the fully-managed platform. Issue #5054 was previously asking for this, and the request was not well understood - it is closed and locked.

I have not been able to find any reference in the REST API for using Anthos on GKE, etc. I'm assuming the service endpoint needs to point to the Anthos cluster.

For reference, the `gcloud` commands look like this for Anthos on GKE - also providing an experience similar to the fully managed solution:
```sh
gcloud run services list --project my-project-8832434 --platform gke --cluster=cluster-1 --cluster-location=us-central1-c
```

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
resource "google_cloud_run_service" "managed" {
  name     = "test-managed"
  location = "us-central1"

  metadata {
    namespace = "my-project-8832434"
  }

  platform {
    type = "FULLY_MANAGED"
  }

  template {}
}

resource "google_cloud_run_service" "anthos" {
  name = "test-anthos"

  metadata {
    namespace = "default"
  }

  platform {
    type             = "GKE"
    cluster          = "cluster1"
    cluster_location = "us-central1-c"
  }

  template {}
}
```

### References

* #5054

**Comment by upodroid** [comment] 2020-12-30 15:01
This is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8077

**Comment by rileykarson** [comment] 2021-01-06 19:10
We'll likely detail how to use the `kubernetes_manifest` resource to provision this instead: https://github.com/hashicorp/terraform-provider-google/issues/8127

**Closed by rileykarson** 2021-01-06 19:10 UTC
Labels: enhancement
