### ISSUE TITLE
vpcAccessConnector functionality missing from app_engine_standard_app_version resource

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [hashicorp/terraform-provider-google#7088] opened 2020-08-24 17:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The VPC Connector field is missing, `vpcAccessConnector` - https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions

### New or Affected Resource(s)

* app_engine_standard_app_version

https://www.terraform.io/docs/providers/google/r/app_engine_standard_app_version.html

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_app_engine_standard_app_version" "vpc_connected" {
  provider = google-beta

  version_id = "1"
  service     = "vpc_connected_app"
  runtime    = "nodejs10"

  deployment {
    zip {
      source_url = "https://storage.googleapis.com/${google_storage_bucket.bucket.name}/${google_storage_bucket_object.object.name}"
    }
  }

  vpc_access_connector {
    name = "projects/connector/locations/europe-west3/connectors/vpcconn"
  }

}
```

### References

* #0000

https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions
https://www.terraform.io/docs/providers/google/r/app_engine_standard_app_version.html

**Comment by danawillow** [comment] 2020-08-24 17:52
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/4988, should appear in next week's release.

**Closed** 2020-08-29 01:00 UTC
Labels: enhancement
