### ISSUE TITLE
Add option for deleting default VPC on enabling compute API

### ISSUE THREAD

**Issue by dancmeyers** [hashicorp/terraform-provider-google#4196] opened 2019-08-09 13:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

This is similar to https://github.com/terraform-providers/terraform-provider-google/issues/1312, except it is not when we are creating the _Project_ that the unwanted default VPC is appearing, it is when we are enabling the Compute API. Ideally we want to be able to specify our own VPC and configuration and not have the default one created/have it deleted before the enabling of the compute API returns. This is because, much like the submitter of the original ticket, we only make use of a small number of regions and don't even want to bother creating subnets in the others.

### New or Affected Resource(s)

google_project_service.enable_compute_api

### Potential Terraform Configuration

```tf
resource "google_project" "project" {
  name                = "Project Name"
  project_id          = "project-name-${random_id.project.hex}"
  folder_id           = var.folder_id
  billing_account     = var.billing_account_id
  auto_create_network = false
}

resource "google_project_service" "enable_compute_api" {
  project = google_project.project.project_id
  service = "compute.googleapis.com"
  auto_create_network = false
}

resource "google_compute_network" "vpc" {
  project                 = google_project.project.project_id
  name                    = "non-default-vpc"
  ... etc
```

### References

https://github.com/terraform-providers/terraform-provider-google/issues/1312

**Comment by upodroid** [comment] 2020-08-11 22:39
@danawillow we can close this issue out. 

You can achieve this by setting the organization constraint `constraints/compute.skipDefaultNetworkCreation`  https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints . 

They can be set via this resource https://www.terraform.io/docs/providers/google/r/google_organization_policy.html.

**Comment by thiagonache** [comment] 2020-10-08 21:33
This is already handled by this https://github.com/hashicorp/terraform-provider-google/pull/1316https://github.com/hashicorp/terraform-provider-google/pull/1316, isn't it?

**Comment by upodroid** [comment] 2020-10-08 21:40
Not quite. The VPC is created when the Compute Engine API is enabled. You can stop this by setting the constraint I mentioned earlier.

I would go a step further and consider removing #1316 from the provider in the next major release.

**Comment by thiagonache** [comment] 2020-10-08 21:52
but we need to support places that do not use Org Policy. I read someone google.com doesn't, so you could not apply such behavior in google.com Org.

**Comment by upodroid** [comment] 2020-10-08 21:56
You shouldn't be using Google Cloud projects that don't belong to an organization as your missing alot of powerful features.

You apply that policy to the organization and it applies to every project that is part of it.

**Comment by thiagonache** [comment] 2020-10-08 22:00
You didn't get what I meant, sorry. English is my second language, so it is not very good. 
What I mean is that independently of best practices, terraform shouldn't force any behavior. You should be able to deploy whenever you want.
I understand best practices and I've implemented the entire enterprise best practices document from Google. So, don't take me wrong, you don't need to tell me that.

**Comment by thiagonache** [comment] 2020-10-08 22:02
but now I see that what you're saying is correct and it is different from what is on the PR I mentioned.

**Comment by upodroid** [comment] 2020-10-08 22:16
I think terraform should be opinionated. 

2 years ago, #1316 was a valid way of doing it but now we have constraints so we should remove it now in favour of using the constraint.

**Comment by thiagonache** [comment] 2020-10-08 22:22
I'm happy with agreeing to disagree. Maybe when I got more mature I'll change my mind but for now, I don't see terraform being opinionated on anything existing.  Thank you for making me think about it.

**Comment by danawillow** [comment] 2020-10-08 22:26
I think supporting users who choose not to use organizations is a completely valid thing to do. Not everyone uses GCP in the exact same way, and especially if people are just starting out and experimenting, it's better to meet people where they are (while also guiding them to best practices).

**Comment by upodroid** [comment] 2020-10-08 22:38
I can submit a doc change to the project resource that recommends the constraint instead of using the auto_create_networks field.

**Comment by dancmeyers** [comment] 2020-10-09 09:12
Some context, as I'm OP - We are part of an Org structure, but I am not an Org Admin. The BBC is a large org, with some top level enforcement of settings, but different teams within the org having their own projects and operating in different ways according to their needs.

The main reason for my team wanting to prevent this behaviour is that we are making use of shared VPCs for cross-project communication, and will only _ever_ want to join projects to the relevant (custom) shared VPC from a host project. But we are one of the teams doing the most development in GCP at current. Most other teams within the Org only have one or two projects, and are making assumptions about the default VPC being automatically created.

As such, I am highly unlikely to be able to convince the Org admins to set `constraints/compute.skipDefaultNetworkCreation` on the entire Org, due to the number of other teams who are assuming the opposite. Each team gets their own folder within the Org, so if this constraint can be set at the folder level I should be able to get _that_ through with some prodding, but it's not clear to me from the docs whether that is possible or not.

**Comment by thiagonache** [comment] 2020-10-09 09:52
You need to have admin permissions at org level but you can apply at folder level. I’m not sure if will be able to have org admin at folder level only at some point but you can ask the admins to set the policy on your folder.

**Comment by upodroid** [comment] 2020-10-09 10:06
Going back to the original issue, it already been fixed for some time. https://github.com/hashicorp/terraform-provider-google/blob/be1e66cfdd7ab36dd0b01b37024378204f84b9ab/google/resource_google_project.go#L179 . The project resource enables the Compute Engine API and deletes the default network. That being said, you need to ensure that auto_create_networks is set to true before the project is created. It has no effect if you set it to true after it has been created.

You can set constraints on folders and projects.  https://cloud.google.com/resource-manager/docs/organization-policy/using-constraints#set_up_enforcement_on_the_organization_resource

**Comment by danawillow** [comment] 2020-10-09 16:44
@upodroid this issue is for doing it _when the compute API is enabled_, not when the project is created (the initial poster specifically calls this out). I'm not sure why you're arguing that the issue is not valid to keep open (especially since it's in our Backlog milestone, which is effectively our "we want to keep this open for discussion purposes" milestone), and I would encourage you to focus your energy elsewhere.

**Comment by upodroid** [comment] 2020-10-09 17:31
I misread the issue.

**Closed** 2023-04-24 17:17 UTC
Labels: enhancement, size/m
