### ISSUE TITLE
google_secret_manager_secret - changing replication setting "automatic = true"  to  auto {}    destroy the secret

### ISSUE THREAD

**Issue by alexku7** [hashicorp/terraform-provider-google#15926] opened 2023-09-21 14:08 UTC
The setting  is deprecated 
`  replication {
    automatic = true
  }`

But changing that to the recommended replacement replaces the secret which leads to loss of all secret version.
` replication {
    auto {}
  }`
  
  
  How can we switch from a deprecated setting to recomnded without deleting the secret which could be critical issue for many companies?

**Comment by edwardmedia** [comment] 2023-09-21 14:58
b/301431126

**Comment by olaf-otto** [comment] 2023-09-23 08:41
I am also affected by this issue. I have existing secret and changed the configuration as state above, resulting in terraform attempting creation of the existing secrets, which naturally failed:

`Error: Error creating Secret: googleapi: Error 409: Secret [projects/..../secrets/...] already exists.`

`terraform plan` yielded the following for said secret. Note that the plan is aware the secret exist, but attempts to recreate it instead of an in-place update. Perhaps this is an issue specific to the `google_secret_manager_secret `resource.

```
 # module.gcp_cloudrun_grafana.google_secret_manager_secret.<...> must be replaced
+/- resource "google_secret_manager_secret" "..." {
      - annotations     = {} -> null
      ~ create_time     = "2023-06-05T23:24:36.554261Z" -> (known after apply)
      + expire_time     = (known after apply)
      ~ id              = "projects/.../secrets/..." -> (known after apply)
      - labels          = {} -> null
      ~ name            = "projects/.../secrets/..." -> (known after apply)
      - version_aliases = {} -> null
        # (2 unchanged attributes hidden)

      ~ replication {
          - automatic = true -> null

          + auto {
            }
        }
    }
```


Any advise on an upgrade path would be appreciated.

**Comment by olaf-otto** [comment] 2023-09-23 20:21
IMO this is the same behavior fixed in #13770, thus we expect an in-place upgrade here (at most), but get a replacement.

My current workaround:

 - find all secrets (assuming all are updated) via `terraform state list | grep \.google_secret_manager_secret\.   `
 - mark secret as tainted `via terraform taint <secret>`
 - Delete secrets from GCP
 - Run `terraform apply`

Not exactly an option in production...

**Comment by toVersus** [comment] 2023-09-24 08:48
This issue is duplicate of the issue https://github.com/hashicorp/terraform-provider-google/issues/15885 and already fixed by https://github.com/hashicorp/terraform-provider-google/pull/15922. We're waiting for the next minor release (4.84) that includes this fix. In terms of past release cycles, I think it will be released within a few days.

See https://github.com/hashicorp/terraform-provider-google/issues/15885#issuecomment-1728299859:
> Targeting the 4.84 release.

**Comment by toVersus** [comment] 2023-09-26 09:48
FYI: [v4.84.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.84.0) has just been released.

**Closed** 2023-09-26 09:57 UTC
Labels: bug, forward/linked, service/secretmanager
