### ISSUE TITLE
Add support for CMEK in Composer

### ISSUE THREAD

**Issue by onklbtgch** [hashicorp/terraform-provider-google#8618] opened 2021-03-05 13:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

CMEK support in Cloud Composer has recently matured to GA [1][2].

### New or Affected Resource(s)

* data.google_composer_environment
* resource.google_composer_environment

### Potential Terraform Configuration

```tf
resource "google_composer_environment" "test" {
  name   = "mycomposer"
  region = "us-central1"
  config {
    node_count = 4

    node_config {
      zone         = "us-central1-a"
      machine_type = "e2-medium"

      network    = google_compute_network.test.id
      subnetwork = google_compute_subnetwork.test.id

      service_account = google_service_account.test.name
    }

    encryption {
      kms_key_name = "projects/[PROJECT_ID]/locations/[REGION]/keyRings/[KEYRING_NAME]/cryptoKeys/[KEY_NAME]"
    }
  }
}
```

### References

1. https://cloud.google.com/composer/docs/cmek
2. https://cloud.google.com/sdk/gcloud/reference/composer/environments/create#--kms-key

**Comment by upodroid** [comment] 2021-03-05 22:01
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/7996

https://github.com/GoogleCloudPlatform/magic-modules/pull/4310

Also this will be available in v3.59 of the provider.

**Closed** 2021-03-08 06:03 UTC
Labels: enhancement
