### ISSUE TITLE
Location must be a required property for cloud run iam resources

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-provider-google#16885] opened 2024-01-02 17:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Describe the problem
Creating a IamBinding with no location specified leads to this cryptic error:

```
google_cloud_run_service_iam_binding.zL7SSH9N3: Creating...
╷
│ Error: Error retrieving IAM policy for cloudrun service "v1/projects/x/locations//services/certifier": Get "https://-run.googleapis.com/v1/projects/x/locations//services/certifier:getIamPolicy?alt=json": dial tcp: lookup -run.googleapis.com: no such host
│ 
│   with google_cloud_run_service_iam_binding.zL7SSH9N3,
│   on stack.tf.json line 259, in resource.google_cloud_run_service_iam_binding.zL7SSH9N3:
│  259:       }
│ 
╵
```

The issue is the default base url for cloud run has a template property `{{location}}` so if you don't specify the location requests go to a bogus url as above.  For the CloudRunServiceIamBinding etc resources, `location` isn't required but this will not work otherwise.

The cloud run service resource itself makes location a mandatory parameter, so I believe this is an oversight.

**Comment by andrewbaxter** [comment] 2024-03-02 12:48
This is specifically about the resources, like https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service_iam#google_cloud_run_service_iam_binding

The documentation does say `(Required)` but the json schema dump shows this:
```
        "google_cloud_run_service_iam_binding": {
          "version": 0,
          "block": {
            "attributes": {
...
              "location": {
                "type": "string",
                "description_kind": "plain",
                "optional": true,
                "computed": true
              },
```

I don't see source code for these resources, are they generated? Maybe this is an issue with google API metadata or the generation code.

FWIW though the datasource also shows location is optional
```
        "google_cloud_run_service_iam_policy": {
          "version": 0,
          "block": {
            "attributes": {
...
              "location": {
                "type": "string",
                "description_kind": "plain",
                "optional": true,
                "computed": true
              },
```

**Comment by ggtisc** [comment] 2024-03-06 23:31
@andrewbaxter Could you please share the link of these json schemas to confirm if it is an official source?

The scenario was replicated with the next code without specifying a location with the next code:

provider "google" {
  #your configuration here
}

resource "google_cloud_run_service" "my_cloud_run_service" {
  name     = "my-cloud-run-service"
  location = "us-central1"

  template {
    spec {
      containers {
        image = "hashicorp/http-echo"
        args  = ["-text='Hello, World!'"]
      }
    }
  }
}

resource "google_cloud_run_service_iam_binding" "binding" {
  service   = google_cloud_run_service.my_cloud_run_service.name
  role      = "roles/run.invoker"
  members = [
    "allUsers"
  ]
}

**Comment by andrewbaxter** [comment] 2024-03-07 10:51
Ah thanks, so you were able to replicate it then?

The schema is the schema generated by `terraform providers schema -json` in a project with the gcp project installed, i.e. from the provider code itself.

**Comment by ggtisc** [comment] 2024-03-08 15:47
The `location` argument appears as optional in a project with the gcp provider installed, while in the IO appears as required: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/cloud_run_service_iam_policy

**Comment by andrewbaxter** [comment] 2024-03-08 16:05
Ah sorry, I meant to respond earlier.

I'm not sure what IO means here, but basically I think this is a bug because per the google docs that parameter is required and gcp gives an error if it isn't provided.  I'd say it's a low priority quality of life bug.  It doesn't block anything since the solution is simply to provide a location, but it can cause delays when trying to deploy.

**Comment by roaks3** [comment] 2024-03-12 19:44
Ok, so a few items here:
- The documentation is incorrect about the location field being required, and that issue is tracked with https://github.com/hashicorp/terraform-provider-google/issues/15909
- Having location optional appears to be intended behavior, where many resource ids include the location, so it doesn't need to be specified again. See https://github.com/hashicorp/terraform-provider-google/issues/12989 as an example. In this case, you may be able to use `google_cloud_run_service.my_cloud_run_service.id` and no `location`.

Since IAM resources are all auto-generated using the same template, I think it is unlikely we would change the behavior of `location` here, even if it is technically required in some cases. For that reason, I'm going to mark this as a combination of Won't Fix and Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/15909.

Please let us know if this doesn't fully address the issue.

**Closed by roaks3** 2024-03-12 19:44 UTC
Labels: bug, service/run, forward/review

**Comment by zli82016** [comment] 2025-04-03 20:54
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10527
