### ISSUE TITLE
Field notificationConfig is missing on resource google_storage_transfer_job

### ISSUE THREAD

**Issue by SamuelNeves** [hashicorp/terraform-provider-google#10109] opened 2021-09-20 18:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The Storage Transfer Job API supports the field notificationConfig  that add the feature to transfer job publish the result of the operation in a topic at the end of the Job. With that is possible to chain another events to be executer after the storage transfer is complete

### New or Affected Resource(s)

* google_storage_transfer_job

### Potential Terraform Configuration

```tf
resource "google_storage_transfer_job" "sample" {
...
  notification_config {
          pubsub_topic="pubsubtopic"
          event_types=["TRANSFER_OPERATION_SUCCESS"]
          payload_format="JSON"
}
}
```

### References

* https://cloud.google.com/storage-transfer/docs/reference/rest/v1/NotificationConfig
* https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/create
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job

**Comment by SamuelNeves** [comment] 2021-09-24 15:00
While this enhancement is not developed I am using a curl in a local exec using the following strucutre:

`    curl  -XPATCH -H "Authorization: Bearer $(gcloud auth application-default print-access-token)"  -H "Content-type: application/json" -d '{"transferJob":{"notificationConfig":{"eventTypes":["TRANSFER_OPERATION_SUCCESS"],"pubsubTopic":"'${TOPIC_ID}'","payloadFormat":"JSON"}},"projectId":"'${PROJECT_ID}'"}' "https://storagetransfer.googleapis.com/v1/${TRANSFER_NAME}"
`

**Comment by c2thorn** [comment] 2022-09-15 18:41
closing as this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7775

**Closed by c2thorn** 2022-09-15 18:41 UTC
Labels: enhancement, size/s
