### ISSUE TITLE
Add support for ingress and egress rules of VPC Service Controls

### ISSUE THREAD

**Issue by sho-abe** [hashicorp/terraform-provider-google#8482] opened 2021-02-17 09:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We can now set [ingress and egress rules](https://cloud.google.com/vpc-service-controls/docs/ingress-egress-rules) for service perimeter in VPC Service controls. I would like Terraform to support this setting as well.

### New or Affected Resource(s)

* google_access_context_manager_service_perimeter
* google_access_context_manager_service_perimeters

### Potential Terraform Configuration

```tf
resource "google_access_context_manager_access_policy" "access-policy" {
  parent = "organizations/123456789"
  title  = "my policy"
}

resource "google_access_context_manager_service_perimeter" "sample" {
  parent = "accessPolicies/${google_access_context_manager_access_policy.access-policy.name}"
  name   = "accessPolicies/${google_access_context_manager_access_policy.access-policy.name}/servicePerimeters/restrict_storage"
  title  = "restrict_storage"
  status {
    restricted_services = ["storage.googleapis.com"]
    
    # Egress rule
    egress_policy {
      egress_from {
        identity_type = "ANY_SERVICE_ACCOUNT"
      }
      egress_to {
        resources = [
          "projects/project"
        ]
        operation {
          service_name = "storage.googleapis.com"
          method_selector {
            method = "*"
          }
        }
      }
    }
  }
}
```

### References

* https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters#ingresspolicy
* https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters#egresspolicy

**Comment by rileykarson** [comment] 2021-02-22 18:35
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8412

**Closed by rileykarson** 2021-02-22 18:35 UTC
Labels: enhancement
