### ISSUE TITLE
google_storage_transfer_job does not allow to configure name

### ISSUE THREAD

**Issue by IchordeDionysos** [hashicorp/terraform-provider-google#12878] opened 2022-10-26 07:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.3

### Affected Resource(s)

* google_storage_transfer_job

### Terraform Configuration Files

```tf

resource "google_storage_transfer_job" "content_asset_mirroring" {
  description = "This is a description."
  name        = "this-is-a-custom-name" # The resource does not allow me to set this contrary to the API, which would allow me to do it.

  transfer_spec {
    object_conditions {
      max_time_elapsed_since_last_modification = "86400s" # 1 day
    }
    transfer_options {
      overwrite_when = "DIFFERENT"
    }
    gcs_data_source {
      bucket_name = google_storage_bucket.source.name
    }
    gcs_data_sink {
      bucket_name = data.google_storage_bucket.sink.name
    }
  }

  schedule {
    schedule_start_date {
      year  = 2022
      month = 10
      day   = 1
    }
    start_time_of_day {
      hours   = 0
      minutes = 0
      seconds = 0
      nanos   = 0
    }
    repeat_interval = "21600s" # every 6 hours
  }
}
```

### Expected Behavior

The name can be configured properly.

### Actual Behavior

I get the following error:
```
Error: Value for unconfigurable attribute

  with google_storage_transfer_job.content_asset_mirroring,
  on cloud_storage.tf line 23, in resource "google_storage_transfer_job" "content_asset_mirroring":
  23:   name        = "transfer-conent-assets-to-prod"

Can't configure a value for "name": its value will be decided automatically
based on the result of applying this configuration.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

No

### Workaround

Create the transfer job in UI with a custom name and import it into Terraform.

**Comment by edwardmedia** [comment] 2022-10-27 15:36
@IchordeDionysos this is by design. The `name` is listed as exported in the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job#name)

And the the error you received seems clear

```
Can't configure a value for "name": its value will be decided automatically
based on the result of applying this configuration.
```

Does this make sense?

**Comment by edwardmedia** [comment] 2022-10-31 19:51
Closing this as it is by design

**Closed by edwardmedia** 2022-10-31 19:51 UTC
Labels: bug, waiting-response
