### ISSUE TITLE
adding, removing env blocks make diffs for other env blocks on google_cloud_run_v2_service and google_cloud_run_v2_job resources

### ISSUE THREAD

**Issue by dullest** [hashicorp/terraform-provider-google#17607] opened 2024-03-17 14:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

v1.6.0

### Affected Resource(s)

- google_cloud_run_v2_service
- google_cloud_run_v2_job

### Terraform Configuration

```tf
data "google_project" "project" {
}

locals {
  env_vars = [
    {
      name  = "FOO1"
      value = "bar1"
    },
    {
      name  = "FOO2"
      value = "bar2"
    },
    {
      name  = "FOO3"
      value = "bar3"
    },
    {
      name  = "FOO4"
      value = "bar4"
    },
  ]
}

resource "google_cloud_run_v2_service" "default" {
  name     = "test"
  location = "asia-northeast1"

  template {
    containers {
      image = "docker/welcome-to-docker"

      ports {
        container_port = 80
      }


      dynamic "env" {
        for_each = local.env_vars
        content {
          name  = env.value["name"]
          value = env.value["value"]
        }
      }
    }
  }
}

resource "google_cloud_run_v2_job" "default" {
  name     = "test"
  location = "asia-northeast1"

  template {
    template {
      containers {
        image = "docker/welcome-to-docker"

        ports {
          container_port = 80
        }

        dynamic "env" {
          for_each = local.env_vars
          content {
            name  = env.value["name"]
            value = env.value["value"]
          }
        }
      }
    }
  }
}

```

### Expected Behavior

Only the target env should be changed.

```diff
locals {
       name  = "FOO1"
       value = "bar1"
     },
-    {
-      name  = "FOO2"
-      value = "bar2"
-    },
     {
       name  = "FOO3"
       value = "bar3"
```

```tf
  # google_cloud_run_v2_job.default will be updated in-place
  ~ resource "google_cloud_run_v2_job" "default" {
        id                       = "redacted"
        name                     = "cloudrun-service"
        # (19 unchanged attributes hidden)

      ~ template {
            # (4 unchanged attributes hidden)

          ~ template {
                # (4 unchanged attributes hidden)

              ~ containers {
                    # (3 unchanged attributes hidden)

                  - env {
                      - name  = "FOO2" -> null
                      - value = "bar2" -> null
                    }

                    # (5 unchanged blocks hidden)
                }
            }
        }
    }

  # google_cloud_run_v2_service.default will be updated in-place
  ~ resource "google_cloud_run_v2_service" "default" {
        id                      = "redacted"
        name                    = "cloudrun-service"
        # (25 unchanged attributes hidden)

      ~ template {
            # (6 unchanged attributes hidden)

          ~ containers {
                # (4 unchanged attributes hidden)

              - env {
                  - name  = "FOO2" -> null
                  - value = "bar2" -> null
                }

                # (6 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Actual Behavior

All subsequent env blocks are recognized as diff

```diff
locals {
       name  = "FOO1"
       value = "bar1"
     },
-    {
-      name  = "FOO2"
-      value = "bar2"
-    },
     {
       name  = "FOO3"
       value = "bar3"
```

```tf
  # google_cloud_run_v2_job.default will be updated in-place
  ~ resource "google_cloud_run_v2_job" "default" {
        id                       = "redacted"
        name                     = "test"
        # (19 unchanged attributes hidden)

      ~ template {
            # (4 unchanged attributes hidden)

          ~ template {
                # (4 unchanged attributes hidden)

              ~ containers {
                    # (3 unchanged attributes hidden)

                  ~ env {
                      ~ name  = "FOO2" -> "FOO3"
                      ~ value = "bar2" -> "bar3"
                    }
                  ~ env {
                      ~ name  = "FOO3" -> "FOO4"
                      ~ value = "bar3" -> "bar4"
                    }
                  - env {
                      - name  = "FOO4" -> null
                      - value = "bar4" -> null
                    }

                    # (3 unchanged blocks hidden)
                }
            }
        }
    }

  # google_cloud_run_v2_service.default will be updated in-place
  ~ resource "google_cloud_run_v2_service" "default" {
        id                      = "redacted"
        name                    = "test"
        # (25 unchanged attributes hidden)

      ~ template {
            # (6 unchanged attributes hidden)

          ~ containers {
                # (4 unchanged attributes hidden)

              ~ env {
                  ~ name  = "FOO2" -> "FOO3"
                  ~ value = "bar2" -> "bar3"
                }
              ~ env {
                  ~ name  = "FOO3" -> "FOO4"
                  ~ value = "bar3" -> "bar4"
                }
              - env {
                  - name  = "FOO4" -> null
                  - value = "bar4" -> null
                }

                # (4 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Steps to reproduce

1. `terraform apply` with multiple env blocks
2. remove one of the env block
3. `terraform apply` again

### References

Cloud Run v1 has alread been fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/4860

b/330546739

**Comment by ggtisc** [comment] 2024-03-18 19:24
Hi @dullest with the steps to reproduce the issue 1st both resources were created, then 1 env variable was removed and finally the change was applied. So are you expecting that the env vars that aren't removed change their values? Because the unique change is that 1 env var was removed from both resources, but for the other variables their values remain.

**Comment by dullest** [comment] 2024-03-19 08:13
I'm expecting env blocks work as a set instead of a list in order to avoid unnecessary diffs.
I confirmed with fixed provider binary on my local with [this change](https://github.com/GoogleCloudPlatform/magic-modules/pull/10214) that the type change from a list to a set fixes the issue.

Let me simplify the behaviors and the steps a bit.

<details>

<summary>Actual Behavior and the steps</summary>

1. applying this resource with 4 env blocks

```hcl
resource "google_cloud_run_v2_service" "default" {
  name     = "test"
  location = "asia-northeast1"

  template {
    containers {
      image = "docker/welcome-to-docker"

      ports {
        container_port = 80
      }

      env {
        name  = "FOO1"
        value = "bar1"
      }

      env {
        name  = "FOO2"
        value = "bar2"
      }

      env {
        name  = "FOO3"
        value = "bar3"
      }

      env {
        name  = "FOO4"
        value = "bar4"
      }
    }
  }
}
```

2. removing one env block (commented out FOO2)

```hcl
resource "google_cloud_run_v2_service" "default" {
  name     = "test"
  location = "asia-northeast1"

  template {
    containers {
      image = "docker/welcome-to-docker"

      ports {
        container_port = 80
      }

      env {
        name  = "FOO1"
        value = "bar1"
      }

      # env {
      #   name  = "FOO2"
      #   value = "bar2"
      # }

      env {
        name  = "FOO3"
        value = "bar3"
      }

      env {
        name  = "FOO4"
        value = "bar4"
      }
    }
  }
}
```

3. applying again shows following diff (current behavior)
It shows FOO3, FOO4 are also recognized as the diff even I didn't change

```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_run_v2_service.default will be updated in-place
  ~ resource "google_cloud_run_v2_service" "default" {
        id                      = "redacted"
        name                    = "test"
        # (25 unchanged attributes hidden)

      ~ template {
            # (6 unchanged attributes hidden)

          ~ containers {
                # (4 unchanged attributes hidden)

              ~ env {
                  ~ name  = "FOO2" -> "FOO3"
                  ~ value = "bar2" -> "bar3"
                }
              ~ env {
                  ~ name  = "FOO3" -> "FOO4"
                  ~ value = "bar3" -> "bar4"
                }
              - env {
                  - name  = "FOO4" -> null
                  - value = "bar4" -> null
                }

                # (4 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
</details>

<details>
<summary>Expected Behavior and the steps</summary>

1. applying this resource with 4 env blocks

```hcl
resource "google_cloud_run_v2_service" "default" {
  name     = "test"
  location = "asia-northeast1"

  template {
    containers {
      image = "docker/welcome-to-docker"

      ports {
        container_port = 80
      }

      env {
        name  = "FOO1"
        value = "bar1"
      }

      env {
        name  = "FOO2"
        value = "bar2"
      }

      env {
        name  = "FOO3"
        value = "bar3"
      }

      env {
        name  = "FOO4"
        value = "bar4"
      }
    }
  }
}
```

2. removing one env block (commented out FOO2)

```hcl
resource "google_cloud_run_v2_service" "default" {
  name     = "test"
  location = "asia-northeast1"

  template {
    containers {
      image = "docker/welcome-to-docker"

      ports {
        container_port = 80
      }

      env {
        name  = "FOO1"
        value = "bar1"
      }

      # env {
      #   name  = "FOO2"
      #   value = "bar2"
      # }

      env {
        name  = "FOO3"
        value = "bar3"
      }

      env {
        name  = "FOO4"
        value = "bar4"
      }
    }
  }
}
```

3. applying again shows following diff 
It only shows FOO2 is  the diff, not like actual behavior showed FOO3, FOO4 are also the diff

```hcl
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/google in /Users/dullest/go/1.21.7/bin
│  - hashicorp/google-beta in /Users/dullest/go/1.21.7/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with
│ published releases.
╵
data.google_project.project: Reading...
google_cloud_run_v2_service.default: Refreshing state... [id=redacted]
data.google_project.project: Read complete after 2s [id=redacted]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_cloud_run_v2_service.default will be updated in-place
  ~ resource "google_cloud_run_v2_service" "default" {
        id                      = "redacted"
        name                    = "test"
        # (25 unchanged attributes hidden)

      ~ template {
            # (6 unchanged attributes hidden)

          ~ containers {
                # (4 unchanged attributes hidden)

              - env {
                  - name  = "FOO2" -> null
                  - value = "bar2" -> null
                }

                # (6 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>

**Comment by ggtisc** [comment] 2024-03-19 17:46
Thanks for the update! Yeah, this solution looks good for you https://github.com/GoogleCloudPlatform/magic-modules/pull/10214

So, are you ok right now, or do you still have issues?

**Comment by dullest** [comment] 2024-03-20 01:25
I'm ok right now. I'll wait the release which will have the fix.

**Comment by ggtisc** [comment] 2024-03-20 16:38
@rileykarson could you please help closing this issue?

**Comment by rileykarson** [comment] 2024-03-20 16:41
Added to our major release milestone, so that this gets accounted for during that. https://github.com/GoogleCloudPlatform/magic-modules/pull/10214 is an outstanding PR to resolve.

**Closed** 2024-07-29 02:37 UTC
Labels: breaking-change, persistent-bug, forward/linked, service/run
