### ISSUE TITLE
Checkpoint_signature error during terraform init

### ISSUE THREAD

**Issue by nandikatlakishore** [hashicorp/terraform-provider-google#16867] opened 2023-12-26 06:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform version: 1.6.2

### Affected Resource(s)
Initializing provider plugins...

- Finding latest version of hashicorp/google-beta...

2023-12-24T11:01:31.542Z [ERROR] Checkpoint error: mkdir /home/appuser/.terraform.d: read-only file system

- Finding latest version of hashicorp/google...

+ terraform validate
2023-12-21T17:35:37.637Z [INFO]  Terraform version: 1.6.2
2023-12-21T17:35:37.637Z [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2023-12-21T17:35:37.637Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.1
2023-12-21T17:35:37.637Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-12-21T17:35:37.637Z [DEBUG] using github.com/zclconf/go-cty v1.14.1
2023-12-21T17:35:37.637Z [INFO]  Go runtime version: go1.21.1
2023-12-21T17:35:37.637Z [INFO]  CLI args: []string{"terraform", "validate"}
2023-12-21T17:35:37.637Z [DEBUG] Attempting to open CLI config file: /home/appuser/.terraformrc
2023-12-21T17:35:37.637Z [INFO]  Loading CLI configuration from /home/appuser/.terraformrc
2023-12-21T17:35:37.637Z [DEBUG] Explicit provider installation configuration is set
2023-12-21T17:35:37.637Z [INFO]  CLI command args: []string{"validate"}
2023-12-21T17:35:37.637Z [ERROR] Checkpoint error: mkdir /home/appuser/.terraform.d: read-only file system
2023-12-21T17:35:37.846Z [DEBUG] checking for provisioner in "."
2023-12-21T17:35:37.848Z [DEBUG] checking for provisioner in "/usr/bin"
2023-12-21T17:35:37.848Z [DEBUG] Building and walking validate graph
2023-12-21T17:35:37.849Z [DEBUG] ProviderTransformer: "google_storage_bucket.bucket" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/hashicorp/google"]
2023-12-21T17:35:37.849Z [DEBUG] ProviderTransformer: "google_storage_bucket_iam_member.members" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/hashicorp/google"]
2023-12-21T17:35:37.849Z [DEBUG] pruning unused provider["registry.terraform.io/hashicorp/google-beta"]
2023-12-21T17:35:37.849Z [DEBUG] created provider logger: level=debug
2023-12-21T17:35:37.849Z [INFO]  provider: configuring client automatic mTLS
2023-12-21T17:35:37.861Z [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.51.0/linux_amd64/terraform-provider-google_v4.51.0_x5 args=[".terraform/providers/registry.terraform.io/hashicorp/google/4.51.0/linux_amd64/terraform-provider-google_v4.51.0_x5"]
2023-12-21T17:35:37.861Z [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.51.0/linux_amd64/terraform-provider-google_v4.51.0_x5 pid=77
2023-12-21T17:35:37.861Z [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.51.0/linux_amd64/terraform-provider-google_v4.51.0_x5
2023-12-21T17:35:37.924Z [ERROR] provider.terraform-provider-google_v4.51.0_x5: plugin init error: error="open /tmp/plugin2300476272: read-only file system" timestamp=2023-12-21T17:35:37.924Z
2023-12-21T17:35:37.925Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.51.0/linux_amd64/terraform-provider-google_v4.51.0_x5 pid=77
╷
│ Error: failed to read schema for google_storage_bucket_iam_member.members in registry.terraform.io/hashicorp/google: failed to instantiate provider "registry.terraform.io/hashicorp/google" to obtain schema: Unrecognized remote plugin message: 

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by roaks3** [comment] 2024-01-02 22:55
@nandikatlakishore it looks like Terraform might be trying to store files to a place where you don't have write access. Could you try updating your configuration or modifying the access? Another approach would be to try another provider to verify if the issue is specifically with the Google provider.

**Comment by edwardmedia** [comment] 2024-01-22 14:49
@nandikatlakishore is this still an issue?

**Comment by edwardmedia** [comment] 2024-01-26 14:02
@nandikatlakishore closing assuming this is no longer an issue

**Closed by edwardmedia** 2024-01-26 14:02 UTC
Labels: bug, waiting-response, service/terraform, forward/exempt
