### ISSUE TITLE
Add Vertex AI Search Deploy Index to Endpoint

### ISSUE THREAD

**Issue by AndrasSandor** [hashicorp/terraform-provider-google#16846] opened 2023-12-20 09:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
An additional resource or and update google_vertex_ai_index is needed to be able to deploy indexes to endpoints.

https://cloud.google.com/vertex-ai/docs/vector-search/deploy-index-vpc#deploy_index_default-drest

### New or Affected Resource(s)

google_vertex_ai_index_endpoint and google_vertex_ai_index

**Comment by roaks3** [comment] 2023-12-21 19:19
This appears to be a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12818, which captures the work to manage deployed indexes

**Closed by roaks3** 2023-12-21 19:19 UTC
Labels: enhancement, forward/review, service/aiplatform-matching-engine
