### ISSUE TITLE
google_composer_environment always must be replaced

### ISSUE THREAD

**Issue by rafstef** [hashicorp/terraform-provider-google#7769] opened 2020-11-10 11:52 UTC
When we launch terraform, in every case, also without change the behavior is resource replace.
Is it normal?

We must re-deploy the cluster every time ?

**Comment by edwardmedia** [comment] 2020-11-10 13:48
@rafstef Normally no. If you update certain attributes, which may force to recreate the resource.  If you don't change any attribute, certainly not. Could you give details about whether you have updated fields and if yes, what they are? I could take a close look.

**Comment by rafstef** [comment] 2020-11-11 12:39
We need to update the env_variables but this behavior is always the same.
If I change or not my terraform code, my plan/apply destroy and re-create my composer.

The resource is 

resource "google_composer_environment"

I am creating a private environment with this option

private_environment_config {
        enable_private_endpoint = true
 }

**Comment by edwardmedia** [comment] 2020-11-11 15:45
@rafstef yes, this is by design. Changing private_environment_config will trigger recreate the resource

https://github.com/hashicorp/terraform-provider-google/blob/2be0beb3757bb10e60669ef4b60c99d67c611c71/google/resource_composer_environment.go#L296

**Comment by rafstef** [comment] 2020-11-12 14:58
The cluster is already created with private_environment_config = true. When I run terraform, without any code change, the behavior is re-deploy.

**Comment by edwardmedia** [comment] 2020-11-14 00:50
@rafstef it is fine with me. I can't repro the issue with below code. Can you share your state and debug log for your 2nd plan?

```
resource "google_composer_environment" "test" {
  name   = "mycomposer-7769"
  region = "us-central1"
  config {
    node_count = 4
    node_config {
      zone         = "us-central1-a"
      machine_type = "e2-medium"
      network    = google_compute_network.test.id
      subnetwork = google_compute_subnetwork.test.id
      service_account = google_service_account.test.name
      
      ip_allocation_policy {
          use_ip_aliases = true
      }
    }
    private_environment_config {
        enable_private_endpoint = true
    }
  }
  depends_on = [google_project_iam_member.composer-worker]
}
resource "google_compute_network" "test" {
  name                    = "composer-test-network-7769"
  auto_create_subnetworks = false
}
resource "google_compute_subnetwork" "test" {
  name          = "composer-test-subnetwork-7769"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.test.id
}
resource "google_service_account" "test" {
  account_id   = "composer-env-account-7769"
  display_name = "Test Service Account for Composer Environment"
}
resource "google_project_iam_member" "composer-worker" {
  role   = "roles/composer.worker"
  member = "serviceAccount:${google_service_account.test.email}"
}
```

**Comment by edwardmedia** [comment] 2020-11-16 21:41
@rafstef is this still an issue with you?

**Comment by edwardmedia** [comment] 2020-11-17 18:33
Closing now assuming it is no longer an question

**Closed by edwardmedia** 2020-11-17 18:33 UTC
Labels: question, waiting-response
