### ISSUE TITLE
When a pubsub subscription is re-created, IAM member is not re-applied

### ISSUE THREAD

**Issue by stjasink** [hashicorp/terraform-provider-google#2301] opened 2018-10-22 13:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.9
+ provider.google v1.19.1
+ provider.template v1.0.0

### Affected Resource(s)

* google_pubsub_subscription
* google_pubsub_subscription_iam_member

### Terraform Configuration Files

Run first:

```tf
resource "google_service_account" "test-account" {
  account_id = "test-account"
}

resource "google_pubsub_topic" "test-topic" {
  name = "test-topic"
}

resource "google_pubsub_subscription" "test-sub" {
  name = "test-sub"
  topic = "${google_pubsub_topic.test-topic.name}"
  ack_deadline_seconds = 30
}

resource "google_pubsub_subscription_iam_member" "test-sub-user" {
  member = "serviceAccount:${google_service_account.test-account.email}"
  role = "roles/pubsub.viewer"
  subscription = "${google_pubsub_subscription.test-sub.name}"
}
```

Then run with ack_deadline_seconds changed:

```tf
resource "google_service_account" "test-account" {
  account_id = "test-account"
}

resource "google_pubsub_topic" "test-topic" {
  name = "test-topic"
}

resource "google_pubsub_subscription" "test-sub" {
  name = "test-sub"
  topic = "${google_pubsub_topic.test-topic.name}"
  ack_deadline_seconds = 60
}

resource "google_pubsub_subscription_iam_member" "test-sub-user" {
  member = "serviceAccount:${google_service_account.test-account.email}"
  role = "roles/pubsub.viewer"
  subscription = "${google_pubsub_subscription.test-sub.name}"
}

```

### Debug Output

https://gist.github.com/stjasink/c0e7574358c20bb55887929de703b9f8

### Expected Behavior

When changing the ack deadline on the subscription, it needs to destroy and recreate the subscription.  I expect the google_pubsub_subscription_iam_member to be applied to the re-created subscription.

### Actual Behavior

The subscription is destroyed and re-created with the new ack deadline but the google_pubsub_subscription_iam_member is not applied to it.

If a second apply is run with the same inputs, then this is run.

### Steps to Reproduce

1. `terraform apply` with the first input, ack deadline set to 30s
2. `terraform apply` with the second input, ack deadline set to 60s
3. Check that the publisher role was not granted to the service account on the second run

### References

* #0000

**Comment by danawillow** [comment] 2018-10-30 23:46
Hey @stjasink, we've seen similar issues before and don't have a great solution (#2213, https://github.com/hashicorp/terraform/issues/19052). In the meantime, the best workaround that I know of is to give the subscription a randomish name using the random provider. That way, when the subscription is recreated, it'll have a different name and will trigger the IAM member to get recreated too.

**Comment by miguepintor** [comment] 2021-11-08 11:34
I can't believe terraform has a big bug like this and there is no progress since 2018.
We are reproducing this issue with these versions:
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.67.0
```

@danawillow , @stjasink Have you found a better way to workaround this? Do you know if terraform have in plan something to fix this?

**Comment by danawillow** [comment] 2021-11-08 20:50
Hi @miguepintor, I don't work on Terraform anymore so I don't have a great answer for you. I'd recommend keeping tabs on https://github.com/hashicorp/terraform-plugin-sdk/issues/122, since that's tracking a fix at an SDK level. I'll also pull in @rileykarson in case he knows something I don't.

While I'm here though, I will point out that I care deeply about the folks working in this code base and want them to feel good about their work and continue to be motivated to work on the provider. Comments like "I can't believe terraform has a big bug like this and there is no progress since 2018," though not actively malicious, can be pretty demoralizing. Just something to keep in mind 🙂

**Comment by rileykarson** [comment] 2021-11-09 17:53
Nothing new from me! Also waiting on https://github.com/hashicorp/terraform-plugin-sdk/issues/122 as we haven't found a really effective provider-side workaround.

I would note that the issue may be mitigated by using an output value like `id` rather than `name` where that is accepted- this issue boils down to Terraform misunderstanding the relationship between resources, and using a value that is "unknown" to Terraform at plan time can help.

**Comment by melinath** [comment] 2023-04-14 16:54
https://github.com/hashicorp/terraform-plugin-sdk/issues/122 has been resolved by adding support for the [`replace_triggered_by` lifecycle meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by). You can use it as follows:

```hcl
resource "google_service_account" "test-account" {
  account_id = "test-account"
}

resource "google_pubsub_topic" "test-topic" {
  name = "test-topic"
}

resource "google_pubsub_subscription" "test_sub" {
  name = "test-sub"
  topic = google_pubsub_topic.test-topic.name
  ack_deadline_seconds = 30
}

resource "google_pubsub_subscription_iam_member" "test-sub-user" {
  member = "serviceAccount:${google_service_account.test-account.email}"
  role = "roles/pubsub.viewer"
  subscription = google_pubsub_subscription.test_sub.name

  lifecycle {
    replace_triggered_by = [
      google_pubsub_subscription.test_sub
    ]
  } 
}
```

Note that this will recreate the iam member every time the test_sub _changes_, not just when test_sub is recreated. If that is a problem, you could limit the `replace_triggered_by` to explicitly fields on  `google_pubsub_subscription.test_sub` that trigger recreation.

This is the recommended path forward for this kind of situation, where Terraform doesn't have a way to otherwise understand the relationship between the two resources. See the discussion on https://github.com/hashicorp/terraform-plugin-sdk/issues/122 for more details.

**Closed by melinath** 2023-04-14 16:54 UTC
Labels: bug, upstream-terraform

**Comment by melinath** [comment] 2023-04-17 22:58
I've opened https://github.com/hashicorp/terraform-provider-google/issues/14343 to track documenting this; it should probably be documented for all IAM resources, not just pubsub subscription.
