### ISSUE TITLE
Removing expiration_ms from google_bigquery_table does not change partition expiration

### ISSUE THREAD

**Issue by s3rvac** [hashicorp/terraform-provider-google#15626] opened 2023-08-25 09:17 UTC
### Community Note

* Please vote on this issue by adding a [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.79.0
```

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

Here is a minimal working example:
```tf
resource "google_bigquery_dataset" "foo" {
  dataset_id = "foo"
}

resource "google_bigquery_table" "bar" {
  dataset_id = google_bigquery_dataset.foo.dataset_id
  table_id   = "bar"

  time_partitioning {
    field         = "dt"
    type          = "DAY"
    expiration_ms = 2592000000
  }

  schema = <<EOF
[
  {
    "name": "dt",
    "type": "DATE"
  }
]
EOF
}
```

### Steps to Reproduce

1. Run `terraform apply`.
2. Remove `expiration_ms` from the `.tf` file, i.e. apply the following change:
    ```diff
    @@ -9,7 +9,6 @@ resource "google_bigquery_table" "bar" {
       time_partitioning {
         field         = "dt"
         type          = "DAY"
    -    expiration_ms = 2592000000
       }

       schema = <<EOF
    ```
3. Run `terraform apply`.

### Debug Output

* [From step 1](https://gist.github.com/s3rvac/28b31214c2130ee277d2cf26f832a8ad)
* [From step 3](https://gist.github.com/s3rvac/5d70ce567304efd42fedd1110f7367fa)

(User names/emails and project IDs have been redacted.)

### Expected Behavior

Step 3 shows a plan to remove the partition expiration, and after applying the plan, the table does not have any partition expiration set (i.e. partitions never expire):
```
Partition expiration: Partitions do not expire
```

### Actual Behavior

Step 3 does not produce any plan (only `No changes. Your infrastructure matches the configuration.`) and the table still has the original partition expiration set:
```
Partition expiration: 30 days
```

**Comment by edwardmedia** [comment] 2023-08-25 13:48
b/297505789

**Comment by wj-chen** [comment] 2023-09-11 17:26
Hi @s3rvac, thank you for raising this issue. `google_bigquery_table.time_partitioning.expiration_ms` is marked a `Computed: true` field (see [mmv1/third_party/terraform/services/bigquery/resource_bigquery_table.go](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/bigquery/resource_bigquery_table.go#L867)) by design. `Computed: true` effectively means that, when a user explicitly specifies a value, that value will be set, and when a user doesn't specify a value, a value will be inferred by the API.

In this case, the absence of `expiration_ms` can't be simply treated as "unsetting the partition expiration", because due to its API design, its absence means "defaulting to using the dataset-level partition expiration value" (see https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset#default_partition_expiration_ms). To achieve the desired behavior of unsetting the partition expiration for a table, you may explicitly set `expiration_ms = 0`. This aligns with other `Computed: true` field behavior. Please give it a try. If it works for your purpose, I'll update the documentation of this field to call this out.

**Comment by s3rvac** [comment] 2023-09-12 09:09
Hi @wj-chen, thank you for reaching out to me with an explanation :+1:. I can confirm that setting `expiration_ms = 0` disables partition expiration, which is exactly what I wanted to achieve :heavy_check_mark:. So, if #8827 is a no go, then I suggest updating the documentation of this field and closing the issue :slightly_smiling_face:.

**Closed** 2023-09-15 21:51 UTC
Labels: bug, forward/linked, service/bigquery
