### ISSUE TITLE
Support wafSettings for google_recaptcha_enterprise_key

### ISSUE THREAD

**Issue by alejandrombc** [hashicorp/terraform-provider-google#14551] opened 2023-05-10 01:11 UTC
I cant find anything related to WAF on the documentation (https://registry.terraform.io/providers/hashicorp/google/4.63.1/docs/resources/recaptcha_enterprise_key)

Is it even possible with the current version?

Thanks!

**Comment by edwardmedia** [comment] 2023-05-10 13:48
@alejandrombc  not possible with the current version. Is it supported by other tools? Can you share the links to what you are looking for?

**Comment by alejandrombc** [comment] 2023-05-10 20:33
I dont know about other tools, but its supported by the `gcloud` command (https://cloud.google.com/recaptcha-enterprise/docs/create-key).

In the meantime I create a `null_resource` that runs the `gcloud` command with the required parameters

```
resource "null_resource" "recaptcha_key" {

 provisioner "local-exec" {
    command = "/bin/bash recaptcha.sh ${var.project} recaptcha-key-name domain.com,localhost"
  }
}
```

And the `sh` is as simple as
```
gcloud recaptcha keys create --web --project=$1 --display-name=$2 --waf-feature="action-token" --waf-service="CA" --integration-type="score" --domains=$3
```

Hopefully this feature gets implemented natively 🙏

**Comment by edwardmedia** [comment] 2023-05-11 17:48
`wafSettings` has not been implemented yet

```
uri: https://recaptchaenterprise.googleapis.com/v1/projects/myproject/keys?alt=json
method: POST

{"displayName": "web-waf", "wafSettings": {"wafFeature": "ACTION_TOKEN", "wafService": "CA"}, "webSettings": {"allowAllDomains": false, "allowAmpTraffic": false, "allowedDomains": ["test.hashicorp.com"], "integrationType": "SCORE"}}
```

**Comment by gtsorbo** [comment] 2023-05-16 16:04
Can you upvote here as well: https://github.com/hashicorp/terraform-provider-google/issues/13401
Thanks!

**Comment by ScottSuarez** [comment] 2023-05-19 22:03
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/13401

**Closed by ScottSuarez** 2023-05-19 22:03 UTC
Labels: enhancement
