### ISSUE TITLE
Disabling autoclass on a google_storage_bucket causes re-create, which it should not.

### ISSUE THREAD

**Issue by dhrp** [hashicorp/terraform-provider-google#15120] opened 2023-07-11 08:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.72.1
+ provider registry.terraform.io/hashicorp/google-beta v4.73.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.

resource "google_storage_bucket" "testbucket" {
  # I also tried it with provider google-beta
  provider = google

  name     = "velcro-clothing-rearrange"
  location = var.gcp_region

  autoclass {
    enabled = false
  }
}

```

### Debug Output

This is the full output of an isolated test; only creating, and changing this one resource.

https://gist.github.com/dhrp/789598bddcd928d8e6d7bb495e39b2a5

### Expected Behavior

Since Google Allows to *disable* the autoclass I expect Terraform to be able to *change* the resource. 

### Actual Behavior
Instead it has to **re-create** the storage bucket (and as a consequence delete everything in it).

### Steps to Reproduce

1. `terraform apply`

with:
```
  autoclass {
    enabled = true
  }
```

and then with
```
  autoclass {
    enabled = false
  }
```

### References

There is another issue that was open (https://github.com/hashicorp/terraform-provider-google/issues/14319); and closed that relates to this issue; **however**, it assumes re-creating the bucket is ok, and focusses on it not happening on every 'apply'. With this issue I want to address the behavior of re-creating.

**ps:** I am aware of the fact that you cannot 'enable' autoclass on a bucket that had autoclass disabled. - But it should be possible to 'disable' autoclass on a bucket.

**ps2:** If you manually disable autoclass (though console or cli), and then run it; no problem or re-create is triggered. So this is a valid workaround.

* #14319

b/291294690

**Comment by edwardmedia** [comment] 2023-07-11 13:32
I do see below. @zli82016  do you know if this is the expected behavior? 

```
      ~ autoclass {
          ~ enabled = true -> false # forces replacement
        }
```

**Comment by zli82016** [comment] 2023-07-11 17:21
The field `autoclass.enabled` has `ForceNew:    true` in the code https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storage/resource_storage_bucket.go.erb#L265

Based on the google cloud [doc](https://cloud.google.com/storage/docs/autoclass#restrictions), Autoclass must be enabled at bucket creation time. Existing buckets can only disable the feature, not enable it.

It looks like a bug. Only set `ForceNew` to the field `autoclass.enabled` when enabling it. When disabling it, `ForceNew` should not be set to this field.

**Comment by zli82016** [comment] 2023-07-11 17:42
This is the bug in storage service and will be assigned to the service team.

**Comment by thomasmaclean** [comment] 2023-09-11 18:37
This was fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8891

**Closed** 2023-09-12 19:22 UTC
Labels: bug, forward/linked, service/storage
