### ISSUE TITLE
VM machine_type change false-positive

### ISSUE THREAD

**Issue by natedogith1** [hashicorp/terraform-provider-google#12681] opened 2022-09-29 14:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.2.3 on linux_amd64

### Affected Resource(s)

* google_compute_instance

### Debug Output

```
~ machine_type              = "n2-highmem-16" -> "n2-custom-16-131072"
```

### Expected Behavior

No changes, since terraform config was unchanged.

### Actual Behavior

GCP used the matching standard machine type instead of the custom machine type, terraform apply reboots the VM, but the machine type doesn't change.

### Steps to Reproduce

1. create terraform config with custom machine type matching a standard machine type (n2-custom-16-131072 matches n2-highmem-16 in my case)
2. `terraform apply`
3. `terraform plan` 

### References

* This looks to be the same problem as #7517

**Comment by edwardmedia** [comment] 2022-09-29 17:37
@natedogith1 sorry about that, but this is caused by API and there is not much we can do at the provider level. Yes, I think the [mitigation](https://github.com/hashicorp/terraform-provider-google/issues/7517#issuecomment-708601418) is the solution we can suggest now. Does this make sense?

**Comment by natedogith1** [comment] 2022-09-29 19:19
The mitigation doesn't work, because we have a lot of VMs using a common module, and sometimes we want to change the machine type.  Couldn't the provider determine that n2-highmem-16 and n2-custom-16-131072 are both N2 and have the same vCPU and RAM?

**Comment by edwardmedia** [comment] 2022-09-29 22:52
@natedogith1 sorry unfortunately there are not much we can do at the provider level. Suppress the diff with the suggestions could lead to more issues. Closing the issue then

**Closed by edwardmedia** 2022-09-29 22:52 UTC
Labels: bug

**Comment by natedogith1** [comment] 2022-09-30 19:43
I'm not sure what you mean about supressing the diff causing more issues.  If you determine that it won't actually change, I wouldn't think there would be any issues.
