### ISSUE TITLE
Add resource_manager_tags to google_compute_instance_template

### ISSUE THREAD

**Issue by maroux** [hashicorp/terraform-provider-google#12952] opened 2022-11-04 20:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Compute Instance template supports resource tags which can be used for firewall rules and IAM policy.

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

```tf
resource "google_tags_tag_key" "key" {
    parent = "organizations/123456789"
    short_name = "keyname"
    description = "For keyname resources."
}

resource "google_tags_tag_value" "value" {
    parent = "tagKeys/${google_tags_tag_key.key.name}"
    short_name = "valuename"
    description = "For valuename resources."
}

resource "google_compute_instance_template" "template" {
  ...

  resource_manager_tag {
    tag_key    = "tagKeys/${google_tags_tag_key.key.id}"
    tag_value = "tagValues/${google_tags_tag_value.value.id}"
  }

  resource_manager_tag {
    ...
  }
}
```

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert
* https://cloud.google.com/resource-manager/docs/tags/tags-overview

**Comment by gilad9366** [comment] 2023-09-07 20:24
Until this is developed, is there a workaround for this?
Perhaps adding the tags after creation?
I couldn't find this option either.

**Comment by LucaPrete** [comment] 2023-12-24 17:22
This should be ready for merge [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/9612)

**Comment by LucaPrete** [comment] 2023-12-24 17:23
btw this seems a duplicate of [this](https://github.com/hashicorp/terraform-provider-google/issues/16356)

**Closed** 2024-01-02 18:42 UTC
Labels: enhancement, size/s, forward/review, service/compute-instances
