### ISSUE TITLE
Re-creation of existing `google_monitoring_monitored_project` resource when upgrading from v4.72.1 to v4.73.0

### ISSUE THREAD

**Issue by dellison-castlight** [hashicorp/terraform-provider-google#15117] opened 2023-07-10 22:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

- Terraform version: v1.0.11
- Google provider version: v4.73.0

### Affected Resource(s)

* google_monitoring_monitored_project

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.

```

### Expected Behavior

There were no changes to the `google_monitoring_monitored_project`, so there should be no changes planned for the `google_monitoring_monitored_project`. When using `google` provider v4.72.1 no changes are planned, both before the upgrade to v4.73.0 and after we tried re-running the plan on v4.72.1

### Actual Behavior

With `google` provider v4.73.0, the plan detects a "change" outside of Terraform:
```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.<redacted>.google_monitoring_monitored_project.monitored_project[0] has been deleted
  - resource "google_monitoring_monitored_project" "monitored_project" {
      - create_time   = "2023-05-02T12:01:53.800288Z" -> null
      - id            = "locations/global/metricsScopes/<redacted>/projects/<redacted>" -> null
      - metrics_scope = "<redacted>" -> null
      - name          = "<redacted>" -> null
    }
```

And then the plan tries to re-add the Metrics Scope:
```
Terraform will perform the following actions:

  # module.<redacted>.google_monitoring_monitored_project.monitored_project[0] will be created
  + resource "google_monitoring_monitored_project" "monitored_project" {
      + create_time   = (known after apply)
      + id            = (known after apply)
      + metrics_scope = "<redacted>"
      + name          = "<redacted>"
    }
```

Which causes the following error during the apply:
```
│ Error: Error creating MonitoredProject: googleapi: Error 409: Requested entity already exists
│ 
│   with module.<redacted>.google_monitoring_monitored_project.monitored_project[0],
```

### Steps to Reproduce

1. Create a `google_monitoring_monitored_project` resource in v4.72.1 (or earlier?) of the`google` provider and `terraform apply`
2. Upgrade `google` provider version to v4.73.0
3. Run `terraform plan` to see that the `google_monitoring_monitored_project` is planned to be created again
4. Run `terraform apply` to get the `Error 409: Requested entity already exists` error

**Comment by submac** [comment] 2023-07-11 08:48
We are experiencing possibly related issue on `4.73.0`. This happens on a newly provisioned `google_monitoring_monitored_project` resource. `4.72.1` works fine. Note `was present, but now absent`

```
Error: Provider produced inconsistent result after apply

When applying changes to
module.target_repo.google_monitoring_monitored_project.app_monitored_project[0],
provider "registry.terraform.io/-/google" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Operation failed: failed running terraform apply (exit 1)
```

**Comment by edwardmedia** [comment] 2023-07-11 15:23
@submac i am having hard time repro this issue. Having tried on terraform both v1.0.11 and v1.5.1, following the steps upgrading the provider from v4.72.1 to v4.73.0, I don't see the diff here. 

From the [changelog of v4.73.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.73.0), I don't see any changes that could contribute to this issue.

Can someone who has experienced this issue provide more repro info?

@zli82016 can you try to repro?

**Comment by dellison-castlight** [comment] 2023-07-11 17:04
@edwardmedia two notes:
- I wasn't sure if reproducing would require using v4.72.1 or an earlier version to create the `google_monitoring_monitored_project` resource. I'm unsure what specific version we created the `google_monitoring_monitored_project` resource with it had been created a little over two months ago and hasn't been changed since from what I can tell.
- I also didn't see any mention of changes to this resource in the changelog, but I did see that the resource went from a "DCL" one to an "MMv1" one. I'm not sure what that means but it seems to have made some changes in the `google/services/monitoring/resource_monitoring_monitored_project.go` file: https://github.com/hashicorp/terraform-provider-google/compare/v4.72.1...v4.73.0#diff-b7b3572cbe4a2a95d15dfc6914c9a09841822a2e40b768a3716133cffdd29dcaL124-R132

**Comment by submac** [comment] 2023-07-11 18:35
I don't want to hijack @dellison-castlight thread. I'm not 100% sure these 2 are related but I will only say I just tested it again, and the same module on provider:

- 4.72.1 works fine
- 4.73.0 fails

terraform 0.12.31

**Comment by edwardmedia** [comment] 2023-07-11 21:00
Seeing a recent change https://github.com/hashicorp/terraform-provider-google/commit/c0c8b12766c11d47744dca54091686d37f6995ae

**Comment by zli82016** [comment] 2023-07-11 21:03
We are going to revert the recent change. 

Revert PR
https://github.com/GoogleCloudPlatform/magic-modules/pull/8315

**Comment by zli82016** [comment] 2023-07-11 21:53
Actually, I cannot reproduce this error.

resource "google_monitoring_monitored_project" "primary" {
  metrics_scope = "local-mediator-361721"
  name          = google_project.basic.name
}

resource "google_project" "basic" {
  project_id = "tf-test-m-id-1"
  name       = "tf-test-m-id-1"
  org_id     = "485359906935"
}


@submac , @dellison-castlight Can you provide your configuration to reproduce? Thanks.

**Comment by melinath** [comment] 2023-07-11 23:05
b/290821294

**Comment by zli82016** [comment] 2023-07-11 23:24
@dellison-castlight , can you please provide the debug logs and terraform configuration if possible? Thanks.

**Comment by yukihato** [comment] 2023-07-12 01:28
I am experiencing the same problem and will provide details.

- terraform version: 1.5.2

- terraform code:
```
resource "google_monitoring_monitored_project" "projects_monitored" {
  provider      = google-beta
  for_each      = toset(["a-project", "b-project"])
  metrics_scope = join("", ["locations/global/metricsScopes/", "c-project"])
  name          = each.value
}
```
The terraform code is based on the following document.
https://cloud.google.com/composer/docs/terraform-cross-project-monitoring


After applying the above to a version older than `4.72.1`, with no changes

- terraform plan on `4.73.0`:
```
# google_monitoring_monitored_project.projects_monitored["a-project"] will be created
+ resource "google_monitoring_monitored_project" "projects_monitored" {
    + create_time   = (known after apply)
    + id            = (known after apply)
    + metrics_scope = "locations/global/metricsScopes/c-project"
    + name          = "a-project"
  }

# google_monitoring_monitored_project.projects_monitored["b-project"] will be created
+ resource "google_monitoring_monitored_project" "projects_monitored" {
    + create_time   = (known after apply)
    + id            = (known after apply)
    + metrics_scope = "locations/global/metricsScopes/c-project"
    + name          = "b-project"
  }  
```

- terraform apply on `4.73.0`:
```
│ Error: Error creating MonitoredProject: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/v1/locations/global/metricsScopes/locations/global/metricsScopes/c-project/projects?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>
│
│
│   with google_monitoring_monitored_project.projects_monitored["a-project"],
│   on main.tf line 810, in resource "google_monitoring_monitored_project" "projects_monitored":
│  810: resource "google_monitoring_monitored_project" "projects_monitored" {
│
```

**Comment by bakuljajan** [comment] 2023-07-12 08:02
I got the same problem with @submac error when applying new project and apply monitoring.

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ google_monitoring_monitored_project.project["kmd-firebase"], provider
│ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

It says fail but when checking on the scoped project it already exist. But when I try to import it using.
`terragrunt import 'google_monitoring_monitored_project.project["kmd-firebase"]' 'v1/locations/global/metricsScopes/kvn-abcd-efgh/projects/kvn-krdv-kmd-frbs-zzzz'` 

It get error with message

```
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to
│ "google_monitoring_monitored_project.project[\"kmd-firebase\"]", the
│ provider detected that no object exists with the given id. Only
│ pre-existing objects can be imported; check that the id is correct and that
│ it is associated with the provider's configured region or endpoint, or use
│ "terraform apply" to create a new remote object for this resource.
╵
```

But when I try to reapply. I got error `Error 409: Requested entity already exists`

```
╷
│ Error: Error creating MonitoredProject: googleapi: Error 409: Requested entity already exists
│
│   with google_monitoring_monitored_project.project["kmd-firebase"],
│   on metric.tf line 8, in resource "google_monitoring_monitored_project" "project":
│    8: resource "google_monitoring_monitored_project" "project" {
```

```bash
terragrunt version

Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.73.0
+ provider registry.terraform.io/hashicorp/google-beta v4.73.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

**Comment by torgeir** [comment] 2023-07-12 13:22
Chiming in just to say that we also experience this issue on v4.73.0, like OP and @yukihato, manifested as previously created `google_monitoring_monitored_project` that has disappeared from the terraform state. It appears that terraform wants to add them back, but it fails during apply with 409 (like @bakuljajan) as the resource already exists in GCP.

We fixed this on our end by reverting to the terraform state we had before v4.73.0 was used to apply and pinning the provider to v4.72.1. By planning with v4.72.1 the issue of the dissappearing `google_monitoring_monitored_project` is not present, and terraform shows no diff in our plan.

terragrunt version v0.39.2
Terraform v1.3.2

**Comment by zli82016** [comment] 2023-07-12 15:29
We can reproduce the issue. Thanks for the information.

Instead of reverting the commit, we are going to fix forward.
https://github.com/GoogleCloudPlatform/magic-modules/pull/8322

**Comment by zli82016** [comment] 2023-07-12 23:17
The patch release with the fix will be out tomorrow morning. Sorry for the trouble.

**Comment by zli82016** [comment] 2023-07-13 16:47
The fix is released in the Terraform google 4.73.1

**Comment by dougaldhub** [comment] 2023-07-14 10:28
I have updated our google module to `4.73.1` to test this fix, and unfortunately it doesn't look like anything has changed from `4.73.0`

Redacted Terraform plan on `4.73.1`

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  # module.project.google_monitoring_monitored_project.primary[0] will be created
  + resource "google_monitoring_monitored_project" "primary" {
      + create_time   = (known after apply)
      + id            = (known after apply)
      + metrics_scope = "locations/global/metricsScopes/<redacted>"
      + name          = "locations/global/metricsScopes/<redacted>/projects/<redacted>"
    }
```

When reverting the module back to `4.72.1` again, terraform is not trying to recreate this resource. Our code looks like this, much the same as others have reported

```
resource "google_monitoring_monitored_project" "primary" {
  provider      = google-beta
  count         = var.centralised_monitoring_enabled ? 1 : 0
  metrics_scope = "locations/global/metricsScopes/${var.monitoring_scoping_project}"
  name          = "locations/global/metricsScopes/${var.monitoring_scoping_project}/projects/${var.project_id}"
  depends_on = [
    module.project
  ]
}
```

I haven't tried applying yet as reverting our statefile or cleaning up duplicate resources is nontrivial in our environment, but I can arrange time to do so if required

**Comment by zli82016** [comment] 2023-07-14 17:14
Hello, @dougaldhub , sorry for the trouble. 

Can you please provide more information? Thanks.
1. Which project does ${var.monitoring_scoping_project} refer to?
2.  Which project does ${var.project_id} refer to? Do you have the configuration to create this project?

**Comment by zli82016** [comment] 2023-07-14 20:31
We can reproduce the issue, @dougaldhub . 

Fix: https://github.com/GoogleCloudPlatform/magic-modules/pull/8360

**Comment by c2thorn** [comment] 2023-07-17 18:29
[v4.73.2](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.73.2) should have the issue described in https://github.com/hashicorp/terraform-provider-google/issues/15117#issuecomment-1635655620 resolved. Closing this issue, let us know if there are any further complications.

**Closed by c2thorn** 2023-07-17 18:29 UTC
Labels: bug

**Comment by Klaitos** [comment] 2023-07-18 09:25
I'm using 4.73.2 version and my terraform plan still want to re-create my google_monitoring_monitored_project although they already exist, resulting in a 409 conflict code on apply. :/

**Comment by Klaitos** [comment] 2023-07-18 11:25
I've found a workaround, my terraform apply is now cleaned.

I had to re-import google_monitoring_monitored_project resources using project id, project number doesn't works :
 ```terraform 
terraform import google_monitoring_monitored_project.redacted v1/locations/global/metricsScopes/scopping-project-id/projects/monitored-project-id
``` 

And in my code I had to update the following block  as follow :
 
```diff
resource "google_monitoring_monitored_project" "redacted" {
  metrics_scope = module.project_monitoring.project_id
-  name          = module.project.project_number
+  name          = module.project.project_id
}
```

Hope that helps

**Comment by c2thorn** [comment] 2023-07-18 14:47
@Klaitos Apologies for the inconvenience. Looks like that case was missed as well. I created https://github.com/hashicorp/terraform-provider-google/issues/15211 to track.
