### ISSUE TITLE
Updating Pub/Sub topic schema causes issues

### ISSUE THREAD

**Issue by oleksiilopasov** [hashicorp/terraform-provider-google#12287] opened 2022-08-09 15:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.1.9, v1.2.x also affected
### Affected Resource(s)

* google_pubsub_topic
* google_pubsub_schema

### Terraform Configuration Files

```tf
# Pub/Sub module
resource "google_pubsub_schema" "ps_schema" {
  name       = var.pubsub_schema_name
  type       = "PROTOCOL_BUFFER"
  definition = var.pubsub_schema_definition
}

resource "google_pubsub_topic" "ps_topic" {
  name = google_pubsub_schema.ps_schema.name

  schema_settings {
    schema   = google_pubsub_schema.ps_schema.id
    encoding = "JSON"
  }
}

# main.tf
module "google_pubsub" {
  source                   = "./modules/pubsub"
  for_each                 = var.sources
  project                  = var.project
  pubsub_schema_name       = var.schema_name
  pubsub_schema_definition = file("<path_to_schema_protobuf_file>")
}
```

### Expected Behavior

1. The developer updates the schema file (The infrastructure with previous schema version already exists)
2. The schema is recreated by Terraform
3. The topic should get the new value of schema self_link and should also be recreated by Terraform as schema_settings field is not mutable

### Actual Behavior

1. The schema is recreated by Terraform
2. The topic is UPDATED IN-PLACE instead of being recreated
3. Because the schema_settings  is not mutable, Terraform should return an exception, though it does not
5. Terraform returns OK code though topic still remains not updated.
6. The deployment seems fine (marked as green), but in fact the schema is recreated with topic not updated -> we have topic referring to _deleted_schema_  -> schema validation is disabled
7. The next deployment fails due to an exception we had to get in p.3 above. Terraform finds the topic’s field schema_settings referring to _deleted_schema_, finds the new schema self_link and tries to update the topic field schema_settings value from _deleted_schema_ to a new schema link. (AGAIN: why updating if the this field is immutable?? Should recreate instead!) However this time Terraform returns an exception the field is not mutable  as it should do.
8. Now the deployment will never succeed due to this error -  thee only way is to delete topic manually and make Terraform recreate it.

### Steps to Reproduce

1. Crete a pair "schema-topic" with terraform
2. Update the existing schema protobuf file and apply the code again
3. The deployment will not return any error cod, the schema will be recreated, but the topic will remain not updated (or recreated) and will refer "deleted schema"
4. Apply the same code again
5. The deployment will fail with error about "immutable field" and never succeed until you delete the topic manually and redeploy it

### Additional info
What I found during the troubleshooting?
The Terraform returns the exception while updating topic’s schema_settings  from old value to the new one, when `old` != `new` . Example `_deleted_schema_` != `<any_valid_schema_self_link>`
The Terraform doesn’t return an exception when  updating topic’s schema_settings  from old value to the new one, when old is equal to new . This occurs when we update the schema in-place, terraform recreates the schema object in GCP, but the name (and self_link) remains the same
Opened question: why terraform still tries to update the object with immutable field instead of recreating it (topic)?
Thanks in advance

**Comment by edwardmedia** [comment] 2022-08-09 16:58
@oleksiilopasov unfortunately this is not the case. Once you apply changes on `google_pubsub_schema`, there is no mechanism in terraform that can **_inform_** `google_pubsub_topic`. One of the solutions you may consider is to apply [taint](https://www.terraform.io/cli/commands/taint). Does this make sense?

```
The topic should get the new value of schema self_link and should also be recreated
```

**Comment by oleksiilopasov** [comment] 2022-08-10 08:28
@edwardmedia Hi, thanks for a quick response
Accoding to to the .tf code
```tf
resource "google_pubsub_topic" "ps_topic" {
  name = google_pubsub_schema.ps_schema.name

  schema_settings {
    schema   = google_pubsub_schema.ps_schema.id
    encoding = "JSON"
  }
}
```
the topic refers schema, so terraform automatically triggers topic to update with new schema id.
BUT
`schema_settings.schema` field is immutable from Pub/Sub API's perspective and topic cannot be updated in-place. It should be recreated the same way, the schema is recreated.
BTW you can not even modify the schema in pubsub the topic manually in Cloud Console, so it's obvious for Terraform to trigger recreation process, not the update in-place
Though (I've just realized) the topic can receive streaming data 24/7 and deleting (recreating) it can cause huge problems while streaming the messages

**Comment by edwardmedia** [comment] 2022-08-10 14:38
@oleksiilopasov did you say it should trigger to recreate `google_pubsub_topic`? I don't think so. Do you see `force recreate` on this resource in the plan?

**Comment by oleksiilopasov** [comment] 2022-08-11 10:45
Ok, it seems we going to refuse from using the schemas. The schema and topic are always working in pair, but have different lifecycles: the schema is always recreated and topic tries to update the immutable field in-place and fails to do that. Each schema recreation breaks this pair :( 
Meanwhile we have realized the second problem - recreating the topic is also not the good idea, cause it's receiving the data messages 24/7. 
Conclusion: GCP should think about maintaining this pair and provide a better solution
Thanks for your help

**Comment by edwardmedia** [comment] 2022-08-11 14:43
@oleksiilopasov sorry about the inconvenience, but I think that is the way by design at Terraform level across all providers. You may think of building `modules` that can put individual resources together to achieve something you described.  Closing this issue then

**Closed by edwardmedia** 2022-08-11 14:43 UTC
Labels: bug
