### ISSUE TITLE
google_sql_database_instance deletion_protection flag does not set deletion protection on the CloudSQL instance

### ISSUE THREAD

**Issue by philip-harvey** [hashicorp/terraform-provider-google#12890] opened 2022-10-26 22:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
1.3.3

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "instance" {
  provider = google-beta

  name             = "private-instance-${random_id.db_name_suffix.hex}"
  region           = "us-central1"
  database_version = "MYSQL_5_7"
deletion_protection = true # actually the default, but just wanted to be clear

  settings {
    tier = "db-f1-micro"
    ip_configuration {
      ipv4_enabled    = false
      private_network = google_compute_network.private_network.id
    }
  }
}
```

### Expected Behavior

Expected that instance deletion protection would be enabled.

### Actual Behavior

Instance deletion protection is not enabled

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is supported via the API.  
https://cloud.google.com/sql/docs/postgres/deletion-protection#rest-v1_1

Tested with Google provider v4.41 and Google beta provider v4.41
Behavior was the same on older provider versions

**Comment by drandell** [comment] 2022-10-27 07:48
duplicate of - https://github.com/hashicorp/terraform-provider-google/issues/12372

**Comment by edwardmedia** [comment] 2022-10-27 15:00
Close as a dup

**Closed by edwardmedia** 2022-10-27 15:00 UTC
Labels: bug
