### ISSUE TITLE
ConfigConnector BackendBucket CDN Not Updating when cacheMode = USE_ORIGIN_HEADERS 

### ISSUE THREAD

**Issue by loganrobertclemons** [hashicorp/terraform-provider-google#13939] opened 2023-03-08 16:32 UTC
This issue is made in conjunction with this GCP Support ticket: 43224166

### Description
DefaultTTL when cache mode is set to USE_ORIGIN_HEADERS is getting set as null by default and attempting to upgrade the resource does not work.

DefaultTTL is getting set to null and the Terraform is not applying successfully:

```
resource "google_storage_bucket" "platform_assets" {
  name          = "${var.appspace_prefix}-${var.appspace_customerName}-${var.appspace_instanceSuffix}-platform-assets.appspacestorage.com"
  location      = "${var.appspace_infra_gcp_region}"
  force_destroy = true

  storage_class = "REGIONAL"

  uniform_bucket_level_access = true

  website {
    main_page_suffix = "index.html"
  }
}

data "google_iam_policy" "object_viewer" {
  binding {
    role = "roles/storage.objectViewer"
    members = [
      "allUsers",
    ]
  }
}

resource "google_storage_bucket_iam_policy" "platform_assets_public_policy" {
  bucket = google_storage_bucket.platform_assets.name
  policy_data = data.google_iam_policy.object_viewer.policy_data

  depends_on = [
    google_storage_bucket.platform_assets
  ]
}

resource "google_compute_backend_bucket" "platform_assets_backend" {
  name        = "${var.appspace_prefix}-${var.appspace_customerName}-${var.appspace_instanceSuffix}-bb-pa"
  description = "Contains appspace UI static assets"
  bucket_name = google_storage_bucket.platform_assets.name
  enable_cdn  = true
  custom_response_headers  = [
    "X-Content-Type-Options:nosniff",
    "Referrer-Policy:strict-origin-when-cross-origin",
    "Strict-Transport-Security:max-age=63072000; includeSubDomains",
    "X-Frame-Options:SAMEORIGIN",
    "server:Appspace"
  ]
  cdn_policy {
   cache_mode = "USE_ORIGIN_HEADERS"
  }

  depends_on = [
    google_storage_bucket.platform_assets
  ]
}
```

Error: Error creating BackendBucket: googleapi: Error 400: Invalid value for field 'resource.cdnPolicy.defaultTtl': '0'. default_ttl cannot be specified with USE_ORIGIN_HEADERS cache_mode., invalid

### Affected Resource(s)
ComputeBackendBucket when cacheMode is set to USE_ORIGIN_HEADERS

google_compute_backend_bucket

### Providers
```
terraform {
  backend "gcs" {
  }
  required_providers {
    google = {
      version = "4.3.0"
    }
  }
}
```

### Additional Notes

Attempting to update it with the gcloud command does work - `gcloud beta compute backend-services update [backend_name_here] --global --cache-mode=CACHE_ALL_STATIC`.

**Comment by edwardmedia** [comment] 2023-03-08 16:39
@loganrobertclemons just curious why you use v4.3.0 of the provider version (vs the latest)?

**Comment by edwardmedia** [comment] 2023-03-08 16:51
The request payload is like this. Looks like `defaultTtl` can't be added in this case

```ts
{
 "bucketName": "issue13939",
 "cdnPolicy": {
  "cacheMode": "USE_ORIGIN_HEADERS",
  "clientTtl": 0,
  "defaultTtl": 0,
  "negativeCaching": false,
  "requestCoalescing": false,
  "serveWhileStale": 0,
  "signedUrlCacheMaxAgeSec": 0
 },
 "customResponseHeaders": [
  "X-Content-Type-Options:nosniff",
  "Referrer-Policy:strict-origin-when-cross-origin",
  "Strict-Transport-Security:max-age=63072000; includeSubDomains",
  "X-Frame-Options:SAMEORIGIN",
  "server:Appspace"
 ],
 "description": "Contains beautiful images",
 "enableCdn": true,
 "name": "issue13939"
}
```

**Comment by edwardmedia** [comment] 2023-03-08 19:31
when `cacheMode` is set `USE_ORIGIN_HEADERS`,  both `clientTtl` and `defaultTtl` need to be removed from the payload

**Comment by edwardmedia** [comment] 2023-03-15 23:27
https://paste.googleplex.com/5376156705488896

**Comment by rileykarson** [comment] 2023-03-16 21:20
Fixing this introduces a regression for https://github.com/hashicorp/terraform-provider-google/issues/10332. Marking as `upstream` as the API needs to tune its validation to be compliant with the proto3-to-json spec.

**Comment by wyardley** [comment] 2023-04-13 23:19
@rileykarson I think this is the same as #10622 and that the custom encoder workaround by a couple of other folks that I reworked in https://github.com/GoogleCloudPlatform/magic-modules/pull/7588 should resolve this?

q: is there an issuetracker issue open for the API behavior already?

**Closed** 2023-04-14 17:41 UTC
Labels: bug, upstream
