### ISSUE TITLE
'default' shortname not supported for service account scope in compute instance resource

### ISSUE THREAD

**Issue by madsonic** [hashicorp/terraform-provider-google#1943] opened 2018-08-25 06:34 UTC
### Terraform Version
Terraform v0.11.8
provider.google v1.17.1

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance

### Expected Behavior
`default` short name should be supported as per [terraform docs](https://www.terraform.io/docs/providers/google/r/compute_instance.html#service_account). such a short name is listed at [gcloud docs](https://cloud.google.com/sdk/gcloud/reference/alpha/compute/instances/set-scopes#--scopes)

### Actual Behavior
```
* google_compute_instance.default: googleapi: Error 400: One or more of the service account scopes are invalid: 'default', serviceAccountScopeInvalid
```

### Steps to Reproduce
set `google_compute_instance.service_account.scopes = ["default"]` and all other required blocks set properly

**Comment by paddycarver** [comment] 2018-08-30 10:40
Sadly, that error seems to be returned by the upstream API, not Terraform, so there's only so much we can do. Could you supply some [debug logs](https://www.terraform.io/docs/internals/debugging.html) so that we can replicate a minimal reproduction to provide to the upstream API team, to try and get this fixed? Or, if it's a problem with how we're calling the API, which is also totally possible, we can fix that. Either way, the best way for us to figure out what's going on is with the debug logs.

**Comment by madsonic** [comment] 2018-09-03 02:27
sure! I might take some time to get back with the logs

**Comment by jnahelou** [comment] 2018-09-04 07:47
In gcloud SDK you can find that scopes aliases are client side defined : 
[/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/constants.py](url)
```py 
SCOPES = {
    'bigquery': ['https://www.googleapis.com/auth/bigquery'],
    ...
    'default':                 
        DEFAULT_SCOPES,        

```
and 
```py
DEFAULT_SCOPES = sorted([
    _STORAGE_RO, _LOGGING_WRITE, _MONITORING_WRITE, _SERVICE_CONTROL_SCOPE,
    _SERVICE_MANAGEMENT_SCOPE, _PUBSUB, _STACKDRIVER_TRACE,
])

```
The documentation is about gcloud CLI.

I think ```default``` alias has not been defined in Google provider because the type is ```map[string]string``` instead of ```map[string][]string```.
```golang
func canonicalizeServiceScope(scope string) string {
	// This is a convenience map of short names used by the gcloud tool
	// to the GCE auth endpoints they alias to.
	scopeMap := map[string]string{
		"bigquery":              "https://www.googleapis.com/auth/bigquery",
		....
```

For my need, I defined a list in my terraform code with this default content..

**Comment by paddycarver** [comment] 2018-11-20 01:55
I think we could probably resolve this at the very least with some documentation, but ideally with a code change, though I don't think Terraform will react super well to us trying to turn one list item into many.

**Comment by danielyaghini** [comment] 2020-03-04 15:41
+1

**Comment by paddycarver** [comment] 2020-03-07 00:42
Spitballing: it may be worth supplying a data source for this instead of hardcoding it in the provider, so people could pass in a shortname to the data source and then interpolate the scopes it returns elsewhere. Not sure if this is a good idea or not, but Terraform would probably react better to it than to one list item becoming many.

**Comment by upodroid** [comment] 2021-02-04 23:59
@rileykarson We can close this one as well. Current guidance is to use cloud-platform scope with custom service accounts.

**Closed** 2021-02-05 18:35 UTC
Labels: documentation, enhancement, size/XS
