### ISSUE TITLE
google_dns_record_set data source should return empty map rather than failing when no data found

### ISSUE THREAD

**Issue by maciekforycki** [hashicorp/terraform-provider-google#12215] opened 2022-08-01 11:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

All? Reproduced at 0.12.31, 0.13.5, 1.2.6

### Affected Resource(s)

data source google_dns_record_set

### Terraform Configuration Files

```tf
data "google_dns_managed_zone" "test" {
  name = "test-zone"
  project = "my-project-id-1234"
}

data "google_dns_record_set" "test" {
  managed_zone = data.google_dns_managed_zone.test.name
  project = "my-project-id-1234"
  name = "non-existing-host.my-domain.com."
  type = "A"
}
```

### Expected Behavior

The data source should return an empty map for non existing recordset.

### Actual Behavior

The data source fails with:

The data source fails with "Error: Only expected 1 record set, got 0" message.

### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment] 2022-08-01 15:32
@maciekforycki Most of resources & data sources behave like this. When you prepare the data source, don't you know if it has records already? Terraform is a tool helping us to build the infrastructure. Not a best one matching other programing languages. This is by design. Closing this issue accordingly

**Closed by edwardmedia** 2022-08-01 15:32 UTC
Labels: bug
