### ISSUE TITLE
unable to provide value for app_yaml_path in app_engine_flexible_app_version

### ISSUE THREAD

**Issue by playersons** [hashicorp/terraform-provider-google#7770] opened 2020-11-10 12:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
0.13.5

### Affected Resource(s)
* app_engine_flexible_app_version

### Terraform Configuration Files

```tf
resource "google_app_engine_flexible_app_version" "hello_world" {
  version_id = "v1"
  project    = "my-project"
  service    = "default"
  runtime    = "python"

  entrypoint {
    shell = "python main.py"
  }

  deployment {
    zip {
      source_url = "https://storage.googleapis.com/my-project-id.appspot.com/hello-world.zip"
    }
    cloud_build_options {
      app_yaml_path = "./hello-world/app.yaml"
    }
  }
...
}
```

### Debug Output

Terraform logs are not available with this error message, but there is a reference to Google Cloud Build logs where following output is shown:

```
Starting Step #1
Step #1: Pulling image: gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa: Pulling from gcp-runtimes/python/gen-dockerfile
Step #1: Digest: sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: Status: Downloaded newer image for gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: Traceback (most recent call last):
Step #1:   File "/builder/gen_dockerfile.py", line 277, in <module>
Step #1:     main()
Step #1:   File "/builder/gen_dockerfile.py", line 273, in main
Step #1:     generate_dockerfile_command(args.base_image, args.config, args.source_dir)
Step #1:   File "/builder/gen_dockerfile.py", line 220, in generate_dockerfile_command
Step #1:     with io.open(config_file, 'r', encoding='utf8') as yaml_config_file:
Step #1: FileNotFoundError: [Errno 2] No such file or directory: './hello-world/app.yaml'
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa" failed: step exited with non-zero status: 1
``` 

### Expected Behavior

The Google App Engine app should have been deployed with instance configuration from the app.yaml.

### Actual Behavior

The error message above indicates that the app.yaml file could not be found. This error persists, regardless of any value that is being provided as the path attribute within the deployment argument block. Unfortunately, the Terraform documentation is not being clear about the expected format, location, etc - and neither is the Google documentation (e.g. https://cloud.google.com/appengine/docs/flexible/python) 

* "./app.yaml"
* "./hello-world/app.yaml"
* "gs://app-engine-bucket/hello-world/app.yaml"
* "gs://app-engine-bucket/app.yaml"
 
### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment] 2020-11-10 14:43
@playersons below is the official doc you may reference. Is the file `app.yam` available in the `https://storage.googleapis.com/my-project-id.appspot.com/hello-world.zip`? If not, can you try by adding it into the zip? 

https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions#cloudbuildoptions

**Comment by playersons** [comment] 2020-11-10 14:59
@edwardmedia thanks for your reply, the app.yaml is in the .zip archive.

**Comment by edwardmedia** [comment] 2020-11-10 17:05
@playersons did you try by something like below if it is at the root of zip file?

```
    cloud_build_options {
      app_yaml_path = "app.yaml"
    }
```

**Comment by playersons** [comment] 2020-11-10 17:22
@edwardmedia appreciate your support, my tf code looks like this here:
```
deployment {
    zip {
      source_url = "https://storage.googleapis.com/my-project-id.appspot.com/hello-world.zip"
    }
    cloud_build_options {
      app_yaml_path = "app.yaml"
    }
  }
```

**Comment by playersons** [comment] 2020-11-10 17:29
thank you, @edwardmedia appreciate your support. my tf code looks like this here
```
deployment {
    zip {
      source_url = "https://storage.googleapis.com/my-project-id.appspot.com/hello-world.zip"
    }
    cloud_build_options {
      app_yaml_path = "app.yaml"
    }
  }
```

**Comment by edwardmedia** [comment] 2020-11-10 18:32
@playersons  can you share the file structure of your `hello-world.zip`? Did you have app.yaml at root?

**Comment by playersons** [comment] 2020-11-11 08:21
this is the content of my hello-world.zip
```
.
├── __pycache__
├── app.yaml
├── main.py
├── main_test.py
├── requirements-test.txt
└── requirements.txt
```

**Comment by edwardmedia** [comment] 2020-11-11 15:50
@playersons what error do you get? Can you post the full TF debug log (you mentioned the log not available, can you explain why?)

**Comment by playersons** [comment] 2020-11-11 16:52
@edwardmedia I was trying to say that TF does not provide very much information in its debug log but does refer to the Cloud Build log instead. This is what TF provides:

```
2020-11-11T17:46:01.506+0100 [DEBUG] plugin.terraform-provider-google_v3.47.0_x5: 2020/11/11 17:46:01 [DEBUG] Unlocked "apps/my-project-id"
2020/11/11 17:46:01 [DEBUG] google_app_engine_flexible_app_version.hello_world: apply errored, but we're indicating that via the Error pointer rather than returning it: Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: Error code 9, message: Cloud build 4b26ccc6-de85-4f05-9185-cc9030f801b3 status: FAILURE
Build error details: Build error details not available.
Full build logs: https://console.cloud.google.com/cloud-build/builds/4b26ccc6-de85-4f05-9185-cc9030f801b3?project=985056533285
2020/11/11 17:46:01 [ERROR] eval: *terraform.EvalApplyPost, err: Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: Error code 9, message: Cloud build 4b26ccc6-de85-4f05-9185-cc9030f801b3 status: FAILURE
Build error details: Build error details not available.
Full build logs: https://console.cloud.google.com/cloud-build/builds/4b26ccc6-de85-4f05-9185-cc9030f801b3?project=985056533285
2020/11/11 17:46:01 [ERROR] eval: *terraform.EvalSequence, err: Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: Error code 9, message: Cloud build 4b26ccc6-de85-4f05-9185-cc9030f801b3 status: FAILURE
Build error details: Build error details not available.
Full build logs: https://console.cloud.google.com/cloud-build/builds/4b26ccc6-de85-4f05-9185-cc9030f801b3?project=985056533285

Error: Error waiting to create FlexibleAppVersion: Error waiting for Creating FlexibleAppVersion: Error code 9, message: Cloud build 4b26ccc6-de85-4f05-9185-cc9030f801b3 status: FAILURE
Build error details: Build error details not available.
Full build logs: https://console.cloud.google.com/cloud-build/builds/4b26ccc6-de85-4f05-9185-cc9030f801b3?project=985056533285


2020-11-11T17:46:01.521+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-11-11T17:46:01.524+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/google/3.47.0/darwin_amd64/terraform-provider-google_v3.47.0_x5 pid=24698
2020-11-11T17:46:01.524+0100 [DEBUG] plugin: plugin exited
```

and this is what's there in Cloud Build:

```
starting build "4b26ccc6-de85-4f05-9185-cc9030f801b3"

FETCHSOURCE
BUILD
Starting Step #0 - "fetcher"
Step #0 - "fetcher": Already have image (with digest): gcr.io/cloud-builders/gcs-fetcher
Step #0 - "fetcher": WARNING: -type=Archive is deprecated; use -type=ZipArchive
Step #0 - "fetcher": Fetching archive gs://my-project-id.appspot.com/hello-world.zip.
Step #0 - "fetcher": ******************************************************
Step #0 - "fetcher": Status:                      SUCCESS
Step #0 - "fetcher": Started:                     2020-11-11T16:45:48Z
Step #0 - "fetcher": Completed:                   2020-11-11T16:45:49Z
Step #0 - "fetcher": Total files:            5
Step #0 - "fetcher": MiB downloaded:         0.00 MiB
Step #0 - "fetcher": MiB/s throughput:       0.01 MiB/s
Step #0 - "fetcher": Time for zipfile:       0.23 s
Step #0 - "fetcher": Time to unzip:          0.00 s
Step #0 - "fetcher": Total time:             0.24 s
Step #0 - "fetcher": ******************************************************
Finished Step #0 - "fetcher"
Starting Step #1
Step #1: Pulling image: gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa: Pulling from gcp-runtimes/python/gen-dockerfile
Step #1: Digest: sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: Status: Downloaded newer image for gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa
Step #1: Traceback (most recent call last):
Step #1:   File "/builder/gen_dockerfile.py", line 277, in <module>
Step #1:     main()
Step #1:   File "/builder/gen_dockerfile.py", line 273, in main
Step #1:     generate_dockerfile_command(args.base_image, args.config, args.source_dir)
Step #1:   File "/builder/gen_dockerfile.py", line 220, in generate_dockerfile_command
Step #1:     with io.open(config_file, 'r', encoding='utf8') as yaml_config_file:
Step #1: FileNotFoundError: [Errno 2] No such file or directory: 'app.yaml'
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/gcp-runtimes/python/gen-dockerfile@sha256:ac444fc620f70ff80c19cde48d18242dbed63056e434f0039bf939433e7464aa" failed: step exited with non-zero status: 1
```

**Comment by edwardmedia** [comment] 2020-11-16 18:05
@playersons I am able to deploy a sample to `app engine flexible`.  I have the `app.yaml` at the root and it is good for me.  I suspect the zip file structure. How did you create the zip file? What do you see by run `vim hello-world.zip`?

**Comment by edwardmedia** [comment] 2020-11-17 18:35
@playersons  Is this still an issue? If yes, as I suggested, double check the zip file structure, or post the result by running vim  command.

**Comment by playersons** [comment] 2020-11-18 08:16
the zip file structure is as follows:
```
" zip.vim version v28
" Select a file with cursor and press ENTER

hello_world/app.yaml
hello_world/main.py
hello_world/main_test.py
hello_world/requirements-test.txt
hello_world/requirements.txt
```

**Comment by edwardmedia** [comment] 2020-11-18 17:39
@playersons looks like there is a folder `hello_world` at the root, and app.yaml is in that folder (not at the root). You may try below command to create the zip file. Let me know if you see the difference
```
zip hello_world.zip app.yaml main.py...
```

**Comment by playersons** [comment] 2020-11-19 12:35
the app.yaml file is present at the root:
```
gsutil ls gs://my-service-bucket.appspot.com
gs://my-service-bucket.appspot.com/app.yaml
gs://my-service-bucket.appspot.com/hello-world.zip
```

**Comment by edwardmedia** [comment] 2020-11-19 14:06
@playersons there is just one file needed which is the `gs://my-service-bucket.appspot.com/hello-world.zip`. `app.yaml` is at the root of `hello-world.zip` file.If you don't want to recreate the zip file, you may also try removing **./** from the 2nd one of your original list

"./hello-world/app.yaml"   ---> "hello-world/app.yaml"

**Comment by edwardmedia** [comment] 2020-11-19 16:48
@playersons Below structure indicates the app.yaml file is NOT at the root of the zip file. I tested my suggestion and it works for me. Please try what I have suggested. Closing this issue as it can't be reproduced. 

```
" zip.vim version v28
" Select a file with cursor and press ENTER

hello_world/app.yaml
hello_world/main.py
hello_world/main_test.py
hello_world/requirements-test.txt
hello_world/requirements.txt
```

**Closed by edwardmedia** 2020-11-19 16:48 UTC
Labels: question
