### ISSUE TITLE
CLOUD_IAM_GROUP_SERVICE_ACCOUNT not supported by google_sql_user

### ISSUE THREAD

**Issue by lodotek** [hashicorp/terraform-provider-google#18283] opened 2024-05-30 17:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.3
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.8.4. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

google_sql_user

### Terraform Configuration

```tf
resource "google_sql_user" "schema_grantor_job" {
  name     = "${var.cluster_name}-cloudsql-schema-grantor"
  # name     = module.cloudsql_schema_grantor_sa.email
  instance = module.cloudsql[count.index].mysql_instance.name
  type     = "CLOUD_IAM_GROUP_SERVICE_ACCOUNT"
}
```

### Actual Behavior

╷
│ Error: expected type to be one of ["BUILT_IN" "CLOUD_IAM_USER" "CLOUD_IAM_GROUP" "CLOUD_IAM_SERVICE_ACCOUNT" ""], got CLOUD_IAM_GROUP_SERVICE_ACCOUNT
│ 
│   with google_sql_user.schema_grantor_job,
│   on main.tf line 142, in resource "google_sql_user" "schema_grantor_job":
│  142:   type     = "CLOUD_IAM_GROUP_SERVICE_ACCOUNT" ## TODO: Codify once this is supported by terraform-google-provider
│ 
╵
make: *** [plan] Error 1

### Steps to reproduce

1. `terraform apply`

### References

https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/users#sqlusertype

b/343783464

**Comment by ggtisc** [comment] 2024-05-30 21:45
Confirmed issue!

As the user reports after a `terraform apply` if the attribute type is equal to `CLOUD_IAM_GROUP_SERVICE_ACCOUNT` it returns the next error:

`Error: expected type to be one of ["BUILT_IN" "CLOUD_IAM_USER" "CLOUD_IAM_GROUP" "CLOUD_IAM_SERVICE_ACCOUNT" ""], got CLOUD_IAM_GROUP_SERVICE_ACCOUNT`

In [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user#type) this isn't valid, but in [Google Cloud documentation](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/users#SqlUserType) it is declared as a valid type.

**Comment by roaks3** [comment] 2024-06-05 16:55
From the service team:

> This feature is working as intended. Customer can use the `CLOUD_IAM_GROUP` for creating Cloud SQL IAM group user via Terraform and then add a service account or a member user account to the group for managing permissions.

It's true that the REST API appears to offer a `CLOUD_IAM_GROUP_SERVICE_ACCOUNT` option, but it appears that this is not intended to be used for Terraform, and our [registry docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user#type) support that.

Closing as Working as Intended

**Closed by roaks3** 2024-06-05 16:55 UTC
Labels: bug, forward/linked, service/sqladmin-infra
