### ISSUE TITLE
Can't create firebase project when authenticated with user account

### ISSUE THREAD

**Issue by maurocolella** [hashicorp/terraform-provider-google#8287] opened 2021-01-25 09:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform 0.14.5 (latest).
google and google-beta providers 3.53.0 (latest).

### Affected Resource(s)

`google_firebase_project`
`google_firebase_web_app`
`google_firebase_web_app_config`

### Terraform Configuration Files

```tf
resource "google_firebase_project" "join_form" {
    provider          = google-beta
    project           = var.project_id
}

resource "google_firebase_web_app" "basic" {
  provider            =  google-beta
  project             =  var.project_id
  display_name        = "Join Form"

  depends_on          = [google_firebase_project.join_form]
}

data "google_firebase_web_app_config" "basic" {
  provider            = google-beta
  web_app_id          = google_firebase_web_app.basic.app_id
}
```

### Debug Output

Output not from debug mode for resource. Received:

```
Error: Error creating Project: googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the firebase.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/xxx",
      "service": "firebase.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
```

### Expected Behavior

The Firebase project should probably be created if it doesn't exist. Even when authenticated as a user, as is the case (GCP project owner), for troubleshooting purposes. If the behavior is similar to App Engine, where projects cannot be destroyed, it would be great to be informed, and advised to use the import feature of terraform.

### Actual Behavior

```
Error: Error creating Project: googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the firebase.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/xxx",
      "service": "firebase.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
```

The resources were not created in Firebase.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I was authenticated as a user when creating the Firebase project. The idea here is to start from, and return to a Google Cloud Project that is empty as it possibly can be. I am not starting with anything except organization roles, ie. projects owners and platform admins.

### References

* #5388

**Comment by edwardmedia** [comment] 2021-01-25 14:29
@maurocolella how do you provide the credential that runs Terraform? What do you mean below?
>I was authenticated as a user when creating the Firebase project.

In the meantime, can you share the full debug log that includes all api requests?

**Comment by maurocolella** [comment] 2021-01-26 09:36
It means that I am running `gcloud auth login` and signing in with Google user credentials, as opposed to using a token or a service account.

I am not comfortable sharing the complete debug log for security/confidentiality reasons, but I have prepared a gist with a simple `grep` on the logs, using "firebase" for matching.

https://gist.github.com/maurocolella/59b58506c32353eabf2dba2f3842bdb0

**Comment by edwardmedia** [comment] 2021-01-26 13:56
@maurocolella the issue is likely related to how you provide the credentials for the Terraform runner. Below is the *the preferred method of provisioning resources with Terraform*. Please follow it to see if that helps resolve your issue. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials

**Comment by maurocolella** [comment] 2021-01-26 14:13
@edwardmedia thanks. This was also suggested in issue #5388.

I understand the security benefits and that this makes sense in CI.

With that considered:
1. Resources related to Firebase are the only resources with which we encounter this issue.
2. If this is a project in its default state, am I required to manually register a service account?
3. What if I want to automate project creation for an organization?

I will test using a service account and report, but I can see multiple use cases where it could be useful to perform firebase provisioning from a _user_ account.

**Comment by edwardmedia** [comment] 2021-01-27 15:41
@maurocolella look at the error from **googleapi**, you might still be able to use the end user account. You can try by following the googleapi suggestion, but that is beyond the Terraform provider. 
>If this is a project in its default state, am I required to manually register a service account?

I don't understand what you mean above
>What if I want to automate project creation for an organization?

Shouldn't using a service account better for the automation?

Reset `waiting response` for your report if you still need support 
>I will test using a service account and report,

**Comment by edwardmedia** [comment] 2021-02-07 18:04
@maurocolella closing this issue then. Feel free to reopen if you still have questions

**Closed by edwardmedia** 2021-02-07 18:04 UTC
Labels: bug, waiting-response

**Comment by maurocolella** [comment] 2021-02-08 01:23
Just to clarify something: as stated in the initial inquiry, I have an **owner** account on the Google Cloud **enterprise** project. Billing is enabled, and the account I use to run terraform has extensive privileges over all enabled services.

It probably shouldn't matter how I authenticate. 

Likewise, we expect a certain level of idempotency. Ideally, teardown should be the reverse operation to a build-up, or at the very least it should be _safe._ We are looking to accelerate our workflow.

Due to this, and platform-specific limitations (App Engine top-level app not destructible, queues that can't be recreated with the same name before seven days...), we've had to treat the google cloud provider as beta, as it doesn't have entirely predictable behavior, and some issues have no workaround at all.

This is viable to quickly bring a platform up, with some caveats. But it's definitely more of a "reference" than a tool on which we can depend in any kind of consistent fashion.
