### ISSUE TITLE
Sigsev error with Google Dataproc creation error with Virtual Cluster Config and Gke Cluster Config

### ISSUE THREAD

**Issue by srevinsaju** [hashicorp/terraform-provider-google#14457] opened 2023-04-29 06:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.4.6
on linux_amd64
```

### Affected Resource(s)

* Tested between v4.56.0 and v4.62.1

### Terraform Configuration Files

```tf
resource "google_dataproc_cluster" "dataproc" {
  name                          = "my-dataproc"
  region                        = "us-east1"
  project                       = var.project_id
  graceful_decommission_timeout = "120s"

  virtual_cluster_config {
    kubernetes_cluster_config {
      kubernetes_namespace = "sorcero-dataproc"

      kubernetes_software_config {
        component_version = {
          "SPARK" : "3.1-dataproc-13"
        }
      }

      gke_cluster_config {
        gke_cluster_target = module.gke.cluster_id

        node_pool_target {
          node_pool = "dataproc-gke"
          roles     = ["DEFAULT"]

          node_pool_config {
            autoscaling {
              min_node_count = 1
              max_node_count = 6
            }

            config {
              machine_type    = "n2-standard-8"
              local_ssd_count = 1
            }

            locations = ["us-east1-b"]
          }
        }
      }
    }
  }

}

module "gke" {
  source                            = "terraform-google-modules/kubernetes-engine/google"
  version                           = "25.0.0"
  project_id                        = var.project_id
  name                              = "gke-cluster"
  release_channel                   = "STABLE"
  region                            = "us-east1"
  network                           = "default"
  subnetwork                        = "default"
  ip_range_pods                     = ""
  ip_range_services                 = ""
}
variable "project_id" {
  type    = string
}
```

### Panic Output

```
google_dataproc_cluster.dataproc: Still creating... [1m50s elapsed]
google_dataproc_cluster.dataproc: Still creating... [2m0s elapsed]
╷
│ Error: Plugin did not respond
│
│   with google_dataproc_cluster.dataproc,
│   on dataproc.tf line 2, in resource "google_dataproc_cluster" "dataproc":
│    2: resource "google_dataproc_cluster" "dataproc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google_v4.62.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x24cf880]

goroutine 29 [running]:
github.com/hashicorp/terraform-provider-google/google.flattenGceClusterConfig(0x2c98920?, 0x0)
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:2423 +0x40
github.com/hashicorp/terraform-provider-google/google.flattenClusterConfig(0xc00264aa00?, 0xc0001cc780)
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:2235 +0x1de
github.com/hashicorp/terraform-provider-google/google.resourceDataprocClusterRead(0x31cadb5?, {0x311b4a0?, 0xc002430000})
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:2089 +0x465
github.com/hashicorp/terraform-provider-google/google.resourceDataprocClusterCreate(0x0?, {0x311b4a0?, 0xc002430000})
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:1353 +0x5f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x3748ed8?, {0x3748ed8?, 0xc00246c5d0?}, 0xd?, {0x311b4a0?, 0xc002430000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0011f5c00, {0x3748ed8, 0xc00246c5d0}, 0xc00102e1a0, 0xc001d0d980, {0x311b4a0, 0xc002430000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0012aa708, {0x3748ed8?, 0xc00246c4b0?}, 0xc002460230)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc001246810, 0xc001246870, {0xc001804580, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0013801e0, {0x3748ed8?, 0xc002427a40?}, 0xc00036bea0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x30a1d00?, 0xc0013801e0}, {0x3748ed8, 0xc002427a40}, 0xc00036be30, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006fbe00, {0x37500a0, 0xc001819860}, 0xc00174f320, 0xc001876cf0, 0x4a81160, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0006fbe00, {0x37500a0, 0xc001819860}, 0xc00174f320, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-google_v4.62.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

The creation should complete successful. 

### Actual Behavior

Segmentation fault. Further terraform plans also fail.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

NA

### References

https://github.com/GoogleCloudPlatform/magic-modules/pull/7811

**Comment by melinath** [comment] 2023-05-02 20:59
I was able to reproduce this issue on 4.63.1 with the configuration above. I'm not sure why this error is happening when we have a very similar test ([TestAccDataprocVirtualCluster_basic](https://github.com/hashicorp/terraform-provider-google/blob/7d2f95669ad0db1fca79c388bfc88c53762f7098/google/resource_dataproc_cluster_test.go#L219)) that is passing consistently. I'll look into it as part of reviewing the PR.

**Comment by melinath** [comment] 2023-05-04 23:12
Looked into this a bit today - it turns out that this bug has existed since the virtual cluster config support was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/6143. I'm not clear why this hasn't been reported before (and I'm _still_ not clear on why our tests are passing in nightly builds - I can't get them to pass locally for unrelated reasons.)

It looks like the client library _always_ returns a (empty) value for ClusterConfig, even if clusterConfig is unset in the API response.

The provider code currently checks whether cluster.Config is a `nil` pointer: https://github.com/hashicorp/terraform-provider-google/blob/14c4df39c94c4c1bc675241fbaf4376e4a5c8a8e/google/resource_dataproc_cluster.go#L2091

But it looks like the pointer is _never_ nil, it just points to a struct with no useful values if it's not set.

**Comment by melinath** [comment] 2023-05-04 23:18
ah, it looks like our tests for dataproc do some custom checking of specific attributes rather than a standard import verify step, because dataproc cluster doesn't support importing. That probably explains why we didn't catch any issues related to this earlier.

**Comment by lorenzostorchi** [comment] 2023-05-05 16:16
Hi, I came across this issue because I have the same problem.
I looked deeper both in source code and debug prints and I found out that `cluster_config` has Computed attribute set to True. That means its value will be "unknown" in the plan and eventually will be set at runtime. This is fine, but apparently a nested block can't be "unknown":

2023-05-05T17:10:05.652+0200 [WARN]  Provider "registry.terraform.io/hashicorp/google" produced an invalid plan for google_dataproc_cluster.dataproc-cluster, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .graceful_decommission_timeout: planned value cty.StringVal("0s") for a non-computed attribute
      **- .cluster_config: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead**
      - .virtual_cluster_config[0].auxiliary_services_config: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
     
So, maybe this is why cluster.Config will never be nil.
Also I don't know if there exists a method that can check if an element (or its children) is "unknown" but that could be a workaround.

**Comment by melinath** [comment] 2023-06-12 16:32
@srevinsaju it looks like this issue was likely resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7917 - let us know if you're still seeing it!

**Closed by melinath** 2023-06-12 16:32 UTC
Labels: bug, crash
