### ISSUE TITLE
I want to create a vm and it should run one powershell script inside it but when ever i'm trying to Provision  the file its throwing timeout error

### ISSUE THREAD

**Issue by vandana-alyana** [hashicorp/terraform-provider-google#14982] opened 2023-06-26 12:34 UTC
Error: file provisioner error
│
│   with google_compute_instance.default,
│   on main.tf line 32, in resource "google_compute_instance" "default":
│   32:   provisioner "file" {
│
│ timeout - last error: dial tcp 34.83.231.249:22: i/o timeout

**Comment by edwardmedia** [comment] 2023-06-26 13:16
@vandana-alyana I am not clear what the problem is. Can you share you config?

**Comment by edwardmedia** [comment] 2023-06-26 15:13
@vandana-alyana What do you mean `should reflect on azure arc`?  I think this is the [terraform](https://developer.hashicorp.com/terraform/language/resources/provisioners/null_resource) feature. You may want to reach out the Terraform to see if they can help. Sorry I don't know much about it.

**Comment by vandana-alyana** [comment] 2023-06-27 04:59
I Want to create a Vm where inside I'm running the powershell script.
I'm getting timeout error.

**Comment by edwardmedia** [comment] 2023-06-27 15:27
@vandana-alyana have you tried manually running the scripts after the vm is created? If you can, you may need to figure out a right way to automate it if that is what you want, but that is beyond what the site can provide for help. If you face an issue in creating the vm with the attributes you need, that is what we can do here. Does this make sense?

**Comment by iennae** [comment] 2023-06-28 05:46
@vandana-alyana it sounds like you are trying to use the Azure Arc service to do multi-cloud and trying to set-up the installation agent. If it's timing out, that sounds like something that you'll need to sort out the requirements to run. It's unclear what's timing out but the error you posted with timeout - last error: dial tcp 34.83.231.249:22: i/o timeout sounds like there is a missing network rule that you'll need to configure. It's not clear what is missing that rule. 

Your best bet is if you have a support contract with Google to create an issue in the support console (https://cloud.google.com/support/) or talking to your Azure support to figure out what you need to configure so that your instance can phone home. This GitHub repository is for the Google terraform provider and the problem you are having isn't with the provider.

**Comment by edwardmedia** [comment] 2023-07-10 13:27
@vandana-alyana closing this assuming this is no longer a question

**Closed by edwardmedia** 2023-07-10 13:27 UTC
Labels: question, waiting-response
