### ISSUE TITLE
Error: googleapi: Error 400: Operation operation-... is currently deleting a node pool for cluster default-cluster. Please wait and try again once it is done., failedPrecondition

### ISSUE THREAD

**Issue by jsoref** [hashicorp/terraform-provider-google#10366] opened 2021-10-21 18:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
  "terraform_version": "0.12.26",

### Affected Resource(s)

* google_container_node_pool
* google_container_cluster

### Terraform Configuration Files

I don't have the terraform files handy (we use atlantis), so, here's roughly what atlantis showed:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:
```

```tf
  # google_container_cluster.default-cluster will be updated in-place
~ resource "google_container_cluster" "default-cluster" {
        cluster_ipv4_cidr           = "10.52.0.0/14"
        default_max_pods_per_node   = 110
        enable_binary_authorization = false
        enable_intranode_visibility = false
        enable_kubernetes_alpha     = false
        enable_legacy_abac          = false
        enable_shielded_nodes       = true
        enable_tpu                  = false
        endpoint                    = "endpoint-ip"
        id                          = "projects/something/locations/us-central1/clusters/default-cluster"
        initial_node_count          = 1
        instance_group_urls         = [
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-a/instanceGroups/gke-default-cluster-default-pool-a22c9cf6-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-b/instanceGroups/gke-default-cluster-default-pool-ef503e49-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-c/instanceGroups/gke-default-cluster-default-pool-f7d54a4a-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-a/instanceGroups/gke-default-cluster-green-40bc61d2-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-b/instanceGroups/gke-default-cluster-green-6c72f0a8-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-c/instanceGroups/gke-default-cluster-green-8f848210-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-a/instanceGroups/gke-default-cluster-basic-green-4777bf38-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-b/instanceGroups/gke-default-cluster-basic-green-869e1113-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-c/instanceGroups/gke-default-cluster-basic-green-79e12cba-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-a/instanceGroups/gke-default-cluster-extra-green-3483bd1a-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-b/instanceGroups/gke-default-cluster-extra-green-d613c7e9-grp",
            "https://www.googleapis.com/compute/beta/projects/something/zones/us-central1-c/instanceGroups/gke-default-cluster-extra-green-a728fe15-grp",
        ]
        label_fingerprint           = "meh"
        location                    = "us-central1"
        logging_service             = "logging.googleapis.com/kubernetes"
        master_version              = "1.20.9-gke.1001"
        monitoring_service          = "monitoring.googleapis.com/kubernetes"
        name                        = "default-cluster"
        network                     = "projects/something/global/networks/default"
        networking_mode             = "VPC_NATIVE"
        node_locations              = [
            "us-central1-a",
            "us-central1-b",
            "us-central1-c",
        ]
        node_version                = "1.20.9-gke.701"
        project                     = "something"
        remove_default_node_pool    = true
        resource_labels             = {}
        self_link                   = "https://container.googleapis.com/v1beta1/projects/something/locations/us-central1/clusters/default-cluster"
        services_ipv4_cidr          = "10.0.0.0/20"
        subnetwork                  = "projects/something/regions/us-central1/subnetworks/default"

        addons_config {

            istio_config {
                disabled = true
            }

            network_policy_config {
                disabled = true
            }
        }

        cluster_autoscaling {
            autoscaling_profile = "BALANCED"
            enabled             = false
        }

        cluster_telemetry {
            type = "ENABLED"
        }

        database_encryption {
            state = "DECRYPTED"
        }

        default_snat_status {
            disabled = false
        }

        ip_allocation_policy {
            cluster_ipv4_cidr_block       = "10.52.0.0/14"
            cluster_secondary_range_name  = "gke-default-cluster-pods-039d41ed"
            services_ipv4_cidr_block      = "10.0.0.0/20"
            services_secondary_range_name = "gke-default-cluster-services-039d41ed"
        }

        maintenance_policy {
            daily_maintenance_window {
                duration   = "PT4H0M0S"
                start_time = "08:00"
            }
        }

        master_auth {
            cluster_ca_certificate = "redacted"

            client_certificate_config {
                issue_client_certificate = false
            }
        }

      ~ master_authorized_networks_config {
          - cidr_blocks {
              - cidr_block = "10.1.2.3/32" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.1.2.3/32"
            }
          - cidr_blocks {
              - cidr_block = "10.2.4.6/32" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.2.4.6/32"
            }
          - cidr_blocks {
              - cidr_block = "10.3.6.9/32" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.3.6.9/32"
            }
          - cidr_blocks {
              - cidr_block = "10.4.2.8/32" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.4.2.8/32"
            }
          - cidr_blocks {
              - cidr_block = "10.5.7.9/32" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.5.7.9/32"
            }
          - cidr_blocks {
              - cidr_block = "10.6.9.3/29" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.6.9.3/29"
            }
          + cidr_blocks {
              + cidr_block = "10.7.11.15/32"
            }
          - cidr_blocks {
              - cidr_block = "10.8.16.32/32" -> null
            }
          + cidr_blocks {
              + cidr_block = "10.8.16.32/32"
            }
        }

        network_policy {
            enabled  = false
            provider = "PROVIDER_UNSPECIFIED"
        }

        node_config {
            disk_size_gb      = 50
            disk_type         = "pd-standard"
            guest_accelerator = []
            image_type        = "COS_CONTAINERD"
            labels            = {}
            local_ssd_count   = 0
            machine_type      = "n1-standard-4"
            metadata          = {
                "disable-legacy-endpoints" = "true"
            }
            oauth_scopes      = [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/userinfo.email",
            ]
            preemptible       = false
            service_account   = "kubernetes-default@something.iam.gserviceaccount.com"
            tags              = [
                "default-pool",
            ]
            taint             = []

            shielded_instance_config {
                enable_integrity_monitoring = false
                enable_secure_boot          = true
            }

            workload_metadata_config {
                node_metadata = "GKE_METADATA_SERVER"
            }
        }

        node_pool {
            initial_node_count  = 0
            instance_group_urls = [
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-a/instanceGroupManagers/gke-default-cluster-default-pool-a22c9cf6-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-b/instanceGroupManagers/gke-default-cluster-default-pool-ef503e49-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-c/instanceGroupManagers/gke-default-cluster-default-pool-f7d54a4a-grp",
            ]
            max_pods_per_node   = 110
            name                = "default-pool"
            node_count          = 0
            node_locations      = [
                "us-central1-a",
                "us-central1-b",
                "us-central1-c",
            ]
            version             = "1.20.9-gke.701"

            management {
                auto_repair  = true
                auto_upgrade = true
            }

            node_config {
                disk_size_gb      = 50
                disk_type         = "pd-standard"
                guest_accelerator = []
                image_type        = "COS_CONTAINERD"
                labels            = {}
                local_ssd_count   = 0
                machine_type      = "n1-standard-4"
                metadata          = {
                    "disable-legacy-endpoints" = "true"
                }
                oauth_scopes      = [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/userinfo.email",
                ]
                preemptible       = false
                service_account   = "kubernetes-default@something.iam.gserviceaccount.com"
                tags              = [
                    "default-pool",
                ]
                taint             = []

                shielded_instance_config {
                    enable_integrity_monitoring = false
                    enable_secure_boot          = true
                }

                workload_metadata_config {
                    node_metadata = "GKE_METADATA_SERVER"
                }
            }

            upgrade_settings {
                max_surge       = 3
                max_unavailable = 0
            }
        }
        node_pool {
            initial_node_count  = 13
            instance_group_urls = [
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-a/instanceGroupManagers/gke-default-cluster-green-40bc61d2-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-b/instanceGroupManagers/gke-default-cluster-green-6c72f0a8-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-c/instanceGroupManagers/gke-default-cluster-green-8f848210-grp",
            ]
            max_pods_per_node   = 110
            name                = "green"
            node_count          = 9
            node_locations      = [
                "us-central1-a",
                "us-central1-b",
                "us-central1-c",
            ]
            version             = "1.20.9-gke.1001"

            autoscaling {
                max_node_count = 20
                min_node_count = 0
            }

            management {
                auto_repair  = true
                auto_upgrade = true
            }

            node_config {
                disk_size_gb      = 250
                disk_type         = "pd-ssd"
                guest_accelerator = []
                image_type        = "COS_CONTAINERD"
                labels            = {}
                local_ssd_count   = 0
                machine_type      = "n2-standard-8"
                metadata          = {
                    "disable-legacy-endpoints" = "true"
                }
                oauth_scopes      = [
                    "https://www.googleapis.com/auth/cloud-platform",
                ]
                preemptible       = false
                service_account   = "kubernetes-default@something.iam.gserviceaccount.com"
                tags              = [
                    "default-pool",
                ]
                taint             = []

                shielded_instance_config {
                    enable_integrity_monitoring = true
                    enable_secure_boot          = true
                }

                workload_metadata_config {
                    node_metadata = "GKE_METADATA_SERVER"
                }
            }

            upgrade_settings {
                max_surge       = 6
                max_unavailable = 0
            }
        }
        node_pool {
            initial_node_count  = 3
            instance_group_urls = [
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-a/instanceGroupManagers/gke-default-cluster-basic-green-4777bf38-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-b/instanceGroupManagers/gke-default-cluster-basic-green-869e1113-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-c/instanceGroupManagers/gke-default-cluster-basic-green-79e12cba-grp",
            ]
            max_pods_per_node   = 110
            name                = "basic-green"
            node_count          = 1
            node_locations      = [
                "us-central1-a",
                "us-central1-b",
                "us-central1-c",
            ]
            version             = "1.20.9-gke.1001"

            autoscaling {
                max_node_count = 20
                min_node_count = 1
            }

            management {
                auto_repair  = true
                auto_upgrade = true
            }

            node_config {
                disk_size_gb      = 100
                disk_type         = "pd-ssd"
                guest_accelerator = []
                image_type        = "COS_CONTAINERD"
                labels            = {}
                local_ssd_count   = 0
                machine_type      = "n1-standard-4"
                metadata          = {
                    "disable-legacy-endpoints" = "true"
                }
                oauth_scopes      = [
                    "https://www.googleapis.com/auth/cloud-platform",
                ]
                preemptible       = false
                service_account   = "kubernetes-default@something.iam.gserviceaccount.com"
                tags              = [
                    "default-pool",
                ]
                taint             = []

                shielded_instance_config {
                    enable_integrity_monitoring = true
                    enable_secure_boot          = true
                }

                workload_metadata_config {
                    node_metadata = "GKE_METADATA_SERVER"
                }
            }

            upgrade_settings {
                max_surge       = 3
                max_unavailable = 0
            }
        }
        node_pool {
            initial_node_count  = 4
            instance_group_urls = [
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-a/instanceGroupManagers/gke-default-cluster-extra-green-3483bd1a-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-b/instanceGroupManagers/gke-default-cluster-extra-green-d613c7e9-grp",
                "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-c/instanceGroupManagers/gke-default-cluster-extra-green-a728fe15-grp",
            ]
            max_pods_per_node   = 110
            name                = "extra-green"
            node_count          = 2
            node_locations      = [
                "us-central1-a",
                "us-central1-b",
                "us-central1-c",
            ]
            version             = "1.20.9-gke.1001"

            autoscaling {
                max_node_count = 4
                min_node_count = 2
            }

            management {
                auto_repair  = true
                auto_upgrade = true
            }

            node_config {
                disk_size_gb      = 250
                disk_type         = "pd-ssd"
                guest_accelerator = []
                image_type        = "COS_CONTAINERD"
                labels            = {}
                local_ssd_count   = 0
                machine_type      = "n2-standard-16"
                metadata          = {
                    "disable-legacy-endpoints" = "true"
                }
                oauth_scopes      = [
                    "https://www.googleapis.com/auth/cloud-platform",
                ]
                preemptible       = false
                service_account   = "kubernetes-default@something.iam.gserviceaccount.com"
                tags              = [
                    "default-pool",
                ]
                taint             = []

                shielded_instance_config {
                    enable_integrity_monitoring = true
                    enable_secure_boot          = true
                }

                workload_metadata_config {
                    node_metadata = "GKE_METADATA_SERVER"
                }
            }

            upgrade_settings {
                max_surge       = 4
                max_unavailable = 0
            }
        }

        pod_security_policy_config {
            enabled = false
        }

        private_cluster_config {
            enable_private_endpoint = false
            enable_private_nodes    = true
            master_ipv4_cidr_block  = "172.16.0.16/28"
            peering_name            = "gke-n8a3c92e0ff4c6d086d8-77c6-295a-peer"
            private_endpoint        = "172.16.0.18"
            public_endpoint         = "192.168.20.80"
        }

        release_channel {
            channel = "REGULAR"
        }

        resource_usage_export_config {
            enable_network_egress_metering       = false
            enable_resource_consumption_metering = true

            bigquery_destination {
                dataset_id = "default_cluster_dataset"
            }
        }

        workload_identity_config {
            identity_namespace = "something.svc.id.goog"
        }
    }

  # google_container_node_pool.default-pool must be replaced
-/+ resource "google_container_node_pool" "default-pool" {
        cluster             = "default-cluster"
      ~ id                  = "projects/something/locations/us-central1/clusters/default-cluster/nodePools/default-pool" -> (known after apply)
        initial_node_count  = 0
      ~ instance_group_urls = [
          - "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-a/instanceGroupManagers/gke-default-cluster-default-pool-a22c9cf6-grp",
          - "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-b/instanceGroupManagers/gke-default-cluster-default-pool-ef503e49-grp",
          - "https://www.googleapis.com/compute/v1/projects/something/zones/us-central1-c/instanceGroupManagers/gke-default-cluster-default-pool-f7d54a4a-grp",
        ] -> (known after apply)
        location            = "us-central1"
      ~ max_pods_per_node   = 110 -> (known after apply)
        name                = "default-pool"
      + name_prefix         = (known after apply)
        node_count          = 0
      ~ node_locations      = [
          - "us-central1-a",
          - "us-central1-b",
          - "us-central1-c",
        ] -> (known after apply)
      ~ project             = "something" -> (known after apply)
      ~ version             = "1.20.9-gke.701" -> (known after apply)

        management {
            auto_repair  = true
            auto_upgrade = true
        }

      ~ node_config {
            disk_size_gb      = 50
          ~ disk_type         = "pd-standard" -> (known after apply)
          ~ guest_accelerator = [] -> (known after apply)
          ~ image_type        = "COS_CONTAINERD" -> (known after apply)
          ~ labels            = {} -> (known after apply)
          ~ local_ssd_count   = 0 -> (known after apply)
            machine_type      = "n1-standard-4"
          ~ metadata          = {
              - "disable-legacy-endpoints" = "true"
            } -> (known after apply)
          ~ oauth_scopes      = [ # forces replacement
                "https://www.googleapis.com/auth/cloud-platform",
              - "https://www.googleapis.com/auth/userinfo.email",
            ]
            preemptible       = false
            service_account   = "kubernetes-default@something"
            tags              = [
                "default-pool",
            ]
          ~ taint             = [] -> (known after apply)

          ~ shielded_instance_config {
              ~ enable_integrity_monitoring = false -> true # forces replacement
                enable_secure_boot          = true
            }

          ~ workload_metadata_config {
              ~ node_metadata = "GKE_METADATA_SERVER" -> (known after apply)
            }
        }

      ~ upgrade_settings {
          ~ max_surge       = 3 -> (known after apply)
          ~ max_unavailable = 0 -> (known after apply)
        }
    }
```

### Expected Behavior

Preferably, apply the changes to the cluster, then apply the deletes to the pool, then apply the create for the replacement pool.

But, as long as the operation runs to completion, I'm not particular on the order of operations.

### Actual Behavior

```
running "/atlantis-data/bin/terraform0.12.26 apply -input=false -no-color \"/atlantis-data/repos/GarnerCorp/pharos/1751/default/terraform/lighthouse/golden-pass/k8s_cluster/golden-pass-k8s_cluster-default.tfplan\"" in "/atlantis-data/repos/GarnerCorp/pharos/1751/default/terraform/lighthouse/golden-pass/k8s_cluster": exit status 1
google_container_node_pool.default-pool: Destroying... [id=projects/sincere-night-272115/locations/us-central1/clusters/default-cluster/nodePools/default-pool]
google_container_cluster.default-cluster: Modifying... [id=projects/sincere-night-272115/locations/us-central1/clusters/default-cluster]
google_container_node_pool.default-pool: Still destroying... [id=projects/sincere-night-272115/locations...default-cluster/nodePools/default-pool, 10s elapsed]
google_container_node_pool.default-pool: Still destroying... [id=projects/sincere-night-272115/locations...default-cluster/nodePools/default-pool, 20s elapsed]
google_container_node_pool.default-pool: Still destroying... [id=projects/sincere-night-272115/locations...default-cluster/nodePools/default-pool, 30s elapsed]
google_container_node_pool.default-pool: Destruction complete after 31s

Error: googleapi: Error 400: Operation operation-1634838845797-581527a0 is currently deleting a node pool for cluster default-cluster. Please wait and try again once it is done., failedPrecondition
```

The `default-pool` pool was deleted, a new one wasn't created, and the changes to `default-cluster` were not applied.

### Steps to Reproduce

1. `terraform apply`

### References

* #3650
* b/298513775

b/299312214

**Comment by KatrinaHoffert** [comment] 2024-08-07 14:31
@zli82016 can this be closed as not reproducible? This one also slipped through our cracks. We are unable to reproduce it and I am suspicious that it was made completely obsolete by https://github.com/hashicorp/terraform-provider-google/pull/13173, which changed how node pool operations handle this type of error (plus they're now concurrent on the server side). More details in the mirrored buganizer ticket.

(There may be a similar error that can result from cluster scoped ops in certain cases, but I view it as a distinct issue that we're still following up on internally.)

**Closed as completed** 2024-08-07 16:46 UTC
Labels: bug, forward/linked, service/container
