### ISSUE TITLE
Please add parent_id the google_project resource to consolidate org_id and folder_id functionality.

### ISSUE THREAD

**Issue by bgmonroe** [hashicorp/terraform-provider-google#7546] opened 2020-10-15 23:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently there is no way to move a project who's 'parent' is set as the org_id (org_id = 1234) to a folder (folder_id = 4321) or vice versa.  This is because these are two optional args that can't be unset by replacing org_id=1234 with folder_id=4321.
Setting one to "" and changing the other doesn't work.

I'm proposing to create a new argument named 'parent_id' who's value can be either the folder_id or the org_id.  This could conceivably replace the org_id and folder_id arguments some day (as they would be unnecessary).

### New or Affected Resource(s)

* google_project

### Potential Terraform Configuration

```tf
resource google_project "my_project" {
    name        = foobar
    project_id  = foobar
    parent_id   = 1234567
}
```

### References

* #7197 
* #1701

**Comment by rileykarson** [comment] 2020-10-19 20:17
Closing as a duplicate of #5073

**Closed by rileykarson** 2020-10-19 20:17 UTC
Labels: enhancement
