### ISSUE TITLE
Ability to add a project as a monitored project

### ISSUE THREAD

**Issue by ruchirjain86** [hashicorp/terraform-provider-google#9842] opened 2021-08-18 06:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Right now Google TF provider does not have the resource to create a monitored project for enabling centralised monitoring.
The API is available but the Terra form resource does not exist.

API: https://cloud.google.com/monitoring/api/ref_v3/rest#rest-resource:-v1.locations.global.metricsscopes.projects

### New or Affected Resource(s)

New Resource required

### References

https://cloud.google.com/monitoring/api/ref_v3/rest#rest-resource:-v1.locations.global.metricsscopes.projects

**Comment by slevenick** [comment] 2021-08-23 17:55
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/2605

**Closed by slevenick** 2021-08-23 17:55 UTC
Labels: enhancement
