### ISSUE TITLE
Add support for GKE Cloud DNS

### ISSUE THREAD

**Issue by jinlinux** [hashicorp/terraform-provider-google#9720] opened 2021-08-04 01:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Please see https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
dns = clouddns
```

### References

* #0000

**Comment by jkrueger-jaconi** [comment] 2021-08-04 08:26
Looks like a duplicate of #9494

**Comment by ScottSuarez** [comment] 2021-08-06 01:07
closing duplicate issue

**Closed by ScottSuarez** 2021-08-06 01:07 UTC
Labels: enhancement
