### ISSUE TITLE
Missing export of `prefix_length` property in `google_compute_global_address` data source

### ISSUE THREAD

**Issue by sestegra** [hashicorp/terraform-provider-google#11389] opened 2022-04-01 07:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.15.0
```

### Affected Resource(s)

`google_compute_global_address ` data source

### Terraform Configuration Files

```tf
data "google_project" "shared_vpc_project" {
  project_id = var.project_id
}

data "google_compute_global_address" "redis_cache_address_range" {
  project = data.google_project.shared_vpc_project.project_id
  name    = var.redis_cache_address_range_name
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

`prefix_length` property should be exported by the `google_compute_global_address` data source.

### Actual Behavior

`prefix_length` property isn't exported by the `google_compute_global_address` data source.

Indeed, when creating the associated `google_compute_global_address` resource, the `prefix_length` parameter is used to define the resource. So we need to retrieve it with the data source.

``` tf
resource "google_compute_global_address" "sub_gcp_shared_ops_b2s_npe_priv_serv_ip_range_redis_th_stg_2" {
  project       = var.project_id
  name          = var.redis_cache_address_range_name
  address_type  = "INTERNAL"
  purpose       = "VPC_PEERING"
  address       = "10.90.242.176"
  prefix_length = "29"
  network       = var.network
}
```

### Steps to Reproduce

1. Use the configuration above with the appropriate values for the variables
2. `terraform apply`

### Important Factoids
N/A

### References
N/A

b/308569255

**Comment by rileykarson** [comment] 2022-04-05 16:49
Note: global address is an old-style fully handwritten datasource, we should wrap it w/ the standard datasource funcs so that it picks up new fields for free.

**Comment by NickElliot** [comment] 2023-11-01 23:17
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/13960, which is a fixed issue.

**Closed** 2023-11-01 23:17 UTC
Labels: enhancement, size/s, forward/linked, service/compute-ipam
