### ISSUE TITLE
Unable to create subordinate CA

### ISSUE THREAD

**Issue by wrobelma** [hashicorp/terraform-provider-google#9663] opened 2021-07-28 19:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v3.77.0
+ provider registry.terraform.io/hashicorp/google-beta v3.77.0

### Affected Resource(s)

* google_privateca_certificate_authority

### Terraform Configuration Files

```tf
resource "google_privateca_ca_pool" "sub" {
  name     = "sub-pool"
  location = "europe-west1"
  tier     = "DEVOPS"

  publishing_options {
    publish_ca_cert = true
    publish_crl     = false
  }
}

resource "google_privateca_certificate_authority" "dev_sub_ca_test" {
  certificate_authority_id = "sub-ca-dev-test"

  pool     = google_privateca_ca_pool.sub.name
  location = "europe-west1"
  type     = "SUBORDINATE"
  lifetime = "473040000s"

  config {
    subject_config {
      subject {
        common_name         = "Dev Sub CA"
        organization        = "test org"
        organizational_unit = "DevOps"
        country_code        = "PL"
      }
    }

    x509_config {
      ca_options {
        is_ca                  = true
        max_issuer_path_length = 0
      }

      key_usage {
        base_key_usage {
          cert_sign = true
          crl_sign  = true
        }

        extended_key_usage {}
      }
    }
  }
 
  key_spec {
    algorithm = "RSA_PKCS1_4096_SHA256"
  }  
}
```

### Debug Output

on apply (create)
╷
│ Error: Error waiting to enable CertificateAuthority: Error waiting for Enabling CertificateAuthority: Error code 9, message: Cannot perform Certificate Authority enablement, Certificate Authority is in state PENDING_ACTIVATION.
│
│   with google_privateca_certificate_authority.dev_sub_ca_test,
│   on cas_ga.tf line 300, in resource "google_privateca_certificate_authority" "dev_sub_ca_test":
│  300: resource "google_privateca_certificate_authority" "dev_sub_ca_test" {
│
╵

### Expected Behavior

Resource is successfully created in a PENDING_ACTIVATION state. 

Standard flow is:
* create subordinate CA in a PENDING_ACTIVATION state
* read CSR from subordinate CA
* go to you organization's root CA and use CSR to create a certificate for sub CA
* download the certificate chain (sub CA cert & root CA cert)
* upload cert chain to sub CA and activate it

Activating subordinate CA is not possible with single apply. It's a 2 step process. 
* When creating just a subordinate CA you need first to create it to fetch its CSR, next use this CSR to create a certificate and then activate subordinate CA with it.
* When creating both root CA and its subordinate CA in GCP the same process applies but there is no way for a subordinate CA to reference to a root CA that should be used for certificate creation - automating the flow: fetch CSR, create certificate, upload certificate, activate sub CA, enable sub CA in the pool.

### Actual Behavior

Terraform created sub CA in GCP in a PENDING_ACTIVATION state but returned an error and tainted the resource. To make it usable, created resource needs to be removed from the state and then imported back for the terraform to see it as a correct untainted resource.

Tainting google_privateca_certificate_authority resource is a bad idea and cannot be effectively used because when going through any case of destroy/create steps this resource is not fully destroyed in GCP (PENDING_DELETION for about 30 days) and creation step will always cause a "resource already exists" error. Similar goes for google_privateca_ca_pool but it cannot be deleted when there are any google_privateca_certificate_authority in it, even when in PENDING_DELETION state (it is shown now as DELETED state when using "gcloud privateca subordinates list" but when using "gcloud privateca subordinates delete my-sub-ca" it shows "... Certificate Authority is in state PENDING_DELETION").

Creating just a subordinate CA in GCP is not possible now with help of terraform.

### Steps to Reproduce

1. `terraform apply`

**Comment by slevenick** [comment] 2021-07-28 23:22
Duplicate of: https://github.com/hashicorp/terraform-provider-google/issues/9604

**Closed by slevenick** 2021-07-28 23:22 UTC
Labels: bug
