### ISSUE TITLE
Permission Denied Error on `tf init` when accessing the backend bucket with impersonate service account.

### ISSUE THREAD

**Issue by hyunuk** [hashicorp/terraform-provider-google#16418] opened 2023-10-31 23:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.6.1
on linux_amd64

### Affected Resource(s)

N/A

### Terraform Configuration Files

https://gist.github.com/hyunuk/29e5799a0a362ed9c0485713730ccb76
See `Steps to Reproduce` below for detailed explanation.

### Debug Output

```sh
Step #0 - "tf init": │ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/hyunuk-jss-00-tf-states/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false": impersonate: status code 403: {
Step #0 - "tf init": │   "error": {
Step #0 - "tf init": │     "code": 403,
Step #0 - "tf init": │     "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
Step #0 - "tf init": │     "status": "PERMISSION_DENIED",
```

### Expected Behavior

I was deploying terraform via Cloud build. The process is the following:
- Created a impersonate service account
- Created a bucket for backend
- Grant necessary IAM permissions to the service account
- Run `tf init` using Cloud build

It was expected to run properly without an error.

### Actual Behavior

When `tf init` is trying to access its backend bucket for the first time after the impersonate service account was created, it shows the 403, PERMISSION_DENIED error described above.
Every time I create the service account, give it to permissions, and run a Cloud build, the error message shown above occurred. Remarkably, when I rerun the same script again, the process runs well without an error.
However, the error re-occurs when I delete the service account and execute the script once more.

### Steps to Reproduce

https://gist.github.com/hyunuk/29e5799a0a362ed9c0485713730ccb76
- Download these gist files in your Cloud shell.
- Change project ID in main.tf to your own project.
- execute ./setup.sh. It will shows an error
- execute ./setup.sh again, It will execute properly.
- To delete Terraform resources and the service account created, execute ./destroy.sh.

### Important Factoids

- I checked whether the service account has the right permission, `roles/iam.serviceAccountTokenCreator`, or not after grant a permission, and it does have.
- I tried to sleep the script after IAM permission has given since I assumed that there might be delay between giving permission and applying it, which didn't work. I tried up to 120 seconds.
- I retried `tf init` step automatically for 3 times, with 10 seconds sleeping for each time if it fails. It didn't work.

**Comment by edwardmedia** [comment] 2023-11-01 14:01
@hyunuk it seems the account fails in accessing the bucket. It is not clear what exactly you did although you provided the steps. 

```
querying Cloud Storage failed:
```

What do you see if you use the service account with owner directly?

**Comment by edwardmedia** [comment] 2023-11-01 17:48
@hyunuk as long as the config works with an account without an error, this issue is likely in the place how you build the solution. 

You may want to test each pieces to see what is missing without the automation. What do you see if you manually run `tf init` with the impersonated service account?

**Comment by hyunuk** [comment] 2023-11-02 00:35
The following is the debug output.
When I manually run tf init with either of owner account or other service account, it runs well. 
The error happens only if it is 1) run Via Cloud Build 2) with an impersonated service account 3) for the first time after it is created.
```shell
Step #0 - "tf init": Initializing the backend...
Step #0 - "tf init": 
Step #0 - "tf init": Successfully configured the backend "gcs"! Terraform will automatically
Step #0 - "tf init": use this backend unless the backend configuration changes.
Step #0 - "tf init": ╷
Step #0 - "tf init": │ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/hyunuk-jss-01-tf-states/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false": impersonate: status code 403: {
Step #0 - "tf init": │   "error": {
Step #0 - "tf init": │     "code": 403,
Step #0 - "tf init": │     "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
Step #0 - "tf init": │     "status": "PERMISSION_DENIED",
Step #0 - "tf init": │     "details": [
Step #0 - "tf init": │       {
Step #0 - "tf init": │         "@type": "type.googleapis.com/google.rpc.ErrorInfo",
Step #0 - "tf init": │         "reason": "IAM_PERMISSION_DENIED",
Step #0 - "tf init": │         "domain": "iam.googleapis.com",
Step #0 - "tf init": │         "metadata": {
Step #0 - "tf init": │           "permission": "iam.serviceAccounts.getAccessToken"
Step #0 - "tf init": │         }
Step #0 - "tf init": │       }
Step #0 - "tf init": │     ]
Step #0 - "tf init": │   }
Step #0 - "tf init": │ }
Step #0 - "tf init": │ 
Step #0 - "tf init": │ 
Step #0 - "tf init": │ 
Step #0 - "tf init": ╵
Step #0 - "tf init": 
Finished Step #0 - "tf init"
ERROR
ERROR: build step 0 "hashicorp/terraform:1.0.0" failed: step exited with non-zero status: 1
--------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 0 "hashicorp/terraform:1.0.0" failed: step exited with non-zero status: 1
ERROR: (gcloud.builds.submit) build 0e9b59b8-245d-45d8-963d-0c9d08ef13cd completed with status "FAILURE"
```

**Comment by edwardmedia** [comment] 2023-11-02 13:10
@hyunuk The log does not tell me much. How did you create the service accounts?  Before you run `tf init`? You said you have given enough time between? I am not sure how much I can help. Obviously the issue is about how you automate your solution.

**Comment by edwardmedia** [comment] 2023-11-06 17:11
@hyunuk does [this](https://github.com/hashicorp/terraform-provider-google/issues/16418#issuecomment-1790697094) make sense? We can help if you see an issue in the provider. But what you had is more about how to automate the process. Closing this now. Feel free to reopen or file a new bug if you believe that is a bug in the provider

**Closed by edwardmedia** 2023-11-06 17:11 UTC
Labels: bug, waiting-response
