### ISSUE TITLE
Add Big lake in the google_bigquery_connection

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [hashicorp/terraform-provider-google#11730] opened 2022-05-19 15:27 UTC
### Description

It would be nice to add the new biglake feature when creating a big query connection
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection
It's actually available through the UI.

### New or Affected Resource(s)

* google_bigquery_connection

### Potential Terraform Configuration

```tf
resource "google_bigquery_connection" "connection" {
    provider      = google-beta
    friendly_name = "👋"
    description   = "a riveting description"
    big_lake {
      connection_id = "my_connection_id"
      data_location = "eu"
    }
}
```

**Comment by gutschenritter** [comment] 2022-05-20 19:15
I'm working on this right now - the connection_id will be added as a new field to the existing external_data_configuration nested object.

**Comment by gutschenritter** [comment] 2022-05-20 19:18
I believe this was resolved in #GoogleCloudPlatform/magic-modules/pull/6020

**Comment by rileykarson** [comment] 2022-05-23 17:29
That seemed to add `serviceAccountId`, but no other kind of cloud resource(s)

**Comment by julio-vaz** [comment] 2022-06-27 19:56
Hello, any update on this?

**Comment by julio-vaz** [comment] 2022-06-28 14:33
Hello again guys, this should be working already since [4.25.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4250-june-15-2022) or I misunderstood it?

Thanks in advance!

**Comment by psvaiter** [comment] 2022-09-02 16:04
BigLake table is a Cloud Resource, so you are able to create a connection with an empty `cloud_resource` block and use that in your `google_bigquery_table` resource. 

(confirmed with v4.33.0)

**Comment by rileykarson** [comment] 2022-09-02 16:23
Closing, seems the service has documentation confirming that's the case. With a Terraform config, too!

https://cloud.google.com/bigquery/docs/biglake-quickstart#terraform

**Closed by rileykarson** 2022-09-02 16:23 UTC
Labels: enhancement, size/s
