### ISSUE TITLE
Support BigQuery authorized datasets

### ISSUE THREAD

**Issue by yu-iskw** [hashicorp/terraform-provider-google#10765] opened 2021-12-16 01:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
BigQuery authorized datasets are now generally available.  So, let's support the feature in the provider as authorized views.

> An authorized dataset lets you authorize all of the views in a specified dataset to access the data in a second dataset. With an authorized dataset, you don't need to configure individual authorized views.

- https://cloud.google.com/bigquery/docs/authorized-datasets

### New or Affected Resource(s)

* google_bigquery_dataset
* google_bigquery_dataset_access

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset" "dataset" {
  project    = "project-a"
  dataset_id = "example_dataset"
  location   = "US"

  access {
    role   = "READER"
    dataset {
      dataset_id = "example_authorized_dataset"
      project_id = "project-b"
    }
  }
}
```

```tf
resource "google_bigquery_dataset_access" "access" {
  project    = "project-1"
  dataset_id = "example_dataset"
  
  dataset {
    project_id = "project-b"
    dataset_id = "example_authorized_dataset"
  }
}
```

### References

* https://cloud.google.com/bigquery/docs/authorized-datasets

**Comment by slevenick** [comment] 2021-12-16 01:21
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/10555

**Closed by slevenick** 2021-12-16 01:21 UTC
Labels: enhancement
