### ISSUE TITLE
Cannot create google_app_engine_application with an SA from a different project 

### ISSUE THREAD

**Issue by bnelson729** [hashicorp/terraform-provider-google#10503] opened 2021-11-04 21:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
TF Version: 0.13.5
Google Provider Version: 4.0.0

### Affected Resource(s)
* google_app_engine_application

### Terraform Configuration Files

```
resource "google_project" "main" {
  name            = "xxx"
  project_id      = "xxx-001"
  folder_id       = xxx
  billing_account = "XXXXXX-XXXXXX-XXXXXX"
}

resource "google_project_service" "project_services" {
  project = google_project.main.project_id
  service = "appengine.googleapis.com"
}

resource "google_app_engine_application" "app" {
  project     = google_project.main.project_id
  location_id = "us-west2"
}
```

### Output
```
Terraform will perform the following actions:

  # google_app_engine_application.app will be created
  + resource "google_app_engine_application" "app" {
      + app_id            = (known after apply)
      + auth_domain       = (known after apply)
      + code_bucket       = (known after apply)
      + database_type     = (known after apply)
      + default_bucket    = (known after apply)
      + default_hostname  = (known after apply)
      + gcr_domain        = (known after apply)
      + id                = (known after apply)
      + location_id       = "us-west2"
      + name              = (known after apply)
      + project           = "xxx-001"
      + serving_status    = (known after apply)
      + url_dispatch_rule = (known after apply)

      + feature_settings {
          + split_health_checks = (known after apply)
        }

      + iap {
          + enabled                     = (known after apply)
          + oauth2_client_id            = (known after apply)
          + oauth2_client_secret        = (sensitive value)
          + oauth2_client_secret_sha256 = (sensitive value)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_app_engine_application.app[0]: Creating...

Error: Error creating App Engine application: googleapi: Error 403: App Engine Admin API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/appengine.googleapis.com/overview?project=655900446813 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/appengine.googleapis.com/overview?project=xxx"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/xxx",
      "service": "appengine.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
, accessNotConfigured

  on ../../modules/service_project/main.tf line 31, in resource "google_app_engine_application" "app":
  31: resource "google_app_engine_application" "app" {
```

### Expected Behavior
A project should be created with an app engine created in us-west-2.

### Actual Behavior
Regardless of how long I wait, it does not create the app engine.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Terraform is running from a service account in another project. The service account has `resourcemanager.projects.create`, but importantly the GCP project where the service account is from does not have `appengine.googleapis.com` enabled. I xxx'd out all the identifying information, but you'll have to trust me that the project number in the error message at `projects/xxx` is not the brand new project. The project number is associated with the GCP project that the service account is from. It's as if the `google_app_engine_application` resource is ignoring the `project` variable and attempted to create the app engine in the SA's GCP project.

**Comment by edwardmedia** [comment] 2021-11-04 23:10
@bnelson729 did you follow below suggestion to enable the api? 

> Error: Error creating App Engine application: googleapi: Error 403: App Engine Admin API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/appengine.googleapis.com/overview?project=655900446813 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Regarding your words under Important Factoids, I'd like to comment 1) The project where the Terraform run shouldn't matter in this case. You can run Terraform from your local machine, can't you? 2) the service account matters. You mentioned it has `resourcemanager.projects.create`, on which project?

Does it make sense?

**Comment by bnelson729** [comment] 2021-11-05 13:16
I have project X and project Y.

Project X holds the SA and does not have `appengine.googleapis.com` enabled. I do not have permissions to enable it and I'm not sure why I would need to.

Project Y is the brand new project that does have `appengine.googleapis.com` enabled. This is the project where I'm trying to create the app engine.

The error message I'm getting says that Project X needs `appengine.googleapis.com` enabled, but that doesn't make any sense because I'm not creating the app engine in Project X. It's as if the `project` variable of `google_app_engine_application` is being ignored and trying to create the app engine in the SA's project (X).

**Comment by edwardmedia** [comment] 2021-11-05 16:05
@bnelson729 This is exact by design. Below is what the [doc](https://cloud.google.com/iam/docs/service-accounts#locations) describes. 

> When a service account is in one project, and it accesses a resource in another project, you usually must enable the API for that resource in both projects. For example, if you have a service account in the project my-service-accounts and a Cloud SQL instance in the project my-application, you must enable the Cloud SQL API in both my-service-accounts and my-application. 

Make sense?

**Comment by edwardmedia** [comment] 2021-11-12 17:54
@bnelson729 is this still an issue?

**Comment by edwardmedia** [comment] 2021-11-16 23:34
@bnelson729 closing this assume it is no longer an issue.

**Closed by edwardmedia** 2021-11-16 23:34 UTC
Labels: bug, waiting-response
