### ISSUE TITLE
google_beta >= 4.32 google_container_node_pool update issue

### ISSUE THREAD

**Issue by yurifrancalacci** [hashicorp/terraform-provider-google#12557] opened 2022-09-14 15:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.32.0
+ provider registry.terraform.io/hashicorp/google-beta v4.32.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
module "cluster-1" {
  source                    = "github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/gke-cluster"
  project_id                = var.project_id
  name                      = "cluster-1"
  location                  = var.region
  network                   = "projects/${var.project_id}/global/networks/${var.vpc_name}"
  subnetwork                = "projects/${var.project_id}/regions/${var.region}/subnetworks/${var.subnet_name}"
  secondary_range_pods      = "pod"
  secondary_range_services  = "serv"
  default_max_pods_per_node = 32
  master_authorized_ranges = {
    internal-vms = "10.0.0.0/8"
  }
  private_cluster_config = {
    enable_private_nodes    = true
    enable_private_endpoint = true
    master_ipv4_cidr_block  = "192.168.0.0/28"
    master_global_access    = false
  }
  labels = {
    environment = "dev"
  }
}
# tftest modules=1 resources=1

module "cluster-1-nodepool-1" {
  source                      = "github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/gke-nodepool"
  project_id                  = var.project_id
  cluster_name                = "cluster-1"
  location                    = var.region
  name                        = "nodepool-1"
  node_count =1
  depends_on = [
    module.cluster-1
  ]
}
```

### Debug Output

https://gist.github.com/yurifrancalacci/aeeb96ae4d4a29168fd298199149b4c5#file-gistfile1-txt

### Expected Behavior

Update the configuration of the node pool

### Actual Behavior

Error in the api call

### Steps to Reproduce

from a clean project
- terraform init
- terraform plan
- terraform apply
- terraform apply

### Important Factoids

the first `terraform apply` completes the setup, the second generates the error

### References

Code reference
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/gke-cluster

* #0000

**Comment by edwardmedia** [comment] 2022-09-14 16:18
Looks like it is a dup https://github.com/hashicorp/terraform-provider-google/issues/12549

**Comment by Syphon83** [comment] 2022-09-15 22:32
Same behaviour here , Error 400 during pool update.

**Comment by shuyama1** [comment] 2022-09-19 17:13
Thanks for reporting the issue! Are you also seeing the error when manage the resource using only `google_container_cluster` and `google_container_node_pool` configuration but not using the module. I was trying to reproduce the error using only the resource configuration and it worked fine for me. So I wonder if only happens when using the module or I've missed something during my local test.

**Comment by Syphon83** [comment] 2022-09-20 08:55
> Thanks for reporting the issue! Are you also seeing the error when manage the resource using only `google_container_cluster` and `google_container_node_pool` configuration but not using the module. I was trying to reproduce the error using only the resource configuration and it worked fine for me. So I wonder if only happens when using the module or I've missed something during my local test.


Hi @shuyama1 , I am currently experiencing this behavior using the GKE module at version 23.0. Unfortunately I am not using resources, sorry.

**Comment by yurifrancalacci** [comment] 2022-09-20 11:31
Hello,
I'm currently testing the same code with the latest (4.37.0) provider version to check if the error is gone. I will keep you updated

**Comment by yurifrancalacci** [comment] 2022-09-26 07:41
issue seems to be resolved with the latest provider.

**Comment by shuyama1** [comment] 2022-09-26 15:03
Thanks for the update! Closing this issue now. Please feel free to reopen this issue or open a new one if the error occurs again.

**Closed by shuyama1** 2022-09-26 15:03 UTC
Labels: bug
