### ISSUE TITLE
Compute IP Deletion & NAT Order of Operations Issue

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-google#12748] opened 2022-10-10 16:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

When attempting to downsize the number of IPs assigned to a manually managed NAT, there is a order of operations issue which occurs which makes this not possible with a common pattern for assigning address to the NAT.

Basically, Terraform is attempting to perform the `delete` operation of the IP before the NAT performs the unattach, in fact even when the first operation fails it does not then proceed to perform the operation to `update` (removal of the NAT IP), likely due to how that operation is computed from the list object.

I think this is ultimately a question of Terraform behavior, if this is considered something which should be changed/fixed or not. If this is not something which will be handled upstream, then I think there is a case to be made for the IP address API to support a "force unattach" option to help with these types of scenarios. 

### Terraform Version

`1.3.1`

### Affected Resource(s)

* `google_compute_address`
* `google_compute_router_nat`

### Terraform Configuration Files

```tf
resource "google_compute_router" "test" {
  project = module.project_context.project_id
  name    = "test-nat-router"
  network = google_compute_network.test.id
  region  = module.project_context.region
}

resource "google_compute_address" "tests" {
  count   = 2
  name    = "test-nat-ip-${count.index}"
  region  = module.project_context.region
  project = module.project_context.project_id
}

resource "google_compute_router_nat" "test" {
  project                             = google_compute_router.test.project
  region                              = google_compute_router.test.region
  name                                = google_compute_router.test.name
  router                              = google_compute_router.test.name
  nat_ip_allocate_option              = "MANUAL_ONLY"
  source_subnetwork_ip_ranges_to_nat  = "ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES"
  nat_ips                             = [for ip in google_compute_address.tests : ip.self_link]
  enable_dynamic_port_allocation      = true
  enable_endpoint_independent_mapping = false

  log_config {
    enable = true
    filter = "ALL"
  }
}
```

### Debug Output

Terraform Output: https://gist.github.com/tgoodsell-tempus/70d32ec38ea3146f6963cc3f2fc6de9b

### Expected Behavior

Our rough expectation is that:
- IP to be deleted is unattached from the Cloud NAT
- IP is then "deleted"

### Actual Behavior

Terraform tries to:
- Delete the IP prior to removing it from the NAT
- Never attempts to update the NAT config with the removal of the IP address

### Steps to Reproduce

Using the sample code above, adjusted for your environment:

1. Set the count value of the addresses from `2` to `1`
2. Run `terraform apply`

### Important Factoids

I'm aware this is likely an issue with how Terraform builds up the order of operations of changes, so I will also cross-post this in that repo as well. 

A potential fix for this, if there's no good path forward for any order of operation changes, would be to see if the compute address API could be extended with a "force unattach from resource" option.

EDIT: A similar issue has been raised in the terraform repo already, https://github.com/hashicorp/terraform/issues/31309, which ultimately recommends using the `create_before_destroy` flag to handle this situation. It's unclear if this is going to be the only solution in the future, but other than provider / API changes this seems to be the main offer.

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/addresses/delete

**Comment by edwardmedia** [comment] 2022-10-10 17:08
@tgoodsell-tempus have you looked at the [depends_on](https://www.terraform.io/language/meta-arguments/depends_on) to see if that help solve your problem?

**Comment by tgoodsell-tempus** [comment] 2022-10-11 01:01
Based on the following issue in the Terraform repo, https://github.com/hashicorp/terraform/issues/31309, I was able to "workaround" the behavior by setting the `create_before_destroy` flag on the `google_compute_address` object.

Full example:
```tf
resource "google_compute_address" "tests" {
  count   = 1
  name    = "test-nat-ip-${count.index}"
  region  = module.project_context.region
  project = module.project_context.project_id

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_router_nat" "test" {
  project                             = google_compute_router.test.project
  region                              = google_compute_router.test.region
  name                                = google_compute_router.test.name
  router                              = google_compute_router.test.name
  nat_ip_allocate_option              = "MANUAL_ONLY"
  source_subnetwork_ip_ranges_to_nat  = "ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES"
  nat_ips                             = [for ip in google_compute_address.tests : ip.self_link]
  enable_dynamic_port_allocation      = true
  enable_endpoint_independent_mapping = false

  log_config {
    enable = true
    filter = "ALL"
  }
}
```

**Comment by edwardmedia** [comment] 2022-10-11 15:53
@tgoodsell-tempus now I see what the problem is. Yes, I think `create_before_destroy` is the solution. I can't think of any other methods available. BTY, this is more about the terraform feature that manage the behavior of inter resources. There is not much we can do at the provider level. Does this make sense?

**Comment by edwardmedia** [comment] 2022-10-31 17:19
Closing this as there is not much we can do at the provider level

**Closed by edwardmedia** 2022-10-31 17:19 UTC
Labels: bug, waiting-response
