### ISSUE TITLE
network_endpoint_type parameter of compute_network_endpoint_group doesn't accept some valid options

### ISSUE THREAD

**Issue by gregnolle** [hashicorp/terraform-provider-google#16093] opened 2023-10-03 13:16 UTC
The `network_endpoint_type` parameter of the `compute_network_endpoint_group` resource doesn't accept the `INTERNET_IP_PORT` value for example, even though this is valid according to Google's documentation.

**Comment by edwardmedia** [comment] 2023-10-03 14:33
@gregnolle it seems fine with me. What version of your provider? If you use the latest version which still does not work for you, can you share your debug log?

  # google_compute_network_endpoint_group.neg will be created
  + resource "google_compute_network_endpoint_group" "neg" {
      + default_port          = 90
      + id                    = (known after apply)
      + name                  = "issue16093"
      + network               = (known after apply)
      + network_endpoint_type = "NON_GCP_PRIVATE_IP_PORT"
      + project               = "myproject"
      + self_link             = (known after apply)
      + size                  = (known after apply)
      + zone                  = "us-central1-a"
    }

**Comment by gregnolle** [comment] 2023-10-03 15:07
Hi @edwardmedia . You've used NON_GCP_PRIVATE_IP_PORT there but that's a different type (it's for private IPs rather than internet IPs). For reference, there's a full list of options in [Google's docs here](https://cloud.google.com/sdk/gcloud/reference/compute/network-endpoint-groups/create#--network-endpoint-type).

**Comment by edwardmedia** [comment] 2023-10-03 16:16
@gregnolle the current accepted values are documented [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_endpoint_group#network_endpoint_type). You may file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&projects=&template=01_enhancement.md) to request? 

Closing this as current behavior is by design

**Closed by edwardmedia** 2023-10-03 16:16 UTC
Labels: bug
