### ISSUE TITLE
Undeclared breaking change - google_compute_subnetwork interplay between reserved_internal_range and ip_cidr_range

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-google#18115] opened 2024-05-13 18:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

provider registry.terraform.io/hashicorp/google v5.29.0

### Affected Resource(s)

google_compute_subnetwork

### Terraform Configuration

```tf
resource "google_compute_subnetwork" "main" {
  name                     = "main"
  ip_cidr_range            = "10.16.0.0/16"
  region                   = "us-central1"
  private_ip_google_access = true
  network     = var.network.self_link
  project     = var.project_id
  description = var.description

  secondary_ip_range = [
    {
      range_name    = "gke-pods"
      ip_cidr_range = "241.0.0.0/14"
    },
    {
      range_name    = "gke-services"
      ip_cidr_range = "241.4.0.0/20"
    },
  ]
}
````

### Expected Behavior

Historically the above code has worked and continues to work if I pin a provider version older than 5.29.0. Additionally, there was not a breaking change declared in https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.29.0. As a result, this code should continue to work in 5.29.0

### Actual Behavior

I receive the below error that appears to trace back to https://github.com/hashicorp/terraform-provider-google/pull/18026/files (and originally https://github.com/GoogleCloudPlatform/magic-modules/pull/10507/files).

```
│ Error: Incorrect attribute value type
│ 
│   on ../modules/fixed-subnetwork/main.tf line 16, in resource "google_compute_subnetwork" "main":
│   16:   secondary_ip_range =  [
|     {
|       range_name    = "gke-pods"
|       ip_cidr_range = "241.0.0.0/14"
|     },
|     {
|       range_name    = "gke-services"
|       ip_cidr_range = "241.4.0.0/20"
|     },
|   ]
│     ├────────────────
│     │ var.secondary_cidr_ranges is list of object with 2 elements
│ 
│ Inappropriate value for attribute "secondary_ip_range": element 0:
│ attribute "reserved_internal_range" is required.

```

### Steps to reproduce

1. `terraform apply`

**Comment by trodge** [comment] 2024-05-13 19:43
I believe this is the same as the issue in https://github.com/hashicorp/terraform-provider-google/issues/12817, and also caused by `SchemaConfigModeAttr` on the parent field.

**Comment by rileykarson** [comment] 2024-05-14 16:45
This is weird case- way back around 0.12/our 2.0.0 we had to annotate a handful of fields with `SchemaConfigModeAttr` for backwards compatibility, as 0.12 had a regression that removed the ability to set explicit empty arrays for those fields. HashiCorp went forward with the change, carving out SchemaConfigModeAttr to provide backwards compatibility for those specific fields.

We later discovered a forwards compatibility issue with new fields in modules in https://github.com/hashicorp/terraform-provider-google/issues/12817 (and possibly another issue) where new fields break preexisting modules; we still can't remove the setting for backwards compatibility reasons, as we lose the ability to express "there are no entries of this type", but now also can't add new fields to these blocks even if the API does.

And, of course, how this _actually_ comes up is that we inadvertently add new fields to these blocks (there are very few of them, updates are rare, and it's easy to forget this case until it happens), don't catch them in our tests which are relatively simple resource invocations- I don't think we can define modules in HC's test runner.

As a workaround you can add an explicit null for the new field. That's the approach suggested by HashiCorp: https://developer.hashicorp.com/terraform/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax

Roughly something like:

```
secondary_ip_range = [
    {
      range_name    = "gke-pods"
      ip_cidr_range = "241.0.0.0/14"
      reserved_internal_range = null
    },
    {
      range_name    = "gke-services"
      ip_cidr_range = "241.4.0.0/20"
      reserved_internal_range = null
    },
  ]
```

> Any ETA on a fix being released?

I'm not sure what the timeline is. Because of the forwards compatibility issue with the setting and the backwards compatibility issue without, we have to weigh reverting the field (breaking anyone who adopted it or set explicit null as a workaround), breaking empty arrays by removing the setting (something we have evaluated and decided against in several successive major releases), or doing nothing.

> In the meantime, can you update the release notes for [v5.29.0 (release)](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.29.0) to note this breaking change and provide a warning about it.

@trodge have you already done this? Can you do it, if not?

**Comment by joe-a-t** [comment] 2024-05-14 17:17
@rileykarson @trodge given the current situation that you do not have a way to solve this globally on your end, please revert https://github.com/hashicorp/terraform-provider-google/pull/18026/files until either you can fix it globally on your end or you do a major release where this kind of breaking change would be acceptable to include. 

I do want to acknowledge that you are providing a work around by having all users explicitly setting that field to `null`, but I believe that requiring this type of user action breaks your compatibility promise in a minor release version. This issue clearly has widespread impact given the high number of 👍 this issue has attracted in less than 24 hours.

**Comment by slevenick** [comment] 2024-05-14 18:16
We're looking into reverting this and making a patch release

See https://github.com/GoogleCloudPlatform/magic-modules/pull/10697

**Comment by joe-a-t** [comment] 2024-05-14 20:23
Any ETA on the release? Also should update the note that was put in [v5.29.0 (release)](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.29.0) to advise people not to implement the work around because it will break with the fix release

**Comment by slevenick** [comment] 2024-05-14 20:24
It should be out today. @trodge can you update the release note with a warning to upgrade directly to 5.29.1 once it's out?

**Comment by slevenick** [comment] 2024-05-14 22:43
[5.29.1](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.29.1) is out for both provider versions as of now, so I'm closing this as fixed. We'll need to see how we can add this feature back in the future

**Closed by slevenick** 2024-05-14 22:43 UTC
Labels: bug, service/terraform
