### ISSUE TITLE
google_compute_network datasource should accept self_link like google_compute_subnetwork does

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#8682] opened 2021-03-12 22:32 UTC
### Affected Resource(s)

* google_compute_network

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

These two data sources are weirdly inconsistent

google_compute_subnetwork supports self_link which is often preferable because it includes the name AND the project in a single reference:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_subnetwork

But for some reason google_compute_network does not?
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_network

For example if I want to reference a network and a subnetwork Ill do something ugly like this, would be MUCH nicer to just ask consumers of a module or script to specify a self_link for both:

```
// Give me the self_link of the subnetwork
data "google_compute_subnetwork" "cluster_subnetwork" {
  self_link = var.subnetwork_self_link
}
// Give me the name of the network and I use the project attribute of the subnetwork- boo
data "google_compute_network" "cluster_network" {
  name = var.pass_this_in
  project = data.google_compute_subnetwork.cluster_subnetwork
}
```

whats extra frustrating about this is google_compute_subnetwork actually includes the parent projects self link as a "network" attribute! ARG! I could just ask for the self_link of the subnetwork and use it to get a ref to the network

I could use tf text parsing functions to get the name and project of the network out of the subnetwork attributes and may resort to that but wow that sucks

**Comment by red8888** [comment] 2021-03-15 17:11
FYI using this as a workaround

```tf
data "google_compute_network" "network" {
  name    = basename(data.google_compute_subnetwork.subnetwork.network)
  project = data.google_compute_subnetwork.subnetwork.project
}

data "google_compute_subnetwork" "subnetwork" {
  self_link = var.my_subnetwork_self_link
}
```

**Comment by roaks3** [comment] 2024-07-31 20:36
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7863

**Closed by roaks3** 2024-07-31 20:36 UTC
Labels: enhancement, size/s, forward/review, service/compute-vpc
