### ISSUE TITLE
Error while creating IAM users for Cloud SQL (Postgresql)

### ISSUE THREAD

**Issue by g-awmalik** [hashicorp/terraform-provider-google#9862] opened 2021-08-19 20:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.0.4
on linux_amd64

### Affected Resource(s)

* google_sql_database_instance
* google_sql_user

### Terraform Configuration Files

**Module:** https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/postgresql/main.tf

**Example:** https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/examples/postgresql-public-iam/main.tf

### Debug Output

https://gist.github.com/g-awmalik/8a5543db0f04d6a29c119a9b3e476f58

### Expected Behavior

The two IAM users should have been created and the `terraform apply` should have completed without errors.

### Actual Behavior

The two IAM users are created successfully however `terraform apply` ends in the following error message referencing each of the two IAM users being created:

       │ Error: Provider produced inconsistent result after apply
       │ 
       │ When applying changes to
       │ module.example.module.postgresql-db.google_sql_user.iam_account["cloudsql-pg-sa-01@ci-sql-db-8341.iam.gserviceaccount.com
       │ true"], provider "provider[\"registry.terraform.io/hashicorp/google\"]"
       │ produced an unexpected new value: Root resource was present, but now
       │ absent.
       │ 
       │ This is a bug in the provider, which should be reported in the provider's
       │ own issue tracker.
       ╵
       ╷
       │ Error: Provider produced inconsistent result after apply
       │ 
       │ When applying changes to
       │ module.example.module.postgresql-db.google_sql_user.iam_account["dbadmin@goosecorp.org
       │ false"], provider "provider[\"registry.terraform.io/hashicorp/google\"]"
       │ produced an unexpected new value: Root resource was present, but now
       │ absent.
       │ 
       │ This is a bug in the provider, which should be reported in the provider's
       │ own issue tracker.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

One of the IAM users being created is a service account which should be created in advance so the module can bind IAM policies to it at the project level and at the Cloud SQL level. It can also be commented out since the other IAM user (non-SA) yields the same error.

**Comment by megan07** [comment] 2021-08-23 16:04
Hi @g-awmalik ! I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9723 and should be fixed in a future release. I'll close for now, but please let me know if you disagree and I can reopen.
Thanks!

**Closed by megan07** 2021-08-23 16:04 UTC
Labels: bug

**Comment by g-awmalik** [comment] 2021-08-23 20:05
Thanks @megan07. Do you know what release that will be and when that will be part master release channel?

**Comment by megan07** [comment] 2021-08-23 20:59
@g-awmalik I can't guarantee an exact date, but it should be a part of `3.82.0` which will likely be released next week.

**Comment by g-awmalik** [comment] 2021-08-23 21:05
Thank you.
