### ISSUE TITLE
google_storage_transfer_job.aws_s3_data_source block is missing "path" parameter

### ISSUE THREAD

**Issue by smic-datalabs-jdcastro** [hashicorp/terraform-provider-google#13936] opened 2023-03-08 08:09 UTC
### Description

In GCP Data Transfer Console, there is an available option to specify the "path" of the S3 Bucket defined as data source.

### New or Affected Resource(s)
*google_storage_transfer_job

### Potential Terraform Configuration

```
resource "google_storage_transfer_job" "sample_data_transfer" {
  description = "sample description"

  transfer_spec {
    object_conditions {
      ...
      ...
    }
    aws_s3_data_source {
      bucket_name = "bucket_name"
      aws_access_key {
        access_key_id     = ****
        secret_access_key = ****
      }
      path = "<path_in_bucket>" <--- include this
    }
  }
```

**Comment by trodge** [comment] 2023-05-01 21:56
b/280345991

**Comment by kiwamizamurai** [comment] 2023-05-11 06:30
similar 
https://github.com/hashicorp/terraform-provider-google/issues/12997

**Comment by kiwamizamurai** [comment] 2023-05-25 19:54
@dilipped yes. this one can be closed

**Comment by dilipped** [comment] 2023-05-25 20:10
@trodge , can you please close this one? I don't have permissions to do it.

**Comment by roaks3** [comment] 2023-07-20 00:19
Yep, duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12997, fixed by https://github.com/hashicorp/terraform-provider-google/pull/14610

**Closed by roaks3** 2023-07-20 00:19 UTC
Labels: enhancement, size/s, crosslinked, service/storage
