### ISSUE TITLE
Datasource for Big Query data set

### ISSUE THREAD

**Issue by josedev-union** [hashicorp/terraform-provider-google#12893] opened 2022-10-27 07:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* data.google_bigquery_dataset

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
data "google_bigquery_dataset" "dataset" {
  dataset_id = "example_dataset"
}
```

### References

* #0000

**Comment by YounesCoder** [comment] 2022-10-27 23:00
You could just retrieve the dataset_id from `outputs `when you create the dataset via `google_bigquery_dataset` ?

```
resource "google_bigquery_dataset" "dataset" {
  dataset_id                  = "example_dataset"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "EU"
}

output "private_datasets" {
  value = google_bigquery_dataset.dataset
  description = "A map of created BigQuery dataset"
}
```

**Comment by josedev-union** [comment] 2022-10-28 07:38
@YounesCoder ofc, we can get dataset_id if we created that via google_bigquery_dataset resource.
But it cannot replace datasource you know.

Typical example is;
How can you get id if you created dataset in other tf workspace? For example, I manage IAM resources in a dedicated workspace and need to bind a role to one dataset. It requires dataset id which is created in other workspace.

**Comment by melinath** [comment] 2022-10-31 17:48
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/5693

**Closed as completed by melinath** 2022-10-31 17:48 UTC
Labels: enhancement, service/bigquery, forward/review
