### ISSUE TITLE
url_mask in google_compute_region_network_endpoint_group.serverless_deployment should be optional

### ISSUE THREAD

**Issue by yuryu** [hashicorp/terraform-provider-google#11242] opened 2022-03-09 06:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
✗ terraform -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.13.0
+ provider registry.terraform.io/hashicorp/google-beta v4.13.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* google_compute_region_network_endpoint_group

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.13.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 4.13.0"
    }
  }
}

resource "google_compute_region_network_endpoint_group" "api" {
  provider              = google-beta
  name                  = "api-neg"
  network_endpoint_type = "SERVERLESS"
  region                = "us-central1"

  description = "API network endpoint group"

  serverless_deployment {
    platform = "apigateway.googleapis.com"
    resource = "api-uscentral1"
  }
}
```

### Debug Output

https://gist.github.com/yuryu/3460cdf33ef985d715b39a47d906a905

### Expected Behavior

It should create a NEG pointing to API Gateway api-uscentral1. Only one of resource and url_mask should be required.

### Actual Behavior

Terraform stops with error:
```
│ Error: Missing required argument
│ 
│   on main.tf line 22, in resource "google_compute_region_network_endpoint_group" "api":
│   22:   serverless_deployment {
│ 
│ The argument "url_mask" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform apply`

### References

* [quickstart](https://cloud.google.com/api-gateway/docs/gateway-serverless-neg#creating_the_load_balancer)
* [gcloud beta compute network-endpoint-groups create](https://cloud.google.com/sdk/gcloud/reference/beta/compute/network-endpoint-groups/create#--serverless-deployment-resource)
* [Original PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/5434)

**Comment by jhasselgren** [comment] 2022-03-26 06:43
Looks like the problem is this line:
https://github.com/hashicorp/terraform-provider-google-beta/blob/bc1dba4806ad1b05138654bd5618d2ba1e4413db/google-beta/resource_compute_region_network_endpoint_group.go#L217

url_mask should be optional

**Comment by jose-lpa** [comment] 2022-04-03 15:33
Hi there. Since the fix for this seems quite trivial, is it going to be added to the next release of the provider? If so, when would it be released? It's actually blocking me to get API Gateway deployed with Terraform, as I didn't have any luck setting the URL mask parameter, but it works with `gcloud` when I use the `resource` one. Thanks.

**Comment by aebrahim** [comment] 2022-04-06 05:15
I had the exact same issue as you did @jose-lpa 

I've made GoogleCloudPlatform/magic-modules#5883 with this one-liner fix - hopefully it gets merged and into a release soon!

**Closed** 2022-04-15 17:52 UTC
Labels: bug
