### ISSUE TITLE
Latest Google beta provider v4.34.0 for gke_container_cluster looking for value of new added attribute node_pool_auto_config 

### ISSUE THREAD

**Issue by anudeet-m** [hashicorp/terraform-provider-google#12471] opened 2022-09-05 12:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

We are using google beta provider to provision gke cluster
### Terraform Version
Terraform v1.1.8
Installed hashicorp/google v4.34.0 
Installed hashicorp/google-beta v4.34.0..

### Affected Resource(s)

*google_container_cluster

### Terraform Configuration Files
We are using the below config to create cluster

`provider           = google-beta
  name               = abc-kcl
  description        = "test-demo-cluster"
  project            = abc
  location           = "euwes-2"
  network            = "test-network"
  subnetwork         = "test-subnetwork"
`

```tf
module.gke-cluster.module.gke_cluster.google_container_cluster.cluster has changed
  ~ resource "google_container_cluster" "cluster" {
        id                          = "projects/abc/locations/europe-west2/clusters/abc-kcl-euwe2"
      ~ master_version              = "1.21.12-gke.2200" -> "1.21.13-gke.900"
        name                        = "abc-kcl-02"
        # (28 unchanged attributes hidden)

  + node_pool_auto_config {
        }


```

### Debug Output
N/A
--->

### Panic Output
<img width="700" alt="Screenshot 2022-09-05 at 14 00 23" src="https://user-images.githubusercontent.com/94185473/188455484-7ea13a6f-c89b-4499-9caf-e027717b92be.png">

### Expected Behavior

The cluster should have been provisioned

### Actual Behavior

It is breaking to create cluster with latest provider looking for the value of node_pool_auto_config

### Steps to Reproduce

1. Create a GKE cluster using the latest google beta provider which is v4.34.0
2.  Run terraform apply

### References

Not that I could find

**Comment by edwardmedia** [comment] 2022-09-06 16:26
@melinath what happened?

**Comment by ayush-jain1** [comment] 2022-09-09 06:28
> @melinath what happened?

@edwardmedia @melinath 
can anyone please look into it ?

**Comment by melinath** [comment] 2022-09-12 20:33
Wasn't able to get to this. I can't easily tell from the provided debug information what the issue is. Could someone experiencing this please provide a minimal configuration that reproduces the issue? i.e. _just_ using the container_cluster resource, not a module. Thanks!

**Comment by philip-harvey** [comment] 2022-09-13 18:14
I think this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/12422

**Comment by edwardmedia** [comment] 2022-09-25 15:23
@anudeet-m it does appear to be a dup. Closing now. Feel free to reopen if the issue persists.

**Closed by edwardmedia** 2022-09-25 15:23 UTC
Labels: bug
