### ISSUE TITLE
google_compute_vpn_tunnel labels fingerprint either invalid or resource labels have changed

### ISSUE THREAD

**Issue by BostjanBozic** [hashicorp/terraform-provider-google#16588] opened 2023-11-22 11:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.7.0
+ provider registry.terraform.io/hashicorp/google-beta v5.7.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Affected Resource(s)

* google_compute_vpn_tunnel

### Terraform Configuration Files

```tf
provider "google" {
  default_labels = {
    created_by  = "terraform"
    environment = "dev"
    owner       = "test_owner"
    project     = "test_project"
  }
}

resource "google_compute_vpn_tunnel" "main" {
  for_each = toset([for vpn in google_compute_ha_vpn_gateway.main.vpn_interfaces[*].id : tostring(vpn)])
  name     = "${var.prefix}-${var.environment}-to-hub-${each.value}"
  project  = var.gcp_project.project_id
  region   = var.gcp_region

  description           = "VPN tunnel ${each.value} to hub VPC"
  ike_version           = 2
  peer_gcp_gateway      = "projects/${var.vpn_to_hub.hub_vpn_gw.project_id}/regions/${var.vpn_to_hub.hub_vpn_gw.region}/vpnGateways/${var.vpn_to_hub.hub_vpn_gw.name}"
  router                = google_compute_router.main.id
  shared_secret         = each.value == "0" ? var.vpn_to_hub.hub_vpn_tunnel_0.ike_secret : var.vpn_to_hub.hub_vpn_tunnel_1.ike_secret
  vpn_gateway           = google_compute_ha_vpn_gateway.main.id
  vpn_gateway_interface = tonumber(each.value)
}
```

### Debug Output

https://gist.github.com/BostjanBozic/a51b1e07055cf12118b615b8d93e18f7

### Expected Behavior

VPN tunnel resource should be updated with correct labels.

### Actual Behavior

Terraform apply fails with following error:
```
╷
│ Error: Error updating VpnTunnel "projects/test-project/regions/europe-west2/vpnTunnels/test-dev-to-hub-0": googleapi: Error 412: Labels fingerprint either invalid or resource labels have changed, conditionNotMet
│ 
│   with module.tf_module.module.network.google_compute_vpn_tunnel.main["0"],
│   on .terraform/modules/tf_module/modules/network/vpn.tf line 37, in resource "google_compute_vpn_tunnel" "main":
│   37: resource "google_compute_vpn_tunnel" "main" {
│ 
╵
╷
│ Error: Error updating VpnTunnel "projects/test-project/regions/europe-west2/vpnTunnels/test-dev-to-hub-1": googleapi: Error 412: Labels fingerprint either invalid or resource labels have changed, conditionNotMet
│ 
│   with module.tf_module.module.network.google_compute_vpn_tunnel.main["1"],
│   on .terraform/modules/tf_module/modules/network/vpn.tf line 37, in resource "google_compute_vpn_tunnel" "main":
│   37: resource "google_compute_vpn_tunnel" "main" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This issue started occurring after bumping provider from v5.6 to v5.7.

### References

* #0000

**Comment by edwardmedia** [comment] 2023-11-22 15:00
@BostjanBozic below is what I got which works. Basically I can't repro the issue. Trying to understand how the payload you got does not have `labelFingerprint`. 

```
 {
  "labelFingerprint": "1TQLkowq0ZY=",
  "labels": {
   "created_by": "terraform",
   "environment": "dev",
   "owner": "test_owner",
   "project": "test_project"
  }
 }
```

Noticed your config has dynamic code. Can you repro with a simple config that only has hardcoded attributes?

**Comment by BostjanBozic** [comment] 2023-11-22 15:18
@edwardmedia thanks for prompt response. Uf, that would be quite a task, since rest of the code depends on this as well and would require some major refactoring.

Would maybe change output suffice for you or is removing dynamic code the only way forward?

This is the output of plan:
```
  # module.tf_module.module.network.google_compute_vpn_tunnel.main["0"] will be updated in-place
  ~ resource "google_compute_vpn_tunnel" "main" {
      ~ effective_labels                = {
          + "created_by"  = "terraform"
          + "environment" = "dev"
          + "owner"       = "test_owner"
          + "project"     = "test_project"
        }
        id                              = "projects/test_project/regions/europe-west2/vpnTunnels/test-dev-to-hub-0"
        name                            = "cms-prd-to-hub-0"
      ~ terraform_labels                = {
          + "created_by"  = "terraform"
          + "environment" = "dev"
          + "owner"       = "test_owner"
          + "project"     = "test_project"
        }
        # (19 unchanged attributes hidden)
    }

  # module.tf_module.module.network.google_compute_vpn_tunnel.main["1"] will be updated in-place
  ~ resource "google_compute_vpn_tunnel" "main" {
      ~ effective_labels                = {
          + "created_by"  = "terraform"
          + "environment" = "dev"
          + "owner"       = "test_owner"
          + "project"     = "test_project"
        }
        id                              = "projects/test_project/regions/europe-west2/vpnTunnels/test-dev-to-hub-1"
        name                            = "cms-prd-to-hub-1"
      ~ terraform_labels                = {
          + "created_by"  = "terraform"
          + "environment" = "dev"
          + "owner"       = "test_owner"
          + "project"     = "test_project"
        }
        # (19 unchanged attributes hidden)
    }
```

**Comment by edwardmedia** [comment] 2023-11-22 16:07
@BostjanBozic the plan looks good, the same as what I got. I am not sure why `labelFingerprint` was not included in your payload.  Can you try [google-beta](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_vpn_tunnel#terraform_labels) to see if that works?

**Comment by BostjanBozic** [comment] 2023-11-23 07:52
@edwardmedia thanks for pointing this out - using google-beta provider actually solves the issue. I know quite some resources need google-beta when adding custom labels, maybe default provider labels were pushed for `google_compute_vpn_tunnel` yet resource itself still requires `google-beta` for labels?

**Comment by CoreDaveP** [comment] 2023-11-23 16:13
We are seeing this issue too - with no dynamic code

│ Error: Error updating VpnTunnel "projects/xxxxxxxxx/europe-west2/vpnTunnels/tnl-01": googleapi: Error 412: Labels fingerprint either invalid or resource labels have changed, conditionNotMet

- Installing hashicorp/google v5.7.0...
- Installed hashicorp/google v5.7.0 (signed by HashiCorp)
- Installing hashicorp/google-beta v5.7.0...
- Installed hashicorp/google-beta v5.7.0 (signed by HashiCorp)

resource "google_compute_vpn_tunnel" "vpntunnel1" {
  name                  = "tnl-01"
  project               = var.project_id
  region                = var.region
  vpn_gateway           = google_compute_ha_vpn_gateway.havpn_gateway.name
  peer_gcp_gateway      = "projects/${var.peer_project_id}/regions/${var.region}/vpnGateways/${var.peer_gateway}"
  shared_secret         = var.secret
  router                = google_compute_router.router.id
  vpn_gateway_interface = 0

  depends_on = [
    google_compute_ha_vpn_gateway.havpn_gateway,
    google_compute_router.router
  ]

  lifecycle {
    prevent_destroy = false
  }
}

Plan looks like :

# google_compute_vpn_tunnel.vpntunnel1 will be updated in-place
  ~ resource "google_compute_vpn_tunnel" "vpntunnel1" {
      ~ effective_labels                = {
          + "data_level"             = "xx"
          + "department"             = "xx"
          + "deploy_by"              = "xx"
          + "environment"            = "xx"
          + "gitlab_project_id"      = "xx"
          + "gitlab_project_path"    = "xx"
          + "operation_support_team" = "xx"
          + "ops_email_1"            = "xx"
          + "product"                = "xx"
          + "system_criticality"     = "xx"
        }
        id                              = "projects/xxxxx/regions/europe-west2/vpnTunnels/tnl-01"
      ~ labels                          = {
          + "data_level"             = "xx"
          + "department"             = "xx"
          + "deploy_by"              = "xx"
          + "environment"            = "xx"
          + "gitlab_project_id"      = "xx"
          + "gitlab_project_path"    = "xx"
          + "operation_support_team" = "xx"
          + "ops_email_1"            = "xx"
          + "product"                = "xx"
          + "system_criticality"     = "xx"
        }
        name                            = "tnl-01"
      ~ terraform_labels                = {
          + "data_level"             = "xx"
          + "department"             = "xx"
          + "deploy_by"              = "xx"
          + "environment"            = "xx"
          + "gitlab_project_id"      = "xx"
          + "gitlab_project_path"    = "xx"
          + "operation_support_team" = "xx"
          + "ops_email_1"            = "xx"
          + "product"                = "xx"
          + "system_criticality"     = "xx"
        }
        # (17 unchanged attributes hidden)

**Comment by edwardmedia** [comment] 2023-11-24 04:31
@CoreDaveP does google-beta help solve your problem? 

@BostjanBozic yes to your question. 

```
resource itself still requires google-beta for labels?
```

**Comment by edwardmedia** [comment] 2023-11-27 17:15
closing this now

**Closed by edwardmedia** 2023-11-27 17:15 UTC
Labels: bug, forward/review, service/compute-vpn

**Comment by CoreDaveP** [comment] 2023-11-27 17:29
> closing this now

Is this closed because it's now fixed ?

**Comment by BostjanBozic** [comment] 2023-11-28 07:53
I would say that the problem is still there, we just found a workaround for now (in your case downgrade to v5.6.0, in my case using `google-beta` provider). But I don't see any PR/commit that would actually address this issue.

**Comment by melinath** [comment] 2024-01-02 19:05
It looks like this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/16588

**Comment by melinath** [comment] 2024-01-10 17:17
This issue has now been resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9768
