### ISSUE TITLE
google_sql_user resources cannot be used when the google_sql_database_instance is stopped

### ISSUE THREAD

**Issue by jlpettersson** [hashicorp/terraform-provider-google#13123] opened 2022-11-28 15:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.4.1

### Affected Resource(s)

* google_sql_user
* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_sql_database_instance" "instance" {
    ...
    settings {
          activation_policy = "NEVER"
          ....
    }
}

resource "google_sql_user" "db_user" {
  instance = google_sql_database_instance.instance.name
  ....
}
```

### Expected Behavior

That I can do `terraform plan` and `terraform apply` successfully.

I expect that I can continue to use Terraform for resource management even while I have stopped a database instance. I would assume that the `google_sql_user` resource to be ignored meanwhile the database instance is stopped (activation_policy = "NEVER"). The current state is that Terraform cannot be used as a tool if I want to have an instance stopped and have `google_sql_user` resources managed by Terraform.

I don't expect to be able to change `google_sql_user` resources while the instance is stopped, but it should not fail to keep the resources.

### Actual Behavior

When doing `terraform plan`, I get the error: `Error 400: Invalid request` because the instanse is not running.

**Comment by edwardmedia** [comment] 2022-11-28 20:41
@jlpettersson what detailed error did you get? Can you share the debug log? I guess it is the API that refuses to serve based on the Error 400. If so, there is no much we can do at the provider level

**Comment by edwardmedia** [comment] 2022-12-11 16:10
@jlpettersson [instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user#instance) is a **required** field for `google_sql_user`. The user belongs to a specific instance. When the provider issue a GET request below, as the instance stop running, the error for api is expected. 

```
https://sqladmin.googleapis.com/sql/v1beta4/projects/sunedward-tf-host/instances/my-sql-insatnce/users
```

Closing this as it is by design

**Closed by edwardmedia** 2022-12-11 16:10 UTC
Labels: bug, waiting-response

**Comment by jlpettersson** [comment] 2022-12-11 16:32
@edwardmedia 

>[instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user#instance) is a required field for google_sql_user. The user belongs to a specific instance. When the provider issue a GET request below, as the instance stop running, the error for api is expected.

Yes, so a solution must be to **avoid** this GET request if the `google_sql_database_instance` resource is _stopped_  ( the `activation_policy` field set to `NEVER`).

Otherwise, Terraform cannot be used as a resource management tool for DB users if you want to have stopped databases (e.g. to save cost).
