### ISSUE TITLE
Support manual build triggers in google_cloudbuild_trigger

### ISSUE THREAD

**Issue by ggprod** [hashicorp/terraform-provider-google#11056] opened 2022-02-08 20:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
This is a request to support creation of manual cloud build triggers as per: https://cloud.google.com/build/docs/automating-builds/create-manual-triggers

### New or Affected Resource(s)

`google_cloudbuild_trigger`

### Potential Terraform Configuration

I believe there would need to be support for the sourceToBuild property of the API: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by rileykarson** [comment] 2022-02-14 18:41
@c2thorn: Dedupe if one exists, otherwise feel free to unassign!

**Comment by c2thorn** [comment] 2022-02-14 18:41
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/8374

**Closed by c2thorn** 2022-02-14 18:41 UTC
Labels: enhancement
