### ISSUE TITLE
instance_group_manager marked tainted if healthcheck failing

### ISSUE THREAD

**Issue by dv-stephen** [hashicorp/terraform-provider-google#9631] opened 2021-07-25 23:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.3

### Affected Resource(s)

* `google_compute_region_instance_group_manager`
* `google_compute_instance_group_manager`

### Terraform Configuration Files

I'm deploying a typical MIG, but with `wait_for_instances = true`:

```tf
resource "google_compute_instance_template" "my_app" {
  project = google_compute_subnetwork.primary_region.project
  region  = google_compute_subnetwork.primary_region.region

  name_prefix  = "my-app-"
  machine_type = "n1-standard-1"

  disk {
    boot         = true
    source_image = "cos-cloud/cos-stable"
    disk_type    = "pd-ssd"
    disk_size_gb = 40
  }

  network_interface {
    subnetwork = google_compute_subnetwork.primary_region.self_link
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_health_check" "my_app" {
  project = google_compute_instance_template.my_app.project
  name    = "my-app"

  check_interval_sec  = 10
  timeout_sec         = 5
  unhealthy_threshold = 5

  http_health_check {
    port         = 80
    request_path = "/-/health"
  }
}

resource "google_compute_region_instance_group_manager" "my_app" {
  project = google_compute_instance_template.my_app.project
  region  = google_compute_instance_template.my_app.region

  name               = "my-app"
  base_instance_name = "my-app"

  version {
    instance_template = google_compute_instance_template.my_app.id
  }

  target_size        = 1
  wait_for_instances = false

  named_port {
    name = "http"
    port = 80
  }

  auto_healing_policies {
    health_check      = google_compute_health_check.my_app.self_link
    initial_delay_sec = 30
  }
}
```

### Debug Output

https://gist.github.com/dv-stephen/610fafba3eddd0de9e941ee6fa7e13bd

### Expected Behavior

If there is an issue with the MIG such as a bad health check or faulty instance config that prevents the MIG from reaching a healthy state, terraform should be able to refresh the resource and allow code changes to fix the MIG.

### Actual Behavior

Terraform hangs on the refresh phase of the MIG resource, waiting for the MIG to become healthy which never happens. The only solution is manual intervention, preventing a GitOps model with changes being made through code.

### Steps to Reproduce

1. Deploy a MIG with `wait_for_instances = true` and a health check that will fail
2. The terraform run will timeout waiting for the MIG to become healthy
3. Run `terraform apply` again which will timeout during the refresh phase

**Comment by edwardmedia** [comment] 2021-07-26 15:40
@dv-stephen do you have the debug log available?

**Comment by dv-stephen** [comment] 2021-07-27 15:24
@edwardmedia Yes, here's the debug log: https://gist.github.com/dv-stephen/610fafba3eddd0de9e941ee6fa7e13bd

**Comment by edwardmedia** [comment] 2021-07-28 20:50
@dv-stephen from the log you provided, I found below line that seems not right. It contains 2 `projects`. It should be just one.  How did you provide the data for `project` in the config? When you say `cannot refresh`, not sure if that is related. 

> GET /compute/beta/projects/projects/strong-bad-o1xy/regions/us-central1/instanceGroupManagers/my-app?alt=json&prettyPrint=false HTTP/1.1

**Comment by dv-stephen** [comment] 2021-07-28 22:30
@edward2a Oh interesting, I didn't catch that. I updated the issue with the actual test code and not just a trivial example. I excluded the project/network resources as they're just boilerplate but can add them if needed.

I didn't completely track it down, but the compute client appends `projects` to its base URL and I'm guessing the resource(s) are also appending adding `projects`.

https://github.com/hashicorp/terraform-provider-google/blob/bafb3b98da3d9bd1daa8731d12a31b823efd6c62/google/config.go#L517

**Comment by edwardmedia** [comment] 2021-07-29 00:31
@dv-stephen once you fix the data for the `project` field, is this still an issue?

**Comment by dv-stephen** [comment] 2021-07-29 03:49
@edward2a Couple of updates:

1. I was wrong about `wait_for_instances = false` having the same behavior. It does ignore the state of the MIG and does allow me to write a custom shell provisioner to query myself. It's still a problem that the `wait_for_instances = true` option prevents the resource from being refreshed and requires manual intervention.

1. The `projects/projects` appears to be a bug in the provider. I hard-coded the `project` field of all the resources but the debug log still shows API requests with `projects/projects`. I believe it's related to the code in my previous comment -- double logic to add `projects` to the URL. I suspect this is happening to a lot more resources than the ones I'm using, perhaps all of the compute resources.

**Comment by edwardmedia** [comment] 2021-07-30 15:53
@dv-stephen how did you hard-code? I assume you were running directly on the provider resources (not modules), right? Can you share your code?

>  hard-coded the project field of all the resources but the debug log still shows API requests with projects/projects

**Comment by dv-stephen** [comment] 2021-07-30 16:01
@edward2a Sure, I set the `project` field of each resource to a static string:

```tf
resource "google_compute_instance_template" "my_app" {
  project = "strong-bad-6nx4"
  region  = google_compute_subnetwork.primary_region.region

  name_prefix  = "my-app-"
  machine_type = "n1-standard-1"

  disk {
    boot         = true
    source_image = "cos-cloud/cos-stable"
    disk_type    = "pd-ssd"
    disk_size_gb = 40
  }

  network_interface {
    subnetwork = google_compute_subnetwork.primary_region.self_link
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_health_check" "my_app" {
  project = "strong-bad-6nx4"
  name    = "my-app"

  check_interval_sec  = 10
  timeout_sec         = 5
  unhealthy_threshold = 5

  http_health_check {
    port         = 80
    request_path = "/-/health"
  }
}

resource "google_compute_region_instance_group_manager" "my_app" {
  project = "strong-bad-6nx4"
  region  = google_compute_instance_template.my_app.region

  name               = "my-app"
  base_instance_name = "my-app"

  version {
    instance_template = google_compute_instance_template.my_app.id
  }

  wait_for_instances = true
  target_size        = 1

  named_port {
    name = "http"
    port = 80
  }

  auto_healing_policies {
    health_check      = google_compute_health_check.my_app.self_link
    initial_delay_sec = 30
  }
}
```

There is no terraform reusable or child module, just the root. The provider is **not** configured with a project -- I specify the `project` for each resource.

**Comment by edwardmedia** [comment] 2021-07-30 16:06
@dv-stephen can you post the debug log?

**Comment by dv-stephen** [comment] 2021-07-30 17:25
@edward2a I'll work on getting you a test project for the MIG issues, but wanted to note that `projects/projects` appears to be a known bug? https://github.com/hashicorp/terraform-provider-google/issues/9657#issuecomment-890003135

**Comment by nphilbrook** [comment] 2021-08-02 19:48
> @edward2a I'll work on getting you a test project for the MIG issues, but wanted to note that `projects/projects` appears to be a known bug? [#9657 (comment)](https://github.com/hashicorp/terraform-provider-google/issues/9657#issuecomment-890003135)

Based on my experience filing the bug you referenced here, there is a pretty common pattern that if you access the `project` or `project_id` attribute of a TF google resource, it will return it in the format `projects/{{ project_id }}`, but this format does NOT work as an input for most resources.

**Comment by edwardmedia** [comment] 2021-08-03 22:56
`projects/projects` is not the reason causing this issue. If you look at the result, actually all resources are created at the end. But likely due to the failure in the health check, `google_compute_region_instance_group_manager` is marked as `tainted` which leads to the `timeout`.

**Comment by edwardmedia** [comment] 2021-08-03 22:56
https://github.com/hashicorp/terraform-provider-google/issues/2447

**Comment by rileykarson** [comment] 2021-08-04 16:44
@dv-stephen: While https://github.com/hashicorp/terraform-provider-google/issues/9657 isn't directly related (the problem there is that the user specified the wrong format and the API is behaving badly)  you're correct that Terraform is incorrectly sending requests to `projects/projects/{{project}}` despite the correct value being in use in your config.

I've spun out https://github.com/hashicorp/terraform-provider-google/issues/9722 to cover investigating that. We hadn't noticed the issue because the API was behaving correctly despite that- I suspect a change to the client library we use is the root cause. That said, I don't believe that error has an effect on the instance group manager behaviour here, so we can _probably_ isolate the two discussions / fixes.

**Comment by edwardmedia** [comment] 2021-08-04 18:03
@ScottSuarez how do you want to resolve this?

**Comment by ScottSuarez** [comment] 2021-08-06 00:11
We could expose a new field such as `wait for statuses`. This would allow the user to specify any number of statuses that they might want to wait for/on. I don't think accepting unhealthy states in `wait_for_instances_status` should be default behavior. Although I'm open to argumentation on why this should be the case.

**Comment by ScottSuarez** [comment] 2021-08-06 00:29
Revision of my previous ask after reading more into the resource.

Could you help me understand how to know when an instance is unhealthy and will never reach a stable state. I'm not very familiar with the health checks but it seems to be apart of `autoHealingPolicies[].healthCheck` which seems to infer some automatic resolution to this unless there is somewhere else a `healthCheck` is visible. 

If we did do such an early preempting with a warning or otherwise I would want to know for certain that it will never reach a stable state. How can I tell that from the resource? Otherwise if I stop the poll when stable may eventually be reached `wait_for_status` seems to be a pointless flag.

**Comment by ScottSuarez** [comment] 2021-08-06 00:43
If I understand correctly

I would need to iterate over each managed instance and verify that every single instance is in an unhealthy state.
https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers/listManagedInstances
https://cloud.google.com/compute/docs/instance-groups/autohealing-instances-in-migs

Would there need to be a buffer here between making the change to IGM and verifying that all downstream instances are unhealthy? This isn't really very tenable, and I would recommend asking the api to add such a feature. If indeed there are scenarios where all downstream VMs will never reach healthy states based on an IGM configuration (which it seems like there are from your ask). I do not believe it should be terraform's requirement to make such a complicated analysis. 

I believe instanceGroupManager api should surface such a status
https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers

**Comment by dv-stephen** [comment] 2021-08-06 15:41
@ScottSuarez I think the problem is that the `create` function invokes the `read` function -- they share the same logic. I believe the `create` logic works as expected: the resource should time out if the desired MIG state is never reached (in my case, `STABLE`). However, the `read` function should **not** require the MIG to be in any particular state, but should just **read** the current state of the MIG. 

Here's where `create` calls `read`: https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_compute_instance_group_manager.go#L462. 

I think a sensible solution is to simply change the `resourceComputeInstanceGroupManagerRead` function to read the current state rather than waiting for in-progress operations to complete: https://github.com/hashicorp/terraform-provider-google/blob/38351f6997e3b5dee1be18f457db02e0a1a21eef/google/resource_compute_instance_group_manager.go#L547.

**Comment by ScottSuarez** [comment] 2021-08-06 17:40
`read` normally doesn't require a state. `wait_for_instances` and `wait_for_instances_status` is what enables it to wait for the status to be green. If you don't use `wait_for_instances` and set it to false it should just shallowly apply the op and read the resource without waiting for the downstream manager to hit any particular state.

reading the resource after create is a normal pattern for terraform resources. It's how we refresh the state of the resource to reconcile what we did with what is present. The operation polling is separate. This is about the actually apply of the initial http call ensuring that the [resource was created as this is an asynchronous action](https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers/insert#response-body).

**Comment by dv-stephen** [comment] 2021-08-06 17:53
@ScottSuarez Yeah, that mostly makes sense; however, `read` should never prevent a terraform resource from being refreshed. Even with `wait_for_instances`, `read` shouldn't be polling and waiting for a resource state -- it should `read` the current state, regardless of what it is. I agree the reading/polling is necessary for `create` and `update`. Does that make more sense?

**Comment by ScottSuarez** [comment] 2021-08-09 18:29
@dv-stephen agreed. We shouldn't be doing this polling during read since it can result a broken refresh. I'll make the change to do this polling during create/update with an increased timeout.

**Closed** 2021-08-17 16:45 UTC
Labels: size/s, persistent-bug
