### ISSUE TITLE
Error creating PatchDeployment: googleapi: Error 403: Cloud OS Config API has not been used in project *** before or it is disabled. 

### ISSUE THREAD

**Issue by sowmiya-ragu** [hashicorp/terraform-provider-google#7307] opened 2020-09-21 07:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.21

### Affected Resource(s)

google_os_config_patch_deployment

### Terraform Configuration Files

```tf
resource "random_id" "id" {
  byte_length = 4
  prefix      = "${var.project_name}-"
}

locals {
  mandatory_Labels = {
    is_terraform      = "true"
    environment       = var.environment
    created_by        = var.created_by
    product_owner     = var.product_owner
    business_unit     = var.business_unit
    team              = var.team
    technical_contact = var.technical_contact
    terraform_repo    = var.tf_repo_path
  }
}

resource "google_project" "project" {
  name            = var.project_name
  project_id      = random_id.id.hex
  billing_account = var.billing_account
  folder_id       = var.folder_id
  labels          = merge(var.additional_labels, local.mandatory_Labels)

}

resource "google_project_iam_member" "developers_group" {
  for_each = var.developer_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.developers_group}"
}

resource "google_project_iam_member" "service-account-owner" {
  project = google_project.project.project_id
  role    = "roles/owner"
  member  = "serviceAccount:${google_service_account.ci-user.email}"
}

resource "google_project_service" "project" {
  for_each = var.google_apis
  project = google_project.project.project_id
  service = each.key
}

resource "google_os_config_patch_deployment" "patch" {

  patch_deployment_id = "test"
  project = google_project.project.project_id

  instance_filter {
    all = true
  }

  patch_config {
    reboot_config = "NEVER"

    apt {
      type = "DIST"
      excludes = [
        "python"]
    }

    yum {
      security = true
      minimal = true
      excludes = [
        "bash"]
    }

    goo {
      enabled = true
    }

    zypper {
      categories = [
        "security"]
    }

    windows_update {
      classifications = [
        "CRITICAL",
        "SECURITY",
        "UPDATE"]
    }


  }

  duration = "10s"

  recurring_schedule {
    time_zone {
      id = "Asia/Kolkata"

    }

    time_of_day {
      hours = "1"
      minutes = "0"
      seconds = "0"
      nanos = "0"
    }

    monthly {
      month_day = "1"
    }
  }
}
```

### Debug Output
**_Error: Error creating PatchDeployment: googleapi: Error 403: Cloud OS Config API has not been used in project **** before or it is disabled._** Enable it by visiting https://console.developers.google.com/apis/api/osconfig.googleapis.com/overview?project=**** then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/osconfig.googleapis.com/overview?project=****"
      }
    ]
  }
]

  on .terraform/modules/test-project-module.os-patch-deployment/os-patch-update/os-config-patch-deployment.tf line 2, in resource "google_os_config_patch_deployment" "patch":
   2: resource "google_os_config_patch_deployment" "patch" {

### Expected Behavior
I'm trying to create a project along with os patch management APIs enabled and a os patch deployment job created. Project is created and APIs are enabled when terraform apply is executed but fails to create a os patch job.

If I execute terraform apply again immediately , it creates the job.

I also tried providing a shell provision with sleep 5m to wait for the APIs to be enabled and then create the job. Still no luck.

Appreciate your help.

**Comment by upodroid** [comment] 2020-09-21 15:31
Hi

Your error happens because you are not referencing the project from the correct resource.

`google_os_config_patch_deployment` is currently dependent on `google_project.project.` instead of `google_project_service.project`. What that means is that the patch deployment will be created immediately after the project is created instead of after the api service is enabled.

Since you are using foreach, do `project = google_project_service.project["osconfig.googleapis.com"].project,` instead of  `project = google_project.project.project_id` .

If this solves your issues, please go ahead and close this issue.

Thank you

**Comment by sowmiya-ragu** [comment] 2020-09-22 06:27
I have also tried setting up depends_on in google_os_config_patch_deployment.
`depends_on = [google_project_service.project]` 
Setting `project = google_project_service.project["osconfig.googleapis.com"].project` in google_project_service throws the below error `Error: Cycle: module.test-project-module.google_project_service.project["osconfig.googleapis.com"], module.test-project-module.google_project_service.project["containeranalysis.googleapis.com”]`

**Comment by edwardmedia** [comment] 2020-09-22 16:05
@sowmiya-ragu what did you see after adding `depends_on = [google_project_service.project]`? Can you share your full code & debug log if the issue is not resolved?

**Comment by sowmiya-ragu** [comment] 2020-09-23 05:11
@edwardmedia Please find the code and log:
`resource "random_id" "id" {
  byte_length = 4
  prefix      = "${var.project_name}-"
}

locals {
  mandatory_Labels = {
    is_terraform      = "true"
    environment       = var.environment
    created_by        = var.created_by
    product_owner     = var.product_owner
    business_unit     = var.business_unit
    team              = var.team
    technical_contact = var.technical_contact
    terraform_repo    = var.tf_repo_path
  }
}

resource "google_project" "project" {
  name            = var.project_name
  project_id      = random_id.id.hex
  billing_account = var.billing_account
  folder_id       = var.folder_id
  labels          = merge(var.additional_labels, local.mandatory_Labels)

  # Sometimes bucket create fails with 'inactive billing account' without this sleep
  # https://github.com/terraform-providers/terraform-provider-google/issues/3429
  provisioner "local-exec" {
    command = "sleep ${var.gcp_flakiness_sleep}"
  }
}

resource "google_project_iam_member" "developers_group" {
  for_each = var.developer_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.developers_group}"
}

resource "google_project_iam_member" "testers_group" {
  for_each = var.testers_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.testers_group}"
}

resource "google_project_iam_member" "ttm_base_image_developers_access" {
  for_each = var.compute_vm_roles
  project = var.ttm_base_image_project_id
  role    = each.key
  member  = "group:${var.developers_group}"
}

resource "google_project_iam_member" "operations_group" {
  for_each = var.operations_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.operations_group}"
}

resource "google_project_iam_member" "monitoring_group" {
  for_each = var.monitoring_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.monitoring_group}"
}

resource "google_project_iam_member" "primary_owner" {
  count   = var.primary_owner != "" ? 1 : 0
  project = google_project.project.project_id
  role    = "roles/owner"
  member  = "user:${var.primary_owner}"
}

resource "google_service_account" "ci-user" {
  project      = google_project.project.project_id
  account_id   = "ci-user"
  display_name = "CI Service Account"
}

resource "google_project_iam_member" "service-account-owner" {
  project = google_project.project.project_id
  role    = "roles/owner"
  member  = "serviceAccount:${google_service_account.ci-user.email}"
}

resource "google_storage_bucket" "tf-state" {
  project = google_project.project.project_id
  name    = "${google_project.project.project_id}-tf-state"
}

module "os-patch-deployment" {

  source = "git::ssh://git@bitbucket.trimble.tools/pnet-platform/gcp-tf-compute-engine//os-patch-update?ref=v0.0.1"
  os_patch_deployment_name = "${var.project_name}-vm-patch"
  project_id = google_project.project.project_id
  patch-time-hours = "1"
  patch-time-minutes = "30"
  patch-time-seconds = "0"
  patch-time-nanos = "0"
  patch-time-day = "1"

}

resource "google_project_service" "project" {
  for_each = var.google_apis
  project = google_project.project.project_id
  service = each.key
}

resource "google_os_config_patch_deployment" "patch" {

  depends_on = [google_project_service.project]
  patch_deployment_id = "test"
  project = google_project.project.project_id

  instance_filter {
    all = true
  }

  patch_config {
    reboot_config = "NEVER"

    apt {
      type = "DIST"
      excludes = [
        "python"]
    }

    yum {
      security = true
      minimal = true
      excludes = [
        "bash"]
    }

    goo {
      enabled = true
    }

    zypper {
      categories = [
        "security"]
    }

    windows_update {
      classifications = [
        "CRITICAL",
        "SECURITY",
        "UPDATE"]
    }


  }

  duration = "10s"

  recurring_schedule {
    time_zone {
      id = "Asia/Kolkata"

    }

    time_of_day {
      hours = "1"
      minutes = "0"
      seconds = "0"
      nanos = "0"
    }

    monthly {
      month_day = "1"
    }
  }
}`

Error log: 
`Error: Error creating PatchDeployment: googleapi: Error 403: Cloud OS Config API has not been used in project **** before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/osconfig.googleapis.com/overview?project=**** then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/osconfig.googleapis.com/overview?project=****"
      }
    ]
  }
]

  on .terraform/modules/test-project-module.os-patch-deployment/os-patch-update/os-config-patch-deployment.tf line 2, in resource "google_os_config_patch_deployment" "patch":
   2: resource "google_os_config_patch_deployment" "patch" {
`

**Comment by upodroid** [comment] 2020-09-23 08:41
Hi

Can you format you code block correctly?

Also that is not the debug logs we need.

Run the following command `TF_LOG=debug terraform apply --auto-approve > debug.log` . Copy the contents of that log into a gist and paste the link to it here. Just run a plan beforehand as it won't prompt you to approve the apply.

Have a look at the gist in this issue https://github.com/hashicorp/terraform-provider-google/issues/7311 for an idea of what we need.

**Comment by sowmiya-ragu** [comment] 2020-09-24 09:45
The issue is resolved with the following code. I dont see much difference in the code which I had previously posted here and now.
`resource "random_id" "id" {
  byte_length = 4
  prefix      = "${var.project_name}-"
}

locals {
  mandatory_Labels = {
    is_terraform      = "true"
    created_by        = var.created_by
    environment       = var.environment
    product              = var.product
    primary-contact-name = var.primary-contact-name
    primary-contact-email = var.primary-contact-email
    team-contact-email = var.team-contact-email
    business-unit = var.business_unit
    terraform_repo    = var.tf_repo_path
  }
}

resource "google_project" "project" {
  name            = var.project_name
  project_id      = random_id.id.hex
  billing_account = var.billing_account
  folder_id       = var.folder_id
  labels          = merge(var.additional_labels, local.mandatory_Labels)

  # Sometimes bucket create fails with 'inactive billing account' without this sleep
  # https://github.com/terraform-providers/terraform-provider-google/issues/3429
  provisioner "local-exec" {
    command = "sleep ${var.gcp_flakiness_sleep}"
  }
}

resource "google_project_iam_member" "developers_group" {
  for_each = var.developer_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.developers_group}"
}

resource "google_project_iam_member" "testers_group" {
  for_each = var.testers_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.testers_group}"
}

resource "google_project_iam_member" "ttm_base_image_developers_access" {
  for_each = var.compute_vm_roles
  project = var.ttm_base_image_project_id
  role = each.key
  member = "group:${var.developers_group}"
}

resource "google_project_iam_member" "operations_group" {
  for_each = var.operations_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.operations_group}"
}

resource "google_project_iam_member" "monitoring_group" {
  for_each = var.monitoring_roles
  project = google_project.project.project_id
  role    = each.key
  member  = "group:${var.monitoring_group}"
}

resource "google_project_iam_member" "primary_owner" {
  count   = var.primary_owner != "" ? 1 : 0
  project = google_project.project.project_id
  role    = "roles/owner"
  member  = "user:${var.primary_owner}"
}

resource "google_service_account" "ci-user" {
  project      = google_project.project.project_id
  account_id   = "ci-user"
  display_name = "CI Service Account"
}

resource "google_project_iam_member" "service-account-owner" {
  project = google_project.project.project_id
  role    = "roles/owner"
  member  = "serviceAccount:${google_service_account.ci-user.email}"
}

resource "google_storage_bucket" "tf-state" {
  project = google_project.project.project_id
  name    = "${google_project.project.project_id}-tf-state"
}

resource "google_os_config_patch_deployment" "patch" {
  depends_on = [google_project_service.project]
  patch_deployment_id = "${var.project_name}-os-patch-deployment"
  project = google_project.project.project_id

  instance_filter {
    all = true
  }

  patch_config {
    reboot_config = "NEVER"

    apt {
      type = "DIST"
      excludes = [
        "python"]
    }

    yum {
      security = true
      minimal = true
      excludes = [
        "bash"]
    }

    goo {
      enabled = true
    }

    zypper {
      categories = [
        "security"]
    }

    windows_update {
      classifications = [
        "CRITICAL",
        "SECURITY",
        "UPDATE"]
    }


  }

  duration = "10s"

  recurring_schedule {
    time_zone {
      id = "Asia/Kolkata"

    }

    time_of_day {
      hours = "1"
      minutes = "30"
      seconds = "0"
      nanos = "0"
    }
    monthly {
      month_day = "28"
    }
  }
}

resource "google_project_service" "project" {
  for_each = var.google_apis
  project = google_project.project.project_id
  service = each.key
}`

**Closed** 2020-09-24 09:49 UTC
Labels: bug
