### ISSUE TITLE
google_iam_policy with dynamic conditional binding always show diff on plan

### ISSUE THREAD

**Issue by theminghuang** [hashicorp/terraform-provider-google#16298] opened 2023-10-18 16:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_iam_policy. But I think it may apply to other data resource with binding as well

### Terraform Configuration Files

```tf
data "google_iam_policy" "policy" {
  binding {
     ...
  }

  dynamic "binding" {
    for_each = lookup(var.viewers, each.key, null) != null ? [lookup(var.viewers, each.key)] : []
    content {
      members = binding.value.members
      role    = "roles/secretmanager.viewer"
      condition {
        expression = binding.value.condition.expression
        title      = binding.value.condition.title
      }
    }
  }
}

resource "google_secret_manager_secret_iam_policy" "policy" {
  project     = var.project_id
  secret_id   = google_secret_manager_secret.secret.secret_id
  policy_data = data.google_iam_policy.policy.policy_data
}
```

### Expected Behavior

Should not show diff on plan after applied.

### Actual Behavior

Show diff on every plan
```
  ~ resource "google_secret_manager_secret_iam_policy" "policy" {
      ...
      ~ policy_data = jsonencode(
          ~ {
              ~ bindings = [
                    # (1 unchanged element hidden)
                  ~ {
                      + condition = {
                          + expression = "some expression"
                          + title      = "some title"
                        }
                      ~ role      = "roles/secretmanager.viewer_withcond_3d5bd4f3d1cd3952fe85" -> "roles/secretmanager.viewer"
                    },
                ]
            }
        )
        # (3 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

b/306360761

**Comment by abheda-crest** [comment] 2024-10-03 09:48
In the `google_secret_manager_secret_iam_*` resources, the condition fields were not supported because the  `iam_conditions_request_type` field was missing in the Secret Manager [Secret resource](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/secretmanager/Secret.yaml).
This issue has now been resolved and support for this field has been added as a part of this [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10844). The condition field was introduced as part of release [5.33.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md?plain=1#L586).  The details regarding the condition field are available in the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_iam#condition).

**Comment by melinath** [comment] 2024-10-03 15:36
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11127

**Comment by melinath** [comment] 2024-10-03 15:36
@abheda-crest thanks for identifying that this has been resolved!

**Closed by melinath** 2024-10-03 15:36 UTC
Labels: bug, upstream, forward/linked, service/secretmanager
