### ISSUE TITLE
google_container_node_pool: modifying taints forces replacement

### ISSUE THREAD

**Issue by xinau** [hashicorp/terraform-provider-google#16054] opened 2023-09-29 10:14 UTC
### Terraform Version

```console
$ terraform version
Terraform v1.5.3
on linux_amd64
...
+ provider registry.terraform.io/hashicorp/google v4.75.0
+ provider registry.terraform.io/hashicorp/google-beta v4.75.0
...

Your version of Terraform is out of date! The latest version
is 1.5.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `google_container_node_pool`

### Terraform Configuration Files

```diff
  resource "google_container_node_pool" "default" {
    name       = "default"
    cluster    = google_container_cluster.default.id
    node_count = 1

    node_config {
      machine_type = "n1-standard"
      service_account = google_service_account.default.email
      oauth_scopes = [
        "https://www.googleapis.com/auth/cloud-platform"
      ]
      taint = [{
        key = "example.com/taint-1"
        effect = "NO_SCHEDULE" cause
        value = "true"
+     }, {
+       key = "example.com/taint-2"
+       effect = "NO_SCHEDULE"
+       value = "true"
      }]
    }
}
```

### Expected Behavior

I've expected that the provider to behave the same way as the Google Cloud console when a new taint is added in that it does an in-place update.

### Actual Behavior

The actual behavior is that a chance to a node pools taints forces a replacement of the node-pool. Having the ability to do an in-place update as provided by the Google Cloud console is critical when managing multiple clusters with multiple node pools and thousands of nodes as a replace or blue-green approach is mostly infeasible.

### Steps to Reproduce

1. Create a GKE node pool using Terraform with a single taint like `example.com/taint-1=true:NoSchedule`
2. Modify the GKE node pool using Terraform by adding a new taint like `example.com/taint-2=true:NoSchedule`
3. Watch Terraform force replace the modified node pool.

b/302797527

**Comment by philip-harvey** [comment] 2023-10-03 20:02
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/13872?

**Comment by xinau** [comment] 2023-10-05 08:32
@philip-harvey thanks for the catch. I've seemed to missed this one. Yes this is a duplicate.

**Closed** 2024-10-25 18:09 UTC
Labels: bug, forward/linked, service/container
