### ISSUE TITLE
TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample failed

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-provider-google#13461] opened 2023-01-11 20:40 UTC
### Affected Resource(s)

* google_cloudfunctions2_function

=== RUN   TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample
=== PAUSE TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample
=== CONT  TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample
    provider_test.go:315: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error waiting to create function: Error waiting for Creating function: Error code 9, message: Creating trigger failed for projects/ci-test-project-188019/locations/us-central1/triggers/tf-test-gcf-functionslac3i8233-241993: generic::failed_precondition: Cloud Pub/Sub did not have the necessary permissions configured to support this operation. Please verify that the service account service-1067888929963@gcp-sa-pubsub.iam.gserviceaccount.com was granted the Cloud KMS CryptoKey Encrypter/Decrypter role for the project containing the CryptoKey resource projects/ci-test-project-188019/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tf-bootstrap-key2/grants/c481b13e954e859d.
        
          with google_cloudfunctions2_function.function,
          on terraform_plugin_test.tf line 61, in resource "google_cloudfunctions2_function" "function":
          61: resource "google_cloudfunctions2_function" "function" {
        
--- FAIL: TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample (144.43s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta	144.467s
FAIL

**Comment by ScottSuarez** [comment] 2023-02-14 20:55
duplicate of [TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample](https://github.com/hashicorp/terraform-provider-google/issues/12908)

**Closed** 2023-02-14 20:55 UTC
Labels: bug, test failure
