### ISSUE TITLE
google_container_cluster addons_config property is ignored after initial apply

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-google#12690] opened 2022-09-30 19:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.58.0
+ provider registry.terraform.io/hashicorp/google v3.84.0
+ provider registry.terraform.io/hashicorp/google-beta v3.84.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
  addons_config {
    http_load_balancing {
      disabled = false
    }
    config_connector_config {
      enabled = true
    }
  }

  lifecycle {
    ignore_changes = [
      node_pool,
    ]
  }
```

### Expected Behavior

Commenting out `addons_config` config and planning should show a diff and disable the addons

### Actual Behavior

Commenting out addons shows no diff.

### Steps to Reproduce

See above config.

### Important Factoids

I'm ignoring `node_pool`. But addons are for the control plane so that shouldn't ignore cluster settings like this right? 

Also, if an addon is manually disabled the state _is_ updated with that change. For example if I dump the entire resource to an output I see this after manually disabling an addon:

```tf
  ~ my-module-output = {
      ~ google_container_cluster = {
          ~ addons_config                     = [
              ~ {
                  ~ config_connector_config               = [
                      ~ {
                          ~ enabled = true -> false
                        },
                    ]
                    # (8 unchanged elements hidden)
                },
            ]
            # (57 unchanged elements hidden)
        }
        # (2 unchanged elements hidden)
    }
```

* #0000

**Comment by edwardmedia** [comment] 2022-10-03 01:54
@red8888 this is expected. When the provider does not send any for `addons_config`, the API set bunch of defaults and send them back in the response, which could have caused permdiff all the time. To mitigate this behavior, Terraform provides [computed](https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#computed) for it. 

With this in place, the provider can't tell any diff for this field. That is what you see. Does that make sense?

**Comment by slevenick** [comment] 2022-10-07 17:53
Closing as intended behavior

**Closed by slevenick** 2022-10-07 17:53 UTC
Labels: bug, waiting-response
