### ISSUE TITLE
Failing test(s): Error code 9, message: encountered some transient internal error, please try again later

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12902] opened 2022-10-28 17:42 UTC
Failure rate: 100% since 2022-10-08

Impacted tests:
- TestAccSqlDatabaseInstance_Timezone
- TestAccSqlDatabaseInstance_SqlServerAuditConfig
- TestAccSqlDatabaseInstance_ActiveDirectory
- TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeClone
- TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica
- TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange
- TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange
- TestAccServiceNetworkingConnection_create
- TestAccRedisInstance_redisInstancePrivateServiceExample
- TestAccMemcacheInstance_update
- TestAccMemcacheInstance_memcacheInstanceBasicExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/348525?buildTab=tests&expandedTest=-7672761041235634148

Message:

```
Error: Error waiting for Create Service Networking Connection: Error code 9, message: encountered some transient internal error, please try again later
```

b/256181958

**Comment by AarshDhokai** [comment] 2022-12-02 11:39
Cumulatively all the tests are failing 100% in builds : 
[Google Cloud](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/357019?buildTab=tests&pager.currentPage=1&status=failed) and [Google Cloud Beta](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/357055?buildTab=tests&pager.currentPage=1&status=all&expandedTest=-7237469270685448170)

**Comment by AarshDhokai** [comment] 2022-12-07 13:04
b/261701420

**Comment by roaks3** [comment] 2022-12-14 21:14
I came across this one in a recent PR, so did a little investigating.

Some historical context I was able to dig up:
* This issue has come up for a number of VCR tests, and one recent case was discussed more here: https://github.com/GoogleCloudPlatform/magic-modules/pull/6667
* That PR led to discussion with the service team on b/254484541 (which relates to an earlier ticket b/251305449)
* The above ticket is not resolved, but there is speculation that the root cause is the IP ranges being too large (the suggestion was to try `prefix_length = 24` instead of `prefix_length = 16`
* Practically speaking, `/24` should be more than enough addresses for our SQL tests, probably our other tests too. Our documentation does recommend `/16`, but we don't need every test to reserve that large of a block: https://cloud.google.com/sql/docs/mysql/private-ip#allocated_range_size
* There have been some prior efforts that seem to be related to these errors, like introducing the bootstrapped network (https://github.com/GoogleCloudPlatform/magic-modules/pull/2920, https://github.com/GoogleCloudPlatform/magic-modules/pull/3039) and using a PATCH instead of POST for creating the connection (https://github.com/GoogleCloudPlatform/magic-modules/pull/2446)
* There was an additional test added that reserved a /16 block the day before this was noticed in our tests, which might indicate was crossed a threshold with that addition: https://github.com/GoogleCloudPlatform/magic-modules/pull/6617
* We have  tests that use `/16` blocks and appear to have no issue, most of which are in Apigee
* There is a very similar error in one of the Apigee tests that implies the IP space is being exhausted:
```
=== RUN   TestAccApigeeInstance_apigeeInstanceIpRangeTestExample
=== PAUSE TestAccApigeeInstance_apigeeInstanceIpRangeTestExample
=== CONT  TestAccApigeeInstance_apigeeInstanceIpRangeTestExample
    provider_test.go:307: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error waiting to create Instance: Error waiting for Creating Instance: Error code 9, message: couldn\t find a free IP space of /22 to launch an instance. Verify the peering ranges are available as per https://cloud.google.com/apigee/docs/api-platform/get-started/install-cli#service-networking and try again
        
          with google_apigee_instance.apigee_instance,
          on terraform_plugin_test.tf line 57, in resource "google_apigee_instance" "apigee_instance":
          57: resource "google_apigee_instance" "apigee_instance" {
        
--- FAIL: TestAccApigeeInstance_apigeeInstanceIpRangeTestExample (612.07s)
```

**Comment by roaks3** [comment] 2022-12-14 21:20
My current theory is that we are reserving too much IP space with our tests, so at some point as our tests are being run in parallel, we run out of space and begin failing subsequent tests. I believe we should try some combination of reserving `/24` blocks across existing tests, and maybe trying bootstrapped network connections so that we don't need to reserve as many blocks.

**Comment by roaks3** [comment] 2023-01-21 01:01
I checked in on this today and the `Error code 9, message: encountered some transient internal error, please try again later` error has not occurred on any of these tests for the last 2 weeks (starting with the [Jan 6 build](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=364987&tab=buildResultsDiv&buildTypeId=GoogleCloud_ProviderGoogleCloudGoogleProject)).

Some of these tests are failing for other reasons now, but I think it's safe to close this ticket.

As for the cause/resolution, it isn't clear to me exactly what resolved this. We had been in the process of capturing more resources with our sweepers, and the Jan 6 build was the first build in multiple months that the sweeper was able to run all the way through (due to disabling the [CloudIdsEndpoints](https://github.com/GoogleCloudPlatform/magic-modules/pull/7071) sweeper and [OSPolicyAssignment](https://github.com/GoogleCloudPlatform/magic-modules/pull/7034) sweeper). My theory is that we had accumulated networking resources in the test project, perhaps due to some of the heavier resources like Composer/SQL/Dataproc not being cleaned up, and that was in some way preventing new SQL instances from being provisioned. But it is interesting that this seemed to start with https://github.com/GoogleCloudPlatform/magic-modules/pull/6617 and end with https://github.com/GoogleCloudPlatform/magic-modules/pull/7071 🤷 .

**Closed by roaks3** 2023-01-21 01:01 UTC
Labels: size/xs, priority/1, test failure, crosslinked
