### ISSUE TITLE
network = "" null # forces replacement

### ISSUE THREAD

**Issue by ckolla-castlight** [hashicorp/terraform-provider-google#15015] opened 2023-06-29 16:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

~> 4.71.0

### Affected Resource(s)

* google_compute_region_network_endpoint_group

### Terraform Configuration Files

``` resource "google_compute_region_network_endpoint_group" "psc-consumer-app" {
  name                  = "psc-consumer-test"
  region                = "us-central1"

  network_endpoint_type = "PRIVATE_SERVICE_CONNECT"
  psc_target_service    = "projects/prj-eng-d-env-test/regions/${data.google_compute_subnetwork.private.region}/serviceAttachments/psc-producer-app"

  network               = data.google_compute_network.main.self_link
  subnetwork            = data.google_compute_subnetwork.private.self_link
}
```

### Debug Output

  # google_compute_region_network_endpoint_group.psc-consumer-artifactory must be replaced
-/+ resource "google_compute_region_network_endpoint_group" "psc-consumer-app" {
      ~ id                    = "projects/prj-eng-d-env-test/regions/us-central1/networkEndpointGroups/psc-consumer-app" -> (known after apply)
        name                  = "psc-consumer-app"
      - network               = "https://www.googleapis.com/compute/v1/projects/prj-d-shared-test/global/networks/vpc-d-shared-test" -> **null # forces replacement**
      ~ project               = "prj-eng-d-env-test" -> (known after apply)
      ~ region                = "https://www.googleapis.com/compute/v1/projects/prj-eng-d-env-test/regions/us-central1" -> "us-central1"
      ~ self_link             = "https://www.googleapis.com/compute/v1/projects/prj-eng-d-env-test/regions/us-central1/networkEndpointGroups/psc-consumer-test" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

### Expected Behavior

The network shouldn't be updated with null( should not fource replacement).

### Actual Behavior

The network is updating with null value.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment] 2023-06-29 16:47
@ckolla-castlight [network](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_endpoint_group#network) is an optional field. Isn't null still a valid value? Any change on network triggers replacement.  Looks like this is by design. Why do you reach below expectation?

```
The network shouldn't be updated with null( should not fource replacement).
```

**Comment by ckolla-castlight** [comment] 2023-06-29 19:57
@edwardmedia, network is an optional field. But we are defining network in our resource to create under right network. We didn't make any changes in the network. Thought terraform apply try to change it to null with # forces replacement which is not expected.

**Comment by edwardmedia** [comment] 2023-06-29 21:22
@ckolla-castlight It seems the `network` is saved in the state. It is the question about what data source is in the 2nd plan. Can you verify what it is?

```
 network               = data.google_compute_network.main.self_link
```

**Comment by edwardmedia** [comment] 2023-07-13 13:08
@ckolla-castlight closing this now assuming it is no longer an issue

**Closed as completed by edwardmedia** 2023-07-13 13:08 UTC
Labels: bug, forward/review, service/compute-networking-neg
