### ISSUE TITLE
Random authentication errors

### ISSUE THREAD

**Issue by c-w** [hashicorp/terraform-provider-google#13730] opened 2023-02-13 21:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.3.8 (provider version 4.52.0)

### Affected Resource(s)

* google_bigquery_dataset
* google_service_account

### Terraform Configuration Files

```tf
resource "google_bigquery_dataset" "datalake" {
  dataset_id                 = "REDACTEDpr436"
  location                   = "us-west1"
  delete_contents_on_destroy = true
  max_time_travel_hours      = 48
}

resource "google_bigquery_table" "telemetry" {
  dataset_id          = google_bigquery_dataset.datalake.dataset_id
  table_id            = "telemetry"
  deletion_protection = false
}

resource "google_service_account" "telemetry" {
  account_id = "REDACTEDpr436"
}

resource "google_service_account_key" "telemetry" {
  service_account_id = google_service_account.telemetry.name
}

resource "google_bigquery_dataset_access" "telemetry_writer" {
  dataset_id        = google_bigquery_dataset.datalake.dataset_id
  user_by_email = google_service_account.telemetry.email
  role                   = "WRITER"
}
```

### Debug Output

Excerpt from stdout:

```
╷
│ Error: Error when reading or editing BigQueryDataset "projects/round-plating-365219/datasets/REDACTEDpr436": googleapi: got HTTP response code 403 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 403 (Forbidden)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>403.</b> <ins>That’s an error.</ins>
│   <p>Your client does not have permission to get URL <code>/bigquery/v2/projects/round-plating-365219/datasets/REDACTEDpr436</code> from this server.  <ins>That’s all we know.</ins>
│ 
│ 
│   with google_bigquery_dataset.datalake,
│   on resources.tf line 674, in resource "google_bigquery_dataset" "datalake":
│  674: resource "google_bigquery_dataset" "datalake" {
│ 
╵
╷
│ Error: Error when reading or editing Service Account "projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gservice***.com": googleapi: got HTTP response code 403 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 403 (Forbidden)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>403.</b> <ins>That’s an error.</ins>
│   <p>Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gservice***.com</code> from this server.  <ins>That’s all we know.</ins>
│ 
│ 
│   with google_service_***.telemetry,
│   on resources.tf line 725, in resource "google_service_***" "telemetry":
│  725: resource "google_service_***" "telemetry" {
│ 
```

Excerpt from debug log:

```
-----------------------------------------------------: timestamp=2023-02-13T21:19:29.904Z
2023-02-13T21:19:29.919Z [INFO]  provider.terraform-provider-google_v4.52.0_x5: 2023/02/13 21:19:29 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 403 Forbidden
Content-Length: 1686
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=UTF-8
Date: Mon, 13 Feb 2023 21:19:29 GMT
Referrer-Policy: no-referrer

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com</code> from this server.  <ins>That’s all we know.</ins>

-----------------------------------------------------: timestamp=2023-02-13T21:19:29.919Z
2023-02-13T21:19:29.919Z [INFO]  provider.terraform-provider-google_v4.52.0_x5: 2023/02/13 21:19:29 [DEBUG] Retry Transport: Stopping retries, last request failed with non-retryable error: googleapi: got HTTP response code 403 with body: HTTP/2.0 403 Forbidden
Content-Length: 1686
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=UTF-8
Date: Mon, 13 Feb 2023 21:19:29 GMT
Referrer-Policy: no-referrer

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com</code> from this server.  <ins>That’s all we know.</ins>: timestamp=2023-02-13T21:19:29.919Z
2023-02-13T21:19:29.919Z [INFO]  provider.terraform-provider-google_v4.52.0_x5: 2023/02/13 21:19:29 [DEBUG] Retry Transport: Returning after 1 attempts: timestamp=2023-02-13T21:19:29.919Z
2023-02-13T21:19:29.919Z [ERROR] provider.terraform-provider-google_v4.52.0_x5: Response contains error diagnostic: diagnostic_summary="Error when reading or editing Service Account "projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com": googleapi: got HTTP response code 403 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com</code> from this server.  <ins>That’s all we know.</ins>
" tf_proto_version=5.3 tf_resource_type=google_service_account @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_severity=ERROR @module=sdk.proto diagnostic_detail= tf_provider_addr=provider tf_req_id=74c3f53e-1b44-7739-2d65-2b94410948a4 tf_rpc=ReadResource timestamp=2023-02-13T21:19:29.919Z
2023-02-13T21:19:29.920Z [ERROR] vertex "google_service_account.telemetry" error: Error when reading or editing Service Account "projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com": googleapi: got HTTP response code 403 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com</code> from this server.  <ins>That’s all we know.</ins>
2023-02-13T21:19:29.920Z [ERROR] vertex "google_service_account.telemetry (expand)" error: Error when reading or editing Service Account "projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com": googleapi: got HTTP response code 403 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com</code> from this server.  <ins>That’s all we know.</ins>
```

### Expected Behavior

Expected resources to be created, read, updated or deleted.

### Actual Behavior

Resource creation, read, update or delete fails with a 403 permissions error although using the same credentials and code worked just on the run before!

### Steps to Reproduce

1. `terraform apply` (works sometimes, randomly breaks and once it's broken it keeps being broken)
2. `terraform destroy` (works sometimes, randomly breaks and once it's broken it keeps being broken)

### Important Factoids

* The service account used to run the terraform script has Owner permissions. I also tried with a different set of permissions but I see the same behavior.
* Re-generating the service account key fixes the deploys for a little while but eventually they start breaking again.
* Re-creating the service account fixes the deploys for some time but they end up breaking again after running a few times.
* I don't see any bad requests on the GCP console logs tab of the service account.

**Comment by edwardmedia** [comment] 2023-02-13 22:14
@c-w interesting. Not sure what happens. One thing I can think of is how you manage the service account that run the terraform? Is it and its roles are managed terraform? Where are there code?

To verify, can you run the terraform with your default account ([gcloud auth application-default login](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login)) to see if the issue persists?

**Comment by c-w** [comment] 2023-02-13 22:38
Thanks for the quick reply @edwardmedia. I manually created the service account and its key in the GCP console, downloaded the key and copied it into a Github Action secret, similar to the flow below:

```sh
tr '\n' ' ' < ~/Downloads/round-plating-365219-b917f819a477.json | xclip -sel clip
```

```yml
run: terraform apply
env:
    TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
```

```hcl
variable "gcp_credentials" {
  type      = string
  sensitive = true
}

provider "google" {
  project = "round-plating-365219"
  region = "us-west1"
  credentials = var.gcp_credentials
}
```

The weird thing is that just after I create the service account, everything works fine for a couple of runs of terraform. Then eventually it breaks. Re-creating the service account or re-creating the access key fixes the issue for a few runs and then it breaks again. Same code and configuration, nothing changes, just eventually when I re-run the Github Action it starts throwing the 403.

**Comment by c-w** [comment] 2023-02-13 22:56
I just made a minimal example for my terraform setup:

```hcl
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.52.0"
    }
  }
}

locals {
  gcp_region  = "us-west1"
  gcp_project = "round-plating-365219"
}

variable "name" {
  type = string
}

variable "gcp_credentials" {
  type      = string
  sensitive = true
}

provider "google" {
  project     = local.gcp_project
  region      = local.gcp_region
  credentials = var.gcp_credentials
}

resource "google_bigquery_dataset" "datalake" {
  dataset_id                 = var.name
  location                   = local.gcp_region
  delete_contents_on_destroy = true
  max_time_travel_hours      = 48
}

resource "google_bigquery_table" "telemetry" {
  dataset_id          = google_bigquery_dataset.datalake.dataset_id
  table_id            = "telemetry"
  deletion_protection = false

  schema = jsonencode([
    {
      name : "foo",
      type : "STRING",
      mode : "REQUIRED",
    },
    {
      name : "bar",
      type : "INTEGER",
      mode : "REQUIRED",
    },
    {
      name : "baz",
      type : "TIMESTAMP",
      mode : "REQUIRED",
    },
    {
      name : "more",
      type : "JSON",
      mode : "NULLABLE",
    },
  ])
}

resource "google_service_account" "telemetry" {
  account_id = var.name
}

resource "google_service_account_key" "telemetry" {
  service_account_id = google_service_account.telemetry.name
}

resource "google_bigquery_dataset_access" "telemetry_writer" {
  dataset_id    = google_bigquery_dataset.datalake.dataset_id
  user_by_email = google_service_account.telemetry.email
  role          = "WRITER"
}

output "BIGQUERY_CREDENTIALS_BASE64" {
  value     = google_service_account_key.telemetry.private_key
  sensitive = true
}
```

With service account and default credentials I wasn't able to get this to fail so far. Which brings me to dig deeper: besides "a bunch of other resources being provisioned into other clouds", the only difference between this minimal example and what I'm doing for real is that I have a switch that changes around the permissions:

```hcl
locals {
  is_prod = var.name === "myProductionEnvironmentName"
}

resource "google_project_iam_custom_role" "telemetry_writer" {
  role_id = "${var.name}.telemetry.writer"
  title   = "${var.name} telemetry writer"
  permissions = [
    "bigquery.datasets.get",
    "bigquery.tables.get",
    "bigquery.tables.updateData",
  ]
  count = local.is_prod ? 1 : 0
}

resource "google_bigquery_dataset_access" "telemetry_writer" {
  dataset_id    = google_bigquery_dataset.datalake.dataset_id
  user_by_email = google_service_account.telemetry.email

  // NOTE(clemens): custom iam roles are soft-deleted so they don't interact
  //  nicely with non-prod buddy builds as the soft deletion lock leads to
  //  errors when spinning down the environments which is why for the non-prod
  //  environments we use a basic role despite it having excessive permissions
  role = local.is_prod ? google_project_iam_custom_role.telemetry_writer[0].id : "WRITER"
}
```

Could this be causing the issue?

**Comment by c-w** [comment] 2023-02-14 00:49
This is strange, I tried to set up a full reproduction environment and couldn’t get it to fail. The only difference: hosted vs self-hosted GitHub Actions runners. So I upgraded my GHA machines and so far it seems stable so perhaps this was an issue in Actions? I’ll watch this a bit more and report back.

**Comment by c-w** [comment] 2023-02-14 08:48
@edwardmedia PTAL the investigations above :arrow_up: Any ideas how I could further investigate what's going on here?

**Comment by edwardmedia** [comment] 2023-02-14 14:45
@c-w it is possible the issue is related to your Github Actions environment while you can't repro it with local setting. Are there any policies in place that could contribute to this? 

```
Your client does not have permission to get URL <code>/v1/projects/round-plating-365219/serviceAccounts/REDACTEDpr436@round-plating-365219.iam.gserviceaccount.com</code> from this server.  
```

**Comment by c-w** [comment] 2023-02-14 19:33
The GHA environment is a standard VM on Hetzner. The GHA runner runs natively on the VM and the Terraform script runs inside of docker-compose with the terraform scripts folder in a volume mount. There's no outbound firewall rules that would restrict traffic. Occassionally the calls do succeed which is what's throwing me off.

**Comment by edwardmedia** [comment] 2023-02-15 14:29
@c-w sorry I don't know much about GHA environment. Do you want to file a support ticket to GHA? By this moment, I don't think it is caused by the provider. Closing this accordingly. Feel free to reopen if you need more help for the provider

**Closed by edwardmedia** 2023-02-15 14:29 UTC
Labels: bug
