### ISSUE TITLE
Terraform Cloud Function Gen2 not supporting custom runtime service account

### ISSUE THREAD

**Issue by manvi-ma** [hashicorp/terraform-provider-google#11764] opened 2022-05-25 08:28 UTC
Tried using the custom service_account_email field in service_config block for cloud function gen2 as mentioned in the official doc page for terraform(https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions2_function), but it throws out an unsupported error for it.

Terraform Version used: Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.21.0
+ provider registry.terraform.io/hashicorp/google-beta v4.21.0

![Screenshot 2022-05-25 141215](https://user-images.githubusercontent.com/86039571/170221367-e7f0e9ab-4c49-4fe0-8194-c4b9b3d8856f.png)
Image 1: Code to use the following service account while running the cloud function.

![170216964-14ddbc85-3192-42f7-893b-891790f3d30a](https://user-images.githubusercontent.com/86039571/170221852-6fa8856a-aba2-4bfa-a9a3-a80f704c0016.png)
Image 2: Unsupported parameter issue being thrown while using terraform plan.

**Comment by drandell** [comment] 2022-05-30 13:18
Duplicate of : https://github.com/hashicorp/terraform-provider-google/issues/11388

**Closed** 2022-06-06 17:27 UTC
