### ISSUE TITLE
google_sql_database_instance doesn’t delete root@% if master_instance_name is set

### ISSUE THREAD

**Issue by yonran** [hashicorp/terraform-provider-google#13155] opened 2022-12-01 03:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.44.1

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
provider "google" {
  project = "terraform-provider-issue-13155"
}

resource "google_sql_source_representation_instance" "dummy" {
  name             = "dummy4"
  region           = "us-west1"
  database_version = "MYSQL_5_7"
  host             = "10.0.0.2"
  port             = 3306
}

resource "google_sql_database_instance" "instance" {
  name             = "mytest4"
  database_version = "MYSQL_5_7"
  region           = "us-west1"
  # we can always promote-replica to enable writing
  master_instance_name = google_sql_source_representation_instance.dummy.name

  settings {
    tier = "db-custom-1-3840"

    availability_type = "ZONAL"

    ip_configuration {
      # enable public IP; this is the default in the console.cloud.google.com wizard
      ipv4_enabled = true
      # disable ssl client certs; allow password auth
      require_ssl = false

      # allow connections from the Internet
      # Intent is to add users with secure passwords later
      authorized_networks {
        value = "0.0.0.0/0"
      }
    }

    # optional: enable general log
    # to watch hackers connect and make queries
    database_flags {
      name  = "general_log"
      value = "on"
    }

    # optional: enable MySQL Audit Plugin
    # to watch hackers make queries
    # (also requires enabling Data Access audit logs
    # and  CALL mysql.cloudsql_create_audit_rule(…))
    # https://cloud.google.com/sql/docs/mysql/use-db-audit
    database_flags {
      name  = "cloudsql_mysql_audit"
      value = "FORCE_PLUS_PERMANENT"
    }
  }
  deletion_protection = false
}

```

### Debug Output

https://gist.github.com/yonran/0b916a05fab43570c4204eb7d8ada09b

### Panic Output

None

### Expected Behavior

Per the NOTE in the [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance), “Second-generation instances include a default 'root'@'%' user with no password. **This user will be deleted by Terraform** on instance creation.”

So I expected there to be no users with an empty password. Or, if there must be a root user, then it should have a secure randomly generated password set, or it should be locked, or it should use [IAM database authentication](https://cloud.google.com/sql/docs/mysql/authentication).

Note that the console.cloud.google.com wizard does NOT create a root user with no password unless you explicitly check “No password”

<img width="524" alt="Screen Shot 2022-12-01 at 11 18 56 PM" src="https://user-images.githubusercontent.com/483060/205257622-b6a6b49f-6c21-4154-bf50-766a5a20b6c5.png">

### Actual Behavior

There is a root@% that is allowed to log in with an empty password! This can accidentally expose the database to easy attackers if you authorize any external networks (e.g. 0.0.0.0/0 above).

The database is in read-only mode as long as the master_instance_name is set, so an attacker can read your data but not write anything. But if you later promote-replica the instance, then an attacker will have read-write access to your database!

### Steps to Reproduce

1. `terraform apply`
2. `export MYSQL_HOST=…`
3. `mysql -u root --password=`

You are now connected to the database

**Comment by edwardmedia** [comment] 2022-12-01 16:22
@yonran can you share you debug log?

**Comment by yonran** [comment] 2022-12-02 09:30
> @yonran can you share you debug log?

Sure I have edited the description

**Comment by edwardmedia** [comment] 2022-12-03 21:30
@yonran Based below code, it appears this rule only applies on a primary instance

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_sql_database_instance.go#L1043

Can you verify this rule by commenting `master_instance_name` in your code?

```tf
resource "google_sql_database_instance" "instance" {
  name             = "mytest4"
  database_version = "MYSQL_5_7"
  region           = "us-west1"
  # we can always promote-replica to enable writing
  # master_instance_name = google_sql_source_representation_instance.dummy.name

  settings {
    tier = "db-custom-1-3840"

    availability_type = "ZONAL"

    ip_configuration {
      # enable public IP; this is the default in the console.cloud.google.com wizard
      ipv4_enabled = true
      # disable ssl client certs; allow password auth
      require_ssl = false

      # allow connections from the Internet
      # Intent is to add users with secure passwords later
      authorized_networks {
        value = "0.0.0.0/0"
      }
    }

    # optional: enable general log
    # to watch hackers connect and make queries
    database_flags {
      name  = "general_log"
      value = "on"
    }

    # optional: enable MySQL Audit Plugin
    # to watch hackers make queries
    # (also requires enabling Data Access audit logs
    # and  CALL mysql.cloudsql_create_audit_rule(…))
    # https://cloud.google.com/sql/docs/mysql/use-db-audit
    database_flags {
      name  = "cloudsql_mysql_audit"
      value = "FORCE_PLUS_PERMANENT"
    }
  }
  deletion_protection = false
}
```

**Comment by yonran** [comment] 2022-12-03 22:34
> @yonran Based below code, it appears this rule only applies on a primary instance

> https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_sql_database_instance.go#L1043

That comment says “Users in a replica instance are inherited from the master instance and should be left alone.” This is true if `master_instance_name` is a `google_sql_database_instance`. In that case, the replica starts out with a copy of the master’s disk and has all the same users, and the users are synced automatically. [About replication in Cloud SQL](https://cloud.google.com/sql/docs/mysql/replication)

However, if `master_instance_name` is a `google_sql_source_representation_instance`, then it starts out with an empty disk, and even when you start replication the users are **not** synced with the master  ([Configure Cloud SQL and the external server for replication: Add users to the Cloud SQL replica](https://cloud.google.com/sql/docs/mysql/replication/configure-replication-from-external#add-users)). Very confusing.

**Comment by edwardmedia** [comment] 2022-12-05 18:12
@yonran agreed the doc night not be super clear, but I think the implementation is by design. Closing it accordingly. Feel free to reopen if you disagree.

**Closed by edwardmedia** 2022-12-05 18:12 UTC
Labels: bug
