### ISSUE TITLE
Attribute enable_endpoint_independent_mapping for resource compute_router_nat is not disabled by default

### ISSUE THREAD

**Issue by stevenammon** [hashicorp/terraform-provider-google#11012] opened 2022-02-01 06:45 UTC
Hi all!

Unlike specified in [this])https://cloud.google.com/nat/docs/overview#specs-rfcs) document (endpoint independent mapping is disabled by default), the provider creates the resource with the mapping enabled by default:

https://github.com/hashicorp/terraform-provider-google/blob/8d3ecd26da8ca215cb4d777be2728fa89827aeff/google/resource_compute_router_nat.go#L184

Regards
Steven

### Affected Resource(s)

* google_compute_router_nat

b/300616679

**Comment by rileykarson** [comment] 2022-02-07 18:45
Note for onduty: If this is a default set in Terraform we want to preserve that, even if it mismatches the API.

**Comment by shijeesh-ns** [comment] 2023-09-15 23:30
This is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/10547

**Closed** 2023-09-16 00:24 UTC
Labels: bug, forward/linked, service/compute-nat
