### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by yash-nigam-db** [hashicorp/terraform-provider-google#12678] opened 2022-09-29 08:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.14.11
Provider version: 
 google = {
      source  = "hashicorp/google"
      version = "3.90.1"
    }

### Affected Resource(s)

google_project_iam_member.pubsub_sa_iam_member["roles/pubsub.publisher"],

### Terraform Configuration Files

```tf
The following TF code is what is referenced in the error

resource "google_project_iam_binding" "gke_opa_iam_binding" {
  for_each = toset(
    [
      "roles/pubsub.publisher"
    ]
  )
  project    = module.cluster_project.project_id
  role       = each.key
  members    = ["serviceAccount:${service_account.service_account_email}"]
  depends_on = [module.gke_opa_service_account]
}
```
### Debug Output

We do not have debug output
### Expected Behavior

Terraform Apply should successfully execute  

### Actual Behavior

Error: Provider produced inconsistent result after apply

When applying changes to
google_project_iam_member.pubsub_sa_iam_member["roles/pubsub.publisher"],
provider "registry.terraform.io/hashicorp/google" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by elsmorian** [comment] 2022-09-29 10:06
We are hitting a very similar bug,

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to google_project_iam_member.staging-owner, provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root
│ resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Versions:
```
# tf version
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.32.0
+ provider registry.terraform.io/hashicorp/google v4.38.0
+ provider registry.terraform.io/hashicorp/google-beta v4.38.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

**Comment by kpocius** [comment] 2022-10-07 08:18
@edwardmedia, we've got the same issue as @yash-nigam-db. Very similar code too:
```
resource "google_project_iam_member" "group_name" {
  for_each = toset([
    "roles/composer.user",
  ])
  project = data.google_project.current.project_id
  member  = "group:group_name@example.com"
  role    = each.key
}
```
It happens on the first apply. That is, it won't let us apply this code, even though the same file contains similar blocks of code that were applied before. So it seems the issue started fairly recently.

What debug info can I provide to make this easier to reproduce?

One thing to note, that at least in our case, the project uses workspaces.

**Comment by kpocius** [comment] 2022-10-07 08:34
Well, this is embarrassing. Turns out in my case group name had a typo 🤦🏻 

The error message could be more useful though.

**Comment by slevenick** [comment] 2022-10-07 17:55
@kpocius how was the group name incorrect, was it a casing issue or just an invalid group name? I ask because I would expect the API to fail with a different error message if the group didn't exist, not for TF to have an inconsistent result

**Comment by kpocius** [comment] 2022-10-07 17:58
The name was misspelled. So yeah, I thought it would say the group didn't exist (which it did in the debug logs), but the main error was "inconsistent results" one.

**Comment by elsmorian** [comment] 2022-10-09 19:39
@edwardmedia It did happen in the initial apply yes.

`google_project_iam_member` was the resource we were trying to use, we ending up using `google_project_iam_binding` to get around this instead

**Comment by edwardmedia** [comment] 2022-10-10 21:46
@yash-nigam-db @elsmorian @kpocius could you share the full debug log for this issue? The log from [here](https://github.com/hashicorp/terraform-provider-google/issues/12678#issuecomment-1262060490) isn't long enough. I need full API requests and responses so I can take a closer look.

**Comment by kpocius** [comment] 2022-10-10 21:55
I think my case is slightly different from what was originally reported. Just tried to replicate using a fake group and got entirely different error, leading me to dig into the "misspelled" group  and the issue there was that I used group alias to refer to a group rather than primary email. So the error message could still be a bit more helpful, but this is such an edge case that I'm not sure it warrants digging into any further.

**Comment by AndreaGiardini** [comment] 2022-10-18 07:27
I can confirm what @kpocius said.

I got the same error on the `google_project_iam_member` resource. I found out that the user I was trying to assign was a domain alias rather than the real domain (we have an alias for xyz.com and xpz.ai). I fixed the problem by using the main account rather than the alias.

**Comment by edwardmedia** [comment] 2022-10-19 23:14
@yash-nigam-db @elsmorian Is this still an issue? Do the answers from other users are helpful?

**Comment by edwardmedia** [comment] 2022-10-23 22:19
@yash-nigam-db @elsmorian closing this assuming this is no longer an issue. Feel free to reopen if you see it differently

**Closed by edwardmedia** 2022-10-23 22:19 UTC
Labels: bug, waiting-response
