### ISSUE TITLE
Unable to update database flags on postgresql

### ISSUE THREAD

**Issue by g-awmalik** [hashicorp/terraform-provider-google#12324] opened 2022-08-17 00:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.32.0
+ provider registry.terraform.io/hashicorp/google-beta v4.32.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

```tf
##### First time apply config
locals {
  read_replica_ip_configuration = {
    ipv4_enabled       = true
    require_ssl        = false
    private_network    = null
    allocated_ip_range = null
    authorized_networks = [
      {
        name  = "${var.project_id}-cidr"
        value = var.pg_ha_external_ip_range
      },
    ]
  }
}

module "pg" {
  source               = "../../modules/postgresql" # using https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/postgresql
  name                 = var.pg_ha_name
  random_instance_name = true
  project_id           = var.project_id
  database_version     = "POSTGRES_13"
  region               = "us-central1"

  // Master configurations
  tier                            = "db-custom-1-3840"
  zone                            = "us-central1-c"
  availability_type               = "REGIONAL"
  maintenance_window_day          = 7
  maintenance_window_hour         = 12
  maintenance_window_update_track = "stable"

  deletion_protection = false

  database_flags = [
    {
      name  = "log_error_verbosity"
      value = "default"
    },
    {
      name  = "log_min_messages"
      value = "warning"
    }
  ]

  user_labels = {
    foo = "bar"
  }

  ip_configuration = {
    ipv4_enabled       = true
    require_ssl        = true
    private_network    = null
    allocated_ip_range = null
    authorized_networks = [
      {
        name  = "${var.project_id}-cidr"
        value = var.pg_ha_external_ip_range
      },
    ]
  }

  backup_configuration = {
    enabled                        = true
    start_time                     = "20:55"
    location                       = null
    point_in_time_recovery_enabled = false
    transaction_log_retention_days = null
    retained_backups               = 365
    retention_unit                 = "COUNT"
  }

  // Read replica configurations
  read_replica_name_suffix = "-test"
  read_replicas = [
    {
      name                  = "0"
      zone                  = "us-central1-a"
      availability_type     = "REGIONAL"
      tier                  = "db-custom-1-3840"
      ip_configuration      = local.read_replica_ip_configuration
      database_flags        = [
        {
          name  = "log_error_verbosity"
          value = "default"
        },
        {
          name  = "log_min_messages"
          value = "warning"
        }
      ]
      disk_autoresize       = null
      disk_autoresize_limit = null
      disk_size             = null
      disk_type             = "PD_HDD"
      user_labels           = { bar = "baz" }
      encryption_key_name   = null
    },
  ]

  db_name      = var.pg_ha_name
  db_charset   = "UTF8"
  db_collation = "en_US.UTF8"

  additional_databases = [
    {
      name      = "${var.pg_ha_name}-additional"
      charset   = "UTF8"
      collation = "en_US.UTF8"
    },
  ]

  user_name     = "tftest"
  user_password = "foobar"

  additional_users = [
    {
      name     = "tftest2"
      password = "abcdefg"
      host     = "localhost"
    },
    {
      name     = "tftest3"
      password = "abcdefg"
      host     = "localhost"
    },
  ]
}
```

```tf
##### Second time apply config
##### the only diff is an added database flag on both master and the replica
locals {
  read_replica_ip_configuration = {
    ipv4_enabled       = true
    require_ssl        = false
    private_network    = null
    allocated_ip_range = null
    authorized_networks = [
      {
        name  = "${var.project_id}-cidr"
        value = var.pg_ha_external_ip_range
      },
    ]
  }
}

module "pg" {
  source               = "../../modules/postgresql" # using https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/postgresql
  name                 = var.pg_ha_name
  random_instance_name = true
  project_id           = var.project_id
  database_version     = "POSTGRES_13"
  region               = "us-central1"

  // Master configurations
  tier                            = "db-custom-1-3840"
  zone                            = "us-central1-c"
  availability_type               = "REGIONAL"
  maintenance_window_day          = 7
  maintenance_window_hour         = 12
  maintenance_window_update_track = "stable"

  deletion_protection = false

  database_flags = [
    {
      name  = "log_error_verbosity"
      value = "default"
    },
    {
      name  = "log_min_messages"
      value = "warning"
    },
    {
      name  = "max_connections"
      value = "2000"
    },
  ]

  user_labels = {
    foo = "bar"
  }

  ip_configuration = {
    ipv4_enabled       = true
    require_ssl        = true
    private_network    = null
    allocated_ip_range = null
    authorized_networks = [
      {
        name  = "${var.project_id}-cidr"
        value = var.pg_ha_external_ip_range
      },
    ]
  }

  backup_configuration = {
    enabled                        = true
    start_time                     = "20:55"
    location                       = null
    point_in_time_recovery_enabled = false
    transaction_log_retention_days = null
    retained_backups               = 365
    retention_unit                 = "COUNT"
  }

  // Read replica configurations
  read_replica_name_suffix = "-test"
  read_replicas = [
    {
      name                  = "0"
      zone                  = "us-central1-a"
      availability_type     = "REGIONAL"
      tier                  = "db-custom-1-3840"
      ip_configuration      = local.read_replica_ip_configuration
      database_flags        = [
        {
          name  = "log_error_verbosity"
          value = "default"
        },
        {
          name  = "log_min_messages"
          value = "warning"
        },
        {
          name  = "max_connections"
          value = "2000"
        },
      ]
      disk_autoresize       = null
      disk_autoresize_limit = null
      disk_size             = null
      disk_type             = "PD_HDD"
      user_labels           = { bar = "baz" }
      encryption_key_name   = null
    },
  ]

  db_name      = var.pg_ha_name
  db_charset   = "UTF8"
  db_collation = "en_US.UTF8"

  additional_databases = [
    {
      name      = "${var.pg_ha_name}-additional"
      charset   = "UTF8"
      collation = "en_US.UTF8"
    },
  ]

  user_name     = "tftest"
  user_password = "foobar"

  additional_users = [
    {
      name     = "tftest2"
      password = "abcdefg"
      host     = "localhost"
    },
    {
      name     = "tftest3"
      password = "abcdefg"
      host     = "localhost"
    },
  ]
}
```

### Debug Output

This is the output of `terraform apply` when applying the second-time-config
https://gist.github.com/g-awmalik/1676dbf71c5f43cc26b049a65550838e

### Expected Behavior

The new database flag i.e. `max_connections` should have been applied to both the master and the replica without errors.

### Actual Behavior

Although the UI shows the database flag has been applied, `terraform apply` crashes when applying the flag on the replica produce a "STALE_DATA" error as shown in the output above.

### Steps to Reproduce

1. `terraform apply` - the first config
2. `terraform apply` - the second config 

### References

This seems somewhat similar: https://github.com/hashicorp/terraform-provider-google/issues/7200 but suggests that we add an `ignore_changes` block which is not feasible.

* #0000

**Comment by g-awmalik** [comment] 2022-08-17 01:03
Just one additional piece of information. If you re-apply the second config after failure it going through just fine. Here's the [gist](https://gist.github.com/g-awmalik/9d57d174ea99e952844b84e851a61d38) for that.

**Comment by jesse-l** [comment] 2022-08-17 03:16
Actually for us it was giving this error, "Error 412: Condition does not match., staleData", for the update after the main and replica nodes had been created.  They did try to run a deploy after getting the 412 error and then they got a different error message, Error 400: This operation is not valid for this instance., invalidOperation.

**Comment by edwardmedia** [comment] 2022-08-17 19:03
@g-awmalik it works fine with me to update the instance by adding `max_connections` block. Looked at the log you shared, I don't understand what caused below change `5 -> 7` and `old: 5, new: 4`. Can you enable TF_LOG=DEBUG and share your debug log?


```tf
      ~ settings {
          ~ version               = 5 -> 7
            # (9 unchanged attributes hidden)

            # (6 unchanged blocks hidden)
        }
```

```
[ORIGINAL ERROR] boss::5: Unable to update metadata, version mismatch (old: 5, new: 4)
```

**Comment by g-awmalik** [comment] 2022-08-17 19:28
I'll try to get you those logs but can you share what version of TF and google provider you're using?

**Comment by edwardmedia** [comment] 2022-08-17 20:00
@g-awmalik Terraform version: 1.2.3. Local build provider should be the latest from github

**Comment by g-awmalik** [comment] 2022-08-17 20:58
OK FWIW i'm on TF v1.2.7 and latest provider version. [Here](https://gist.github.com/g-awmalik/f4499d940eafe98dc5ab9211365011e3) are the debug logs.

Just to confirm, you are reproducing this with the same configs I shared, right?

**Comment by edwardmedia** [comment] 2022-08-17 21:35
@g-awmalik no I am on the resource level. It behaves normal. I have seen anything wrong. 

You are on the module. Can you try by removing the replicate to see if the problem remain?

```
 "error": {
    "code": 412,
    "message": "Condition does not match.",
    "errors": [
      {
        "message": "Condition does not match.",
        "domain": "global",
        "reason": "staleData",
        "location": "If-Match",
        "debugInfo": "BossException (STALE_DATA): Unable to update metadata, version mismatch (old: 5, new: 4). {domain: cloud.sql.BossError, code: STALE_DATA, arguments, []}\n\tat com.google.storage.speckle.boss.util.exception.BossException.staleData(BossException.java:583)\n\tat com.google.storage.speckle.boss.util.exception.BossException.staleData(BossException
```

**Comment by g-awmalik** [comment] 2022-08-17 22:07
At just the resource `google_sql_database_instance` level, you won't see it. The problem occurs when you have replicas and you create multiple `google_sql_database_instance` resources and set them as replicas on the master using the [`master_instance_name`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#master_instance_name) argument. That is what the [module](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/postgresql/main.tf) does and [this](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/postgresql/read_replica.tf) is where it creates and sets the replicas on the master.

I *think* that's where the provider internally updates the `version` on the `settings` attribute which goes out of sync with the config and the next time you apply an update it complains that there are changes made outside of TF.

**Comment by edwardmedia** [comment] 2022-08-22 22:22
@jesse-l I see the same error with your code. But the request sent from the provider is Okay. My 2nd apply is successful. No issue on a single resource, as you discovered below. I think the issue is at the API. You may file an issue against SQL API for an explanation?

```
At just the resource google_sql_database_instance level, you won't see it
```

**Comment by edwardmedia** [comment] 2022-08-25 16:20
@jesse-l does this make sense? Sorry for the inconvenience but I am afraid there is little we can help at the provider level

**Comment by edwardmedia** [comment] 2022-08-30 13:46
@jesse-l closing this now as there is little we can do for this. Feel free to reopen if you want to continue the conversation

**Closed by edwardmedia** 2022-08-30 13:46 UTC
Labels: bug, waiting-response
