### ISSUE TITLE
Memcached 1.6 not supported in Terraform

### ISSUE THREAD

**Issue by Sourc** [hashicorp/terraform-provider-google#16191] opened 2023-10-10 12:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

All, tested with 5.1.0.

### Affected Resource(s)

`google_memcache_instance`

### Expected Behavior

Specifying the property `memcache_version = "MEMCACHE_1_6"` should work since [it's possible to upgrade instances from 1.5 to 1.6](https://cloud.google.com/memorystore/docs/memcached/upgrade-memcached-version) (even though the GUI does not yet support creating instances with version 1.6, at the time of writing).

### Actual Behavior

Terraform fails to plan, `expected memcache_version to be one of [MEMCACHE_1_5 ], got MEMCACHE_1_6`

b/305197643

**Comment by edwardmedia** [comment] 2023-10-10 13:04
@Sourc Trying to understand if this issue is at the provider level or the API. Can you share the config and debug log?

**Comment by Sourc** [comment] 2023-10-10 13:07
I don't know if the APIs have been updated behind the scenes to fully support version 1.6 yet, but right now we're not getting past the validation here https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/memcache/resource_memcache_instance.go#L240

**Comment by gaurav172** [comment] 2023-10-15 09:30
The issue is at provider level. APIs have been updated to support 1.6.15 in create instance as well as upgrade instance call https://cloud.google.com/memorystore/docs/memcached/create-instance-gcloud#creating_a_memcached_instance

**Comment by gaurav172** [comment] 2023-11-15 05:37
@trodge can this issue be closed now that the PR is merged ?

**Closed** 2023-12-13 18:18 UTC
Labels: bug, forward/linked, service/memcache
