### ISSUE TITLE
google_cloudbuild_worker_pool resource uses the old private API (according to GCP support)

### ISSUE THREAD

**Issue by parabolic** [hashicorp/terraform-provider-google#10632] opened 2021-11-24 10:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.1.0
+ provider registry.terraform.io/hashicorp/google-beta v4.1.0
```

### Affected Resource(s)

* google_cloudbuild_worker_pool

### Terraform Configuration Files

```tf
resource "google_cloudbuild_worker_pool" "public_ip" {
  provider = google-beta

  name     = "public-ip"
  location = local.region
  worker_config {
    no_external_ip = false
  }
  network_config {
    peered_network = google_compute_network.vpc_network.id
  }
  depends_on = [google_service_networking_connection.cloudbuild]
}

```

### Debug Output
```
google_cloudbuild_worker_pool.public_ip: Creating...
╷
│ Error: Error creating WorkerPool: googleapi: Error 403: project is not allowlisted for this feature, please contact Google Cloud Support at https://cloud.google.com/support-hub
│
```

### Panic Output

None

### Expected Behavior

The google_cloudbuild_worker_pool should have been created.

### Actual Behavior

Terraform errored out.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
I reached out to GCP support and they said that the worker_pool resource is GA and that terraform uses the old private API:
>The private pools feature has reached General Availability (GA) and no longer requires allowlisting; you can access it without restrictions by using the Cloud Console or the Cloud SDK [1]. The Terraform provider, however, is still making use of the old private API, and therefore projects need to be allowlisted to be able to use it.

### References

* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_worker_pool

**Comment by goagrawal** [comment] 2021-11-30 13:08
Seems related to : https://github.com/hashicorp/terraform-provider-google/issues/9684

**Comment by c2thorn** [comment] 2021-12-01 18:21
Yes I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9684

**Closed by c2thorn** 2021-12-01 18:21 UTC
Labels: bug

**Comment by parabolic** [comment] 2021-12-01 18:30
Sorry about that I did a search but I somehow did not find the already open issue.
