### ISSUE TITLE
google_project data source with depends_on is quirky

### ISSUE THREAD

**Issue by Unichron** [hashicorp/terraform-provider-google#9285] opened 2021-06-02 19:13 UTC
### Terraform Version

0.15.4

### Terraform Configuration Files

```tf
resource "random_id" "foo" {
  byte_length = 1
}

data "google_project" "this" {
  depends_on = [random_id.foo]
  //  project_id = ""
}

resource "local_file" "foo" {
  filename = data.google_project.this.project_id
}
```

### Expected Behavior

Running `terraform apply` should work.

### Actual Behavior

```
│ Error: Missing required argument
│ 
│   with local_file.foo,
│   on main.tf line 15, in resource "local_file" "foo":
│   15:   filename = data.google_project.this.project_id
│ 
│ The argument "filename" is required, but no definition was found.
```

### Important Factoids
If I remove `depends_on = [random_id.foo]` the apply runs nicely. If I uncomment `project_id=""` I get an inconsistent final plan error:

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for local_file.foo to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/local" produced an invalid new value for .filename: was cty.StringVal(""), but now
│ cty.StringVal("redacted").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

I don't actually need the depends_on on the data source, but this code is inside a module and the whole module has a depends_on, I tried to reduce the complexity thus I represented the issue like above.

I'm not sure this is an error with the provider or terraform itself, but I couldn't reproduce it with other data sources.

**Comment by edwardmedia** [comment] 2021-06-03 20:49
@Unichron I think this behavior is caused by the limitations from the combination of the Terraform core and the provider. 

First, Setting the `depends_on` meta-argument within data blocks defers reading of the data source until after all changes to the dependencies have been applied. 

Secondly `project_id` is defined as an optional field for the data source (it is required for the resource fyi). If you don't provide data to `project_id`, the plan will ignore it. If you provide the data for it, it should be fine. By saying that, this behavior only happens when you provide the `depend_on` but no `project_id`.  Any other combinations should be fine. Due to other more common use cases, I guess we can not set the `project_id` to be required for the data source.

Does this make sense to you?

**Comment by Unichron** [comment] 2021-06-04 11:00
@edwardmedia 

> If you don't provide data to project_id, the plan will ignore it.
Is that because of the core and you cannot influence it? If so I guess a solution would be to introduce an optional `current` boolean flag to be able to explicitly request the current project. 

Having said that, in the meantime I realized that even if this bug/limitation is fixed I'm still stuck with the fact that the depends_on on the data source makes subsequent terraform apply wreak havoc because of the deferred reading (dependent resources wanting to be recreated because required fields go from xxx to 'known after apply').

**Comment by edwardmedia** [comment] 2021-06-04 15:33
@Unichron Technically, `project_id` is always required to make an api call. Giving it optional enables users to choose the default project, `GOOGLE_PROJECT`, which is the majority of use cases. The boolean flag seems already being answered by whether you provide the `project_id` or not. The module you use should be able to properly handle this based on the behaviors discovered. 

I don't think the provider can do much with this issue. Closing this issue now. Feel free to reopen if you need further discussion.

**Closed by edwardmedia** 2021-06-04 15:33 UTC
Labels: bug, waiting-response
