### ISSUE TITLE
Failing test(s): TestAccTPUNode_tpuNodeBasicExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12523] opened 2022-09-09 21:47 UTC
### Affected Resource(s)
* google_tpu_node

Failure rate: 100%

Impacted tests:
- TestAccTPUNode_tpuNodeBasicExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/335482?buildTab=tests&expandedTest=-6496095039754300046

Message:

```
Error: Error waiting to create Node: Error waiting for Creating Node: Error code 3, message: Cloud TPU received an invalid argument. The 'CIDR Range' value "10.2.0.0/29" on network "tp-networkdefault4153782072545391213" conflicts with another subnet or object in the (peered) customer network.
```

Related: https://github.com/hashicorp/terraform-provider-google/issues/10223

Separate from https://github.com/hashicorp/terraform-provider-google/issues/10222

**Comment by AarshDhokai** [comment] 2022-12-02 12:46
- TestAccTPUNode_tpuNodeBasicExample
[Google Cloud](https://ci-oss.hashicorp.engineering/project.html?testNameId=-6496095039754300046&projectId=GoogleCloud&tab=testDetails&branch_GoogleCloud=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) - 89% failure
[Google Cloud Beta](https://ci-oss.hashicorp.engineering/project.html?testNameId=-6496095039754300046&projectId=GoogleCloudBeta&tab=testDetails&branch_GoogleCloudBeta=%3Cdefault%3E&fromExperimentalUI=true&showExperimentalUIOptout=true) - 72% failure

**Comment by AarshDhokai** [comment] 2022-12-08 05:29
b/261800055

**Comment by roaks3** [comment] 2023-04-13 18:11
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11895

**Closed by roaks3** 2023-04-13 18:11 UTC
Labels: size/xs, priority/2, test failure, crosslinked
