### ISSUE TITLE
Apigee environment to support Forward Proxy configuration

### ISSUE THREAD

**Issue by carlosmscabral** [hashicorp/terraform-provider-google#17855] opened 2024-04-15 19:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Apigee now supports Forward Proxying for the environment. 

### New or Affected Resource(s)

* google_apigee_environment

### Potential Terraform Configuration

```tf 
```

### References

https://cloud.google.com/apigee/docs/api-platform/fundamentals/environments-working-with#configure-forward-proxying
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments

**Comment by xuchenma** [comment] 2024-04-15 23:26
This seems like a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/17832

**Comment by melinath** [comment] 2024-04-22 17:19
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/17832

**Closed by melinath** 2024-04-22 17:19 UTC
Labels: enhancement, service/apigee, forward/review
