### ISSUE TITLE
google_kms_key_ring uses remote state project

### ISSUE THREAD

**Issue by bbr32** [hashicorp/terraform-provider-google#10601] opened 2021-11-19 18:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```sh
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.1.0
```

### Affected Resource(s)

* google_kms_key_ring
* google_kms_crypto_key
* google_kms_key_ring_iam_binding

### Terraform Configuration Files

```tf
terraform {
  backend "gcs" {
    bucket        = "bucket_in_project_1"
    prefix          = "terraform/state"
    credentials = "/path/to/key.json"
  }
}

provider "google" {
  region         = "europe-west3"
  project        = "project_2"
  credentials = "/path/to/key.json"
}

resource "google_kms_key_ring" "key_ring" {
  project  = "project_2"
  name     = "key-name"
  location = "europe-west3"
}

```

### Debug Output

N/A

### Panic Output

```sh
Error: Error when reading or editing KMSKeyRing "projects/project_2/locations/europe-west3/keyRings/key-name": googleapi: Error 403: Cloud Key Management Service (KMS) API has not been used in project PROJECT_1_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=PROJECT_1_ID then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

### Expected Behavior

State is stored in a gcs bucket in `project_1` and the resource must be created in `project_2`.
Terraform should create google_kms_key_ring in project_2.

### Actual Behavior

Terraform tries to create the google_kms_key_ring resource in `project_1`. We get a 403 error because KMS API is not enabled in project_1

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I get the same behaviour with `google_kms_crypto_key` and `google_kms_key_ring_iam_binding`, I haven't tried with every kms resources.

### References

* #0000

**Comment by ndmckinley** [comment] 2021-11-22 19:23
Hi there - sorry, but I suspect you will need to enable the KMS API in project 1 here.  I bet your credentials are for a service account in project 1.  This matters because the relevant service needs to be enabled in both the project where the service will be used, and the project where your credentials are from.

We don't consider this a bug - it's the expected behavior of the GCP API - so I'm closing this issue.  Please me know if I'm wrong about your service account - if there's a different issue we can work to debug it.

**Closed by ndmckinley** 2021-11-22 19:23 UTC
Labels: bug
