### ISSUE TITLE
google_tags_tag_key error when deleted outside of terraform

### ISSUE THREAD

**Issue by natedogith1** [hashicorp/terraform-provider-google#18329] opened 2024-06-05 15:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v4.84.0

### Affected Resource(s)

google_tags_tag_key
google_tags_tag_value

### Terraform Configuration

```tf
resource "google_tags_tag_key" "AppSupportEmail" {
    parent      = "projects/${google_project.project.project_id}"
    short_name  = "ApplicationSupportEmail"
    description = "ApplicationSupportEmail, project owner."
}

resource "google_tags_tag_value" "AppSupportEmail_value" {
    parent      = "tagKeys/${google_tags_tag_key.AppSupportEmail.name}"
    short_name  = local.required_tags.t_owner
    description = "ApplicationSupportEmail, project owner."
}

resource "google_tags_tag_binding" "AppSupportEmail_binding" {
    parent      = "//cloudresourcemanager.googleapis.com/projects/${google_project.project.number}"
    tag_value   = "tagValues/${google_tags_tag_value.AppSupportEmail_value.name}"
}
```

### Debug Output

```
╷
│ Error: Error when reading or editing TagsTagKey "tagKeys/281480053217266": googleapi: Error 403: Permission denied on resource 'tagKeys/281480053217266' (or it may not exist).
│ com.google.apps.framework.request.StatusException: <eye3 title='PERMISSION_DENIED'/> generic::PERMISSION_DENIED: Permission denied on resource 'tagKeys/281480053217266' (or it may not exist).
│ 
│   with google_tags_tag_key.AppSupportEmail,
│   on main.tf line 605, in resource "google_tags_tag_key" "AppSupportEmail":
│  605: resource "google_tags_tag_key" "AppSupportEmail" {
│ 
╵
╷
│ Error: Error when reading or editing TagsTagValue "tagValues/281479541854131": googleapi: Error 403: Permission denied on resource 'tagValues/281479541854131' (or it may not exist).
│ com.google.apps.framework.request.StatusException: <eye3 title='PERMISSION_DENIED'/> generic::PERMISSION_DENIED: Permission denied on resource 'tagValues/281479541854131' (or it may not exist).
│ 
│   with google_tags_tag_value.AppSupportEmail_value,
│   on main.tf line 611, in resource "google_tags_tag_value" "AppSupportEmail_value":
│  611: resource "google_tags_tag_value" "AppSupportEmail_value" {
│ 
╵
```

### Expected Behavior

The plan should have shown the key being created

### Actual Behavior

The plan errored with the message "Error 403: Permission denied on resource 'tagKeys/281480053217266' (or it may not exist)."

### Steps to reproduce

1. `terraform apply`
2. Manually delete tag key in GCP console
3. `terraform plan`

**Comment by ggtisc** [comment] 2024-06-06 18:25
This looks like a duplicate of this other [issue](https://github.com/hashicorp/terraform-provider-google/issues/15928) presenting a 403 instead a 404.

**Closed by ggtisc** 2024-06-06 18:25 UTC
Labels: bug, forward/review, service/cloudresourcemanager-tags
