### ISSUE TITLE
Support the new `evaluationMissingData` field in `google_monitoring_alert_policy`

### ISSUE THREAD

**Issue by ronisec** [hashicorp/terraform-provider-google#11227] opened 2022-03-07 14:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Stackdriver recently added support for a new alert configuration. That configuration is called `evaluationMissingData`. See more details at https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#EvaluationMissingData. It is used in the following API Request resources:
1. https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#metricthreshold
2. https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#monitoringquerylanguagecondition

Please add support through Terraform.

### New or Affected Resource(s)

* google_monitoring_alert_policy

### Potential Terraform Configuration

```tf
resource "google_monitoring_alert_policy" "my_latency" {
  notification_channels = [google_monitoring_notification_channel.slack_alerts.id]
  display_name          = "My Alert Name"
  documentation {
    content = "My documentation"
  }
  combiner = "OR"
  conditions {
    display_name = "Latency Above 3.5 hours"
    condition_monitoring_query_language {
      query    = <<EOT
      fetch k8s_pod::custom.googleapis.com/my_latency_metric_ms
      | align next_older(1m)
      | filter (resource.namespace_name = 'default')
      | condition gt(val(), 1000 * 60 * 60 * 3.5)
      EOT
      duration = "600s"
      trigger {
        count = 1
      }
      evaluationMissingData = "EVALUATION_MISSING_DATA_INACTIVE"
    }
  }
```

### References

* https://issuetracker.google.com/issues/208369628

**Comment by ggerritsen** [comment] 2022-06-22 15:12
This issue looks like a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11161, or am I looking wrong?

**Closed** 2022-07-19 18:06 UTC
Labels: enhancement, size/s
