### ISSUE TITLE
Support creation of BigQuery Connections (Biglake and Remote Functions)

### ISSUE THREAD

**Issue by nickrosener** [hashicorp/terraform-provider-google#16046] opened 2023-09-28 21:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The [google_bigquery_connection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection) resource doesn't yet support Big Lake and Remote Functions connections. Supporting this would help simplify my Serverless data workflows and managing connections across environments.

### New or Affected Resource(s)

* google_bigquery_connection

**Comment by roaks3** [comment] 2023-09-29 17:21
This looks like it might be a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11730, and a `cloud_resource` might solve the problem.

**Comment by nickrosener** [comment] 2023-09-30 05:50
@roaks3 you're 100% right, thank you. Closing now 👍

**Closed** 2023-09-30 05:50 UTC
Labels: enhancement, service/bigquery, forward/review
