### ISSUE TITLE
google_vpc_access_connector always gets recreated if network is not defined

### ISSUE THREAD

**Issue by rlaakkol** [hashicorp/terraform-provider-google#11304] opened 2022-03-18 13:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

1.0.0

### Affected Resource(s)

* google_vpc_access_connector

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
resource "google_vpc_access_connector" "serverless_vpc_connector" {
  provider = google-beta
  project  = var.project
  name     = "serverless-vpc-con"
  subnet {
    name = google_compute_subnetwork.serverless_subnet.name
  }
  machine_type  = var.serverless_vpc_connector_machine_type
}
```

### Expected Behavior

The resource should not be recreated when there are no changes.

### Actual Behavior

The resource gets recreated on every apply:
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.network.google_vpc_access_connector.serverless_vpc_connector has been changed
  ~ resource "google_vpc_access_connector" "serverless_vpc_connector" {
        id             = "[redacted]"
        name           = "serverless-vpc-con"
      + network        = "primary-network"
        # (8 unchanged attributes hidden)
.
.
.
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.network.google_vpc_access_connector.serverless_vpc_connector must be replaced
-/+ resource "google_vpc_access_connector" "serverless_vpc_connector" {
      ~ id             = "[redacted]" -> (known after apply)
      ~ max_instances  = 3 -> (known after apply)
      ~ min_instances  = 2 -> (known after apply)
        name           = "serverless-vpc-con"
      - network        = "primary-network" -> null # forces replacement
      + region         = (known after apply)
```

I tried explicitly setting the `network` argument to `primary-network` which it in reality is, but specifying both a network and a subnet is forbidden in the resource schema: https://github.com/hashicorp/terraform-provider-google-beta/blob/v4.14.0/google-beta/resource_vpc_access_connector.go#L122

A workaround that seems to do the trick is to add the `network` attribute to the `ignore_changes` list for this resource.

### Steps to Reproduce

1. `terraform apply`

**Comment by brettcurtis** [comment] 2022-03-22 14:28
Any W/A ? I opened a ticket with Google in case it is an API issue as @flovouin mentioned.

**Comment by slevenick** [comment] 2022-03-23 18:18
Did this work previously? I'm guessing the API changed in some way, or else we would have noticed this problem a long time ago.

**Comment by brettcurtis** [comment] 2022-03-23 18:24
The last workflow I had run successfully was 20 days ago. FWIW, that was a different provider version as well, I can dig in if that's useful. But yes, it use to work.

**Comment by slevenick** [comment] 2022-03-23 18:26
Thanks for looking! It looks like we have a test that started failing that corresponds to this, so it was an API change that caused this. I'll get in contact with the API team and see what the fix should be.

**Comment by brettcurtis** [comment] 2022-03-23 18:28
old version: Installed hashicorp/google-beta v4.12.0 

vs. new: Installed hashicorp/google-beta v4.15.0

just in case that's helpful too..

**Comment by slevenick** [comment] 2022-03-23 21:05
Internal reference # 226408742 for tracking purposes

**Comment by Verhaeg** [comment] 2022-03-30 12:33
Testes with hashicorp/google-beta v4.15.0 still having the same issue
and it seems the issue is not public (https://issuetracker.google.com/issues/226408742)

But can confirm that adding the lifecycle ignore works for now and is a controlled state (since we are passing the subnet name) so it is possible to go with that for now ;)

**Comment by cbuschka** [comment] 2022-04-01 10:22
We are also experiencing this issue. Thanks for the lifecycle workaround. (https://github.com/hashicorp/terraform-provider-google/issues/11304#issuecomment-1075278027) Interestingly we can observe the flickering of the network field on the GCP web console too by repeatedly reloading the subnetworks view.

**Comment by brettcurtis** [comment] 2022-04-01 12:25
Info from internal support on 3/28: 

>I have excellent news for you, the Product Team commented that they will disable these changes in the new release. This release will be done by the end of this week. This gives us a chance to make a fix on the Terraform provider side and give you time to upgrade to a newer version ideally in the following month.

**Comment by slevenick** [comment] 2022-04-11 22:41
This *should* be fixed by the API team. My linked PR will fix this going forward for when the API introduces this change again

**Closed** 2022-04-11 22:41 UTC
Labels: bug
