### ISSUE TITLE
Kubernetes cluster destroyed and created each time

### ISSUE THREAD

**Issue by LukeMauldin** [hashicorp/terraform-provider-google#13367] opened 2022-12-30 19:47 UTC
### Terraform Version
1.3.6 for Linux

### Affected Resource(s)
provider: google
resource: google_container_cluster

### Terraform Configuration Files
```tf
## Create network and subnetworks
resource "google_compute_network" "main-cluster-network" {
  name                    = "main-cluster-network"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "main-cluster-subnetwork" {
  name          = "main-cluster-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = var.region
  network       = google_compute_network.main-cluster-network.id
  secondary_ip_range {
    range_name    = "services-range"
    ip_cidr_range = "192.168.1.0/24"
  }

  secondary_ip_range {
    range_name    = "pod-ranges"
    ip_cidr_range = "192.168.64.0/22"
  }
}

## Create kubernetes cluster
resource "google_service_account" "main-cluster-svc" {
  account_id   = "main-cluster-svc"
  display_name = "Primary Cluster Nodes Service Account"
}

resource "google_container_cluster" "main-cluster" {
  name     = "main-cluster"
  location = var.region

  enable_autopilot = true

  network    = google_compute_network.main-cluster-network.id
  subnetwork = google_compute_subnetwork.main-cluster-subnetwork.id

  ip_allocation_policy {
    cluster_secondary_range_name  = "services-range"
    services_secondary_range_name = google_compute_subnetwork.main-cluster-subnetwork.secondary_ip_range.1.range_name
  }

  maintenance_policy {
    recurring_window {
      start_time = "2022-12-18T00:00:00Z"
      end_time   = "2050-01-01T04:00:00Z"
      recurrence = "FREQ=WEEKLY"
    }
  }

  release_channel {
    channel = "REGULAR"
  }

  node_config {
    # This should be acceptable as long as any user request completes within 30 seconds
    spot  = true

    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.main-cluster-svc.email
    oauth_scopes    = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }

  private_cluster_config {
    enable_private_nodes = true
    enable_private_endpoint = false
  }
}

## Create container artifact registry
resource "google_artifact_registry_repository" "artifact-container-repos" {
  location = "us-central1"
  project = var.environment_to_project_id[var.env_name]
  repository_id = "container-repos"
  format = "DOCKER"
}
```

### Debug Output
https://gist.github.com/LukeMauldin/11e1fd2dfd3d7f9503c3c561d6027325

### Panic Output
N/A

### Expected Behavior
Terraform should not have recreated the cluster because nothing about the cluster changed.  The only section I added was the section to create the container artifact registry.  I also did not make any changes manually to the Kubernetes cluster.

### Actual Behavior
Terraform destroyed and recreated the Kubernetes cluster which adds 15+ minutes to every iteration

### Steps to Reproduce
`terraform apply`

**Comment by edwardmedia** [comment] 2022-12-31 21:26
@LukeMauldin where did you see the `google_container_cluster` was gonna recreated? Can you point that out? I do see below lines in the log but they are not the one you was talking about, I guess.

```
google_artifact_registry_repository.artifact-container-repos[0m will be created
```

```
google_project_iam_member.gke-service-account-artifactregistry-reader[0m will be created
```

**Comment by davdmrgn** [comment] 2023-01-07 01:55
The problem is `enable_autopilot = true` cannot specify an alternate service account as documented. It will always deploy as `default`, so if you re-apply the plan it will try to re-deploy with the service account, resulting in the issue described.


When using the gcloud CLI, you must use the parameters `--autoprovisioning-service-account` for the service account and `--autoprovisioning-scopes` for oauth scopes. The terraform provider must be updated with these options.

**Comment by edwardmedia** [comment] 2023-03-11 17:53
@LukeMauldin glad you have found a fix. Closing the issue then.

**Closed by edwardmedia** 2023-03-11 17:53 UTC
Labels: bug, service/container
