### ISSUE TITLE
bigquery table schema with field having missing mode attribute causes perma plan diff

### ISSUE THREAD

**Issue by owennewo** [hashicorp/terraform-provider-google#7979] opened 2020-12-10 10:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26
### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```
terraform {
  backend "gcs" {}
  required_version = "0.12.26"
}
provider "google" {
  version     = "v3.50.0"
  region      = var.region
  zone        = var.zone
}
provider "google-beta" {
  version     = "v3.50.0"
  region      = var.region
  zone        = var.zone
}
```
### Expected Behavior

When a bigquery table schema has fields like this where mode of field is not specified:
```
schema = <<EOF
[  {
    "name": "PageNo",
    "type": "INTEGER"
  },
  {
    "name": "IngestTime",
    "type": "TIMESTAMP"
  }
]
EOF
```
After the `google_bigquery_table` resource is applied it should be possible to plan this resource and it should show zero change (nothing to do).  i.e. It should not show perma change.

### Actual Behavior

Terraform believes that the plan is requesting that `"mode" : "NULLABLE"` should be removed (note this mode is the default mode)
```
schema = <<EOF
[  {
   - "mode": "NULLABLE",
    "name": "PageNo",
    "type": "INTEGER"
  },
  {
   - "mode": "NULLABLE",
    "name": "IngestTime",
    "type": "TIMESTAMP"
  }
]
EOF
```
Not all field types have this issue.  `INTEGER` and `TIMESTAMP` are affected but `DATE` is not

On its own this is a bit annoying, the workaround is to include the default mode in terraform.
However if JSON field ordering of schema has also changed (as in my case) it can show a massive delta (mostly field ordering changes) making the cause of this issue difficult to spot.  Initially I thought #6803 (JSON schema diff suppresion) wasn't working but I believe if there is a change (e.g. due to this bug) then #6803 is unable to suppresses the field reordering parts.   i.e. #6803 works great but only if there is no delta. 

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`
### Important Factoids

This issue may be hard to reproduce. For instance it happens consistently in our dev environment but which has seen multiple schema changes applied to it but it did not happen in our QA environment which only had the final schema applied to it.
### References

* #0000

**Comment by edwardmedia** [comment] 2020-12-10 14:25
@owennewo can you hare the debug log?

**Comment by jaycarlton** [comment] 2020-12-14 18:44
@edwardmedia I can repro. My logs are [here](https://gist.github.com/jaycarlton/aefd923ed2052831070fec65496e6ba4).

In my case I've tried every combination of setting my fields to `"NULLABLE"`, 'null', and just leaving the fields out. I still see this frequently in my workflow, where I create a number of tables from JSON files with a `for` loop.

**Comment by jaycarlton** [comment] 2020-12-14 20:25
You can also observe a very similar phenomenon with the `description` field, which is optional, and cycles between `""`, `null`, and missing altogether in the input file. I've generally resolved to set this field every time to a nonempty string so it stays stable.

I want to say I've seen it on other optional fields as well, but I'm not sure.

**Comment by ScottSuarez** [comment] 2020-12-15 17:55
@owennewo @jaycarlton

So I took a look at this resource and couldn't reproduce this. It does not seem like this `mode:nullable` reproduces on every configuration, and in my case I could not reproduce it. In our implementation we are simply surfacing the api get for this object and don't really do a whole lot on top of that. I went ahead and did a manual get on a configuration I deployed and confirmed that default wasn't getting inserted to the schema

This is the configuration I deployed
```hcl
resource "google_bigquery_dataset" "test" {
	dataset_id = "tf_test_scoot"
}

resource "google_bigquery_table" "test" {
	table_id   = "tf_test_scooter"
	dataset_id = google_bigquery_dataset.test.dataset_id

	time_partitioning {
		type                     = "DAY"
		field                    = "IngestTime"
		require_partition_filter = true
	}
  schema = <<EOF
[  {
    "name": "PageNo",
    "type": "INTEGER"
  },
  {
    "name": "IngestTime",
    "type": "TIMESTAMP"
  }
]
EOF
}
```


and below is a scrubbed api get from the [rest api](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/get)
```json
{
....
  "schema": {
    "fields": [
      {
        "name": "PageNo",
        "type": "INTEGER"
      },
      {
        "name": "IngestTime",
        "type": "TIMESTAMP"
      }
    ]
  },
  "timePartitioning": {
    "type": "DAY",
    "field": "IngestTime",
    "requirePartitionFilter": true
  },
  "numBytes": "0",
  "numLongTermBytes": "0",
  ...
}
```

Notice the `"mode" : "NULLABLE"` is not apart of the schema. I suspect this is some inconsistent api behavior. Could you supply me with your full (scrubbed) configuration so I can try to repo on my end?

I think the best solution here may be to file a bug with the api. We can also add support to suppress this diff in these scenarios but realistically we would want a configuration that we could add a testcase for. If I can't reproduce this I wouldn't want to add support that I can't maintain test coverage for.

**Comment by jaycarlton** [comment] 2020-12-15 18:20
Most of our config is [open source](https://github.com/all-of-us/workbench-terraform-modules/pull/4). Is there a tool for bundling up the whole thing and redacting it?

**Comment by ScottSuarez** [comment] 2020-12-15 21:25
We would just have to parse the json and do a manual comparison with these fields. The current function doing this comparison is [located here](https://github.com/hashicorp/terraform-provider-google/blob/a3015d0d1f5612315eaa8619dbd76f3c0ea15aef/google/resource_bigquery_table.go#L61). I'll take a stab at resolving this for you guys. @jaycarlton also gave me some of the example plans so hopefully I can get a repro on my side.

**Comment by owennewo** [comment] 2020-12-16 11:20
> @owennewo can you share its debug log?

[bq_perma_diff_debug_plan.txt](https://github.com/hashicorp/terraform-provider-google/files/5702280/bq_perma_diff_debug_plan.txt)

Here is plan with TF_LOG=DEBUG

**Comment by ScottSuarez** [comment] 2021-01-07 15:04
Checked in the [fix for this](https://github.com/GoogleCloudPlatform/magic-modules/pull/4347).. thanks for your patience. Holidays held things up. Hope this will make your lives easier :)

**Closed by ScottSuarez** 2021-01-07 15:04 UTC
Labels: persistent-bug
