### ISSUE TITLE
Support IPv6 address type for google_compute_forwarding_rule resource.

### ISSUE THREAD

**Issue by ericayyliu** [hashicorp/terraform-provider-google#13557] opened 2023-01-24 00:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Internal TCP/UDP Loadblancer now supports IPv6 address type, by specifying `--ip_version = IPV6`. See [here](https://cloud.google.com/load-balancing/docs/internal/setting-up-internal#gcloud_9) for more details of setting up IPv6 forwarding rule.

### New or Affected Resource(s)

* google_compute_forwarding_rule

### Potential Terraform Configuration

```tf
resource "google_compute_forwarding_rule" "<%= ctx[:primary_resource_id] %>" {
  name   = "<%= ctx[:vars]['forwarding_rule_name'] %>"
  region = "us-central1"

  load_balancing_scheme = "INTERNAL"
  backend_service       = google_compute_region_backend_service.backend.id
  all_ports             = true
  network               = google_compute_network.default.name
  subnetwork            = google_compute_subnetwork.default.name
  ip_version            = "IPV6"
}
```

### References

* [Internal TCP/UDP LoadBalancing](https://cloud.google.com/load-balancing/docs/internal)

**Comment by ericayyliu** [comment] 2023-01-24 00:47
Added pull request https://github.com/GoogleCloudPlatform/magic-modules/pull/7150

**Comment by nkinkade** [comment] 2023-03-10 00:09
For reference, this issue may functionally be a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/11890, though that issue is specifically referring to an `ip_version` argument for an external load balancer, which this one is referring to an internal one. I don't believe it should matter, as long as the option is available for this resource.

**Comment by melinath** [comment] 2023-12-21 23:36
This was resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8453

**Closed by melinath** 2023-12-21 23:36 UTC
Labels: enhancement, size/s, forward/review, service/compute-l7-load-balancer
