### ISSUE TITLE
google_cloudfunctions_function -> support secrets

### ISSUE THREAD

**Issue by lwsanty** [hashicorp/terraform-provider-google#10059] opened 2021-09-13 13:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I see that provider supports _Cloud Run_ creation with secret environment variables, see [example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables).

I see that _Cloud Functions_ natively support secrets, see [documentation](https://cloud.google.com/functions/docs/configuring/secrets).

But, according to providers [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function) `cloudfunctions_function` does not have a secrets support.

### New or Affected Resource(s)

* cloudfunctions_function

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

data "google_project" "project" {
  provider = google-beta
}

resource "google_secret_manager_secret" "secret" {
  provider = google-beta

  secret_id = "secret"
  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "secret-version-data" {
  provider = google-beta

  secret = google_secret_manager_secret.secret.name
  secret_data = "secret-data"
}

resource "google_secret_manager_secret_iam_member" "secret-access" {
  provider = google-beta

  secret_id = google_secret_manager_secret.secret.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${data.google_project.project.number}-compute@developer.gserviceaccount.com"
  depends_on = [google_secret_manager_secret.secret]
}

resource "google_cloudfunctions_function" "function" {
  provider = google-beta

  name        = "function"
  entry_point = "TheFunc"
  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = "projects/${var.google_project}/topics/${var.topic}"
    failure_policy {
      retry = false
    }
  }
  runtime               = var.runtime
  service_account_email = var.google_service_account
  region                = var.google_region_global
  source_archive_bucket = var.sources_bucket
  source_archive_object = var.source
  vpc_connector         = var.vpc_connector
  labels = {
    environment = var.namespace
  }

  env {
    name = "SECRET_ENV_VAR"
    value_from {
      secret_key_ref {
        name = google_secret_manager_secret.secret.secret_id
        key = "1"
      }
    }
  }
}
```

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-secret-environment-variables
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function
- https://cloud.google.com/functions/docs/configuring/secrets

**Comment by slevenick** [comment] 2021-09-13 23:53
Closing as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/9946

**Closed by slevenick** 2021-09-13 23:53 UTC
Labels: enhancement
