### ISSUE TITLE
Show caution of caveats of google_project_iam_binding in the doc

### ISSUE THREAD

**Issue by hgsgtk** [hashicorp/terraform-provider-google#18042] opened 2024-05-08 01:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

When a user wants to manage IAM users' role via Terraform, using the Terraform resource, google_project_iam_binding, has a risk of breaking existing infrastructure because it can affect the resource outside of Terraform, although the official doc does not warn it.
A straightforward recommendation is to use [google_project_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#google_project_iam_member) instead of it, but it could be nice if the documentation tells the user that.

### New or Affected Resource(s)

* google_project_iam_binding
* google_project_iam_member

### Potential Terraform Configuration

```tf 
```

**Comment by SarahFrench** [comment] 2024-05-09 17:40
I'm afraid we need to close this issue as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/17329

**Closed by SarahFrench** 2024-05-09 17:40 UTC
Labels: enhancement, forward/review, service/cloudresourcemanager-crm
