### ISSUE TITLE
Unable to label disk when made with google_compute_instance

### ISSUE THREAD

**Issue by thomaswors** [hashicorp/terraform-provider-google#9097] opened 2021-05-06 17:53 UTC
### Description ###

The Boot Disk block in google_compute_instance does not support labels. 

This can be mitigated by declaring a google_compute_disk and having the instance use this disk, however that leads to issues when updating existing resources.

If an existing instance has a disk mounted, it cannot destroy that disk until the instance is dead. An instance "depends on" block will have issues starting if the disk object is not made first, so it is a chicken before the egg problem. 

The easiest fix would be to allow tags either directly, or just inherited from the instance itself when defined in google_compute_instance.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#boot_disk

### Potential Terraform Configuration

Example where labels could be direct in the boot_disk block, explicitly stated. 
```
resource "google_compute_instance" "foo" {
  name         = "foo"
  description  = "instance"
  boot_disk {
    initialize_params {
      image = data.google_compute_image.image.self_link
      size = 50
      labels = {
      foo = "bar"
      }
    }
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#boot_disk
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_disk#labels

**Comment by thomaswors** [comment] 2021-05-06 18:20
My suggestion is addressed in the beta-provider.
https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/data-sources/compute_instance#boot_disk

There is still the issue of not being able to re-create the disk with a new image if it is in use by an existing instance.
```
12:40:35  google_compute_disk.boot_disk: Creating...
12:40:35  google_compute_instance.foo: Creating...
12:40:46  google_compute_disk.boot_disk: Still creating... [10s elapsed]
12:40:55  google_compute_disk.boot_disk: Still creating... [20s elapsed]
12:40:57  google_compute_disk.boot_disk: Creation complete after 21s [id=projects/foo/disk]
12:40:57  
12:40:57  Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].source': 'projects/foo/disk'. The referenced disk resource cannot be found., invalid
```

**Comment by thomaswors** [comment] 2021-05-06 18:24
second complaint being looked at here
https://github.com/hashicorp/terraform-provider-google/issues/9045#issuecomment-833608963

**Comment by ixb49** [comment] 2022-01-17 23:35
I can confirm putting `labels` block inside boot_disk -> initialize_params works in latest provider. This was added in https://github.com/hashicorp/terraform-provider-google/pull/3766 . Documentation was updated then however seems to have been removed at a later point.

**Comment by roaks3** [comment] 2022-09-28 19:41
Closing as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8861

**Closed by roaks3** 2022-09-28 19:41 UTC
Labels: enhancement, size/s
