### ISSUE TITLE
Fix TestAccFilestoreInstance_* tests

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#7960] opened 2020-12-07 19:52 UTC
Terraform wants to update the `file_shares` block after applying. Very likely the block needs to be set to computed.

**Comment by melinath** [comment] 2020-12-08 17:26
This is a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7750

**Closed by melinath** 2020-12-08 17:26 UTC
Labels: size/S, test failure
