### ISSUE TITLE
google_compute_url_map 

### ISSUE THREAD

**Issue by grzebis1** [hashicorp/terraform-provider-google#9210] opened 2021-05-21 01:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/google v3.51.0
+ provider registry.terraform.io/hashicorp/google-beta v3.51.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0

### Affected Resource(s)

`google_compute_url_map.url_map[0]`

#### GCP resources definition
```tf 
resource "google_compute_region_target_https_proxy" "proxy" {
  count            = var.enabled ? 1 : 0
  region           = var.region
  name             = var.name
  description      = var.desc
  url_map          = google_compute_region_url_map.url_map[0].id
  ssl_certificates = [var.google_compute_region_ssl_certificate_id]
}

resource "google_compute_region_url_map" "url_map" {
  count    = var.enabled ? 1 : 0
  provider = google

  region      = var.region
  name        = var.name
  description = var.desc
  host_rule {
    hosts        = var.hosts
    path_matcher = "allpaths"
  }
  default_service = google_compute_region_backend_service.neg_backend[var.default_service].id

  path_matcher {
    name            = "allpaths"
    default_service = google_compute_region_backend_service.neg_backend[var.default_service].id

    dynamic "route_rules" {
      for_each = {
        for backend, config in var.backends : backend => config if(config.type == "neg")
      }
      content {
        priority = route_rules.value.priority
        match_rules {
          prefix_match = route_rules.value.path_prefix
        }
        service = google_compute_region_backend_service.neg_backend[route_rules.key].id
      }
    }
  }
}
```

#### TF variables
```tf
l7_ilb_ingress = {
  enabled        = true
  static_ip_name = "apps-platdev-ingress-l7-internal"
  cert_version   = 1
  key_version    = 1
  hosts = [
    "apps-platdev.gcpnp.anz",
    "*.apps-platdev.gcpnp.anz",
  ]
  health_check = {
    host = "httpbin.apps-platdev.gcpnp.anz"
    port = "443"
    path = "/"
  }
  backends = {
    "ingressgateway" = {
      path_prefix           = "/"
      type                  = "neg"
      priority              = 1
      max_rate_per_endpoint = 4000
      negs = [
        "https://www.googleapis.com/compute/v1/projects/apps-platdev/zones/australia-southeast1-a/networkEndpointGroups/k8s1-istio-system-ingressgateway",
        "https://www.googleapis.com/compute/v1/projects/apps-platdev/zones/australia-southeast1-b/networkEndpointGroups/k8s1-istio-system-ingressgateway",
        "https://www.googleapis.com/compute/v1/projects/apps-platdev/zones/australia-southeast1-c/networkEndpointGroups/k8s1-istio-system-ingressgateway",
      ]
    }
  }
}
```

### Debug Output

**https://gist.github.com/grzebis1/9219257dccb3fb0c5e5a2324648a1170**

### Expected Behavior

The new Host should be added to the google_compute_url_map and the terraform apply should finish without errors

### Actual Behavior

Run a `terraform apply` and you get the following error

```tf
When expanding the plan for
module.l7_ilb_ingress.google_compute_region_url_map.url_map[0] to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/google-beta" produced an invalid new value
for .map_id: was cty.NumberIntVal(4.224932892444940201e+18), but now
cty.NumberIntVal(4.2249328924449403e+18).
```

### Steps to Reproduce

1. Create a google_compute_url_map with a number of hosts
2. Add an additional host and run Terraform apply

**Comment by upodroid** [comment] 2021-05-21 14:27
Hi

This was fixed a while back in 3.51.1 and higher.

More details are in the changelog and the linked pull requests.

https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3511-january-07-2021

**Comment by edwardmedia** [comment] 2021-05-21 21:06
@grzebis1 can you try using the latest provider to see if you are still able to repro?

**Comment by edwardmedia** [comment] 2021-06-03 23:45
@grzebis1 based on your `thumb up`, I guess the issue is resolved. Closing the issue then

**Closed by edwardmedia** 2021-06-03 23:45 UTC
Labels: bug, waiting-response
