### ISSUE TITLE
URL map resource overwrites path matchers

### ISSUE THREAD

**Issue by PumpkinSeed** [hashicorp/terraform-provider-google#15417] opened 2023-08-07 14:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.4.5
on linux_amd64
```

### Affected Resource(s)

* google_compute_url_map

### Terraform Configuration Files

```tf
resource "google_compute_url_map" "tf-review-app-urlmap" {
  name        = "tf-review-app-url-map"
  description = "The main URL map of the review app"

  default_service = google_compute_backend_bucket.tf-review-app-default-backend-definition.id
}
```

### Expected Behavior

[Kind of related issue.](https://github.com/hashicorp/terraform-provider-google/issues/8662)

Creating a basic URL map and adding path matchers by using the separate gcloud command to adding path matchers. It won't be managed in the terraform, because a separate CI will add them.

Command: `gcloud compute url-maps add-path-matcher`

### Actual Behavior

After I added a few path matchers with the command from above I needed to change the main terraform. After I applied the changes the `google_compute_url_map` resource removed all the path matchers added manually.

Since there is a separate CLI command for that I assume there should be a flag or something inside the resource definition to keep those path matchers.

### Steps to Reproduce

```tf
resource "google_storage_bucket" "test" {
  name          = "test"
  location      = "US"
  force_destroy = true

  uniform_bucket_level_access = true

  website {
    main_page_suffix = "index.html"
    not_found_page   = "index.html"
  }
}

resource "google_compute_backend_bucket" "test" {
  name        = "test"
  description = "Test"
  bucket_name = google_storage_bucket.test.name
}

resource "google_compute_url_map" "test" {
  name        = "test"
  description = "Test"

  # Create a bucket and a backend_bucket
  default_service = google_compute_backend_bucket.test.id
}
```

```
terraform apply

# Add path matcher
gcloud compute url-maps add-path-matcher test \
    --path-matcher-name=test-path-new \
    --new-hosts=example.com \
    --default-backend-bucket=test

# This will remove the path matcher from above.
terraform apply
```

**Comment by edwardmedia** [comment] 2023-08-07 17:03
@PumpkinSeed not sure if I understood completely. Once you update the resource via gcloud, the config has been updated according at the server (api), but the terraform config and the local state are not updated. Once you call `terraform apply` now, terraform will try to update the api with your local config. This is the normal behavior. Did you see the behavior differently in other places?

**Comment by PumpkinSeed** [comment] 2023-08-07 17:17
Use-case: We have a feature called "review app". It is deploying the application per git branch. This means that each branch has it's domain like `{branch_name}.company.com`. This is done by Bitbucket Pipeline. For this I initially created a URL map and the pipeline keep attaching path matchers to satisfy the `{branch_name}.company.com`. We have ad many path matchers as branches. So like DNS registered as well.

---

The behavior when I'm using pure gcloud cli:

#### 1. Creating initial URL map

It will create the initial url map and it should be run only once.

```
gcloud compute url-maps something --default-backend-bucket=def-bucket
```

#### 2. Add path matcher

This will be added for each branch. So every time when a branch has the "first pipeline run", we run the following to setup the path matcher.

```
gcloud compute url-maps add-path-matcher something \
    --path-matcher-name=something-path-{branch} \
    --new-hosts={branch}.company.com \
    --default-backend-bucket=bucket-{branch}
```

---

The behavior when I create the URL map with Terraform:

#### 1. Create URL map

```
resource "google_compute_url_map" "something" {
  name        = "something"
  description = "Something"

  # Create a bucket and a backend_bucket
  default_service = "def-bucket"
}
```

#### 2. Add path matcher

Same as above

```
gcloud compute url-maps add-path-matcher something \
    --path-matcher-name=something-path-{branch} \
    --new-hosts={branch}.company.com \
    --default-backend-bucket=bucket-{branch}
```

This all working fine until I want to modify something in the main terraform project. (Note we have everything per project on the same place, so we are managing all the terraform manifests for one particular GCP project).
So when I modify something (for example I add a new service account) and apply the changes, the `google_compute_url_map` removes all the path matchers what I added from the pipeline.

**Comment by edwardmedia** [comment] 2023-08-07 17:42
@ScottSuarez do you have any suggestions for this case?

**Comment by PumpkinSeed** [comment] 2023-08-10 11:06
Do you have any update on that? 

I think a flag would be sufficient to not to remove those.

**Comment by zli82016** [comment] 2023-08-15 17:22
@PumpkinSeed , there is not a flag to do that. 

As @edwardmedia mentioned, after you ran gcloud command, you have to update the terraform config to match whatever you added via gcloud. If you don't update the terraform config, it means that the path matcher will be removed.

**Comment by zli82016** [comment] 2023-08-15 17:32
I wonder if it will work to add path matcher by using the terraform configuration like this

```
resource "google_compute_url_map" "something" {
  name        = "something"
  description = "Something"

  # Create a bucket and a backend_bucket
  default_service = "def-bucket"

  path_matcher {
    name            = "xxxx"
    default_service = xxxx
  }

}
```

**Comment by PumpkinSeed** [comment] 2023-08-16 10:40
I will check the underlying code, and I will try to suggest something. I see that it works differently. What I can imagine as base problem that the resource check the difference between the existing url map and the one which is defined in the terraform. It sees that we only defined a URL map but there is no path matcher in the definition. 

I think one solution can be that only checks whether there is an existing url map and not checking the the other resources belongs to the url map. This requires to separate the resources. Like we can create different resources for url map creation and we can have the path matcher and attach to url map's id. (Just like the orther issue mentioned).

**Comment by rileykarson** [comment] 2023-09-05 17:19
Is Terraform plan indicating it will remove the path matchers, or is this happening after not getting displayed in plan? The shape of a resource between Terraform and gcloud is not always 1:1, so this may be intended.

`lifecycle.ignore_changes` may preserve the value(s) you want, to allow mixed-management.

**Comment by PumpkinSeed** [comment] 2023-09-08 11:24
@rileykarson Yes, the plan displays that it will remove them. I think the issue is mainly related to how the terraform stores the state about the url_map's path_matchers. It's checking the state and it decides that the actual response of the API call of the path_matcher does not match with the state stored for path matchers. 

I need to check out this `ignore_changes`, once I tried it, I will come back with the results.

**Comment by rileykarson** [comment] 2023-09-08 17:55
Thanks! Yeah, I think this is an issue of a mismatch between gcloud and Terraform/the API and working as intended. In the API, the pathMatchers are a field on the url map object (https://cloud.google.com/compute/docs/reference/rest/v1/urlMaps) while the gcloud commands represent some of those fields as subresources.

That's something we did on Router with subresources like https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_peer, and in a few other places. We tend to stick closer to the API now than we did at the time that decision was made for Router- sometimes those kind of customizations can turn out well, and other times they can be harmful to end users as the API evolves.

`lifecycle.ignore_changes` should almost certainly achieve what you want here, though.

**Comment by PumpkinSeed** [comment] 2023-09-11 10:09
@rileykarson 

I tried the `lifecycle.ignore_changes` with `all`. I didn't want to investigate a better option for that, because I got the issue resolved. 

Thanks for the help. I don't want to close this one, because if you want to fix it somehow it will be there, but I'm good with the `lifecycle.ignore_changes`. So decide what you want with this ticket.

**Comment by rileykarson** [comment] 2023-09-11 16:13
I'm going to close this as the resource is working as intended and the use case is supported. We'd accept an issue asking to add a resource with a smaller scope to more obviously cover the use case, although would need to confer with the service team for feedback on whether that's something we'd move forward with.

**Closed by rileykarson** 2023-09-11 16:13 UTC
Labels: persistent-bug
