### ISSUE TITLE
implement serverTlsPolicy for https_proxy resources

### ISSUE THREAD

**Issue by jogoldberg** [hashicorp/terraform-provider-google#14980] opened 2023-06-26 10:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Please implement serverTlsPolicy as an argument for these resources as outlined in [Google's Documents](https://cloud.google.com/compute/docs/reference/rest/v1/targetHttpsProxies) so that we can make use of google_network_security_server_tls_policy resource introduced in [google-beta provider v4.66.0](https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.66.0)

### New or Affected Resource(s)

* google_compute_target_https_proxy
* google_compute_region_target_https_proxy

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_network_security_server_tls_policy" "default" {
  provider    = google-beta
  name        = "my-tls-policy"
  location    = "global"
  description = "TLS Policy for mTLS"
  #server_certificate = google_compute_ssl_certificate.default[0].self_link
  mtls_policy {
    client_validation_trust_config = "projects/${var.project_number}/locations/global/trustConfigs/my-trust-config-created-in-cli"
    client_validation_mode         = "ALLOW_INVALID_OR_MISSING_CLIENT_CERT"
  }
}

resource "google_compute_target_https_proxy" "default" {
  name                 = "test-proxy"
  url_map             = google_compute_url_map.default.id
  ssl_certificates   = [google_compute_ssl_certificate.default.id]
  server_tls_policy =  google_network_security_server_tls_policy.default.id
}
```

### References

* #14686
* GoogleCloudPlatform/magic-modules#7822
* hashicorp/terraform-provider-google-beta#5619
* https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.66.0

b/290613151

**Comment by jogoldberg** [comment] 2023-06-26 10:48
Linking references:

#14686
GoogleCloudPlatform/magic-modules#7822
hashicorp/terraform-provider-google-beta#5619

**Comment by melinath** [comment] 2023-09-25 18:07
It looks like this was fixed for google_compute_target_https_proxy but not for google_compute_region_target_https_proxy.

**Comment by maxi-cit** [comment] 2023-09-26 15:09
@melinath I started working on this

**Comment by maxi-cit** [comment] 2023-11-07 15:25
Hello @melinath I had a small talk with Babi Seal and he confirmed that currently there is no plan to deliver the regional scenario. I believe that we can close this issue.

**Comment by jogoldberg** [comment] 2023-11-17 17:01
@maxi-cit  What do you mean "no plan to deliver the regional scenario"? The API currently supports it afaik. It's definitely implemented from gcloud CLI, as that's currently my only option for provisioning this.  I've been 5 months for this to be added. Why would you suggest closing it?

**Comment by maxi-cit** [comment] 2023-11-17 18:45
Hello @jogoldberg, I opened a PR implementing the regional scenario but it failed due to some restriction in the API. Please check this [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/9105).

**Comment by maxi-cit** [comment] 2023-12-06 18:16
Hello folks, I had a recent communication from some Google people that this feature is currently work in progress. So, we will need to wait for a time for it become available.

**Closed** 2024-04-23 17:39 UTC
Labels: enhancement, size/s, forward/linked, service/compute-l7-load-balancer
