### ISSUE TITLE
Hierarchical firewall rules no longer in beta

### ISSUE THREAD

**Issue by ct-dh** [hashicorp/terraform-provider-google#8742] opened 2021-03-22 12:22 UTC
The hierarchical firewall rule support is currently marked as in beta but looks like the service has been GA for about a month now.

https://cloud.google.com/vpc/docs/release-notes#February_26_2021

**Comment by rileykarson** [comment] 2021-03-22 17:43
Dupe of https://github.com/hashicorp/terraform-provider-google/issues/8229

**Closed by rileykarson** 2021-03-22 17:43 UTC
Labels: enhancement
