### ISSUE TITLE
Add recaptcha key resource

### ISSUE THREAD

**Issue by bbr32** [hashicorp/terraform-provider-google#8703] opened 2021-03-16 17:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It would be nice to have a resource to create recaptcha keys as seen in the API guide to create keys : https://cloud.google.com/recaptcha-enterprise/docs/create-key#create-key-drest 

There might be other resources linked to this as well, let me know if I can contribute to this :) 

### New or Affected Resource(s)

* google_recaptcha_key

### Potential Terraform Configuration

```tf
resource "google_recaptcha_key" "key" {
  project = "project-id"
  display_name = "name"
  domains = ["domain"]
}
```

### References

* b/183510674

**Comment by pranavsky** [comment] 2021-10-01 11:17
+1

**Comment by rileykarson** [comment] 2021-11-16 00:28
@shuyama1: I think this is a dupe of https://github.com/hashicorp/terraform-provider-google/issues/10513, right? I must have forgotten to check for this when filing that one. Whoops!

**Comment by shuyama1** [comment] 2021-11-16 00:48
Yeah, I think so! Sorry, also forgot to link these two issues.

**Comment by rileykarson** [comment] 2021-11-16 00:50
Cool, deduped.

**Closed** 2021-12-02 20:41 UTC
Labels: enhancement, new-resource, size/m, tpgtools
