### ISSUE TITLE
Root resource was present, but now absent (google_privateca_certificate)

### ISSUE THREAD

**Issue by ayobuba** [hashicorp/terraform-provider-google#17402] opened 2024-02-25 16:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.3.9

### Affected Resource(s)

google_privateca_certificate

### Terraform Configuration

```tf
resource "google_privateca_certificate" "default" {
  for_each = { for k, v in var.ca_pool_resource : k => v if v.create_google_privateca_certificate }

  pool                  = google_privateca_ca_pool.default[each.key].name
  name                  = "${each.value.certificate.name}-${random_id.this[each.key].hex}"
  location              = each.value.certificate.location
  certificate_authority = local.this_ca[each.key]
  #  certificate_authority = google_privateca_certificate_authority.this_ca[each.key].certificate_authority_id
  lifetime = "860s"
  config {
    subject_config {
      subject {
        organization = try(each.value.certificate.subject_config.subject.organization, "shara")
        common_name  = try(each.value.certificate.subject_config.subject.common_name, "shara")
      }
    }
    x509_config {
      ca_options {
        is_ca = try(each.value.certificate.x509_config.ca_options.is_ca, false)
      }
      key_usage {
        base_key_usage {
          digital_signature  = try(each.value.certificate.x509_config.key_usage.base_key_usage.digital_signature, true)
          content_commitment = try(each.value.certificate.x509_config.key_usage.base_key_usage.content_commitment, true)
          key_encipherment   = try(each.value.certificate.x509_config.key_usage.base_key_usage.key_encipherment, false)
          data_encipherment  = try(each.value.certificate.x509_config.key_usage.base_key_usage.data_encipherment, true)
          key_agreement      = try(each.value.certificate.x509_config.key_usage.base_key_usage.key_agreement, false)
          cert_sign          = try(each.value.certificate.x509_config.key_usage.base_key_usage.cert_sign, true)
          crl_sign           = try(each.value.certificate.x509_config.key_usage.base_key_usage.crl_sign, true)
          decipher_only      = try(each.value.certificate.x509_config.key_usage.base_key_usage.decipher_only, true)
        }
        extended_key_usage {
          server_auth      = try(each.value.certificate.x509_config.key_usage.extended_key_usage.server_auth, true)
          client_auth      = try(each.value.certificate.x509_config.key_usage.extended_key_usage.client_auth, true)
          email_protection = try(each.value.certificate.x509_config.key_usage.extended_key_usage.email_protection, true)
          code_signing     = try(each.value.certificate.x509_config.key_usage.extended_key_usage.code_signing, true)
          time_stamping    = try(each.value.certificate.x509_config.key_usage.extended_key_usage.time_stamping, true)
        }
      }
    }
    public_key {
      format = "PEM"
      key    = base64encode(tls_private_key.this[each.key].public_key_pem)
    }
  }

}
```

### Debug Output

https://gist.github.com/ayobuba/396f7d65439d2975555aef4fda1b368b

### Expected Behavior

google_privateca_certificate.default["dev_ca_pool"] resource should have been created.

### Actual Behavior

Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ google_privateca_certificate.default["dev_ca_pool"], provider
│ "provider[\"registry.terraform.io/hashicorp/google\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-google/issues/12564

**Comment by zli82016** [comment] 2024-02-26 23:58
@ayobuba , can you please provide the config for `var.ca_pool_resource`?  How many values does `var.ca_pool_resource` have? Did other `google_privateca_certificate.default` fail?

Also, can you please provide the detailed debug logs? There is only the error message in the provided log.txt file.

**Comment by reith** [comment] 2024-04-02 20:40
Seems like a duplicate of #14241

**Closed** 2024-04-26 07:04 UTC
Labels: bug, service/privateca, forward/review
