### ISSUE TITLE
Add MD5 Authentication option for Cloud Router BGP Sessions

### ISSUE THREAD

**Issue by ckent99999** [hashicorp/terraform-provider-google#16594] opened 2023-11-22 21:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When creating a BGP session for something like an HA VPN, Google Cloud offers the ability to enhance security by adding an MD5 Authentication sting to the BGP peering configuration.  This feature is available in API, user GUI and gcloud CLI.  However, this does not appear to be available in Terraform.   This request is to add that ability.

For reference the gcloud command would be:
gcloud compute routers update-bgp-peer NAME \
--peer-name=PEER_NAME \
--md5-authentication-key=MD5_AUTHENTICATION_KEY

### New or Affected Resource(s)

I am assuming that "google_compute_router_peer" would be the applicable resource

### Potential Terraform Configuration
Here is an example of what I would like added

resource "google_compute_router_peer" "peer" {
  name                      = "my-router-peer"
  router                    = "my-router"
  region                    = "us-central1"
  peer_ip_address           = "169.254.1.2"
  peer_asn                  = 65513
  advertised_route_priority = 100
  interface                 = "interface-1"
#Add this#
  md5_auth_key              = "penny"
}

### References

**Comment by SarahFrench** [comment] 2023-11-27 18:09
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/13103

**Closed by SarahFrench** 2023-11-27 18:09 UTC
Labels: enhancement
