### ISSUE TITLE
Fix TestAccActiveDirectoryDomainTrust_*

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-provider-google#7159] opened 2020-08-31 16:26 UTC
### Affected Resource(s)

* google_active_directory_domain_trust

These have been failing for a few days in a row, but not always for the same reason.  May need to look into adjusting timeouts, requesting more quota, etc. Pretty sure the way quota works we basically can only have 2 or 3 domains at one time, and we need to keep one running for the trust test, which means we get 1-2 we can create in a given test run. Also, the sweeper is broken (the delete URL is wrong)

**Comment by danawillow** [comment] 2020-10-23 22:29
I've made some progress on this, but there's a lot of manual setup that needs to happen in order to get the trust working. I've gotten maybe halfway? There's an email thread that says how far I've gotten. If whoever picks this up needs passwords for any accounts, they're stored in the place internally where passwords live and shared with the team.

**Comment by melinath** [comment] 2021-04-16 16:52
Just ran into this one again.

**Comment by melinath** [comment] 2021-05-26 20:40
TestAccActiveDirectoryDomainTrust_activeDirectoryDomainTrustBasicExample has been failing consistently for a few months now; I think it's a separate issue from the flakiness described above, so I've opened https://github.com/hashicorp/terraform-provider-google/issues/9238 to track that issue.

**Comment by mitj04** [comment] 2022-12-05 06:36
b/261371935

**Comment by melinath** [comment] 2023-10-16 17:29
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/16261

**Closed by melinath** 2023-10-16 17:29 UTC
Labels: size/s, test-failure, forward/exempt, service/managedidentities
