### ISSUE TITLE
Update docs for resource google_sql_database_instance

### ISSUE THREAD

**Issue by omelnyk1** [hashicorp/terraform-provider-google#8783] opened 2021-03-29 10:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Please update documentation https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance with query insights settings.

### New or Affected Resource(s)

* google_sql_database_instance

### References

* Resource schema: https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_sql_database_instance.go#L396
* GCP documentation: https://cloud.google.com/sql/docs/postgres/insights-overview

**Comment by c2thorn** [comment] 2021-03-29 17:44
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/8743

**Closed by c2thorn** 2021-03-29 17:44 UTC
Labels: enhancement
