### ISSUE TITLE
Support custom headers on backend bucket and backend service

### ISSUE THREAD

**Issue by Sytten** [hashicorp/terraform-provider-google#7299] opened 2020-09-17 19:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It is now possible to set custom request and response headers on backend services and backend buckets.

### New or Affected Resource(s)

* google_compute_backend_bucket
* google_compute_backend_service

### Potential Terraform Configuration

```tf
resource "google_compute_backend_bucket" "image_backend" {
  name        = "image-backend-bucket"
  bucket_name = google_storage_bucket.image_bucket.name

  custom_request_header {
    name = "MyRequestHeader"
    value = "MyRequestHeaderValue"
  }

  custom_response_header {
    name = "MyResponseHeader"
    value = "MyResponseHeaderValue"
  }
}
```

### References

* https://cloud.google.com/load-balancing/docs/custom-headers

**Comment by cagataygurturk** [comment] 2020-11-16 19:30
@ndmckinley this issue can be closed now :)

**Comment by ndmckinley** [comment] 2020-11-16 19:43
Ah of course, thank you.  :)

**Comment by lpzdvd-packlink** [comment] 2020-12-01 16:56
@ndmckinley @cagataygurturk I'm trying it for HSTS header and it does not seem to work.
should it be block?
not sure about implementation considering examples...

```
custom_response_headers {
  strict-transport-security = "max-age=63072000; includeSubDomains; preload"
}
```

**Comment by lpzdvd-packlink** [comment] 2020-12-01 18:07
> @ndmckinley @cagataygurturk I'm trying it for HSTS header and it does not seem to work.
> should it be block?
> not sure about implementation considering examples...
> 
> ```
> custom_response_headers {
>   strict-transport-security = "max-age=63072000; includeSubDomains; preload"
> }
> ```

In fact I also tried a dummy example like:

```
custom_response_headers = ["color: blue"]
```

and it seems to be the terraform right syntax but I've been unable to get any header working (also tried X-Frame-Options: DENY as seen in doc).

**Custom headers only seems to be working using UI or gcloud command an are visible after 5-6 minutes.** Opened a case in GCP and they confirmed it. BTW, it does not work in GKE ingress controllers either.

**Comment by cagataygurturk** [comment] 2020-12-01 18:12
@lpzdvd-packlink You are right. Terraform succeeds but the setting is not persisted. 

@ndmckinley do you think it is a Terraform issue?

**Comment by ndmckinley** [comment] 2020-12-01 18:31
I think that's unlikely - I am not sure how the tests passed if the values are not persisted, let me ask this week's onduty to look into that.  @c2thorn, any guesses?

**Comment by lpzdvd-packlink** [comment] 2020-12-02 16:51
Just to clarify,

I've been looking for an answer last weeks because we're passing trough an audit process and it requires custom response headers. It started in GKE ingress controllers (implements HTTP(s) LB) and we realized there are no BackedConfig spec but you can manually patch ingress (using gcloud CLI or UI). It works but is erased after some minutes. Btw, this feature is not in the product roadmap.

The we tried pure L7 LBs outside GKE scope. We patched using UI and gcloud and got header exactly 6 minutes after it has been applied but there was no terraform support and then I landed in this issue. Btw, it worked for dummy thing like `color: blue` but got problems in real headers (maybe not so RFC compliant).

Hope it helps.

**Comment by c2thorn** [comment] 2020-12-02 22:44
Looks like `customResponseHeaders` is available in the [beta API](https://cloud.google.com/compute/docs/reference/rest/beta/backendServices) but not [v1](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices). Since the google-beta provider uses the beta API, that seems to be working and those tests are passing. @lpzdvd-packlink @cagataygurturk can you confirm if using the google-beta provider solves this for you? I'll remove the field from the GA provider.

**Comment by cagataygurturk** [comment] 2020-12-02 23:42
@c2thorn Correct, with the beta provider the property is properly applied and persisted. Thanks for fixing and apologies for the bug I have created!

**Comment by lpzdvd-packlink** [comment] 2020-12-03 08:39
It will be nice if examples are updated as it's not clear if custom headers is a block or list(string).

**Comment by lpzdvd-packlink** [comment] 2020-12-03 15:26
@c2thorn it works as expected.
Just one question, how do we know it is promoted again to GA?

**Comment by c2thorn** [comment] 2020-12-03 18:48
@lpzdvd-packlink We can promote to GA after the API promotes the field to GA, and I am not sure when that would be. The [google provider changelog](https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md) will have an entry for when it is promoted to GA, and the [field documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#custom_response_headers) will no longer have the `Beta` tag.

**Closed** 2020-12-04 22:35 UTC
Labels: enhancement, size/S

**Comment by cagataygurturk** [comment] 2020-12-05 17:04
> It will be nice if examples are updated as it's not clear if custom headers is a block or list(string).

@lpzdvd-packlink The example usage is here and it is as same as custom request headers: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#example-usage---backend-service-network-endpoint
