### ISSUE TITLE
Treat column mode = NULLABLE and unspecified column mode as the same

### ISSUE THREAD

**Issue by jasonmcboyd** [hashicorp/terraform-provider-google#6755] opened 2020-07-07 22:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'm not sure if this is a bug report or a feature request.

If a big query table is created with a column that has the mode left unspecified and then later the mode is changed to "NULLABLE" `terraform plan` will indicate an update is required:

```
 ​~ schema              = jsonencode(
	 ​~ [
		 ​~ {
			 ​+ mode = "NULLABLE"
			   ​name = "AccountID"
			   ​type = "NUMERIC"
		   ​},
		 ​  <ommitted for brevity>
	   ​]
   ​)
```

I understand why no change is made but I think, given that [mode defaults to "NULLABLE" when no mode is specified](https://cloud.google.com/bigquery/docs/schemas#modes), the provider should treat these as the same and not indicate that an update is required.

### New or Affected Resource(s)

* google_bigquery_table

### Potential Terraform Configuration

No new configuration proposed. Just amended plan output.

### References

* #0000

**Comment by danawillow** [comment] 2020-07-17 15:49
Hi @jasonmcboyd, the docs at https://www.terraform.io/docs/providers/google/r/bigquery_table.html#schema say:
> ~>NOTE: Because this field expects a JSON string, any changes to the string will create a diff, even if the JSON itself hasn't changed. If the API returns a different value for the same schema, e.g. it switched the order of values or replaced STRUCT field type with RECORD field type, we currently cannot suppress the recurring diff this causes. As a workaround, we recommend using the schema as returned by the API.

Unfortunately this is just another instance of that case. Marking as a persistent bug because fixing it would be tricky and require us to do some thinking about how we handle diffs on json fields. I don't expect us to get around to it any time soon though.

**Comment by melinath** [comment] 2021-06-02 22:57
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7979

**Closed by melinath** 2021-06-02 22:57 UTC
Labels: persistent-bug, size/m
