### ISSUE TITLE
enable autoscaler on google_bigtable_instance

### ISSUE THREAD

**Issue by jamesp2202** [hashicorp/terraform-provider-google#10774] opened 2021-12-20 13:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

google cloud bigtable, - enable autoscaler via terraform.  Google bigtable now has a built in auto-scaler, would be nice to be able to do this using terraform.

### New or Affected Resource(s)

* google_bigtable_instance

### Potential Terraform Configuration

```tf
resource "google_bigtable_instance" "production-instance" {
  name    = "production"
  project = project_name

  cluster {
    cluster_id   = "production"
    num_nodes    = 5
    zone         = "us-central1-b"
    storage_type = "SSD"
  }

 autoscaling_policy {
    max_replicas    = 5
    min_replicas    = 1

    cpu_utilization {
      target = 0.7
    }
  }


}
```

### References

https://cloud.google.com/bigtable/docs/autoscaling

**Comment by mattayes** [comment] 2021-12-20 13:52
Duplicate of #10758.

**Comment by shuyama1** [comment] 2021-12-21 18:00
Dup of https://github.com/hashicorp/terraform-provider-google/issues/10758 as mentioned by @mattayes, and therefore closing this.

**Closed by shuyama1** 2021-12-21 18:00 UTC
Labels: enhancement
