### ISSUE TITLE
Disable the insecure read-only port on new Autopilot clusters

### ISSUE THREAD

**Issue by zaphod72** [hashicorp/terraform-provider-google#19153] opened 2024-08-15 20:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

When creating a new GKE Autopilot cluster I want to disable the insecure read-only port as per https://cloud.google.com/kubernetes-engine/docs/how-to/disable-kubelet-readonly-port#disable-autopilot

The `gcloud container clusters create-auto` flag is `--no-autoprovisioning-enable-insecure-kubelet-readonly-port`
This setting does not appear to be available in the `google_container_cluster` Terraform resource.

### New or Affected Resource(s)

google_container_cluster

b/362329176

**Comment by wyardley** [comment] 2024-08-26 20:28
@melinath I created #19236 to cover this -- See comments [here](https://github.com/hashicorp/terraform-provider-google/issues/15208#issuecomment-2299839033) and [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/11272#issuecomment-2302322004), but assuming `node_pool_auto_config.node_kublet_config` is what's needed there, https://github.com/GoogleCloudPlatform/magic-modules/pull/11272 won't cover it as currently stands.

However, it will be a bit of extra work, because it doesn't look like `node_kublet_config` is currently supported _at all_ for `node_pool_auto_config`.

**Comment by melinath** [comment] 2024-08-29 15:39
Closing as a duplicate of https://github.com/hashicorp/terraform-provider-google/issues/19236 - please let me know if that seems incorrect!

**Closed by melinath** 2024-08-29 15:39 UTC
Labels: enhancement, size/m, forward/linked, service/container
