### ISSUE TITLE
Support setting IAM on `google_compute_instance_template`

### ISSUE THREAD

**Issue by carusooo** [hashicorp/terraform-provider-google#15653] opened 2023-08-29 03:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support setting IAM on `google_compute_instance_template`, this would allow using a command like [`gcloud compute instance-templates set-iam-policy`](https://cloud.google.com/sdk/gcloud/reference/compute/instance-templates/set-iam-policy) in infrastructure-as-code

### New or Affected Resource(s)

* *google_compute_instance_template_iam_policy*  Authoritative. Sets the IAM policy for the instance and replaces any existing policy already attached.
* *google_compute_instance_template_iam_binding* Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the instance are preserved.
* *google_compute_instance_template_iam_member* Non-authoritative. Updates the IAM policy to grant a role to a new member. Other members for the role for the instance are preserved.

### Potential Terraform Configuration

```tf
resource "google_compute_instance_template_iam_member" "template_user" {
  template    = google_compute_instance_template.app_template.id
  role     = "roles/compute.instanceAdmin"
  member  = "serviceAccount:${var.template_admin_service_account}"
}

```

### References

* N/A

b/309764285

**Comment by c2thorn** [comment] 2023-11-28 20:13
closing as duplicate of https://github.com/hashicorp/terraform-provider-google/issues/7257

**Closed by c2thorn** 2023-11-28 20:13 UTC
Labels: enhancement, new-resource, size/s, forward/linked, service/compute-instances
