### ISSUE TITLE
403: Error deleting default network in project in google_project resource. Provider version 3.88

### ISSUE THREAD

**Issue by macksclark** [hashicorp/terraform-provider-google#11028] opened 2022-02-03 16:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.14.9
provider version 3.88

### Affected Resource(s)

* google_project

### Terraform Configuration Files

```tf
# Set up intake projects.
module "intake_projects" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 11.1.0"

  for_each = toset(concat(
    local.intake_project_ids,
  ))

  name                    = each.value
  org_id                  = ""
  folder_id               = local.root_folder_id
  billing_account         = local.google_owned_billing_account
  lien                    = false # To be created in DPT deployment
  default_service_account = "keep"
  create_project_sa       = false
  // Enable cloud functions api in order to create default service account.
  activate_apis = ["cloudfunctions.googleapis.com"]
}

# Set up other shared projects (csr, audit, network), data projects.
module "projects" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 11.1.0"

  for_each = toset(concat(
    local.shared_project_ids,
    local.data_project_ids
  ))

  name                    = each.value
  org_id                  = ""
  folder_id               = local.root_folder_id
  billing_account         = local.google_owned_billing_account
  lien                    = false # To be created in DPT deployment
  default_service_account = "keep"
  create_project_sa       = false
  activate_apis           = []
}
```

### Debug Output

```
Error: Error deleting default network in project hde-t46-stage-intake: googleapi: Error 403: Permission denied on resource project hde-t46-stage-intake.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.DebugInfo",
    "detail": "Project 'project:hde-t46-stage-intake' not found or deleted."
  },
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developer console API key",
        "url": "https://console.developers.google.com/project/hde-t46-stage-intake/apiui/credential"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/hde-t46-stage-intake",
      "service": "compute.googleapis.com"
    },
    "reason": "CONSUMER_INVALID"
  }
]
, forbidden
 
  on .terraform/modules/intake_projects/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
  65: resource "google_project" "main" {
```

### Expected Behavior

Project successfully created and default network deleted. It seems that this would all happen in one terraform apply call, so it should happen seamlessly.

### Actual Behavior

Project was created but nothing further was set up in the project after this error. 

### Steps to Reproduce

Issue is flaky- does not always happen, but `terraform apply`.

### Important Factoids

* This happens when authenticating as a user and in our automated tests which use a service account.
* We see 2 different variations of the issue, one where the default_network cannot be deleted and one where we get a project not found like `Error: googleapi: Error 403: Project 'project_number:X' not found or deleted., forbidden`
* The issue happens on several projects in a row
* The error code is CONSUMER_INVALID which seems suspicious 

### References

https://github.com/hashicorp/terraform-provider-google/issues/3582 seems to be a similar issue but we are not 

* Internal Issue [http://b/218359032]( http://b/218359032)

**Comment by slevenick** [comment] 2022-02-03 21:38
Can you reproduce this bug without using modules? I'm curious what is happening under the hood there, as I don't know how default networks are deleted

**Comment by yeweidaniel** [comment] 2022-02-03 23:12
Hi Sam, it seems the default network deletion is done in the provider code [here](https://github.com/hashicorp/terraform-provider-google/blob/8c69e943f8c991588bb53c9ca4e4a0f4686e29f7/google/resource_google_project.go#L203).

I tried terraform apply using below snippet and it finished successfully.

```
module "devops_project" {
  source                  = "terraform-google-modules/project-factory/google"
  version                 = "~> 11.1.0"
  name                    = local.project_id
  org_id                  = ""
  folder_id               = local.root_folder_id
  billing_account         = local.billing_account
  lien                    = false
  default_service_account = "keep"
  create_project_sa       = false
  activate_apis = ["cloudbuild.googleapis.com", "compute.googleapis.com"]
  auto_create_network = true
}
```

However running the same thing with a different project_id and `auto_create_network` set to false resulted in this error.

Creating a new project via Cloud Console also showed no `default` network. Note we do have `constraints/compute.skipDefaultNetworkCreation` org policy enforced. Perhaps that deletion line needs to account for it if `auto_create_network` is set to `false`? Another suspicion is IAM propagation delays after project creation.

**Comment by slevenick** [comment] 2022-02-04 19:48
Yeah, sounds like it could be a propagation issue. Can you reproduce this without using the module so that we can look at how the resources are being set up, what permissions are granted etc?

**Comment by yeweidaniel** [comment] 2022-02-07 04:32
Yes, I was able to reproduce using the raw Terraform resource for google_project. I ran twice and this error happened on the 2nd try.

```
resource "google_project" "my_project-in-a-folder" {
  name        = local.project_id
  project_id = local.project_id
  folder_id.  = local.root_folder_id
  auto_create_network = false
  billing_account         = local.billing_account
}
```

**Comment by bharathkkb** [comment] 2022-02-07 17:55
I was also able to repro this and we are seeing intermittent failures in CI

**Comment by slevenick** [comment] 2022-02-07 18:04
Strange, https://github.com/hashicorp/terraform-provider-google-beta/pull/2566 was added back in 3.44.0 to address this in some capacity. I wonder if something changed recently to cause this to pop back up again

**Comment by benzhang94** [comment] 2022-02-07 21:07
👍  for this issue.
I experienced the exact same. Only difference is that after TF created the project and failed to delete the default VPC, it actually then deletes the project, which leave the project ID occupied. Re-applying doesn't work as TF considers that the project was not created and tries to create it, but unable to go through due to the project id was taken.

**Comment by c2thorn** [comment] 2023-02-21 18:26
According to the internal issue, this was resolved within a week and was not a Terraform issue.

**Closed by c2thorn** 2023-02-21 18:26 UTC
Labels: bug
