### ISSUE TITLE
Add md5_authentication_key in google_compute_router

### ISSUE THREAD

**Issue by rjouhann** [hashicorp/terraform-provider-google#13103] opened 2022-11-22 17:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It is not possible to setup MD5 authentication using the GCP Terraform provider while [we can using the console, gcloud or API.](https://cloud.google.com/network-connectivity/docs/router/how-to/use-md5-authentication#api)

FYI, This feature is GS since early November 2022:

> **[November 01, 2022](https://cloud.google.com/network-connectivity/docs/router/release-notes)**
> The Cloud Router BGP MD5 authentication feature is Generally Available ([GA](https://cloud.google.com/products#product-launch-stages)).

### New or Affected Resource(s)

* google_compute_router

### Potential Terraform Configuration

Add property md5_authentication_key in bgp_peers block.

```tf
resource "google_compute_router" "google_router_1" {
  provider = google
  name     = "myGoogleCloud Router"
  network  = google_compute_network.vpc_1.id
  bgp {
    asn               = 16550
    advertise_mode    = "CUSTOM"
    advertised_groups = ["ALL_SUBNETS"]
    md5_authentication_key = "secret"
  }
}
```

**Comment by melinath** [comment] 2022-11-30 21:32
b/260899743

**Comment by ayush-jain1** [comment] 2023-02-06 09:19
@melinath @googlerjk  Any tentative timeline for this feature to be released ?

**Comment by c2thorn** [comment] 2023-02-06 17:01
@ayush-jain1 no timeline at this moment.

**Comment by rileykarson** [comment] 2023-03-22 18:07
Note: Restrictions in the API make integration to Terraform as-is impractical.

The issue is that keys are modeled as top-level values in the parent router, allowing reuse, and the API requires that they're in use by a BGP Peer at creation time. Sequencing issues in Terraform mean that the only viable approach would be to add them to `google_compute_router_peer`, which would require dropping that resource out of our code generator and make import/reuse of keys infeasible.

**Comment by melinath** [comment] 2024-02-06 16:56
Thanks! This seems to be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9666, closing.

**Closed by melinath** 2024-02-06 16:56 UTC
Labels: enhancement, size/s, priority/1, forward/linked, service/compute-router
