### ISSUE TITLE
Failing test(s): TestAccApigeeOrganization_apigeeOrganizationCloudFullDisableVpcPeeringTestExample (Beta)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16063] opened 2023-09-29 15:59 UTC
### Failure rates

- 57% since 2023-08-10

### Impacted tests

- TestAccApigeeOrganization_apigeeOrganizationCloudFullDisableVpcPeeringTestExample (Beta only)

### Affected Resource(s)

* google_apigee_organization

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/6707821277812550034?currentProjectId=TerraformProviders_GoogleBeta&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccApigeeOrganization_apigeeOrganizationCloudFullDisableVpcPeeringTestExample
=== PAUSE TestAccApigeeOrganization_apigeeOrganizationCloudFullDisableVpcPeeringTestExample
=== CONT  TestAccApigeeOrganization_apigeeOrganizationCloudFullDisableVpcPeeringTestExample
    vcr_utils.go:152: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_apigee_organization.org will be updated in-place
          ~ resource "google_apigee_organization" "org" {
                id                                   = "organizations/tf-testcxofis6cee"
                name                                 = "tf-testcxofis6cee"
                # (12 unchanged attributes hidden)
              ~ properties {
                  ~ property {
                      ~ name  = "features.hybrid.enabled" -> "features.mart.connect.enabled"
                        # (1 unchanged attribute hidden)
                    }
                  ~ property {
                      ~ name  = "features.mart.connect.enabled" -> "features.hybrid.enabled"
                        # (1 unchanged attribute hidden)
                    }
                }
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccApigeeOrganization_apigeeOrganizationCloudFullDisableVpcPeeringTestExample (412.82s)
FAIL
```

b/303808035

**Comment by SarahFrench** [comment] 2023-09-29 16:00
Just looks like an ordering issue. The weird thing is that the test is flaky - you'd expect the problem to be constant if the config always has properties in one order and the API always reorders them.

**Comment by melinath** [comment] 2024-04-09 21:54
Duplicate of https://github.com/hashicorp/terraform-provider-google/issues/13274

**Closed by melinath** 2024-04-09 21:54 UTC
Labels: size/s, test-failure, forward/linked, service/apigee, test-failure-50
