### ISSUE TITLE
Failing test(s): TestAccIdentityPlatformTenant**

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#12789] opened 2022-10-14 14:32 UTC
Failure rate: 100% since oct 11 2022

Impacted tests:
- TestAccIdentityPlatformTenant_identityPlatformTenantUpdate
- TestAccIdentityPlatformTenantOauthIdpConfig_identityPlatformTenantOauthIdpConfigUpdate
- TestAccIdentityPlatformTenantOauthIdpConfig_identityPlatformTenantOauthIdpConfigBasicExample
- TestAccIdentityPlatformTenantInboundSamlConfig_identityPlatformTenantInboundSamlConfigUpdate
- TestAccIdentityPlatformTenantInboundSamlConfig_identityPlatformTenantInboundSamlConfigBasicExample
- TestAccIdentityPlatformTenant_identityPlatformTenantBasicExample
- TestAccIdentityPlatformTenantDefaultSupportedIdpConfig_identityPlatformTenantDefaultSupportedIdpConfigUpdate
- TestAccIdentityPlatformTenantDefaultSupportedIdpConfig_identityPlatformTenantDefaultSupportedIdpConfigBasicExample

Nightly builds:
- https://ci-oss.hashicorp.engineering/viewLog.html?buildId=344314&buildTypeId=GoogleCloud_ProviderGoogleCloudGoogleProject

Upstream issue filed a metabug mb/105513339

```
Error: Error creating Tenant: googleapi: Error 400: INVALID_PROJECT_ID
```

**Comment by AarshDhokai** [comment] 2022-12-02 12:10
All the tests are failing 100% - [Google Cloud](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/357019?buildTab=tests&pager.currentPage=1&status=failed) and [Google Cloud Beta](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/357055?buildTab=tests&pager.currentPage=1&status=all&expandedTest=-7237469270685448170)

**Comment by AarshDhokai** [comment] 2022-12-07 13:37
b/261703826

**Comment by roaks3** [comment] 2022-12-20 21:08
I looked a bit closer at this one after looking at the metabug ticket, and I think I've found the root cause:
- There were two `google.cloud.identitytoolkit.admin.v2.ProjectConfigService.UpdateConfig` made by the CI service account on October 11, 2022 at 6:39:52 AM GMT-4, which I believe have cleared the `multiTenant` setting
- A new resource was introduced the same day that called `PATCH projects/{{project}}/config` for create, update, and delete operations: https://github.com/GoogleCloudPlatform/magic-modules/pull/6679
- The resource **does** include update mask, but the mask is only applied for update, not create or delete
- On Oct 11, the PR was submitted with a test, which started off by running create
- No mask was applied to the `PATCH projects/{{project}}/config` on create ([see log](https://00f74ba44bb1b33fd120018a3daedcce292026fb81-apidata.googleusercontent.com/download/storage/v1/b/ci-vcr-logs/o/beta%2Frefs%2Fheads%2Fauto-pr-6679%2Fartifacts%2F2fafbde6-c080-46a2-9c17-af4448686ee2%2Frecording%2FTestAccIdentityPlatformProjectDefaultConfig_identityPlatformProjectDefaultConfigExample.log?jk=AFshE3Wex5ACX8EPHtxkVA6yJ1GOM_d81XGHzqsvzzMggCkOGyuPey0nDNp_COsi4GACzkrNNp2SaTv7mUJfPYTwfyRhPWfyTdIsrkALc9e0DVorm6W6c3CAlhknQt4-g9GsuCbSc6txQCo8tvdlU3e16acpMRVXJKwYuO4Jxx-kSKvgUI-O4m-43ynVVOFGoAlM9VipNoC0SjvBvzcAbUVKsI25vNxV8MmhlZ9ZAER9lqNu0Sfi2B24s6TMAm9rOXOLfg6tauftv_8to93tB-33AyRG0BMMrgXc0_xRiuFSSiKvNPcWBx9czPObhwg4HsaiI5CpNUhT79wRMcX4oZCTEFMGslWwPo8gf6FRnBm_Bo_WswaQtgD-0tWXqeuXTDqUZZNDwUoSpx3vv2EQX1HDjjHc1U9QmdL8F6_qsP2D0O6Q0KWPsWaw6cMDqmodLqTTnTWZeDTkT8UgG-FTouEKNMzhpusx6Hf4pp37lidTgwXNHXHRTTqw2ZEygQEvaOzNDFWPtaA0iYUTqvPQ680eUhM3iRpnvoy_PR_QFUL7wrktHOOJ020KVnRaz-oKPUQIGP52L6ZXAkc0DOdnX4309JuLfPMAeD2fjNHiipiuXLH8K8ipnM5YngmEgo4S47H1klYhJf4kvQjpP-ex2CgqUF62q2sDxAqlv9KmwJK_TdzStylC3n3b1PPsEO5bnJXfJACwU_jbfvE0n6KjK2Qn76bu3HjiV7SB-QB9ymQKcYVckexF-lD9e3FRZ_UoDaJIJlurUmRYcDgWPmuHJwCZ6l9XRNKcMuO_6BAJEYvLjT41ARm30GpE3t7jnNcNxiQE4Bq1qddGw7B5coVsCg__EhvMfM-nK0BR1wyhHUhjKusVY0-jQ_noW9sMAOpBfdbpdMh_5jGl9xnTyOFRaaHXWbgw4CbdHM9DCuiklHesFUnRzAtEPU_mjHn5OHzO-y4Bqr8CX78E8CH-bnBt5H5sllHKMwXN95HqW_U8LjKcLflhDtf8U2SfJJKMypkY0GFD3Ra60jUWO2XipuTnpvQvvU3P2UNUP2CXu_vQPxej2lqixNckELCRHrusf7yE9FNk1Jmk1PfuB1y9ZPSGysaB4tuPvW2aO0E17QAdTHRVJGnmTvsb6kFdFEkUhYNo4t9a26QTnhtHAFNXddHwyeq9pSdLAhEExCQjVQSwLZukaaZBDosr5YuLTs2F6bPuGKmdjhGcwE1sMeHHwnEpw2hSjSilANLj8yASjnqWdcgjoS3ol-DCwYHMAbdqaGAUR3BwYQCz-8_L-ltqSYzdNVgUcgk9WVmPFkiZuvzn3--u2-MKwUGGsfR8xazEgKXMcCzDGiGYCz3i0YjY4-K7IogKoBzJO5dop-3mCvlzHdEpfkgJpMxvjTR6rsHsrJbS6O_BZMzd&isca=1))
- The API response shows that `multiTenant` options were cleared out (there may be other fields that were also reset)
- **Not so sure on this piece:** All subsequent calls of this test, including after merge, passed with a no-op, because the initial read matches the config. This would explain why the call is never made again after Oct 11.

I believe we will want to consider some options for preventing this from happening in the future, and helping us debug issues like this more efficiently, but immediate actions would probably be:
1. Find out previous settings of our main project
2. Disable`TestAccIdentityPlatformProjectDefaultConfig_identityPlatformProjectDefaultConfigExample`, and potentially revert https://github.com/GoogleCloudPlatform/magic-modules/pull/6679, since it may result in unexpected destructive behavior for other project fields
3. Restore the previous state of the main project

**Comment by roaks3** [comment] 2022-12-20 21:12
@ScottSuarez @melinath if the above explanation seems adequate to either of you, I can go ahead and work on resolving.

**Comment by melinath** [comment] 2022-12-21 21:42
@roaks3 we probably wouldn't be able to revert the PR since it added a new resource and was already released - removing the resource would be a breaking change. Is there a bug in the resource that we can / should resolve, or is this something inherent in how the resource is intended to work? if it's inherent we may just need to make the tests isolate the resource in its own project.

**Comment by ScottSuarez** [comment] 2022-12-21 22:04
I agree with Steven, a disabling of the test or isolation of the test to it's own project looks like the right move. Deleting this resource would be a breaking change at this point.

**Comment by roaks3** [comment] 2022-12-21 23:48
Ah ok, that makes sense, thanks for pointing out the breaking change! I think we definitely want to isolate the test to its own project, but I believe there may also be other problems with the resource (eg. the lack of an update mask could clear other user settings). I would suggest we start by just disabling the test to ensure that our CI environment will remain stable, and then work out a solution to the resource that both fixes any bugs and uses another project to test.

**Comment by roaks3** [comment] 2022-12-22 16:15
Clarification on my above breakdown:

| **Not so sure on this piece**: All subsequent calls of this test, including after merge, passed with a no-op, because the initial read matches the config. This would explain why the call is never made again after Oct 11.

This appears incorrect. The test was not run for a period of time while the original PR was in review, but then once it was merged, it looks like the tests were running normally after that and the update calls were being made to the API on every run.

**Comment by roaks3** [comment] 2023-01-31 18:35
We have the ticket created above for fixing this particular resource that was clearing the setting, and since then we have not seen this error. I believe we can safely close this issue.

**Closed by roaks3** 2023-01-31 18:35 UTC
Labels: size/xs, priority/2, test failure, crosslinked
