### ISSUE TITLE
Regional Managed SSL Certificates

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#7836] opened 2020-11-17 23:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Create a regional version of Global Managed SSL Certificate. I noticed that it was missing when I promoted Global equivalent to GA.

### New Resource

* google_compute_region_managed_ssl_certificate

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* https://cloud.google.com/compute/docs/reference/rest/v1/regionSslCertificates

**Comment by rileykarson** [comment] 2020-11-23 18:31
Small instead of Medium- this should be almost an exact copy of `google_compute_managed_ssl_certificate`

**Comment by mitj04** [comment] 2022-12-28 09:38
b/263850830

**Comment by mitj04** [comment] 2022-12-28 11:48
It seems like it's a duplicate of [issues/5819](https://github.com/hashicorp/terraform-provider-google/issues/5819).

**Closed** 2022-12-28 11:59 UTC
Labels: enhancement, size/s, crosslinked
