### ISSUE TITLE
Changing AliasIP issue

### ISSUE THREAD

**Issue by ArsenyBelorukov** [hashicorp/terraform-provider-google#12286] opened 2022-08-09 13:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
# terraform -v
Terraform v1.2.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.31.0
```

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.31.0"
    }
  }
}

variable "project" {
  description = "project ID"
  type        = string
}

locals {
  region = "us-central1"
  zone = "us-central1-a"
}

provider "google" {
  project = var.project
  zone    = local.zone
}

resource "google_compute_network" "custom-test" {
  name                    = "test-network"
  auto_create_subnetworks = false
}
resource "google_compute_subnetwork" "network-with-private-secondary-ip-ranges" {
  name          = "test-subnetwork"
  ip_cidr_range = "10.2.0.0/24"
  region        = local.region
  network       = google_compute_network.custom-test.id
  secondary_ip_range {
    range_name    = "tf-test-secondary-range"
    ip_cidr_range = "192.168.10.0/24"
  }
}


resource "google_compute_instance" "instance1" {
  name         = "instance1"
  machine_type = "e2-micro"
  boot_disk {
    initialize_params {
    image = "debian-cloud/debian-10"
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.network-with-private-secondary-ip-ranges.self_link
    alias_ip_range {
      subnetwork_range_name = "tf-test-secondary-range"
      ip_cidr_range = "192.168.10.2/32"
    }
    alias_ip_range {
      subnetwork_range_name = "tf-test-secondary-range"
      ip_cidr_range = "192.168.10.3/32"
    }
    # alias_ip_range {
    #   subnetwork_range_name = "tf-test-secondary-range"
    #   ip_cidr_range = "192.168.10.4/32"
    # }
  }
}
```

### Debug Output

https://gist.github.com/ArsenyBelorukov/2f131fe14872001f7b16321f0774c535

### Actual Behavior

Currently, changing AliasIPs is performed in two steps 
https://github.com/hashicorp/terraform-provider-google/blob/9d577db230bead275a4a1a6ae2c15a608a9dba1b/google/services/compute/resource_compute_instance.go#L1892

1. Setting AliasIP to an empty list (it equals deleting them)
2. Setting AliasIP to the needed list

This way has dowsides:

1. When applying a new configuration, the instance loses aliasIPs ranges for ~30s even if they are not been changed (192.168.10.2 in example)
2. If something goes wrong in step 2 (for example new aliasIP is already used for another instance) host be left without any aliasIPs ranges.

### Expected Behavior

Terraform should delete unneeded AlisaIPs ranges, and then add new ones.

Via gcloud it looks (deleting 192.168.10.3, then adding 192.168.10.4):
```bash
➜  issue git:(master) ✗ gcloud compute instances describe  instance1 --format="json"  | jq '.networkInterfaces[0].aliasIpRanges'
[
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  },
  {
    "ipCidrRange": "192.168.10.3/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]

➜  issue git:(master) ✗ gcloud compute instances network-interfaces update instance1 --aliases 'tf-test-secondary-range:192.168.10.2/32'
Updating network interface [nic0] of instance [instance1]...done.

➜  issue git:(master) ✗ gcloud compute instances describe  instance1 --format="json"  | jq '.networkInterfaces[0].aliasIpRanges'
[
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]

➜  issue git:(master) ✗ gcloud compute instances network-interfaces update instance1 --aliases 'tf-test-secondary-range:192.168.10.2/32;tf-test-secondary-range:192.168.10.4/32'
Updating network interface [nic0] of instance [instance1]...done.

➜  issue git:(master) ✗ gcloud compute instances describe  instance1 --format="json"  | jq '.networkInterfaces[0].aliasIpRanges'
[
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  },
  {
    "ipCidrRange": "192.168.10.4/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]
```

### Steps to Reproduce

1. `terraform apply`

### References

https://cloud.google.com/vpc/docs/configure-alias-ip-ranges#modifying_alias_ip_ranges_for_an_existing_instance

b/321386607

**Comment by edwardmedia** [comment] 2022-08-09 15:25
@ArsenyBelorukov I don't understand what the issue here. Here is what I can see from the log you provided. Can you clarify what was wrong?

Initial state
```tf
   "aliasIpRanges": [
    {
     "ipCidrRange": "192.168.10.2/32",
     "subnetworkRangeName": "tf-test-secondary-range"
    },
    {
     "ipCidrRange": "192.168.10.3/32",
     "subnetworkRangeName": "tf-test-secondary-range"
    }
 ],
```

What to change
```
          ~ alias_ip_range {
              ~ ip_cidr_range         = "192.168.10.3/32" -> "192.168.10.4/32"
                # (1 unchanged attribute hidden)
            }
```

final state
```tf
 "aliasIpRanges": [
  {
   "ipCidrRange": "192.168.10.2/32",
   "subnetworkRangeName": "tf-test-secondary-range"
  },
  {
   "ipCidrRange": "192.168.10.4/32",
   "subnetworkRangeName": "tf-test-secondary-range"
  }
 ],
```

**Comment by ArsenyBelorukov** [comment] 2022-08-09 18:29
@edwardmedia 
Yes, the final state is correct.
But during applying configuration, terraform deleted "192.168.10.2/32" and added it again, although it could be left untouched.

Even if I just added a new AlisaIP range
```bash
          + alias_ip_range {
              + ip_cidr_range         = "192.168.10.4/32"
              + subnetwork_range_name = "tf-test-secondary-range"
            }
```
terraform does two requests:  removes existing AlisaIP ranges, and then set needed. 
https://gist.github.com/ArsenyBelorukov/2f131fe14872001f7b16321f0774c535#file-debug_output_2-L646

But this change could be done by one request, only
```
== body start ==
{"aliasIpRanges": [{"ipCidrRange": "192.168.10.2/32", "subnetworkRangeName": "tf-test-secondary-range"}, {"ipCidrRange": "192.168.10.3/32", "subnetworkRangeName": "tf-test-secondary-range"}, {"ipCidrRange": "192.168.10.4/32", "subnetworkRangeName": "tf-test-secondary-range"}], "fingerprint": "8qjEBOF3vK8="}
== body end ==
```

Problem is that all ranges stop working on the instance, while Terraform applies the configuration.

So I suppose terraform could do it more sensible.
For example, if currently I have
`192.168.10.2/32,192.168.10.3/32 `
and want to get 
`192.168.10.2/32,192.168.10.4/32 `
so change is 
`"192.168.10.3/32" -> "192.168.10.4/32"`

terraform should 
1. remove 192.168.10.3/32 by making request
```
{"aliasIpRanges": [{"ipCidrRange": "192.168.10.2/32", "subnetworkRangeName": "tf-test-secondary-range"}]}
```
2. add new range 192.168.10.4/32
```
{"aliasIpRanges": [{"ipCidrRange": "192.168.10.2/32", "subnetworkRangeName": "tf-test-secondary-range"}, {"ipCidrRange": "192.168.10.4/32", "subnetworkRangeName": "tf-test-secondary-range"}]}
```

**Comment by edwardmedia** [comment] 2022-08-10 21:11
@ArsenyBelorukov here is the reason why it behaves this way. This is by design. Closing the issue then

_Alias IP ranges cannot be updated; they must be removed and then added unless you are changing subnetwork/network_

**Comment by ArsenyBelorukov** [comment] 2022-08-10 21:25
@edwardmedia 
I gave the example of how it should be removed. 
It is not necessary to remove **all** AliasIP ranges. Terraform should remove unneeded and then add the described list.

In the current situation, terraform just brokes network connectivity to AliasIps, but should not

**Comment by edwardmedia** [comment] 2022-08-11 00:29
@ArsenyBelorukov can you share you the full log of your gcloud command execution? You said `Via gcloud it looks (deleting 192.168.10.3, then adding 192.168.10.4):`

I receive below error. 

```
{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'resource.aliasIpRanges': ''. Cannot simultaneously add and remove alias IP ranges.",
    "errors": [
      {
        "message": "Invalid value for field 'resource.aliasIpRanges': ''. Cannot simultaneously add and remove alias IP ranges.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
```

**Comment by ArsenyBelorukov** [comment] 2022-08-12 09:16
@edwardmedia thanks for your attention!


python pseudo-code:
```python
current_aliasip_ranges = [
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  },
  {
    "ipCidrRange": "192.168.10.3/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]

desired_aliasip_ranges = [
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  },
  {
    "ipCidrRange": "192.168.10.4/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]

intersection_aliasip_ranges = [range for range in current_aliasip_ranges if range in desired_aliasip_ranges ] 
# [{'subnetworkRangeName': 'tf-test-secondary-range', 'ipCidrRange': '192.168.10.2/32'}]
```

Applying the new config should be done in two steps:
1. Setting common ranges for current_aliasip_ranges and desired_aliasip_ranges. It removes the unneeded 192.168.10.3/32 range 
```
gcloud compute instances network-interfaces update instance1 --zone us-central1-a --aliases 'tf-test-secondary-range:192.168.10.2/32'  --log-http
```
https://gist.githubusercontent.com/ArsenyBelorukov/2f131fe14872001f7b16321f0774c535/raw/c882ad4d9f731fd209c10bf844a06b25d91db1ec/gcloud_step1

Result:
```
➜  ~ gcloud compute instances describe instance1 --format="json"  | jq '.networkInterfaces[0].aliasIpRanges'
[
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]
```
2. Setting full desired_aliasip_ranges, it adds the new 192.168.10.4/32 range:
```
gcloud compute instances network-interfaces update instance1 --aliases 'tf-test-secondary-range:192.168.10.2/32;tf-test-secondary-range:192.168.10.4/32'  --log-http
```
https://gist.githubusercontent.com/ArsenyBelorukov/2f131fe14872001f7b16321f0774c535/raw/c882ad4d9f731fd209c10bf844a06b25d91db1ec/gcloud_step2

Result
```
➜  ~ gcloud compute instances describe instance1 --project=itops-test-320312 --zone us-central1-a --format="json"  | jq '.networkInterfaces[0].aliasIpRanges'
[
  {
    "ipCidrRange": "192.168.10.2/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  },
  {
    "ipCidrRange": "192.168.10.4/32",
    "subnetworkRangeName": "tf-test-secondary-range"
  }
]
```

**Comment by edwardmedia** [comment] 2022-08-15 16:50
@ArsenyBelorukov I see what you mean now.  Currently the SDK does not directly support handling common nodes. Change this to enhancement for triage.

**Comment by melinath** [comment] 2024-01-20 00:04
I'm going to change this back to a bug since it's an issue with the implementation rather than a coverage gap, and it seems like the current behavior is problematic.

**Comment by karolgorc** [comment] 2024-09-17 14:03
i think this issue can be closed

**Comment by melinath** [comment] 2024-09-17 15:52
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/11321

**Closed by melinath** 2024-09-17 15:52 UTC
Labels: bug, size/m, forward/linked, service/compute-instances
