### ISSUE TITLE
apigee_environment_iam lacks info on the `org_id` field 

### ISSUE THREAD

**Issue by astellingwerf** [hashicorp/terraform-provider-google#17821] opened 2024-04-11 13:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

The example snippets on https://registry.terraform.io/providers/hashicorp/google/5.24.0/docs/resources/apigee_environment_iam mention the `org_id`, but the list under *Argument Reference* does not. It's probably helpful to add it, not just for completeness sake, but also because the format is significant. For example, it appears that it (contrary to what the name logically implies) must be prefixed by "organizations/".

### New or Affected Resource(s)

- google_apigee_environment_iam_binding
- google_apigee_environment_iam_member
- google_apigee_environment_iam_policy

### Potential Terraform Configuration

```tf 
```

**Comment by melinath** [comment] 2024-04-22 17:25
duplicate of https://github.com/hashicorp/terraform-provider-google/issues/15909

**Closed by melinath** 2024-04-22 17:25 UTC
Labels: enhancement, service/apigee, forward/review
